### PR TITLE
[ci] simplified and speeded up Travis

### PR DESCRIPTION
**Pull request by StrikerRUS**
All things we need are already installed on Travis's trusty images.

### CODE REVIEW

**Comment by guolinke** [comment]
@StrikerRUS it seems there are many failed builds in travis due to the branch clone...

**Comment by StrikerRUS** [comment]
@guolinke I see only `check-docs` fails for the second day, but I don't know how to fix it. Maybe problem will disappear in a few days without our help or we can exclude Laurae's table site from the Linkchecker by parameter.

**Comment by guolinke** [comment]
@Laurae2 can you help to fix the url error of your site ?

**Comment by StrikerRUS** [comment]
I think the best hotfix now, since it's can be reached by ordinal browsers, is just not to check this site. I've created a PR: #1430.

**Comment by Laurae2** [comment]
@guolinke Seems I can't fix it, probably related to Tableau/Amazon certificates.

**Comment by guolinke** [comment]
@StrikerRUS it seems the gpu test is down after merged this PR.

**Pull request merged**
