### PR TITLE
[python] copy old Booster's attributes to new one in refit method

### LINKED ISSUE #1657: [python] copy info from old Booster to new one in refit method
Refer to the discussion in #1629.

### PR DESCRIPTION
**Pull request by StrikerRUS**
Fixed #1657.

I'm confused about the need to copy
https://github.com/Microsoft/LightGBM/blob/a760eae4ff06fa8d522ed53e7df8c31d9e8298f0/python-package/lightgbm/basic.py#L1438

Also, I'm not sure whether `__attr` should be **copied**.

But I suppose that it's logically correct to reset the info connected to the previous data (e.g. `__train_data_name`, `best_iteration`, `valid_sets`, etc.) after calling the `refit` method.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@guolinke What is your opinion on `__attr` and should `__set_objective_to_none` be copied?

**Comment by guolinke** [comment]
I think the `__attr` can be copied. For the `__set_objective_to_none`, as refit cannot support the custom objective, maybe we should check it?

**Comment by StrikerRUS** [comment]
Sorry, I'm not sure that I fully understood the part about `__set_objective_to_none`.

**Comment by guolinke** [comment]
@StrikerRUS it this ready to merge ?
BTW, it seems appveyor is down..

**Comment by StrikerRUS** [comment]
@guolinke
Please, clarify what did you mean under 
>  maybe we should check it [__set_objective_to_none]?

 I suppose, Appveyor fails due to the new release (0.20) of scikit-learn which brought new (Deprecation and Future) warnings. I will take a look at this today.

**Comment by guolinke** [comment]
@StrikerRUS 
__set_objective_to_none means there exists a custom objective function.
In this case, we cannot use refit.
So when calling refit in a booster with __set_objective_to_none, we should throw a error.

**Pull request merged**
