### PR TITLE
[ci] Stop running CUDA tests at CI

### PR DESCRIPTION
**Pull request by StrikerRUS**
Unblock LightGBM development process.
Refer to #4165.

I hope in the near future we will just revert this commit and restore running CUDA at our CI.

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Thank you! I agree, this is the right thing to do for now. Otherwise the pull requests will keep piling up and it will get harder to manage them and for others to contribute.

**Comment by StrikerRUS** [comment]
@jameslamb I guess

```
* checking whether package 'lightgbm' can be installed ... WARNING

Found the following significant warnings:

  Warning: package 'R6' was built under R version 4.0.5

See 'D:/a/LightGBM/LightGBM/lightgbm.Rcheck/00install.out' for details.
```
 should be fixed by #4158, right?

**Comment by jameslamb** [comment]
> @jameslamb I guess
> 
> ```
> * checking whether package 'lightgbm' can be installed ... WARNING
> 
> Found the following significant warnings:
> 
>   Warning: package 'R6' was built under R version 4.0.5
> 
> See 'D:/a/LightGBM/LightGBM/lightgbm.Rcheck/00install.out' for details.
> ```
> 
> should be fixed by #4158, right?

it should, yep! I remember we've had issues like that before once about a week has passed after an R release. Was trying to get ahead of it with #4158. This puts us in a difficult position where now #4158 can't pass without this PR and this PR can't pass without #4158.

Since neither of us have admin rights to merge while ignoring CI, and since this PR is just removing an entire file, it's ok with me if you push this CUDA change to the branch in #4158.

**Comment by jameslamb** [comment]
Or, alternatively, comment out any R jobs that are breaking with this error and we can uncomment them in a later PR. Just to get things working again.

**Comment by StrikerRUS** [comment]
@jameslamb 
>Since neither of us have admin rights to merge while ignoring CI

I thought you have them.
https://github.com/microsoft/LightGBM/pull/3874#issuecomment-769303472
https://github.com/microsoft/LightGBM/pull/4169#issuecomment-816989474

**Comment by jameslamb** [comment]
Oh! Interesting, I thought I'd lost them recently but it seems like I can merge with admin rights **ONLY AFTER ALL CI CHECKS ARE DONE RUNNING** (regardless of whether or not they succeed)

I can't merge this one, for example.

image

But I can merge #4158 (notice the button is not grayed out)

image

And I can merge #4162 

image

**Comment by jameslamb** [comment]
Ok this PR is almost done (just waiting on one more QEMU check to finish), I'll merge this with admin rights as soon as Azure completes.

**Pull request merged**
