### PR TITLE
[ci] Install matplotlib and graphviz when creating conda env

### PR DESCRIPTION
**Pull request by shiyu1994**
This is trying to solve #5507.

### CODE REVIEW

**Comment by jameslamb** [comment]
ha oh! Didn't know you were also working on this. I just opened #5510 with an alternative approach that I hope might be a bit more future-proof than re-ordering when we install things.

Let's see which one works 😬

**Comment by shiyu1994** [comment]
@jameslamb Thanks. I think both solutions are okay as long as they work. I can close this one if you feel that #5510 is a better solution.

**Review by jameslamb — APPROVED** [review]
I do feel like #5510 might be a more permanent solution to this...but I'm approving this since it's building successfully for now. That way, you can merge this to unblock CI and work on other things (since it's late for me here in the U.S. and I'm about to go to sleep).

I'll probably continue experimenting with #5510 more this week.

Thanks for working on this!

**Comment by shiyu1994** [comment]
Thanks. But it seems that Windows bdist build fails now with Azure DevOps. Not sure if it is related to this change. Will restart the tests to check.

**Comment by shiyu1994** [comment]
https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=13642&view=logs&j=67ae2ff8-4b33-578b-0813-9c0440091667

**Comment by jameslamb** [comment]
I just pushed a change over in https://github.com/microsoft/LightGBM/pull/5510 that I think could be a permanent fix. Learned today that it's possible to include build tags in the environment description for conda, so for example you can do

```shell
conda install 'python=3.7.12[build=*cpython]`
```

**Comment by shiyu1994** [comment]
Close with a replacing solution in #5510.

**Pull request closed without merging**
