### PR TITLE
[python-package] Fix mypy errors for fit() incompatible signature

### PR DESCRIPTION
**Pull request by IdoKendo**
Contributes to https://github.com/microsoft/LightGBM/issues/3867.

`mypy` currently raises the following errors regarding the signature of the fit() method:
```
python-package\lightgbm\sklearn.py:987: error: Signature of "fit" incompatible with supertype "LGBMModel"  [override]
python-package\lightgbm\sklearn.py:987: note:      Superclass:
python-package\lightgbm\sklearn.py:987: note:          def fit(self, X: Any, y: Any, sample_weight: Any = ..., init_score: Any = ..., group: Any = ..., eval_set: Any = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Any = ..., eval_class_weight: Any = ..., eval_init_score: Any = ..., eval_group: Any = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., feature_name: Any = ..., categorical_feature: Any = ..., callbacks: Any = ..., init_model: Union[str, Path, Booster, LGBMModel, None] = ...) -> Any      
python-package\lightgbm\sklearn.py:987: note:      Subclass:
python-package\lightgbm\sklearn.py:987: note:          def fit(self, X: Any, y: Any, sample_weight: Any = ..., init_score: Any = ..., eval_set: Any = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Any = ..., eval_init_score: Any = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, 
bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., feature_name: Any = ..., categorical_feature: Any = ..., callbacks: Any = ..., init_model: Union[str, Path, Booster, LGBMModel, None] = ...) -> Any
python-package\lightgbm\sklearn.py:1033: error: Signature of "fit" incompatible with supertype "LGBMModel"  [override]
python-package\lightgbm\sklearn.py:1033: note:      Superclass:
python-package\lightgbm\sklearn.py:1033: note:          def fit(self, X: Any, y: Any, sample_weight: Any = ..., init_score: Any = ..., group: Any = ..., eval_set: Any = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Any = ..., eval_class_weight: Any = ..., eval_init_score: Any = ..., eval_group: Any = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., feature_name: Any = ..., categorical_feature: Any = ..., callbacks: Any = ..., init_model: Union[str, Path, Booster, LGBMModel, None] = ...) -> Any     
python-package\lightgbm\sklearn.py:1033: note:      Subclass:
python-package\lightgbm\sklearn.py:1033: note:          def fit(self, X: Any, y: Any, sample_weight: Any = ..., init_score: Any = ..., eval_set: Any = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Any = ..., eval_class_weight: Any = ..., eval_init_score: Any = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., feature_name: Any = ..., categorical_feature: Any = ..., callbacks: Any = ..., init_model: Union[str, Path, Booster, LGBMModel, None] = ...) -> Any
python-package\lightgbm\dask.py:1164: error: Signature of "fit" incompatible with supertype "LGBMClassifier"  [override]
python-package\lightgbm\dask.py:1164: note:      Superclass:
python-package\lightgbm\dask.py:1164: note:          def fit(self, X: Any, y: Any, sample_weight: Any = ..., init_score: Any = ..., eval_set: Any = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Any = ..., 
eval_class_weight: Any = ..., eval_init_score: Any = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., feature_name: Any = ..., categorical_feature: Any = ..., callbacks: Any = ..., init_model: Union[str, Path, Booster, LGBMModel, None] = ...) -> Any
python-package\lightgbm\dask.py:1164: note:      Subclass:
python-package\lightgbm\dask.py:1164: note:          def fit(self, X: Union[Any, Any], y: Union[Any, Any, Any], sample_weight: Union[Any, Any, None] = ..., init_score: Union[Any, Any, Any, None] = ..., eval_set: Optional[List[Tuple[Union[Any, Any], Union[Any, Any, Any]]]] = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Optional[List[Union[Any, Any]]] = ..., eval_class_weight: Optional[List[Union[Dict[Any, Any], str]]] = ..., eval_init_score: Optional[List[Union[Any, Any, Any]]] = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., **kwargs: Any) -> DaskLGBMClassifier
python-package\lightgbm\dask.py:1164: error: Signature of "fit" incompatible with supertype "LGBMModel"  [override]
python-package\lightgbm\dask.py:1164: note:          def fit(self, X: Any, y: Any, sample_weight: Any = ..., init_score: Any = ..., group: Any = ..., eval_set: Any = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Any = ..., eval_class_weight: Any = ..., eval_init_score: Any = ..., eval_group: Any = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., feature_name: Any = ..., categorical_feature: Any = ..., callbacks: Any = ..., init_model: Union[str, Path, Booster, LGBMModel, None] = ...) -> Any        
python-package\lightgbm\dask.py:1164: note:          def fit(self, X: Union[Any, Any], y: Union[Any, Any, Any], sample_weight: Union[Any, Any, None] = ..., init_score: Union[Any, Any, Any, None] = ..., eval_set: Optional[List[Tuple[Union[Any, Any], Union[Any, Any, Any]]]] = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Optional[List[Union[Any, Any]]] = ..., eval_class_weight: Optional[List[Union[Dict[Any, Any], str]]] = ..., eval_init_score: Optional[List[Union[Any, Any, Any]]] = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., **kwargs: Any) -> DaskLGBMClassifier
python-package\lightgbm\dask.py:1336: error: Signature of "fit" incompatible with supertype "LGBMRegressor"  [override]
python-package\lightgbm\dask.py:1336: note:      Superclass:
python-package\lightgbm\dask.py:1336: note:          def fit(self, X: Any, y: Any, sample_weight: Any = ..., init_score: Any = ..., eval_set: Any = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Any = ..., 
eval_init_score: Any = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., feature_name: Any = ..., categorical_feature: Any = ..., callbacks: Any = ..., init_model: Union[str, Path, Booster, LGBMModel, None] = ...) -> Any
python-package\lightgbm\dask.py:1336: note:      Subclass:
python-package\lightgbm\dask.py:1336: note:          def fit(self, X: Union[Any, Any], y: Union[Any, Any, Any], sample_weight: Union[Any, Any, None] = ..., init_score: Union[Any, Any, None] = ..., eval_set: Optional[List[Tuple[Union[Any, Any], Union[Any, Any, Any]]]] = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Optional[List[Union[Any, Any]]] = ..., eval_init_score: Optional[List[Union[Any, Any]]] = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., **kwargs: Any) -> DaskLGBMRegressor
python-package\lightgbm\dask.py:1336: error: Signature of "fit" incompatible with supertype "LGBMModel"  [override]
python-package\lightgbm\dask.py:1336: note:          def fit(self, X: Any, y: Any, sample_weight: Any = ..., init_score: Any = ..., group: Any = ..., eval_set: Any = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Any = ..., eval_class_weight: Any = ..., eval_init_score: Any = ..., eval_group: Any = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., feature_name: Any = ..., categorical_feature: Any = ..., callbacks: Any = ..., init_model: Union[str, Path, Booster, LGBMModel, None] = ...) -> Any        
python-package\lightgbm\dask.py:1336: note:          def fit(self, X: Union[Any, Any], y: Union[Any, Any, Any], sample_weight: Union[Any, Any, None] = ..., init_score: Union[Any, Any, None] = ..., eval_set: Optional[List[Tuple[Union[Any, Any], Union[Any, Any, Any]]]] = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Optional[List[Union[Any, Any]]] = ..., eval_init_score: Optional[List[Union[Any, Any]]] = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., **kwargs: Any) -> DaskLGBMRegressor
python-package\lightgbm\dask.py:1489: error: Signature of "fit" incompatible with supertype "LGBMRanker"  [override]
python-package\lightgbm\dask.py:1489: note:      Superclass:
python-package\lightgbm\dask.py:1489: note:          def fit(self, X: Any, y: Any, sample_weight: Any = ..., init_score: Any = ..., group: Any = ..., eval_set: Any = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Any = ..., eval_init_score: Any = ..., eval_group: Any = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., eval_at: Union[List[int], Tuple[int, ...]] = ..., feature_name: Any = ..., categorical_feature: Any = ..., callbacks: Any = ..., init_model: Union[str, Path, Booster, LGBMModel, None] = ...) -> Any
python-package\lightgbm\dask.py:1489: note:      Subclass:
python-package\lightgbm\dask.py:1489: note:          def fit(self, X: Union[Any, Any], y: Union[Any, Any, Any], sample_weight: Union[Any, Any, None] = ..., init_score: Union[Any, Any, None] = ..., group: Union[Any, Any, None] = ..., eval_set: Optional[List[Tuple[Union[Any, Any], Union[Any, Any, Any]]]] = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Optional[List[Union[Any, Any]]] = ..., eval_init_score: Optional[List[Union[Any, Any]]] = ..., eval_group: Optional[List[Union[Any, Any]]] = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., eval_at: Union[List[int], Tuple[int, ...]] = ..., **kwargs: Any) -> DaskLGBMRanker
python-package\lightgbm\dask.py:1489: error: Signature of "fit" incompatible with supertype "LGBMModel"  [override]
python-package\lightgbm\dask.py:1489: note:          def fit(self, X: Any, y: Any, sample_weight: Any = ..., init_score: Any = ..., group: Any = ..., eval_set: Any = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Any = ..., eval_class_weight: Any = ..., eval_init_score: Any = ..., eval_group: Any = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., feature_name: Any = ..., categorical_feature: Any = ..., callbacks: Any = ..., init_model: Union[str, Path, Booster, LGBMModel, None] = ...) -> Any        
python-package\lightgbm\dask.py:1489: note:          def fit(self, X: Union[Any, Any], y: Union[Any, Any, Any], sample_weight: Union[Any, Any, None] = ..., init_score: Union[Any, Any, None] = ..., group: Union[Any, Any, None] = ..., eval_set: Optional[List[Tuple[Union[Any, Any], Union[Any, Any, Any]]]] = ..., eval_names: Optional[List[str]] = ..., eval_sample_weight: Optional[List[Union[Any, Any]]] = ..., eval_init_score: Optional[List[Union[Any, Any]]] = ..., eval_group: Optional[List[Union[Any, Any]]] = ..., eval_metric: Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]], List[Union[str, Union[Callable[[ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]], Callable[[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]], Union[Tuple[str, float, bool], List[Tuple[str, float, bool]]]]]]], None] = ..., eval_at: Union[List[int], Tuple[int, ...]] = ..., **kwargs: Any) -> DaskLGBMRanker
```

## Notes for Reviewers
This was tested by running mypy as documented in https://github.com/microsoft/LightGBM/issues/3867.

```
mypy \
    --exclude='python-package/compile/|python-package/build' \
    --ignore-missing-imports \
    python-package/
```

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks for helping with this!

But I'm sorry, I disagree with most of the proposed changes. The `fit()` methods of the estimators in `lightgbm.sklearn` should not be identical to each other...they expect different arguments for the different machine learning tasks (e.g., `group` is only relevant to ranking).

That same principle applies for the `fit()` methods on classes in `lightgbm.dask`, which are intended to mimic them. In addition, the `lightgbm.dask` estimators cannot simply have the same types for their arguments as the underlying `lightgbm.sklearn` things that they inherit from...special consideration has to be given there to how distributed training works and how to orchestrate moving data around multiple processes / machines.

If you haven't used Dask or LightGBM before, I recommend not closing this PR and not trying to attempt to fix the `mypy` warnings related to these `fit()` methods at this time.

**Comment by IdoKendo** [comment]
> Thanks for helping with this!
> 
> But I'm sorry, I disagree with most of the proposed changes. The `fit()` methods of the estimators in `lightgbm.sklearn` should not be identical to each other...they expect different arguments for the different machine learning tasks (e.g., `group` is only relevant to ranking).

Since mypy does not accept different signatures for child classes, these errors regarding differences in the signature are unsolvable then. Would you rather just silence them with `# type: ignore`?

**Comment by jameslamb** [comment]
> Would you rather just silence them with `# type: ignore`?

I'm willing to look at a proposal for that! I'd want to be sure that `#type: ignore` is at the lowest level possible... e.g., if it's possible I'd prefer to not stop type checking at `LGBMClassifier.fit()` and all the way down, so `mypy` could still catch issues like "`y` should be a `pandas` Series or `numpy` array but you passed a list".

If it's possible to specifically opt out of these signature-mismatch warnings, that would be even better.

**Comment by IdoKendo** [comment]
> If it's possible to specifically opt out of these signature-mismatch warnings, that would be even better.

It is possible! I've reverted the previous changes and added the override ignore tag to the fit method to silence these errors specifically.

**Review by jameslamb — APPROVED** [review]
Very nice, thank you so much! I didn't know about `# type: ignore[override]` before. That's exactly what I was hoping for.

The failing CI jobs aren't related to your change. Once we fix them (in #5689), I'll re-run them for this PR and merge it.

**Comment by jameslamb** [comment]
Thanks again for the help @IdoKendo !

**Pull request merged**
