### PR TITLE
Release v4.1.0

### PR DESCRIPTION
**Pull request by jameslamb**
### Release checklist:

Copied from #5952, with a few changes.

*before merge*

- [x] Update [VERSION.txt](https://github.com/microsoft/LightGBM/blob/master/VERSION.txt) number.
- [x] Update version in [Appveyor config file](https://github.com/microsoft/LightGBM/blob/master/.appveyor.yml).
- [x] Update version in [`configure` file of R-package](https://github.com/microsoft/LightGBM/blob/master/R-package/configure): `/gha run r-configure`.
- [x] Change `development.mode` from `unreleased` to `release` in [pkgdown config file](https://github.com/microsoft/LightGBM/blob/master/R-package/pkgdown/_pkgdown.yml).
- [x] Update version in `python-package/pyproject.toml`
- [x] Add release branch to [RTD versions](https://readthedocs.org/projects/lightgbm/versions/), trigger a new build, check docs
- [x] All docs for new behavior have Sphinx `versionadded::` annotations ([docs on those](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded))
- [x] All new parameters in `config.h` have `*New in version {version}*` comments added
    - https://github.com/microsoft/LightGBM/pull/6076/commits/daa040096443a191c6d86fb3967bcf366e029a92
- [x] Run the valgrind checks with `/gha run r-valgrind` ([docs link](https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#valgrind)) 
- [x] manually test Python and R packages on M1/M2 Mac

PRs that should be merged before releasing:

None.

*after merge*

- [ ] Push commit with `v*` tag to trigger `GitHubRelease` action at Azure Pipelines.
- [ ] Convert automatic GitHub release from `Draft` to normal one.
- [ ] Update [`stable` tag at GitHub](https://github.com/microsoft/LightGBM/releases/tag/stable).
- [ ] Add new tag to [RTD versions](https://readthedocs.org/projects/lightgbm/versions/) and trigger a new build.
- [ ] ~Upload release to [CRAN](https://cran.r-project.org/package=lightgbm)~.
    - ⚠️ blocked:
        - https://github.com/microsoft/LightGBM/pull/5952#issuecomment-1634916384
        - #5987
- [ ] Remove the release branch from RTD versions
- [ ] Upload release to [PyPI](https://pypi.org/project/lightgbm/).
- [ ] Update [cran-comments.md](https://github.com/microsoft/LightGBM/blob/master/R-package/cran-comments.md) when new release is accepted on CRAN.
- [ ] Upload release to [NuGet](https://www.nuget.org/packages/LightGBM/).
- [ ] Update version and commit hash in [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lightgbm.rb) ([docs](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md#to-submit-a-version-upgrade-for-the-foo-formula))

### Notes for Reviewers

I believe this should be `v4.1.0` instead of `v4.0.0` because of the addition of position-bias correction for learning-to-rank: #5929.

This release of the R package will not be published to CRAN, as #5987 has still not been resolved. I'll prioritize that and maybe we'll be able to release the next version to CRAN.

### CODE REVIEW

**Comment by jameslamb** [comment]
> Add release branch to [RTD versions](https://readthedocs.org/projects/lightgbm/versions/), trigger a new build, check docs

✅ docs built successfully: https://readthedocs.org/projects/lightgbm/builds/21819866/

✅ and look good to me: https://lightgbm.readthedocs.io/en/release-v4.1.0/

**Comment by jameslamb** [comment]
>  manually test Python and R packages on M1/M2 Mac

The R package passed on an M1 Mac Mini: https://mac.r-project.org/macbuilder/results/1689263124-d89c2bc709b122ea/.

**Comment by jameslamb** [comment]
I will test the Python package on my M2 mac laptop tonight. If that passes, then I think this is ready to release!

@shiyu1994 @guolinke @jmoralez Could you please review this and approve if you agree with releasing the current state of `master` as v4.1.0?

**Review by guolinke — APPROVED** [review]

**Review by shiyu1994 — APPROVED** [review]

**Comment by jameslamb** [comment]
Tested the Python package on my M2 Mac laptop today.

I had to run without OpenMP support (a documented issue in #4229 and #5764), but otherwise LightGBM compiled successfully and the Python tests passed. I'll try to work on those issues for the next release.

So with that.... I think we are ready to release!

@jmoralez since this has been up for a couple days and since both @guolinke and @shiyu1994 have approved, I won't wait for your approval... I'll merge this later today, once CI passes unless we hear any objections from you before then.

**Review by jmoralez — APPROVED** [review]

**Comment by jameslamb** [comment]
Thanks everyone! I'll merge this and start on the other release tasks.

Please don't merge anything else for the next few hours...so the automatic changelog won't get corrupted.

**Comment by jameslamb** [comment]
Ran the following to create the `v4.1.0` tag and update the `stable` tag.

```shell
git fetch upstream --tags
git tag -d stable
git push upstream :refs/tags/stable
git tag stable v4.1.0
git push upstream stable v4.1.0
```

*(NOTE: I alias this repo to `upstream` and my fork to `origin` in my `git` settings)*

https://github.com/microsoft/LightGBM/tags

Screenshot 2023-09-11 at 5 19 02 PM

That triggered an Azure DevOps build which should create the release automatically: https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=15169&view=results. This takes around 90 minutes (because of the QEMU CI job).

NOTE: I messed this up last time. In v4.0.0, I directly published the `release-drafter` release. That's why that one has the author as `release-drafter`

Screenshot 2023-09-11 at 5 21 06 PM

... while all the others have @guolinke .

image

Sorry about that! I won't make that mistake again.

**Comment by jameslamb** [comment]
> Add release notes from release-drafter to the automatically-created GitHub release, convert it from Draft to published.

This is done. The release is now officially up here on GitHub, and all artifacts from Azure DevOps have been attached to it.

image

https://github.com/microsoft/LightGBM/releases/tag/v4.1.0

**Comment by jameslamb** [comment]
> Add new tag to [RTD versions](https://readthedocs.org/projects/lightgbm/versions/) and trigger a new build.

This is done.

Passing build: https://readthedocs.org/projects/lightgbm/builds/21891719/

Docs: https://lightgbm.readthedocs.io/en/v4.1.0/

Screen Shot 2023-09-11 at 8 56 36 PM

**Comment by jameslamb** [comment]
>  put up another PR incrementing development version here in GitHub

Put up #6090

**Comment by jameslamb** [comment]
Uploaded v4.1.0 wheels and sdist to PyPI 😁

Screen Shot 2023-09-11 at 9 09 08 PM

https://pypi.org/project/lightgbm/4.1.0/

image

https://pypi.org/project/lightgbm/4.1.0/#files

**Comment by jameslamb** [comment]
> Upload release to [NuGet](https://www.nuget.org/packages/LightGBM/).

This is done

image

https://www.nuget.org/packages/LightGBM/4.1.0

**Comment by jameslamb** [comment]
> update version and commit hash in Homebrew formula

Someone else already put up a PR for this: https://github.com/Homebrew/homebrew-core/pull/142052

**Comment by jameslamb** [comment]
I think all tasks are complete, and this release is done!

Thanks so much for the help everyone, and especially @shiyu1994 for the suggestion. I'm very happy that we might start doing smaller, more frequent releases of LightGBM, and I think the project's users will be too 😁

**Pull request merged**
