### PR TITLE
Update callback.R with keyword arguments

### PR DESCRIPTION
**Pull request by philip-khor**
Addresses part of #3390. Also added `isTRUE()` for some of the logical checks, please advise if this is okay

I also had issues with generating the roxygen2 documentation: was not able to run the roxygenize step due to this error: 
```
Error in .f(.x[[i]], ...) : 
  R6 class (lgb.Booster) without source references. If you use the `installed` load method in `DESCRIPTION`, then try re-installing the package with option '--with-keep.source'. E.g. `install.packages(..., INSTALL_OPTS = "--with-keep.source")`.
```

The steps I did are as follows:
1. open LightGBM as R project in RStudio 
2. latest roxygen2 version on CRAN is 7.1.1 -> `install.packages("roxygen2")` works
3. regular 'sh' did not work: to workaround, in R console, run `system("./build-cran-package.sh")`. Did this on WSL2. 
4. build package with `R CMD INSTALL lightgbm_3.*.tar.gz` (note underscore)

### CODE REVIEW

**Comment by jameslamb** [comment]
Thanks @philip-khor !

I just fixed the typo (`lightgbm_` instead of `lightgbm.`) in #3390 , sorry about that!

I remember seeing that `{roxygen2}` error a while ago...maybe it worked differently for me because I had previous installations of `{lightgbm}` around. I just updated #3390 to include the `--with-keep.source` flag. 

<hr>

Can you clarify what it means that `sh` "did not work"?

**Review by jameslamb — APPROVED** [review]
This looks great, thank you so much for contributing!

I'd like to leave the "keyword arguments for internal functions" fix on other files from #3390 for other Hacktoberfest contributes, but if you have the time and interest we'd welcome another pull request that fixes other places where you think we should be using `isTRUE()`.

**Comment by philip-khor** [comment]
Okay that's weird, `sh build-cran-package.sh` works now. 

But I remember previously hitting errors along the lines of "missing options for set", even when I replaced it with `bash`.

**Comment by philip-khor** [comment]
> 
> 
> This looks great, thank you so much for contributing!
> 
> I'd like to leave the "keyword arguments for internal functions" fix on other files from #3390 for other Hacktoberfest contributes, but if you have the time and interest we'd welcome another pull request that fixes other places where you think we should be using `isTRUE()`.

Got it, thanks!

**Comment by jameslamb** [comment]
> Okay that's weird, `sh build-cran-package.sh` works now.
> 
> But I remember previously hitting errors along the lines of "missing options for set", even when I replaced it with `bash`.

hmmm ok, I'm not sure what could cause that. If you see it again, please open an issue and we'll take a look.

**Pull request merged**
