### PR TITLE
add boosting_type to python sklearn

### PR DESCRIPTION
**Pull request by wxchan**
solve #120

### CODE REVIEW

**Comment by guolinke** [comment]
@wxchan it cannot pass the test. Did you check the passed string of parameters?

**Comment by wxchan** [comment]
I made a mistake. It should pass the tests now.

**Comment by guolinke** [comment]
@wxchan can you re-generate the doc as well?

**Comment by wxchan** [comment]
I already add this alter to the doc.

**Comment by guolinke** [comment]
@wxchan  can you also help to test the speed and accuracy of python package, and compared with command line version? I think we can further optimize the efficient of c_api.

**Comment by wxchan** [comment]
@guolinke is there an easy-access and reproducible environment we can use to compare the performances among different languages versions? For example, on Azure? There may be more language packages in the future. It may be better to compare them under same environment.

**Comment by Allardvm** [comment]
@wxchan I'd be happy to contribute performance tests for the Julia package for comparison.

**Comment by guolinke** [comment]
@wxchan I will ask for some resources to do this.

**Pull request merged**
