### PR TITLE
minor changes to R package for robustness and efficiency

### PR DESCRIPTION
**Pull request by bfgray3**

### CODE REVIEW

**Comment by guolinke** [comment]
@Laurae2

**Comment by Laurae2** [comment]
Change back all `message` to `cat`.

`cat` should be using for the following reasons:

* It is stdout and not stderr
* Text is in R default color and not a warning/error color (red)

It also does not pass example tests (errors). Make sure you are able to run **all tests and examples** locally (both the `demo` folder, and the Rd documentation examples).

For `mget`, the issue I have with it is it returns a list of all objects existing in the global environment, which should be avoided in the case there are thousands or millions of them. Not sure if I would provide additional gains versus a vectorized `ls()` + `apply`.

I need to dig more later today, there will be more changes to do but first the R tests must pass locally.

**Comment by bfgray3** [comment]
I have reverted to `cat` from `message`.  The reason I personally prefer `message` is that it can be handled by both `suppressMessages` and `tryCatch`, giving the user more control and flexibility than something simpler, like a `verbose` argument.  I have also gotten rid of `mget`, in favor of `Filter` (which calls `lapply`), and `get`.  Can you please help me understand which tests are failing?  As of my first pull request I see all tests are green.

**Comment by Laurae2** [comment]
Due to how the library is linked to R (not using R way of printing), it is not possible to control what is printed on screen.
For instance, using sink will fail to capture LightGBM-specific messages. We may switch to message when LightGBM will hook into R headers for printing, which is not trivial with the licensing issues.

For the tests, there are no R tests running on Travis / Appyevor. Every R test (demo + examples) should be run locally to test whether it breaks or not, while giving correct results. It is why it every test looks green on the pull request.

The most important tests are on lgb.Dataset and lgb.train and lgb.cv.

**Comment by bfgray3** [comment]
I'm having a terribly hard time getting the package installed on my Windows machine.  From the `R-package` directory, I tried the following:

```
> devtools::install()
Error: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 1
> devtools::build()
Error: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 1
```

I have tried to follow the instructions on the `README.md`, but I'm stuck and can't even get the package installed to look at these tests locally.  Do you have any suggestions on how I can get this installed, or if you are able to see what tests are failing could you point me to which ones are not green?

**Comment by Laurae2** [comment]
@bfgray3 

> if you are able to see what tests are failing could you point me to which ones are not green?

I only tested `lgb.train` and it did not run successfully.

> I'm stuck and can't even get the package installed to look at these tests locally

You need cmake installed and available in PATH. On Windows machine, you also need Rtools installed and available in PATH.

**Comment by bfgray3** [comment]
Thanks for the pointers @Laurae2.  I still cannot get the package loaded.  As shown by the below output, I have both cmake and Rtools installed and available in my PATH:

```
> all(vapply(c("cmake", "rtools"), grepl, logical(1), x = Sys.getenv()[["PATH"]], ignore.case = TRUE))
[1] TRUE
```

I get the following, among other output, when running `devtools::load_all(".")`.  Do you know what might be the cause?  It seems that cmake doesn't like one of the files in a subdirectory of Rtools.

```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:9 (PROJECT):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:9 (PROJECT):
  No CMAKE_CXX_COMPILER could be found.

Warning: running command 'cmake  -G "Visual Studio 12 2013 Win64" ..' had status 1
CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeMinGWFindMake.cmake:12 (message):
  sh.exe was found in your PATH, here:

  C:/Rtools/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.
```

**Comment by Laurae2** [comment]
The warning about Rtools can be ignored as it is expected when using Rtools with cmake.

**Comment by bfgray3** [comment]
I am having trouble with the following error when running `devtools::check(".")`, but I did discover and fix a bug I had introduced in `lgb.stratified.folds`.

```
[100%] Linking CXX shared library ..\lib_lightgbm.dll
[100%] Built target _lightgbm
Found library file: <filepath>/LightGBM/R-package/src/lib_lightgbm.dll to move to <filepath>/AppData/Local/Temp/Rtmp4UgMvG/devtools_install_ed49337be/lightgbm/libs/x64* DONE (lightgbm)
Loading required package: R6
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object '<filepath>/LightGBM/R-package/src/lib_lightgbm.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.
```

**Comment by guolinke** [comment]
@Laurae2 ping me when this is ready to merge.

**Comment by bfgray3** [comment]
I think it should be ready to go now.

**Pull request merged**
