### PR TITLE
[python-package] lambdarank cv split by group

### PR DESCRIPTION
**Pull request by wxchan**
#390 

it's strange that it sometimes causes segmentation fault (1 of 3 times), cannot figure out why yet

### CODE REVIEW

**Comment by guolinke** [comment]
@wxchan 
it happens after this PR or before ?

**Comment by guolinke** [comment]
@wxchan 
Check the length of `used_indices` at this line: https://github.com/Microsoft/LightGBM/blob/master/src/io/sparse_bin.hpp#L337 ?

**Comment by wxchan** [comment]
@guolinke 
seem the error is before this pr

the following codes cause segfault with current master branch:
```
import numpy as np
import lightgbm as lgb
from sklearn.datasets import load_svmlight_file
X_train, y_train = sklearn.datasets.load_svmlight_file('../../examples/lambdarank/rank.train')
q_train = np.loadtxt('../../examples/lambdarank/rank.train.query')
params = {'objective': 'lambdarank', 'verbose': -1}
lgb_train = lgb.Dataset(X_train, y_train, group=q_train, params=params)
lgb.cv(params, lgb_train, num_boost_round=20, nfold=5, metrics='l2', verbose_eval=False)
```

it happens when the length of subsets smaller than some number, for example, `lgb.cv(params, lgb_train, num_boost_round=20, nfold=5, metrics='l2', verbose_eval=False)` will not cause any error

**Comment by guolinke** [comment]
@wxchan fixed in the latest commit.

**Pull request merged**
