### PR TITLE
[ci] add support for 8.0 and 8.6 CUDA archs

### PR DESCRIPTION
**Pull request by StrikerRUS**
https://en.wikipedia.org/wiki/CUDA#GPUs_supported

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@jameslamb Could you please take a look at the failing Dask test? I don't believe that failure is related to the changes in this PR. Looks like some collisions in random ports search algorithm again.

**Comment by jameslamb** [comment]
> @jameslamb Could you please take a look at the failing Dask test? I don't believe that failure is related to the changes in this PR. Looks like some collisions in random ports search algorithm again.

thanks for letting me know!

I looked into it today and opened #4458 for us to discuss further. I think this is a random problem and this PR will be unblocked by re-running CI.

**Review by jameslamb — COMMENTED** [review]
Looks ok to me based on that link you provided, thanks!

But before I approve, could you merge in `master` to get the changes from #4453? Since I think they're closely related.

**Comment by StrikerRUS** [comment]
@jameslamb Sure, merged.

**Review by jameslamb — APPROVED** [review]
Looks good to me! I don't see any new warnings in logs for CUDA CI jobs.

Not merging just in case you want an approval from another reviewer who is more familiar with CUDA (but it's ok with me if you merge this without another such approval).

**Comment by StrikerRUS** [comment]
@jameslamb Thank you! I think this PR is quite straightforward to require a second review.

**Pull request merged**
