### PR TITLE
Fix R Tree Parse

### PR DESCRIPTION
**Pull request by yanyachen**
This PR will fix the `lgb.model.dt.tree` function so that `lgb.interprete` function can use column: leaf_parent.

I'm sorry @Laurae2 , I saw your PR very late.

### CODE REVIEW

**Comment by guolinke** [comment]
@yanyachen leaf_parent is needed ?

**Comment by yanyachen** [comment]
Yes, it's needed by the `lgb.interprete` for finding tree decision path.

**Comment by guolinke** [comment]
@yanyachen 
sorry, I remove it in this commit: https://github.com/Microsoft/LightGBM/commit/cc83cd6757824f1ee161260bc57384470a7a077e 
maybe you need add it back in tree.cpp .

**Comment by yanyachen** [comment]
No, I think it's OK, as long as all the information about the tree path is there. And I think the model dump right now is clear and better. 
I can modify `lgb.model.dt.tree` later to better adopt your new change.

**Comment by guolinke** [comment]
@yanyachen any updates ?

**Comment by yanyachen** [comment]
Sorry, I'm busy on work these days, will try to finish in this weekend.

**Comment by yanyachen** [comment]
Already committed and rebased, please review, thanks.
Sorry for late.

**Comment by guolinke** [comment]
@yanyachen Thanks very much

**Pull request merged**
