### PR TITLE
Improve training speed in parallel learning where workers is not powers of 2

### PR DESCRIPTION
**Pull request by qrqpjxq**
Improve training speed in parallel learning where workers is not powers of 2

### CODE REVIEW

**Comment by guolinke** [comment]
Thanks for the contribution. 
Do you use the recursive-halving for the non-power-of-2 machines ? 
Actually, we have this before, but it is not efficient compared with the pair wise exchange. 
https://github.com/Microsoft/LightGBM/commit/7737b45e10203718ec682347d39524f436de3d01#diff-826309c5e7db10774b5a8999984b5ded

The reason, it has two additional process ( some nodes need to send/receive all data from its neighbor), and all other nodes are idle in this additional process, as a result, the overall time cost will be about 3x than the recursive-halving of power-of-2. 

Though simple pair wise algorithm needs n-1 time communication, but it doesn't have additional cost. 
Thus, it will be faster than the recursive-halving when machine is not power-of-2 .

**Comment by qrqpjxq** [comment]
I tried in our cluster, num_data is 7000w; num_features is 30; tree configuration: num_trees=50; num_leaves=512
when set:
num_workers = 64 it take 218s
num_workers = 65 it take 221s
num_workers = 127 it take 178s
if use pair wise algorithm, num_workers = 65 it take 1022s
(training time is relation to cluster load)
It seems in our cluster recursive-halving is faster, i don't know if just recursive-halving method work better in our environment.

**Comment by guolinke** [comment]
@qrqpjxq okay, i see. 
I think the reason the num_featrues is 30 in you tasks. 
As a result, the communication volume is very small. So the communication times will be a largest cost in your task. 

As a result, I think a better solution is:
1. when communication volume is large, we use the pair-wise solution. 
2. when communication volume is small, we use the allgather to got all data from all machines, and do the reduce scatter locally.  

What do you think ?

**Comment by qrqpjxq** [comment]
I think your idea will work well, can have a try.
and there are two cases if have any reference value：
1. in my test, num_features=30 and num_bins=9600(about, some feature is category)
2. before now, i have try AllreduceByAllGather to instead ReduceScatter(have redundant reduce compute locally) when workers is not power of 2, and training time reduce a litter.

**Comment by guolinke** [comment]
@qrqpjxq sounds good. 
The process of recursive halving when non-power-of-2 is not so elegant. 
We can decide a threshold, for example, num_bins < 10000 (total communication size is about 200,000KB), And use the AllreduceByAllGather in that case.
Could you help for this ?

**Comment by qrqpjxq** [comment]
Ok, i will try it.
But in paper "optimization of collective communication operations in mpich"(52), it use bruck algorithm(AllreduceByAllGather used it) when total data gathered < 80KB.

**Comment by guolinke** [comment]
@qrqpjxq I think the threshold could be changed. we also can let it configurable ( put it in the parameters.)

**Comment by guolinke** [comment]
@qrqpjxq updates ?

**Comment by qrqpjxq** [comment]
i'm sorry for forget reply you. i'm very busy these days. i will do it in the latter days of holiday, or if you have time, can you do it?

**Comment by guolinke** [comment]
@qrqpjxq It is not urgent. We can wait you to do this.

**Comment by guolinke** [comment]
@qrqpjxq updates ?

**Pull request closed without merging**
