### PR TITLE
[ci] fix R tests for macOS on Azure Pipelines

### PR DESCRIPTION
**Pull request by StrikerRUS**
Fix current `master` fails.
Have no idea why it started to fail:
```
* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked

** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c capture.c -o capture.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c export.c -o export.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c internal.c -o internal.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c lib.c -o lib.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c version.c -o version.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o rlang.so capture.o export.o internal.o lib.o version.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: malformed file
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd:4:18: error: unknown enumerated scalar
platform:        zippered
                 ^~~~~~~~
 file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [rlang.so] Error 1
ERROR: compilation failed for package ‘rlang’
```
Refer to https://github.com/golang/go/issues/31159#issuecomment-481910401.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@jameslamb Oops! Didn't see we already have an issue for that. Just noticed failed `master` and googled the hotfix 😄 

Fixed #2856.

**Comment by StrikerRUS** [comment]
Not sure that this fix is fully correct:
```
ld: warning: URGENT: building for OSX, but linking against dylib (/usr/lib/libc++.dylib) built for (unknown). Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking against dylib (/usr/lib/libSystem.dylib) built for (unknown). Note: This will be an error in the future.
```
(this is for the main library and it can potentially break our artifacts).
I think we should ping someone from Azure team to know what they have changed that we started encounter this error.

**Comment by guolinke** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

**Comment by guolinke** [comment]
BTW, it seems xcode9.4.1 is not supported in macos10.14. https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#installed-sdks

**Comment by StrikerRUS** [comment]
@guolinke 
> BTW, it seems xcode9.4.1 is not supported in macos10.14.

It is: https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xcode
image

SDKs are something different: https://travis-ci.community/t/catalina-and-xcode-11-1-support/5392/2

**Comment by StrikerRUS** [comment]
Tried to install 10.13 SDK `macOS_SDK_headers_for_macOS_10.13.pkg` - the same error as before. I guess we need either something like #2752, or fix at Azure side.

**Comment by StrikerRUS** [comment]
OK, due to we have some problems building R packages from sources on macOS (refer to #2752 and https://github.com/microsoft/LightGBM/pull/2856#issue-382627276), I'm going to hotfix this by forcing installation of **binary** packages for macOS (even if they are a little bit outdated compared to CRAN sources).

@jameslamb Please feel free to propose a better long-term fix when you'll have time, but I'll merge this PR right after green CI checks as it blocks all other PRs.

**Comment by jameslamb** [comment]
> OK, due to we have some problems building R packages from sources on macOS (refer to #2752 and [#2856 (comment)](https://github.com/microsoft/LightGBM/pull/2856#issue-382627276)), I'm going to hotfix this by forcing installation of **binary** packages for macOS (even if they are a little bit outdated compared to CRAN sources).
> 
> image
> 
> @jameslamb Please feel free to propose a better long-term fix when you'll have time, but I'll merge this PR right after green CI checks (your outdated approval will allow me to do that 😃 ) as it blocks all other PRs.

totally fine with me, thank you!

**Pull request merged**
