### PR TITLE
[WIP] expose 'load/save model from/to string' to c_api

### PR DESCRIPTION
**Pull request by wxchan**

### CODE REVIEW

**Comment by wxchan** [comment]
@guolinke why there is no boosting_type (gbdt or dart) in model file now? only 'tree'.

**Comment by guolinke** [comment]
because they both train trees. I think the trees trained by dart should can be loaded by gbdt as well. Maybe we can change name "boosting_type" to "submodel_type".

**Comment by wxchan** [comment]
@guolinke so both gbdt and dart are just training methods. All the model loaded from file (or string) are treated as gbdt? Then for my current code, boosting_type in `Booster(const char* boosting_type, const char* model_str)` is not needed?

**Comment by guolinke** [comment]
@wxchan I think it is not need. And if we really need it, we can read it from model_str.

**Comment by wxchan** [comment]
@guolinke I finished this pr. You can review it.

**Pull request merged**
