### PR TITLE
[ci] prevent `categorical.model` and `model.txt` files being left behind after testing

### PR DESCRIPTION
**Pull request by neNasko1**
Contributes to #6361.

This PR prevents `categorical.model` and `model.txt` being left after executing pytest by using the `tmp_path` fixture, as suggested in the linked issue.

### CODE REVIEW

**Comment by neNasko1** [comment]
@jameslamb this a fix of the issue you linked as a good-first-issue in #6586

**Comment by neNasko1** [comment]
> Thanks! This looks great.
> I've merged latest master into this, to be sure it's being tested against the latest code.

Thanks for the time taken! 

An R test is failing with a what seems to me connectivity error. Is that the case?:
```
Downloading https://github.com/microsoft/LightGBM/releases/download/v2.0.12/rtools43-5550-5548.exe
Invoke-WebRequest: D:\a\LightGBM\LightGBM\.ci\test-r-package-windows.ps1:12
Line |
  12 |      Invoke-WebRequest -Uri $url -OutFile $destfile
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | One or more errors occurred. (The response ended prematurely. (ResponseEnded))
Error: Process completed with exit code 1.
```

**Comment by jameslamb** [comment]
Yeah I think you're right that that's a temporary networking-related issue. I just manually re-triggered it.

**Comment by jameslamb** [comment]
Thanks for the help!

**Pull request merged**
