### PR TITLE
[docs] Add installation instructions using MacPorts

### PR DESCRIPTION
**Pull request by Mottl**

### CODE REVIEW

**Comment by StrikerRUS** [comment]
**Blocked** due to the **conflict** with #1522.

The installation guide is rather large, so I'm not sure that changes `brew` -> `port` desire the own section in the guide. They are unrelated to the LightGBM installation process :-/
I suppose that a note like "replace `brew` command with `port` is you are using MacPorts" will be enough.

**Comment by chivee** [comment]
@StrikerRUS, maybe we can using < details > ?

**Comment by StrikerRUS** [comment]
@chivee I like your idea! Also, we can add `Contents` section for better navigation. I can take this, after merging #1522.

However, I still think that for `brew` -> `port` a note will be enough.

**Comment by StrikerRUS** [comment]
Closed as stale.

**Pull request closed without merging**
