### PR TITLE
v2.3.0 realese

### PR DESCRIPTION
**Pull request by guolinke**
@StrikerRUS @Laurae2 @jameslamb @henry0312 
Which PRs should be included in this release ?

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@guolinke Yeah, just wanted to create an issue about new release. You're reading my thoughts! 😄 

I'd like to include:
- [ ] #2127 as a bug fix,
- [ ] #2043 as a visual addition for a new feature #2041,
- [ ] #2071 as a bug fix.

Also it's will be cool to fix issue #1990 before new release.

P.S. Please check recent messages in Slack channel.

**Comment by jameslamb** [comment]
LGTM. I have nothing to add for this release beyond what @StrikerRUS has noted

**Comment by Laurae2** [comment]
@guolinke We can also include #2159 in 2.2.4 as it fixes a major bug in the best score returned by the LightGBM booster.

- [ ] #2159 [R-package] Fix best_iter and best_score

**Comment by chivee** [comment]
adding a reference to #2190.

**Comment by StrikerRUS** [comment]
I think we have a lot of new features, behavior changes, etc. to label new release as `2.3.0`. WDYT guys?

**Comment by guolinke** [comment]
@StrikerRUS sure, could you make the change?

**Comment by StrikerRUS** [comment]
Also, I'd like to merge

- [ ] #2304

 before the release. It's ready and awaiting second reviewer.

**Comment by StrikerRUS** [comment]
I guess the main reason of such long delay #2209 is almost ready. Can we try to review and merge the following PRs before new release as well?
- [ ] #2391 (as default value, which affects only appearance, changer)
- [ ] #2383 (as memory saver)
- [ ] #2381 (as continuation of work on new unreleased feature)
- [ ] #2325 (as new feature)

**Comment by jayantsahewal** [comment]
Is there a tentative target date for this release? There are a few critical bugs which have been fixed and merged in master months ago but haven't been released yet.

**Comment by guolinke** [comment]
@jayantsahewal sorry, we will move fast for the rest PRs.
@StrikerRUS let us target it before 1 OCT?

**Comment by StrikerRUS** [comment]
@guolinke Sure! Let's try!

Please don't forget to add a Git tag `v2.3.0` in order to trigger changelog generation:
https://github.com/microsoft/LightGBM/blob/7b2963d9a5c4d6b90ce7bbf58eefb86ca089b229/.vsts-ci.yml#L170-L172

**Comment by StrikerRUS** [comment]
Wow, all blocking PRs have been merged! 🎉

**Comment by guolinke** [comment]
I will create a release soon.

**Comment by jayantsahewal** [comment]
You guys rock! Thank you so much for getting this release out!!

**Comment by StrikerRUS** [comment]
@jayantsahewal Thank you and all users for your patience! We are very sorry about the long delay with this release.

**Comment by StrikerRUS** [comment]
@ankane Sorry for bothering you! Can you please help us to bump the version of LightGBM in Homebrew for the first time? [Their docs say](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-submit-a-version-upgrade-for-the-foo-formula) that `brew` should be used for that. But what if I have no macOS? Can I simply edit `url` and `sha256` fields manually?

**Comment by ankane** [comment]
@StrikerRUS You can edit it manually and submit a PR. The brew command is just a shortcut for it.

**Comment by ankane** [comment]
Example PR: https://github.com/Homebrew/homebrew-core/pull/44644

**Comment by StrikerRUS** [comment]
@ankane Thanks! I've created: https://github.com/Homebrew/homebrew-core/pull/44685.

**Comment by ankane** [comment]
Looks great. I think something is wrong with the Homebrew build system (some PRs haven't been built from 5 days ago), so there may be some delay.

**Comment by chris-smith-zocdoc** [comment]
Should there have been a corresponding java release (lightgbmlib) with this @guolinke ? The latest I see on maven.org is `2.2.400` from August https://search.maven.org/search?q=g:com.microsoft.ml.lightgbm

**Comment by StrikerRUS** [comment]
@chris-smith-zocdoc We released JAR files here in our repo: https://github.com/microsoft/LightGBM/releases/tag/v2.3.0. For maven update, ping @imatiach-msft .

**Pull request merged**
