### PR TITLE
[ci] fix installation of clang-18 (fixes #6306)

### LINKED ISSUE #6306: [ci] [R-package] clang-18 jobs failing:  Unable to locate package clang-18
## Description

CI jobs across multiple PRs have been failing like this for the last few days:

```text
Reading state information...
E: Unable to locate package clang-18
E: Unable to locate package clangd-18
E: Unable to locate package clang-format-18
E: Unable to locate package clang-tidy-18
E: Unable to locate package clang-tools-18
E: Unable to locate package lldb-18
E: Unable to locate package lld-18
E: Unable to locate package llvm-18-dev
E: Unable to locate package llvm-18-tools
E: Unable to locate package libomp-18-dev
E: Unable to locate package libc++-18-dev
E: Couldn't find any package by regex 'libc++-18-dev'
E: Unable to locate package libc++abi-18-dev
E: Couldn't find any package by regex 'libc++abi-18-dev'
E: Unable to locate package libclang-common-18-dev
E: Unable to locate package libclang-18-dev
E: Unable to locate package libclang-cpp18-dev
E: Unable to locate package libunwind-18-dev
Error: Process completed with exit code 100.
```

## Reproducible example

Example build from #6301: https://github.com/microsoft/LightGBM/actions/runs/7795162057/job/21344942028?pr=6301

This is only happening with `clang-18` specifically.

## Additional Comments

Instructions for installing development versions of LLVM: https://apt.llvm.org/

This failing CI job was added in #6265 about 3 weeks ago, and has been working since then.

### PR DESCRIPTION
**Pull request by jameslamb**
Fixes #6306

These modifications are based on the "Debian" section at https://apt.llvm.org/.

### CODE REVIEW

**Review by jmoralez — APPROVED** [review]

**Review by shiyu1994 — APPROVED** [review]

**Comment by shiyu1994** [comment]
It seems that the Mariner Linux agent fails to start again in this CI. Let's check if this happens more frequently than before and to decide whether to take some actions.

**Comment by jameslamb** [comment]
> It seems that the Mariner Linux agent fails to start again in this CI.

Thanks for pointing that out @shiyu1994 , yes I agree. Over the last few weeks, I think I've had to restart at least one Azure DevOps job on almost every commit. I'll try to capture more logs the next time I see that, maybe we can find the root cause.

**Comment by jameslamb** [comment]
thanks for the quick response everyone!

**Comment by jameslamb** [comment]
I just saw a few more of these: https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=15757&view=results

```text
Starting: Initialize job
Agent name: 'lgbub6c5400017H'
Agent machine name: 'lgbub6c5400017H'
Current agent version: '3.232.3'
Agent running as: 'AzDevOps'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: 1ESHostedPoolValidation (1.0.26350327)
Downloading task: CmdLine (2.231.1)
Downloading task: Bash (3.231.5)
Downloading task: PublishBuildArtifacts (1.231.1)
Downloading task: ComponentGovernanceComponentDetection (0.2420208.1)
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: AgentEnablePipelineArtifactLargeChunkSize = true Source: $(AGENT_ENABLE_PIPELINEARTIFACT_LARGE_CHUNK_SIZE) 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
   Knob: ProcessHandlerTelemetry = true Source: $(AZP_75787_ENABLE_COLLECT) 
   Knob: IgnoreVSTSTaskLib = true Source: $(AZP_AGENT_IGNORE_VSTSTASKLIB) 
   Knob: FailJobWhenAgentDies = true Source: $(FAIL_JOB_WHEN_AGENT_DIES) 
   Knob: CheckForTaskDeprecation = true Source: $(AZP_AGENT_CHECK_FOR_TASK_DEPRECATION) 
   Knob: MountWorkspace = false Source: $(AZP_AGENT_MOUNT_WORKSPACE) 
Finished checking job knob settings.
##[error]File not found: 'docker'
```

**Comment by jameslamb** [comment]
opened #6316 so we can discuss the CI instability there

**Pull request merged**
