### PR TITLE
[python-package] prefix cast_numpy_array_to_dtype with _

### PR DESCRIPTION
**Pull request by Madnex**
Contributes to https://github.com/microsoft/LightGBM/issues/5313

### CODE REVIEW

**Comment by jameslamb** [comment]
@Madnex , I think you might want to change the commit on this PR prior to it being merged.

Screen Shot 2022-10-10 at 10 13 28 PM

Do you see how the profile picture from your GitHub account isn't displayed? That means that you do not have your email set in your `~/.gitconfig` to one that is tied to your GitHub account.

See the suggestions in https://github.com/microsoft/LightGBM/pull/3607#issuecomment-735358654 for how to fix this.

**Review by jameslamb — APPROVED** [review]
looks good to me, thanks! I'll wait a few days to hear if you want to fix the commit attribution before merging this.

**Comment by Madnex** [comment]
Thanks for the tipp! I added my email in the git config :)

**Comment by jameslamb** [comment]
commits look good to me, thanks!

> For the next changes in basic.py should I keep creating PRs for each function

It's ok to start grouping a few together in each PR, now that you've done a few of these.

Thanks very much for your help with this project!

**Pull request merged**
