### PR TITLE
[python][tests] small Python tests cleanup

### PR DESCRIPTION
**Pull request by StrikerRUS**
- Rename temp model file to not overcomplicate `.gitignore`.
- Reduce code duplication in params definition.
- Use asserts from `unittest` module for consistency with the rest codebase.

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
I personally have a preference for `assert` with an arbitrary expression instead of the added indirection of the unittest builtins, but I wont block this PR

**Comment by StrikerRUS** [comment]
@jameslamb 
This looks like a "good first issue" to rewrite **all** tests removing `unittest` dependency and referring [`test_dask.py`](https://github.com/microsoft/LightGBM/blob/master/tests/python_package_test/test_dask.py) and [`test_dual.py`](https://github.com/microsoft/LightGBM/blob/master/tests/python_package_test/test_dual.py) as examples. WDYT?

**Comment by jameslamb** [comment]
I agree! I can write it up

**Comment by StrikerRUS** [comment]
Thanks! Please do it. 🙂

**Comment by jameslamb** [comment]
> Thanks! Please do it.

added #3732. Feel free to edit it if there's anything you'd like to change.

**Comment by StrikerRUS** [comment]
Thank you!

**Pull request merged**
