### PR TITLE
Fix compilation problems with MSVC

### PR DESCRIPTION
**Pull request by huanzhang12**
This PR is trying to fix compilation problems in GPU code with MSVC 2015, in issue #439.
@tt83 Can you test if it removes all warnings?
For the long string literal problem I am still trying to figure out a clean resolution.

### CODE REVIEW

**Comment by tt83** [comment]
Forgot to mention about OpenMP issue. MSVC implementation of OpenMP allows only signed int type as loop parameter, but in one place unsigned int is used, so compiler generates error.
Most warnings are eliminated. Some other warnings (line numbers slightly differ):
```
gpu_tree_learner.cpp(111): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
gpu_tree_learner.cpp(367): warning C4456: declaration of 'i' hides previous local declaration
gpu_tree_learner.cpp(377): warning C4456: declaration of 'i' hides previous local declaration
gpu_tree_learner.cpp(538): warning C4456: declaration of 'i' hides previous local declaration
gpu_tree_learner.cpp(590): warning C4101: 'e': unreferenced local variable
gpu_tree_learner.cpp(605): warning C4101: 'e': unreferenced local variable
gpu_tree_learner.cpp(620): warning C4101: 'e': unreferenced local variable
gpu_tree_learner.cpp(198): warning C4100: 'is_feature_used': unreferenced formal parameter

```

**Comment by huanzhang12** [comment]
@tt83 Can you test if it everything is fine now?
I am also trying to workaround the C2026 error by string concatenation in commit 3e6e2ab. Can you test if it works on VS 2015?

**Comment by tt83** [comment]
Yep. All is ok now.

**Comment by huanzhang12** [comment]
@tt83 That's great! Thanks for testing it on MSVC!
@guolinke This PR is ready to merge now ;)

**Comment by tt83** [comment]
You are welcome.
Is it make sense to support number of bins > 256? I got this on my data (LightGBM v1):
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Check failed: num_bin_ <= max_bin at LightGBM/src/io/bin.cpp, line 195 .
```
And I had to increase number of bins. Is it ok ?
Sorry for offtopic.

**Comment by guolinke** [comment]
@tt83 Did you use the categorical feature? 
It is the bug in V1. You can just remove this line(line 195).

**Comment by tt83** [comment]
@guolinke Yes, I used categorical feature. So is it bug or is it normal for categorical data?

**Comment by guolinke** [comment]
it is normal for the categorical feature. we didn't limit its max_bin .

**Pull request merged**
