### PR TITLE
WIP: [CUDA] New CUDA version

### PR DESCRIPTION
**Pull request by shiyu1994**
Current GPU and CUDA versions of LightGBM only calculate histograms on GPU. This is a new CUDA version for LightGBM which runs the whole training process on GPU.

### CODE REVIEW

**Comment by guolinke** [comment]
That is amazing! Thank you @shiyu1994

**Review by jameslamb — COMMENTED** [review]
Whoa!! Didn't know you were working on this, amazing!!! 🚀 

This is a very large amount of new code to review. Is it possible to break it up into multiple PRs? For example, could the predictor changes and the training changes be separated?

It would also be helpful to go through the diff and look for other unrelated or small changes to move to separate PRs. For example, whitespace-only changes like this one:

image

**Comment by StrikerRUS** [comment]
This is awesome! 🚀 

> This is a very large amount of new code to review. Is it possible to break it up into multiple PRs?

👍 

Also, I noticed some occurrences of debugging code like `Log::Warning`s or `NewCUDATreeLearner` used by default and commented code left in this PR. I think it's better to clean them up.

Will current CUDA implementation and new one coexist for some time? Or what's a plan?

image

image

I think it will also make sense to ping @ChipKerchner and @austinpagan who contributed original CUDA implementation.

**Comment by shiyu1994** [comment]
@jameslamb @StrikerRUS I'll decompose this PR into three parts: tree learner, objective and metric, and predictor. I think we should release a stable version before the new CUDA version.

**Comment by shiyu1994** [comment]
One option would be to keep the old cuda version as `cuda_hist`, and the new cuda version as `cuda` in the device type parameter.

**Comment by guolinke** [comment]
> One option would be to keep the old cuda version as `cuda_hist`, and the new cuda version as `cuda` in the device type parameter.

I think `cuda_hist` name may cause confusing, it makes `cuda` is like the not hist version.

**Comment by StrikerRUS** [comment]
@shiyu1994 
> One option would be to keep the old cuda version as `cuda_hist`, and the new cuda version as `cuda` in the device type parameter.

Does new version reuse current CUDA histograms building code?

**Comment by shiyu1994** [comment]
@StrikerRUS No, there's no dependence on the old CUDA histogram code.

**Comment by StrikerRUS** [comment]
@shiyu1994 Maybe then we can name new version as `cuda_exp` (from `experimental`, or any other better naming) and after some number of releases remove current `cuda` code and rename `cuda_exp` into normal `cuda`?

**Comment by shiyu1994** [comment]
@StrikerRUS I agree. Let's add the new CUDA version as `cuda_exp` for some versions, and replace the old CUDA version with it until it stabilizes.

**Comment by GeorgePearse** [comment]
How can I build this branch?

**Comment by shiyu1994** [comment]
@GeorgePearse Thanks for using LightGBM. To build this branch, you may clone from https://github.com/shiyu1994/LightGBM/tree/cuda-new-refactor-2 and follow the build instruction of LightGBM CUDA version here. https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-cuda-version-experimental
Note that this is still a in-progress PR and there may be some bugs remain to be fixed.

**Comment by GeorgePearse** [comment]
@shiyu1994 Thanks! Just need to try to find the fastest training model possible. Stability not a worry. Is it useful for me to add any bugs I encounter here? Or is there good enough test coverage that I'll just be restating what's already known.

**Comment by shiyu1994** [comment]
@GeorgePearse Yes, if you find any bug you may post it here. There are some features that CUDA version of this branch does not support, including training with categorical features. Other additional features during training, like monotonic constraints, extremely random trees are not supported.

I'm not working with #4630, which only dispatches the tree learner part to CUDA. That branch is relatively more complete. I'll finish #4630 first, and then merge additional contents in this PR.

Thanks for your support.

**Comment by jameslamb** [comment]
> I'm now working with https://github.com/microsoft/LightGBM/pull/4630, which only dispatches the tree learner part to CUDA. That branch is relatively more complete. I'll finish https://github.com/microsoft/LightGBM/pull/4630 first, and then merge additional contents in this PR.

@shiyu1994 is it still your plan to merge `master` into this PR branch? Or should this be closed and new PRs opened for additional CUDA changes.

**Comment by shiyu1994** [comment]
> Or should this be closed and new PRs opened for additional CUDA changes.

@jameslamb I believe we should close this. I'll open additional PRs for the rest CUDA work. Thanks!

**Pull request closed without merging**
