### PR TITLE
Fix SingleRowPredictor::IsPredictorEqual comparison (invert)

### PR DESCRIPTION
**Pull request by AlbertoEAF**
This fixes the issue https://github.com/microsoft/LightGBM/issues/2798.

As stated in that issue, this should fix the bug in case the parameters change, and improve performance when they don't.

Please give me feedback if I'm doing anything in a less than desirable way.

### CODE REVIEW

**Comment by guolinke** [comment]
ping @imatiach-msft to confirm

**Comment by imatiach-msft** [comment]
@AlbertoEAF great catch, this should improve performance during scoring.  The main bugfix that introduced this bug was changing the correctness from:
(single_row_predictor_.get() == nullptr)
to:
single_row_predictor_[predict_type].get() == nullptr
so that when calling raw predict and predict for probabilities the function would return the correct values, but it looks like now we are not re-using the cached predictor which is horrible.  Sorry I introduced this performance issue after fixing the correctness issue before.

"worse, not creating a new one if conditions change"
I don't think this can happen from someone using mmlspark which is calling those APIs (since the model is immutable after it is trained) but this is definitely something that could help anyone who is using the native API directly, although I'm not aware of anyone other than mmlspark using LGBM_BoosterPredictForMatSingleRow and LGBM_BoosterPredictForCSRSingleRow.  Regardless this is a great fix, and thank you for sending it out!

**Comment by imatiach-msft** [comment]
also adding @eisber for context who added the original optimizations, it looks like his optimizations of improving scoring by 3-4X are missing in latest mmlspark

**Comment by AlbertoEAF** [comment]
Thank you @matiach-smft :)

Regarding no one else using the native API, I'm working on a solution that uses it for high throughput low latency scoring. If I can help a bit this project great, I'd like to learn and help more :)

**Pull request merged**
