### PR TITLE
Change cxx standard from 11 to 14 in CMake

### PR DESCRIPTION
**Pull request by SpinEch0**
compile in macos with clang15 failed when cxx11 in cmake because enable_if_t is available since c++14

### CODE REVIEW

**Comment by SpinEch0** [comment]
@jameslamb Hi, my environment info:
os: 
macOS 14.3
clang:
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.3.0
Thread model: posix

when I compile with no modifications, there are some errors:
```
mkdir build
cd build && cmake ..
make -j8
# errors:
LightGBM/external_libs/eigen/Eigen/src/Core/util/Meta.h:310:22: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'fmt::enable_if_t'?
struct array_size<T, std::enable_if_t<((T::SizeAtCompileTime & 0) == 0)>> {
                     ^~~~~~~~~~~~~~~~
                     fmt::enable_if_t
```
In [https://en.cppreference.com/w/cpp/types/enable_if](https://en.cppreference.com/w/cpp/types/enable_if), it saided that enable_if_t is since c++14:

<h3 style="color: rgb(0, 0, 0); background: none rgb(255, 255, 255); font-weight: bold; margin: 0px 0px 0.3em; overflow: hidden; padding: 1.1em 0px 0.2em 0.75em; border-bottom: none; width: auto; font-size: 16.896px; font-family: DejaVuSans, &quot;DejaVu Sans&quot;, arial, sans-serif; font-style: normal; font-variant-ligatures: no-common-ligatures; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="mw-headline" id="Helper_types">Helper types</span></h3>
template< bool B, class T = void >using enable_if_t = typename enable_if<B,T>::type; |   | (since C++14)

**Comment by jameslamb** [comment]
Thanks for the details. I'm not able to replicate that.

I just compiled the latest version of LightGBM on an M2 macOS laptop (very similar to your setup).

```shell
git clone \
    --recursive \
    https://github.com/microsoft/LightGBM.git \
    /tmp/LightGBM

cd /tmp/LightGBM
cmake -B build -S .
cmake --build build
```

Compilation of LightGBM succeeded, using a very similar version of AppleClang to the one you're using.

<details><summary>configure logs (click me)</summary>

```shell
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Found OpenMP_C: -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include (found version "5.0") 
-- Found OpenMP_CXX: -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Performing Test MM_PREFETCH
-- Performing Test MM_PREFETCH - Failed
-- Performing Test MM_MALLOC
-- Performing Test MM_MALLOC - Success
-- Using _mm_malloc
-- Configuring done (0.9s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/LightGBM/build
```

</details

<details><summary>Build logs (click me)</summary>

```text
[  2%] Building CXX object CMakeFiles/lightgbm_capi_objs.dir/src/c_api.cpp.o
[ 10%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/config_auto.cpp.o
[ 10%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/bin.cpp.o
[ 10%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/config.cpp.o
[ 12%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/dataset.cpp.o
[ 15%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/dataset_loader.cpp.o
[ 17%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/file_io.cpp.o
[ 20%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/json11.cpp.o
[ 23%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/metadata.cpp.o
[ 23%] Built target lightgbm_capi_objs
[ 25%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/parser.cpp.o
[ 28%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/train_share_states.cpp.o
[ 30%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/io/tree.cpp.o
[ 33%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/metric/dcg_calculator.cpp.o
[ 35%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/metric/metric.cpp.o
[ 38%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/network/linker_topo.cpp.o
[ 41%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/network/linkers_mpi.cpp.o
[ 43%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/network/linkers_socket.cpp.o
[ 46%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/network/network.cpp.o
[ 48%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/objective/objective_function.cpp.o
[ 51%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/treelearner/data_parallel_tree_learner.cpp.o
[ 53%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/treelearner/feature_histogram.cpp.o
[ 56%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/treelearner/feature_parallel_tree_learner.cpp.o
[ 58%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/treelearner/gpu_tree_learner.cpp.o
[ 61%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/treelearner/gradient_discretizer.cpp.o
[ 64%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/treelearner/linear_tree_learner.cpp.o
[ 66%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/treelearner/serial_tree_learner.cpp.o
[ 69%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/treelearner/tree_learner.cpp.o
[ 71%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/treelearner/voting_parallel_tree_learner.cpp.o
[ 74%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/utils/openmp_wrapper.cpp.o
[ 89%] Built target lightgbm_objs
[ 94%] Linking CXX shared library /tmp/LightGBM/lib_lightgbm.dylib
[ 94%] Building CXX object CMakeFiles/lightgbm.dir/src/main.cpp.o
[ 97%] Building CXX object CMakeFiles/lightgbm.dir/src/application/application.cpp.o
[ 97%] Built target _lightgbm
[100%] Linking CXX executable /tmp/LightGBM/lightgbm
[100%] Built target lightgbm
```

</details>

More information about my setup:

```shell
cmake --version
# cmake version 3.26.4

clang++ --version
# Apple clang version 15.0.0 (clang-1500.3.9.4)
# Target: arm64-apple-darwin23.4.0
# Thread model: posix
# InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I do not see any uses of `enable_if_t` in LightGBM.

```shell
git grep enable_if_t
```

I strongly suspect that the issue you're facing lies in some difference between your setup and mine. If you want to see LightGBM drop C++11 support by default, we'll have to identify that difference.

So, to start... what do you observe if you run the exact same commands I shared above? Please share all the logs as I did.

**Comment by SpinEch0** [comment]
@jameslamb  Hi, I find that I use wrong submodule version:
```
git submodule update --init --remote
```
Sorry for my mistake. I will close the PR.

**Comment by jameslamb** [comment]
ah interesting! Ok then yeah I guess maybe you got a different version of `Eigen` than this project uses.

No problem, thanks for using LightGBM.

**Review by saadalowerdi — APPROVED** [review]

**Pull request closed without merging**
