### PR TITLE
rewrite test with unittest

### PR DESCRIPTION
**Pull request by wxchan**
@guolinke there are 3 unittests cannot pass. Can you help check the reasons? I use `@unittest.skip("Can't pass yet")` to denote them.

### CODE REVIEW

**Comment by guolinke** [comment]
@wxchan 
for test_engine: you should pass num_class to Dataset as well.

**Comment by guolinke** [comment]
for test_sklearn: should pass metric if using early_stopping.

**Comment by wxchan** [comment]
Ok, the error message is misleading. 

Is it possible we give a default metric according to which subclass(Classifier, Regressor or Ranker) user chooses?

**Comment by guolinke** [comment]
@wxchan can check eval_metric is None or not and give a default value before call fit.

**Comment by guolinke** [comment]
@wxchan Can I merge this now ?

**Comment by wxchan** [comment]
I finish now. You can wait the check pass.

**Comment by wxchan** [comment]
Wait a min. I am going to remove verbose_eval.

**Comment by wxchan** [comment]
@guolinke Done.

The check is more clear now. 
```
----------------------------------------------------------------------
running test_engine.py
....[LightGBM] [Warning] Ignoring Column_0 , only has one value
[LightGBM] [Warning] Ignoring Column_32 , only has one value
[LightGBM] [Warning] Ignoring Column_39 , only has one value
..
----------------------------------------------------------------------
Ran 6 tests in 0.996s
OK
```

Btw, I think you should add an issue template like [this](https://github.com/dmlc/mxnet/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by chivee** [comment]
@wxchan  added

**Comment by wxchan** [comment]
@chivee ok, thx

**Pull request merged**
