### PR TITLE
[dask] run Dask tests on aarch64 architecture

### PR DESCRIPTION
**Pull request by StrikerRUS**
Refer to https://github.com/microsoft/LightGBM/pull/3948#discussion_r575694158.

Now that QEMU is setup and proved to be stable on our CI, let's run Dask tests on aarch64 architecture and see what happens.

### CODE REVIEW

**Comment by jameslamb** [comment]
seems like they worked ok! I can see in the logs that the Dask tests definitely ran

```text
../tests/python_package_test/test_dask.py .............................. [ 16%]
..........................................s.................             [ 36%]
```

**Comment by jameslamb** [comment]
wait I take that back. Was looking at the wrong test. A lot of them failed, although the build wasn't marked as failed.

https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=9255&view=logs&j=c2f9361f-3c13-57db-3206-cee89820d5e3&t=bf5b33f9-9072-549e-d8b1-cab79a1dd2a9

```text
../tests/python_package_test/test_dask.py xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx [ 16%]
xxxxxxxxxxxxxxxx...................xxxxxxxxxxxxxx...........             [ 35%]
```

**Comment by jameslamb** [comment]
This code is on the code path of the `client` fixture we import from `distributed`, maybe that's the reason?

https://github.com/dask/distributed/blob/aa8e2dd87f58a29e3f4efb65e0ffcd83239ccc68/distributed/utils_test.py#L649

Don't know why we don't see anything in the logs though...

**Comment by StrikerRUS** [comment]
> I don't see anything in the logs explaining why so many were xfailed.

Yeah, me too!..

Also, build took ~1.5h with only few passed tests. Guess all xfailed ones were aborted before completing.

> This code is on the code path of the `client` fixture we import from `distributed`, maybe that's the reason?

If that's true, then it is very dangerous to use this fixture because we may not spot actual errors with our main Dask builds as the whole build will be marked green.

**Comment by jameslamb** [comment]
> > I don't see anything in the logs explaining why so many were xfailed.
> 
> Yeah, me too!..
> 
> Also, build took ~1.5h with only few passed tests. Guess all xfailed ones were aborted before completing.
> 
> > This code is on the code path of the `client` fixture we import from `distributed`, maybe that's the reason?
> 
> If that's true, then it is very dangerous to use this fixture because we may not spot actual errors with our main Dask builds as the whole build will be marked green.

I agree :/

I'll have to investigate more

**Comment by jameslamb** [comment]
I just updated this to latest `master`. There have been a lot of changes and fixes to the Dask tests since this was first opened, especially removing the `client` fixture in #4159.

**Comment by StrikerRUS** [comment]
Looks better than https://github.com/microsoft/LightGBM/pull/3996#issuecomment-780636048.
```
../tests/python_package_test/test_dask.py FF..FF..FF..FF..FF..FF..FF..FF [ 12%]
..FF..FF..FF..FF..FF..FF..FF..FF..F...F......FF..FF..FF..FF..FF..FF..FF. [ 25%]
.FF..F...............F..F..F..F..F..F..F..F..F..F..F..F..F..F..F..F..... [ 39%]
.....................................s.................................. [ 53%]
...s.................F...F.s........                                     [ 60%]

...

= 69 failed, 444 passed, 6 skipped, 2 xfailed, 400 warnings in 2145.62s (0:35:45) =
```

Not in terms of number of failed tests but in terms that they are `failed` now not `xfailed`. So seems you were right and `client` fixture was very dangerous.

**Comment by jameslamb** [comment]
Interesting! I looked quickly at the logs from https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=9916&view=logs&j=c2f9361f-3c13-57db-3206-cee89820d5e3, seems most of the errors are some form of this:

```text
../tests/python_package_test/test_dask.py:1357: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/root/miniconda/envs/test-env/lib/python3.9/site-packages/dask/base.py:285: in compute
    (result,) = compute(self, traverse=False, **kwargs)
/root/miniconda/envs/test-env/lib/python3.9/site-packages/dask/base.py:568: in compute
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
/root/miniconda/envs/test-env/lib/python3.9/site-packages/dask/base.py:568: in <listcomp>
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
/root/miniconda/envs/test-env/lib/python3.9/site-packages/dask/array/core.py:1075: in finalize
    return concatenate3(results)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

arrays = [array([[-1.19671438, -1.19956281, -1.0494877 ],
       [-1.19671438, -1.19956281, -1.0494877 ],
       [-0.89701348, ...94126 , -1.0494877 ],
       [-1.19671438, -1.19956281, -1.0494877 ],
       [-1.19671438, -0.8994126 , -1.0494877 ]])]

    def concatenate3(arrays):
        """Recursive np.concatenate
    
        Input should be a nested list of numpy arrays arranged in the order they
        should appear in the array itself.  Each array should have the same number
        of dimensions as the desired output and the nesting of the lists.
    
        >>> x = np.array([[1, 2]])
        >>> concatenate3([[x, x, x], [x, x, x]])
        array([[1, 2, 1, 2, 1, 2],
               [1, 2, 1, 2, 1, 2]])
    
        >>> concatenate3([[x, x], [x, x], [x, x]])
        array([[1, 2, 1, 2],
               [1, 2, 1, 2],
               [1, 2, 1, 2]])
        """
        from .utils import IS_NEP18_ACTIVE
    
        # We need this as __array_function__ may not exist on older NumPy versions.
        # And to reduce verbosity.
        NDARRAY_ARRAY_FUNCTION = getattr(np.ndarray, "__array_function__", None)
    
        arrays = concrete(arrays)
        if not arrays:
            return np.empty(0)
    
        advanced = max(
            core.flatten(arrays, container=(list, tuple)),
            key=lambda x: getattr(x, "__array_priority__", 0),
        )
    
        if IS_NEP18_ACTIVE and not all(
            NDARRAY_ARRAY_FUNCTION
            is getattr(type(arr), "__array_function__", NDARRAY_ARRAY_FUNCTION)
            for arr in core.flatten(arrays, container=(list, tuple))
        ):
            try:
                x = unpack_singleton(arrays)
                return _concatenate2(arrays, axes=tuple(range(x.ndim)))
            except TypeError:
                pass
    
        if concatenate_lookup.dispatch(type(advanced)) is not np.concatenate:
            x = unpack_singleton(arrays)
            return _concatenate2(arrays, axes=list(range(x.ndim)))
    
        ndim = ndimlist(arrays)
        if not ndim:
            return arrays
        chunks = chunks_from_arrays(arrays)

        def dtype(x):
            try:
                return x.dtype
            except AttributeError:
                return type(x)
    
        result = np.empty(shape=shape, dtype=dtype(deepfirst(arrays)))
    
        for (idx, arr) in zip(
            slices_from_chunks(chunks), core.flatten(arrays, container=(list, tuple))
        ):
            if hasattr(arr, "ndim"):
                while arr.ndim < ndim:
                    arr = arr[None, ...]
>           result[idx] = ar

E           ValueError: could not broadcast input array from shape (500,3) into shape (500,)
```

I can do some research and see if similar errors have been reported to `dask/dask` or `dask/distributed`.

**Comment by jameslamb** [comment]
Not sure if it's relevant, but it does look like the aarch64 builds are getting slightly newer versions of the key dependencies.

**`Linux_latest bdist`** ([logs](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=9916&view=logs&j=b463fb3a-b487-5cfc-fc07-6d216464ba86&t=c16b9cdb-c4c8-59f9-2ae2-b81f62c3a9d0))

```text
dask               pkgs/main/noarch::dask-2021.4.0-pyhd3eb1b0_0
dask-core          pkgs/main/noarch::dask-core-2021.4.0-pyhd3eb1b0_0
distributed        pkgs/main/linux-64::distributed-2021.4.0-py38h06a4308_0
numpy              pkgs/main/linux-64::numpy-1.20.1-py38h93e21f0_0
numpy-base         pkgs/main/linux-64::numpy-base-1.20.1-py38h7d8b39e_0
```

**`QEMU_multiarch bdist`** ([logs](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=9916&view=logs&j=c2f9361f-3c13-57db-3206-cee89820d5e3&t=bf5b33f9-9072-549e-d8b1-cab79a1dd2a9))

```text
dask               conda-forge/noarch::dask-2021.4.1-pyhd8ed1ab_0
dask-core          conda-forge/noarch::dask-core-2021.4.1-pyhd8ed1ab_0
distributed        conda-forge/linux-aarch64::distributed-2021.4.1-py39ha65689a_0
numpy              conda-forge/linux-aarch64::numpy-1.20.2-py39h43e3299_0
```

I mention that because the error we're getting seems to be happening at the level where Dask is doing sum `numpy` operations, so it could come from an incompatible mix of Dask and `numpy`.

**Comment by StrikerRUS** [comment]
Just noticed that it's all-green now! 😱 

I'd like to make any random Dask test to fail and check QEMU reaction.

**Comment by jameslamb** [comment]
oh wow, great! Yes, I'm curious to see what happens if you add a `raise ValueError()` or something to one of the Dask tests

**Comment by StrikerRUS** [comment]
OK, corrupted Dask test on QEMU failed as it was expected:
```
=========================== short test summary info ============================
FAILED ../tests/python_package_test/test_dask.py::test_warns_and_continues_on_unrecognized_tree_learner
= 1 failed, 512 passed, 6 skipped, 2 xfailed, 342 warnings in 4202.86s (1:10:02) =
```
Reverting test commit now.

**Comment by StrikerRUS** [comment]
Were all previous test failures on QEMU due to environment compatibility issues or did the latest Dask (or its deps) include a real fix? If latter, I think it will be useful to identify that release and document it as minimum required version for aarch64 platform. How do you think @jameslamb ?

**Comment by StrikerRUS** [comment]
I'm going to push some empty commits to check the tests stability and measure their time consumption.

**Comment by StrikerRUS** [comment]
Well, the latest 5 jobs were passed and Dask tests add no more than 35min to the overall QEMU job time. Now its' duration either ~50min or ~105min (this binarization is due to that sometimes QEMU job is x2 faster than other times).
Are we OK with this setup?

**Comment by jameslamb** [comment]
> Now its' duration either ~50min or ~105min (this binarization is due to that sometimes QEMU job is x2 faster than other times). 

Oh interesting! I never noticed that big differences between different job runtimes before.

> Are we OK with this setup?

I am ok with this setup for now. The level of activity on the project hasn't been high enough that that would be add significant friction to the development process.

**Comment by StrikerRUS** [comment]
> I am ok with this setup for now.

Me too. Merge?

**Review by jameslamb — APPROVED** [review]
Yes, let's merge! Thanks for doing this. I'm glad to see more coverage of the Dask package.

**Pull request merged**
