### PR TITLE
Enable boost_from_average as default for binary objective

### PR DESCRIPTION
**Pull request by zkurtz**
This appears to fix issue #1336, leading to greater default boosting efficiency particularly for small unbalanced binary regression problems.

The change is simple; I copied verbatim the BoostFromScore method in the xentropy objective:

https://github.com/Microsoft/LightGBM/blob/5392c9eaf616b10028170346db898a598739a1a7/src/objective/xentropy_objective.hpp#L107-L128

To the future: There is much in common between `xentropy` and `binary` objectives; it's not clear to me yet whether one should subsume the other.  I.e., if `xentropy` ends up doing essentially the same thing as `binary`, maybe `xentropy` should become simply an alias for `binary`.

### CODE REVIEW

**Comment by olofer** [comment]
@zkurtz xentropy allows continuous target labels in [0,1] whereas binary assumes targets that are distinct 0 or 1; "probability regression" versus classification if you will, sometimes that distinction can be useful; binary can also be slightly optimized/simplified for the two-value case.

**Comment by zkurtz** [comment]
Great feedback, I'll close this for now while I take a closer look.

**Comment by guolinke** [comment]
@zkurtz can you discard these duplicated changes ?

**Comment by zkurtz** [comment]
@guolinke Does this look better? I'm not sure how the duplication occurred, but doing `git push origin +HEAD^:master` just one time seemed to fix it as per https://stackoverflow.com/a/8225166/2232265

**Pull request merged**
