### PR TITLE
Add nuspec for NuGet packaging

### PR DESCRIPTION
**Pull request by souravsingh**

### CODE REVIEW

**Comment by souravsingh** [comment]
Related to #74

**Comment by souravsingh** [comment]
@guolinke I would need some help in finishing this.

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by guolinke** [comment]
@souravsingh 
What is your purpose of this PR?

**Comment by souravsingh** [comment]
@guolinke The PR is for creating the NuGet package for LightGBM.

**Comment by chivee** [comment]
@souravsingh , do you have any further plan on the creating.

**Pull request closed without merging**
