### PR TITLE
[python-package] change default best_iteration to 0

### PR DESCRIPTION
**Pull request by wxchan**
https://github.com/Microsoft/LightGBM/pull/479#issuecomment-298356703

### CODE REVIEW

**Comment by wxchan** [comment]
do I need to update python docs manually now?

**Comment by guolinke** [comment]
@wxchan maybe we can replace these api doc with the ReadTheDocs URL.

**Comment by wxchan** [comment]
@guolinke I think the doc issue can be dealt with together. I change it manually now. It's ready to merge.

**Comment by henry0312** [comment]
Is `num_iteration=-1` at https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L351  ok?

**Comment by wxchan** [comment]
the only purpose is to make best_score = eval_result[best_iteration - 1], passing -1 or 0 to predict function makes no differences.

**Comment by henry0312** [comment]
I see. Thanks!

**Pull request merged**
