### PR TITLE
fix index of numeric_feature_map_ in AddFeaturesFrom (fixes #5410)

### LINKED ISSUE #5410: Should use other->numeric_feature_map_[i] in AddFeaturesFrom
## Description
In this line: https://github.com/microsoft/LightGBM/blob/master/src/io/dataset.cpp#L1486
I think
``` C++
int feat_ind = numeric_feature_map_[i];
```
should be
``` C++
int feat_ind = other->numeric_feature_map_[i];
```
The loop condition ```i < (other->numeric_feature_map_).size()``` tells the same story.

### Code
``` python
import lightgbm as lgb
import numpy as np

a = np.zeros((100, 1), dtype=np.float32)
b = np.random.normal(size=(100, 5))

dataset_a = lgb.Dataset(a).construct()
dataset_b = lgb.Dataset(b).construct()

dataset_a.add_features_from(dataset_b)
```
### Output
```
[LightGBM] [Warning] There are no meaningful features, as all feature values are constant.
[LightGBM] [Warning] Find the same feature name (Column_0) in Dataset::AddFeaturesFrom, change its name to (D2_Column_0)

Traceback (most recent call last):
  File "add.py", line 10, in <module>
    dataset_a.add_features_from(dataset_b)
  File "C:\test_lgb_add\lib\site-packages\lightgbm\basic.py", line 2437, in add_features_from
    _safe_call(_LIB.LGBM_DatasetAddFeaturesFrom(self.handle, other.handle))
OSError: exception: access violation reading 0x0000000000000000
```

## Environment info
Command(s) you used to install LightGBM

```shell
pip install lightgbm==3.3.2
```

### PR DESCRIPTION
**Pull request by EdmondElephant**
Fix this issue: https://github.com/microsoft/LightGBM/issues/5410

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks for the fix @EdmondElephant !

Would you please add a test for this case, to ensure that this bug isn't accidentally re-introduced by future changes to the project?

You could, for example, take the sample Python code you created for #5410 and add it as a test case in https://github.com/microsoft/LightGBM/blob/master/tests/python_package_test/test_basic.py. With some `assert` statements, like this

```python
import lightgbm as lgb
import numpy as np

a = np.zeros((100, 1), dtype=np.float32)
b = np.random.normal(size=(100, 5))

dataset_a = lgb.Dataset(a).construct()
dataset_b = lgb.Dataset(b).construct()

dataset_a.add_features_from(dataset_b)
assert dataset_a.num_feature == 6
```

**Comment by guolinke** [comment]
@EdmondElephant do you have time to add a simple test as @jameslamb suggests? We can help you to add the test if you are busy.

**Comment by StrikerRUS** [comment]
Kindly ping @EdmondElephant

**Comment by jameslamb** [comment]
@EdmondElephant Are you still interested in pursuing this?

If you tell us you are too busy, or don't respond in the next 2 weeks or so, I'll close this PR and open a new one with the changes + the request test.

You could also add me to the collaborators on your fork of LightGBM, so that I could push changes directly to this PR.

Thanks again for your help with LightGBM!

**Comment by EdmondElephant** [comment]
@jameslamb Sorry I'm a newbie to github and open-source projects, (and a bit busy...). I've tried to add you to the collaborators, please help add the request test and go ahead.

**Comment by jameslamb** [comment]
Sorry for the long delay. I'm ready to help get this merged. I received + accepted the invitation to your fork, and am able to push to it. Thanks for that!

I'll update this to latest `master` and push a unit test some time in the next few days, then ask other maintainers to help with reviews.

**Comment by jameslamb** [comment]
I just pushed https://github.com/microsoft/LightGBM/pull/5434/commits/7e32261db0ae075df25495ecead6d9da7afbeee8, adding a unit test.

That test segfaults on `master` and passes on this branch.

Since I now have a commit on this PR, my approval shouldn't count towards a merge. I'm going to dismiss my review, and wait for another maintainer to review.

**Comment by jameslamb** [comment]
@EdmondElephant can you please add a comment here like this?

```text
@microsoft-github-policy-service agree
```

Sorry, but it seems that Microsoft may have recently changed the way that it asks contributors to sign a Contributor License Agreement (CLA)

**Review by StrikerRUS — APPROVED** [review]

**Comment by jameslamb** [comment]
@EdmondElephant are you interested in continuing this contribution?

If so, please leave a comment agreeing to the CLA (https://github.com/microsoft/LightGBM/pull/5434#issuecomment-1275518491).

After you've done that, I can update this branch to latest `master` and merge it.

If we don't hear from you in the next two weeks, I'll close this and open a new pull request with these changes (preserving your commit so you'll still get credit as a contributor).

**Comment by jameslamb** [comment]
It's been a few months since we asked for the CLA to be signed. I'm closing this, and have replaced it with #5650.

> preserving your commit so you'll still get credit as a contributor

I take this back. Since you haven't signed the CLA, I didn't include your commits in #5650. I don't think Microsoft's policies commits from authors who haven't signed the CLA to be merged in here.

--------

Thanks very much for discovering, investigating, and fixing this bug! I hope you'll consider contributing to LightGBM again in the future when you have the time to work with us.

**Pull request closed without merging**
