### PR TITLE
Add SaveModelToString()

### PR DESCRIPTION
**Pull request by cbecker**
Added `SaveModelToString` and modified `SaveModelToFile` to use it.

To be merged after https://github.com/Microsoft/LightGBM/pull/234

### CODE REVIEW

**Comment by guolinke** [comment]
@cbecker  conflicts ?

**Comment by cbecker** [comment]
I thought it was not necessary, but just needed some rebasing. Ready now, you can wait for the test to be sure, but should be fine.

**Comment by wxchan** [comment]
@guolinke I think this change can be applied to c_api too, then we can use model string to copy models instead of temp file.

**Comment by guolinke** [comment]
@wxchan can you help to do this ? I am quite busy recently. 
i think its logic is just like the dump model.

**Comment by cbecker** [comment]
yes I can do this, but right now to me there is higher priority to fix https://github.com/Microsoft/LightGBM/pull/226#discussion_r96829151

Do you have any ideas on that one? Afterwards I will work on this one.

**Comment by guolinke** [comment]
@cbecker I think just load feature_info while loading model so that feature_info will never be null.  
feature importance is not need to load again is because these information are calculated based on loaded models.

**Pull request merged**
