### PR TITLE
throw error when meet non ascii

### LINKED ISSUE #2226: Wrong size of feature_names
## Environment info

Operating System: 
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
``` 

CPU/GPU model:

C++/Python/R version: 
```
Python 3.6.6 (default, Jul 27 2018, 16:21:42) 
[GCC 6.3.0 20170516] on linux
```

LightGBM version or commit hash:
`lightgbm==2.2.3`

## Reproducible examples

It is difficult to make it reproducible :) 
I've checked various issues related to this such as 
https://github.com/Microsoft/LightGBM/issues/379 which led to this merge https://github.com/microsoft/LightGBM/pull/426
https://github.com/Microsoft/LightGBM/issues/540

Please find bellow the code I used 

```
    lgb_train = lgb.Dataset(X_train, label=y_train, categorical_feature=categorical_feature)
    lgb_valid = lgb.Dataset(X_valid, label=y_valid, categorical_feature=categorical_feature)

    param = {
        # 'objective': 'binary',
        'objective': 'xentropy',
        # 'metric': 'auc',
        'random_state': 1,
        "verbosity": -1,
        'learning_rate': 0.05,
        'num_threads': 16,
    }

    X_cols
    print('len(X_cols)', len(X_cols))
    print('len(X_cols)', len(list(set(X_cols))))
    print('len set with replace space with underscore ', len(set([c.replace(' ', '_') for c in X_cols])))
    X_train
    model_gbm = lgb.train(params=param,
                          train_set=lgb_train,
                          num_boost_round=4000,
                          valid_sets=[lgb_train, lgb_valid],
                          early_stopping_rounds=20,
                          feature_name=X_cols,
                          verbose_eval=20,
                          )
```

Which lead to this 

image

I've the feeling that the problem is linked to this, but unsure how to solve it. https://github.com/microsoft/LightGBM/pull/426

I'm curently commenting `feature_name=X_cols,` to avoid bug in my pipeline.

### PR DESCRIPTION
**Pull request by guolinke**
to fix #2226

### CODE REVIEW

**Comment by guolinke** [comment]
ping @StrikerRUS for review

**Comment by StrikerRUS** [comment]
Is `feature_name` the only model's field in which users' arbitrary strings are stored?

**Comment by guolinke** [comment]
@StrikerRUS there are some parameters with string type, e.g. data_filename, could be set by user and store in model file.

**Comment by StrikerRUS** [comment]
Maybe then add the same check for them too?

**Comment by jameslamb** [comment]
@StrikerRUS can this PR be merged?

**Comment by StrikerRUS** [comment]
@guolinke What do you think about enabling this check for other user's strings, like different paths as you've mentioned? https://github.com/microsoft/LightGBM/pull/2229#issuecomment-502691751

cc @jameslamb

**Comment by guolinke** [comment]
@StrikerRUS done

**Pull request merged**
