### PR TITLE
[cmake] fixes static build for macos with OpenMP enabled (fixes #6601)

### LINKED ISSUE #6601: Build fails on macos with openmp and static lib enabled
## Description
Build fails on macos with `openmp` and static lib enabled

```shell
cmake -B build -S . -DBUILD_STATIC_LIB=ON && cmake --build build -j4
```

```
...
Replacing hard-coded OpenMP install_name with '@rpath/libomp.dylib'...
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open file: lib_lightgbm.dylib (No such file or directory)
```

### PR DESCRIPTION
**Pull request by Mottl**
Fixes #6601 with `-DBUILD_STATIC_LIB=ON` on macos with `USE_OPENMP` enabled

### CODE REVIEW

**Comment by Mottl** [comment]
@microsoft-github-policy-service agree

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks very much for this, and sorry for breaking builds of the static library on macOS. We probably need to add some CI coverage of that.

Could you please instead skip this entire block, by adding a `NOT BUILD_STATIC_LIB` into this condition?

https://github.com/microsoft/LightGBM/blob/9a76aae1b5979a455bf6d80728d2a88f36823380/CMakeLists.txt#L755

All of this logic, like modifying RPATH entries, should be unnecessary for the static library.

**Comment by Mottl** [comment]
Thanks James. Done.

**Review by jameslamb — APPROVED** [review]
Thanks for the fix!

I pulled your branch onto my M2 mac and tested like this:

```shell
git remote add mottl git@github.com:Mottl/LightGBM.git
git fetch mottl macos_openmp_cmake_fix

cmake \
    -B build \
    -S . \
    -DBUILD_STATIC_LIB=ON \
    -DUSE_OPENMP=ON

cmake --build build --target all -j4
```

Saw everything build successfully, with 0 warnings or errors.

```text
[ 89%] Built target lightgbm_objs
[ 97%] Linking CXX static library /Users/jlamb/repos/LightGBM/lib_lightgbm.a
[ 97%] Building CXX object CMakeFiles/lightgbm.dir/src/application/application.cpp.o
[ 97%] Building CXX object CMakeFiles/lightgbm.dir/src/main.cpp.o
[ 97%] Built target _lightgbm
[100%] Linking CXX executable /Users/jlamb/repos/LightGBM/lightgbm
[100%] Built target lightgbm
```

Also inspected the library a bit and everything looked correct.

```shell
ar -t ./lib_lightgbm.a
nm ./lib_lightgbm.a
```

**Pull request merged**
