### PR TITLE
Update versions of LightGBM dependencies

### PR DESCRIPTION
**Pull request by StrikerRUS**
Refer to #3763.

All dependencies were updated to the latest available stable version.

https://github.com/boostorg/compute/releases/tag/boost-1.78.0
https://gitlab.com/libeigen/eigen/-/releases/3.4.0
~https://github.com/lemire/fast_double_parser/releases/tag/v0.5.0~ see https://github.com/microsoft/LightGBM/pull/4935#issuecomment-1010122490
https://github.com/fmtlib/fmt/releases/tag/8.1.1

### CODE REVIEW

**Comment by StrikerRUS** [comment]
All failing CI jobs is R-package jobs and the error is about hidden files:
```
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  src/external_libs/fmt/support/bazel/.bazelrc
  src/external_libs/fmt/support/bazel/.bazelversion
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.

CRAN-pack does not know about
  src/external_libs/fmt/support/bazel/.bazelrc
  src/external_libs/fmt/support/bazel/.bazelversion
```

**Comment by jameslamb** [comment]
> error is about hidden files

Adding additional rules in https://github.com/microsoft/LightGBM/blob/master/R-package/.Rbuildignore should fix that.

**Comment by StrikerRUS** [comment]
Here is a description for them in the original PR they were introduced:

> The `.bazelrc` is kind of optional. It could simply be deleted. In its current form, it just avoids that some temporary Bazel-related folders are created.

> The `.bazelversion` file can also be deleted. It is just a file for Bazelisk and a nice way to document which Bazel version was aimed for/tested with (I am pretty sure that it works with almost every Bazel version).

https://github.com/fmtlib/fmt/pull/2505#issuecomment-922366665

According to this, I agree that we can safely ignore/remove them.

**Comment by StrikerRUS** [comment]
`Linux_latest regular` job is failing (probably segfault):
```
../tests/python_package_test/test_dual.py s                              [ 64%]
../tests/python_package_test/test_engine.py .....................s...s.. [ 68%]
..................................../__w/1/s/.ci/test.sh: line 212:  7869 Killed                  pytest $BUILD_DIRECTORY/tests
##[error]Bash exited with code '255'.
```
https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=11943&view=logs&j=275189f9-c769-596a-7ef9-49fb48a9ab70&t=3a9e7a4a-04e6-52a0-67ea-6e8f6cfda74f
Need to identify the failing testcase and try to reproduce the error.

**Comment by StrikerRUS** [comment]
The latest commit passes all CI checks. I'd like to run CI multiple times to identify flaky test and affected environments.
1. ✔️ 
2. ...

**Comment by StrikerRUS** [comment]
Seems that failing test is `test_model_size`
https://github.com/microsoft/LightGBM/blob/ce486e5b45a6f5e67743e14765ed139ff8d532e5/tests/python_package_test/test_engine.py#L2285
and I guess that segfault happens here
https://github.com/microsoft/LightGBM/blob/ce486e5b45a6f5e67743e14765ed139ff8d532e5/tests/python_package_test/test_engine.py#L2304

**Comment by StrikerRUS** [comment]
Reverting `fast_double_parser` update for now.

1. ...

**Comment by StrikerRUS** [comment]
I think this PR is ready for review.

Based on [15 successful CI runs](https://github.com/microsoft/LightGBM/pull/4935#issuecomment-1011429547) we can hope that this dependencies version upgrade is quite stable. I triggered all 15 runs via with empty commits because I noticed that sometimes if you re-run CI via closing-reopening a PR or by manually clicking rerun UI button (for those CIs where it's possible) new re-triggered CI job may reuse a previous runner, which breaks independency of tests.

**Review by jameslamb — APPROVED** [review]
Looks great! Thanks for the thorough testing and explanation about `fast_double_parser`.

**Comment by StrikerRUS** [comment]
Just marked this PR as `WIP` because I'd like to merge #4953 first. Also, I forgot to run tests with swapped compilers at CI. Sorry for the inconvenience!

**Comment by StrikerRUS** [comment]
Well, I think this PR is ready for review.
https://github.com/microsoft/LightGBM/pull/4935#issuecomment-1011429547

**Comment by jameslamb** [comment]
Thanks for the very thorough testing! I support merging this.

Pretty exciting, looks like there have been a lot of improvements in Eigen from the version currently shipped with LightGBM to now. For example, https://eigen.tuxfamily.org/index.php?title=3.4.

**Pull request merged**
