### PR TITLE
WIP: [ci] test R package with development version of {Matrix}

### PR DESCRIPTION
**Pull request by jameslamb**
The maintainers of the R package `{Matrix}` have asked maintainers of all packages on CRAN that depend on `{Matrix}` to test against a development version of that library, which will be released to CRAN some time in the next month. See #4200 for the exact message they sent.

This PR proposes testing against that version by temporarily changing `R_BUILD_TYPE = "cran"` builds in LightGBM's CI to install the development version of `{Matrix}` from source. I hope that it can be reverted in the future once `{Matrix}` 1.3-3 makes it to CRAN.

### CODE REVIEW

**Comment by jameslamb** [comment]
Pushing an empty commit to re-trigger CI, to preserve logs for #4204.

**Comment by StrikerRUS** [comment]
Sorry, I didn't get it. Are maintainers of `Matrix` package actively developing new version right now or they have frozen adding new features and just fixing reported bugs right now (something like release candidate)? I mean, isn't enough to run all our R-package tests with new version of `Matrix` package only once? Or we need to monitor almost every commit in their `master` branch?

**Comment by jameslamb** [comment]
It's like a release candidate. Testing against it on every commit here would catch changes to `{lightgbm}` that make it incompatible with that upcoming release of `{Matrix}`.

**Review by StrikerRUS — APPROVED** [review]
I'm afraid this PR will lead to even more CI errors we have to fix in order to continue the development process. I'd better leave this change in a form of PR and sync the base branch with `master` once a week, for example.

But I'll defer to you @jameslamb .

**Comment by jameslamb** [comment]
That's fine with me. I'll convert it back to draft and dismiss your approving review, so that it isn't accidentally merged.

**Comment by jameslamb** [comment]
Ok it looks like I'm not able to dismiss the review, but marking it as draft and adding "WIP" to the title is enough to block merging.

**Comment by jameslamb** [comment]
`{Matrix}` 1.3-3 has been published to CRAN. However, not all checks have run yet.

https://cran.r-project.org/web/checks/check_results_Matrix.html

image

I think we can safely close this PR, since now `install.packages()` from CRAN will return version 1.3-3 in LightGBM's CI jobs.

**Pull request closed without merging**
