### PR TITLE
fix model feature importances

### LINKED ISSUE #750: feature importance in saved model ignores the num_iteration parameter (uses full model)
Feature importance reported by LGBM_BoosterSaveModel and LGBM_BoosterSaveModelToString is always for the full model, ignoring the num_iteration parameter used to limit the number of trees reported.

### PR DESCRIPTION
**Pull request by wxchan**
fix #750

### CODE REVIEW

**Comment by wxchan** [comment]
It's finished. I pushed the commit to wrong branch.

@ungil can you help check if it's ok?

**Comment by ungil** [comment]
I'm not sure why (maybe I made some mistake?) but it seems to be off by one. The importance included in the file is the one for the "next" model.

For example, setting num_leaves=3 and num_threads=1 in simple_example.py and adding the lines gbm.save_model('model1.txt',1) and gbm.save_model('model2.txt',2) I get the following results:

```
**model1.txt**
tree
num_class=1
num_tree_per_iteration=1
[...]
Tree=0
num_leaves=2
split_feature=0
split_gain=-1
[...]
Tree=1
num_leaves=3
split_feature=25 26
split_gain=65.906192444293836 36.816528512507055
[...]
feature importances:
Column_25=3
Column_26=1

**model2.txt**
tree
num_class=1
num_tree_per_iteration=1
[...]
Tree=0
num_leaves=2
split_feature=0
split_gain=-1
[...]
Tree=1
num_leaves=3
split_feature=25 26
split_gain=65.906192444293836 36.816528512507055
[...]
Tree=2
num_leaves=3
split_feature=25 25
split_gain=59.480334430465355 34.499828333108738
[...]
feature importances:
Column_25=3
Column_26=2
Column_27=1
```

There is also a compilation warning:
```
LightGBM/src/boosting/gbdt.cpp: In member function 'std::vector<std::pair<long unsigned int, std::__cxx11::basic_string<char> > > LightGBM::GBDT::FeatureImportance(int) const':
LightGBM/src/boosting/gbdt.cpp:1100:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t iter = 0; iter < num_used_model; ++iter) {
                         ~~~~~^~~~~~~~~~~~~~~~
```

(I've also noticed that with the changes introduced over the last couple of days the results of running a program are not the same as before... but maybe that's expected)

**Comment by wxchan** [comment]
@ungil Thanks for your review. The extra one tree is because the boost_from_average parameter. I think the extra Tree 0 should not be used for calculation of feature importance, is this right? @guolinke I will fix this and the warning later.

**Comment by ungil** [comment]
I still get the same output. It tuns out that num_iteration is already incremented to account for the --th tree before FeatureImportance(num_iteration) is called: https://github.com/Microsoft/LightGBM/blob/master/src/boosting/gbdt.cpp#L957

**Comment by wxchan** [comment]
@ungil you are right. Sorry for my carelessness.

**Comment by ungil** [comment]
It seems correct now. Thanks!

**Comment by guolinke** [comment]
@wxchan ready for merge ?

**Comment by wxchan** [comment]
@guolinke yes, it's all done.

**Pull request merged**
