### PR TITLE
Update OS X compability

### PR DESCRIPTION
**Pull request by kventinel**

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@kventinel Please explain your changes.

**Comment by kventinel** [comment]
This changes need to add possibility to build this project on OS X.

**Comment by StrikerRUS** [comment]
LightGBM can be compiled on macOS successfully and we have tests for this. What versions of macOS, CMake, compiler do you use?

**Comment by kventinel** [comment]
Mojave 10.14.5, GNU Make 3.81

**Comment by StrikerRUS** [comment]
And what version of gcc?

**Comment by kventinel** [comment]
I have clang-1001.0.46.4

**Comment by StrikerRUS** [comment]
OK, and what about CMake version?

**Comment by kventinel** [comment]
I already have written it. (CMake 3.13.2)

**Comment by StrikerRUS** [comment]
You edited your message later, so sorry I didn't see CMake version, sorry.

This is known issue on Mojave with default AppleClang, refer to #1923. See our installation guide for additional CMake arguments which can fix this.
However `OpenMP` package name is platform-independent.

**Comment by kventinel** [comment]
But with OPENMP name i able to build this project.

**Comment by StrikerRUS** [comment]
It should be something connected with your environment. Do you have any links for your fix?

**Comment by kventinel** [comment]
No.

**Pull request closed without merging**
