### PR TITLE
[docs] fixing max_depth param description

### PR DESCRIPTION
**Pull request by KOLANICH**
https://github.com/Microsoft/LightGBM/blob/59f10453dc4a3841339702524124063fa5db6870/src/treelearner/serial_tree_learner.cpp#L351

BTW, should it be unsigned?

### CODE REVIEW

**Comment by KOLANICH** [comment]
BTW, why not to do it on CI automatically?

**Comment by StrikerRUS** [comment]
Because after generating anything on CI side it should be pushed back to GitHub.

**Comment by KOLANICH** [comment]
>Because after generating anything on CI side it should be pushed back to GitHub.

1. What's the problem with it? Azure Pipelines support secret variables.
2. If the docs are generated from the source, why not to remove them completely from the repo?

**Comment by StrikerRUS** [comment]
> 1. What's the problem with it? Azure Pipelines support secret variables.

It's still insecure. It produces additional mess in the repo. Imagine: every commit is duplicated by the CI.

>2.  If the docs are generated from the source, 

Only params description is generated from the source.

**Comment by StrikerRUS** [comment]
@KOLANICH Remembering your position about the CLA https://github.com/microsoft/LightGBM/pull/1873#issuecomment-454150389, we are taking over your PRs, if you don't mind.
> so feel free to close the PR and add the links and everything else you feel needed yourself from your account and your name, I don't object, …

Can you please clarify your comment?
https://github.com/microsoft/LightGBM/pull/1879#issue-233389039
>https://github.com/Microsoft/LightGBM/blob/59f10453dc4a3841339702524124063fa5db6870/src/treelearner/serial_tree_learner.cpp#L351
BTW, should it be unsigned?

**Comment by KOLANICH** [comment]
I just wonder why a signed int is used for a parameter which semantics is to be a number >= 0. Shouldn't an unsigned int be used for that?

**Comment by StrikerRUS** [comment]
Ah, got it, thanks!
But users can pass a negative value, e.g. `-1` to indicate "no limit".

**Comment by KOLANICH** [comment]
>But users can pass a negative value, e.g. -1 to indicate "no limit".

But 0 is also "no limit".

**Comment by StrikerRUS** [comment]
You are right!
It's possible save all semantics with unsigned value. However, this change will be not backward compatible.

BTW, at present, all params are signed values, even `num_boost_round` and other which should be strictly greater zero.

**Comment by StrikerRUS** [comment]
Proposed changes were made in #2155.

**Pull request closed without merging**
