### PR TITLE
[python-package] add plot metrics

### PR DESCRIPTION
**Pull request by wxchan**
#171

### CODE REVIEW

**Comment by wxchan** [comment]
Should I change it to `plot_metric` since it only plots one metric?

**Comment by wxchan** [comment]
an example in `examples/python-guide/plot_example.py`:
plot_example

**Comment by guolinke** [comment]
@wxchan Did this finish?

**Comment by wxchan** [comment]
@guolinke wait a minute.

**Comment by wxchan** [comment]
@guolinke I change one misleading comment. Now finished. You can wait till the check passes.

**Pull request merged**
