### PR TITLE
fix cpp lint in json11

### PR DESCRIPTION
**Pull request by guolinke**
json11 issues from #1990

### CODE REVIEW

**Comment by StrikerRUS** [comment]
Awesome PR! Only 4 issues remains! I'm so happy. 🎉 

Seems the most diff produced here is due to code redactor settings, right?

**Comment by guolinke** [comment]
yes, as the indent is 4 previously, I reformat the style by copy-and-paste.

**Comment by jameslamb** [comment]
> Awesome PR! Only 4 issues remain! I'm so happy. 🎉
> 
> Seems the most diff produced here is due to code redactor settings, right?

@StrikerRUS after this PR is done, I think we should put `// NOLINT` on the remaining 4 issues, capture the work to remove those in an issue, and permanently enable `cpplint` as a proper CI check to prevent any new issues being introduced.

**Comment by StrikerRUS** [comment]
@jameslamb I like your suggestion!

**Pull request merged**
