### PR TITLE
Remove CMAKE_CXX_COMPILER and CMAKE_C_COMPILER for OSX

### PR DESCRIPTION
**Pull request by henry0312**
#710

### CODE REVIEW

**Comment by henry0312** [comment]
we need to update [Installation Guide](https://github.com/Microsoft/LightGBM/wiki/Installation-Guide) like this:

```
git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
mkdir build ; cd build
cmake -DCMAKE_CXX_COMPILER=/usr/local/bin/g++- -DCMAKE_C_COMPILER=/usr/local/bin/gcc ..
make -j4 
```

**Comment by guolinke** [comment]
This may broke the installation of python/R package, since it is hard to specific ```-DCMAKE_CXX_COMPILER=/usr/local/bin/g++- -DCMAKE_C_COMPILER=/usr/local/bin/gcc``` in their nested cmake command.

**Comment by guolinke** [comment]
BTW, can this ```cmake -DCMAKE_CXX_COMPILER=/usr/local/bin/g++- -DCMAKE_C_COMPILER=/usr/local/bin/gcc```
simplify to ```cmake -DCMAKE_CXX_COMPILER=g++7 - -DCMAKE_C_COMPILER=gcc7``` ?

**Comment by henry0312** [comment]
Currently, `brew install gcc` installs gcc-7, so `-DCMAKE_CXX_COMPILER=g++-7 - -DCMAKE_C_COMPILER=gcc-7` is also ok until release of gcc-8.

**Comment by guolinke** [comment]
@henry0312 
It that okay if just using ```cmake -DCMAKE_CXX_COMPILER=g++ - -DCMAKE_C_COMPILER=gcc``` ?

**Comment by chivee** [comment]
I agreed that we should remove the line that specific the g++ in the cmake for Apple. but that means that we should also alter the travis test script as well. I have branched a [branch](https://github.com/Microsoft/lightGBM/tree/mac-build) for testing

**Comment by henry0312** [comment]
`-DCMAKE_CXX_COMPILER=g++` and `-DCMAKE_C_COMPILER=gcc` may be not okay, because `gcc` and `g++` are Clang, not GNU GCC in OSX.

```
~/.ghq/github.com/henry0312/LightGBM remove_apple_compiler*
❯ type gcc
gcc is /usr/bin/gcc

~/.ghq/github.com/henry0312/LightGBM remove_apple_compiler*
❯ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

~/.ghq/github.com/henry0312/LightGBM remove_apple_compiler*
❯ type g++
g++ is /usr/bin/g++

~/.ghq/github.com/henry0312/LightGBM remove_apple_compiler*
❯ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by chivee** [comment]
@henry0312  ,the problem that we are faced is that the apple linked the `gcc` and `g++` to AppleClang, I have added the test for the mac, but which means that Apple users should manually specify their compiler.

**Comment by guolinke** [comment]
can following works ? 
```
export CXX=g++-7
export  CC=gcc-7
cmake  ..
```

if this can work, we can use it for the python/R build .

**Comment by chivee** [comment]
actually `/usr/local/bin/g++` didn't exist if you are only install gcc using brew

**Comment by henry0312** [comment]
@guolinke This may works, I guess.

@chivee you're right. So we specify gcc-7, gcc-6 and so on.

**Comment by chivee** [comment]
I have checked that the minimum version that we need is gcc 4.8.3 and clang 3.8

**Comment by henry0312** [comment]
I don't know much about Travis.
Which gcc (GNU) in osx of Travis are available?

**Comment by chivee** [comment]
We have fully control of which version should be use in Travis.

**Comment by henry0312** [comment]
Then, I think exporting `CXX` and `CC` before tests is fine for Travis.

**Comment by guolinke** [comment]
you can try to add following at this line:https://github.com/Microsoft/LightGBM/blob/master/.travis/test.sh#L16

```
export CXX=g++-7
export CC=gcc-7
```

**Comment by henry0312** [comment]
it this osx's tests script?

**Comment by guolinke** [comment]
@henry0312 it is the test for all systems.

**Comment by chivee** [comment]
@guolinke, we don't need to specific version in the travis, because that the osX version travis used didn't link gcc to AppleClang

**Comment by henry0312** [comment]
@chivee Is `gcc` and `g++` GNU GCC in osx of Travis?

**Comment by chivee** [comment]
@henry0312 , Refer to a [previous blog](https://blog.travis-ci.com/2014-06-20-osx-update-june-2014/), I guess yes

**Comment by henry0312** [comment]
> GCC 4.8 (available as gcc-4.8, gcc is still Apple’s LLVM-gcc) (GitHub issue #2423)

This means `gcc` is LLVM-gcc....🤔

**Comment by chivee** [comment]
Yes, let's stay using 'g++-7'

**Comment by henry0312** [comment]
sorry, I don't understand https://github.com/Microsoft/LightGBM/pull/719#issuecomment-317168499.

Does "version" in your comment mean os type?

**Comment by henry0312** [comment]
Anyway, all tests in Travis are passed 🎉

**Pull request merged**
