### PR TITLE
add 'mlr3learners.lightgbm' to README

### PR DESCRIPTION
**Pull request by t-wojciech**
CC @jameslamb

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
thanks @t-wojciech ! Much appreciated

**Comment by t-wojciech** [comment]
No problem!

**Comment by guolinke** [comment]
it seems this PR trigger the release of v3.1.2 ... very wreid

**Comment by jameslamb** [comment]
@guolinke no no it was my fault, not related to this PR

**Pull request merged**
