### PR TITLE
[ci] update CODEOWNERS

### PR DESCRIPTION
**Pull request by jameslamb**
This PR proposes a few updates to `CODEOWNERS`, to better reflect the current state of development in this project. As a reminder, this file is just used to set the _default_ reviewers for pull requests, based on the files touched by the PR. It isn't an authoritative list of who can / cannot review something.

* adds @jmoralez as a reviewer for R-related changes (per https://github.com/microsoft/LightGBM/pull/5048#discussion_r822871397)
* removes @wxchan and @henry0312, as it has been several years since they've contributed to this project
* adds myself to all Docker-related changes

## Notes for Reviewers

When I opened this PR, GitHub raised several of the following errors

> Unknown owner on line 15: make sure @chivee exists and has write access to the repository

image

image

@shiyu1994 or @guolinke ... has @chivee 's access to the repo been revoked? I don't have permission to see that.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@jameslamb 

> has @chivee 's access to the repo been revoked? I don't have permission to see that.

You just have to find any his comment and check the associated badge.

image


E.g. you and me are collaborators:

image
image

So yes, @chivee doesn't have write access to this repository anymore.

**Comment by StrikerRUS** [comment]
> to better reflect the current state of development in this project.

WDYT about writing something like years of active contributing here to prevent pings of currently inactive persons?
https://lightgbm.readthedocs.io/en/latest/FAQ.html#critical-issues

But I can't remember that topic starters ever ping someone 😃 .

**Review by guolinke — APPROVED** [review]

**Comment by jameslamb** [comment]
> You just have to find any his comment and check the associated badge.

ah thank you! I'm sorry, I remember now that you've told me about that trick before.

> @chivee doesn't have write access to this repository anymore

Ok, removed from `CODEOWNERS` in https://github.com/microsoft/LightGBM/pull/5063/commits/45e93b3c1b3892186ac724c968d7c512d8109a73.

> WDYT about writing something like years of active contributing here to prevent pings of currently inactive persons?

I don't think it's necessary. Like you said, I can't recall seeing an issue where someone tagged specific maintainers because of that list. My vote is to avoid adding additional information there that might become obsolete if we forget to update it regularly.

**Comment by StrikerRUS** [comment]
@jameslamb 
> I don't think it's necessary. ... My vote is to avoid adding additional information there that might become obsolete if we forget to update it regularly.

OK, I see.

**Review by StrikerRUS — APPROVED** [review]

**Comment by StrikerRUS** [comment]
I believe we should merge this only after @jmoralez's review.

**Review by jmoralez — APPROVED** [review]

**Comment by jameslamb** [comment]
👋 thanks all. And thanks @jmoralez for volunteering to help out on the R package!

**Pull request merged**
