### PR TITLE
[ci] Recover running CUDA tests at CI (fixed #4611)

### PR DESCRIPTION
**Pull request by shiyu1994**
The NVIDIA driver on the ci CUDA machine has been reloaded, and now we can recover the CUDA tests.

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
🚀 awesome, thank you so much!

And looks like they all passed, so no new CUDA-specific problems were introduced in the brief period these jobs weren't running.

**Comment by jameslamb** [comment]
@shiyu1994 just a very small thing...I noticed that your commit on this PR wasn't linked to your GitHub account

image

That probably means that your `~/.gitconfig` currently uses an email address that is not tied to your GitHub account. When this happens, it means that the lines you changed in PR's won't count in the "Contributors" view on the project's homepage. That doesn't matter much for this one, but would definitely want to be sure you get full credit for work on bigger PRs where I also see this issue, like #4528.

In case you've never dealt with this before, you can see https://github.com/uptake/pkgnet/pull/284#pullrequestreview-518230330 for information on how to fix it.

But to be clear...I don't think it needs to be blocking for this PR.

**Review by StrikerRUS — APPROVED** [review]
Thanks a lot @shiyu1994 !

**Comment by shiyu1994** [comment]
@jameslamb Thanks a lot for the reminder. I'll fix it.

**Pull request merged**
