### PR TITLE
add dart parameter to sklearn interface

### PR DESCRIPTION
**Pull request by wxchan**
@guolinke move from #140 , you can close that thread

1. I suggest adding them one by one in the end of `init`
in [sklearn.base.BaseEstimator](http://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html):

> Notes
> All estimators should specify all the parameters that can be set at the class level in their __init__ as explicit keyword arguments (no *args or **kwargs).

2. do we really need override get_params? I suggest move `if self.nthread <= 0: params.pop('nthread', None)` to fit() and delete this method.

### CODE REVIEW

**Comment by guolinke** [comment]
@wxchan , 
for 1, it seems will have many parameters...
for 2. Have you tested to not pop ```nthread``` in ```get_params``` ? I remember it will cause error..

**Comment by wxchan** [comment]
It passes the test even if I delete pop nthread. What kind of error did you meet?

**Comment by guolinke** [comment]
I forget the details. it seems is something like parameter xxx not found.
If it can pass the test. I think it is ok.

**Comment by wxchan** [comment]
Perhaps some error in c_api already been fixed?

I think we should follow sklearn.base.BaseEstimator though there will be many parameters because it's inherited, and it can let user know where to set drop_rate etc.

**Pull request merged**
