### PR TITLE
Fast single row predict API v2

### PR DESCRIPTION
**Pull request by AlbertoEAF**
- Fix bug introduced in PR #2992 for Fast predict (closes https://github.com/microsoft/LightGBM/issues/3241)
- Uses the newer API to make *Fast predict calls faster 
  The latest single-thread benchmark with a model of 42 numerical features achieved a speedup 1.30x-1.85x vs the standard single row prediction API)
- Stricter API with const parameters

### CODE REVIEW

**Comment by AlbertoEAF** [comment]
@imatiach-msft @StrikerRUS @guolinke please review, it is now even faster by the latest tests.

Thank you for waiting for the patch and good luck with the v3 release! ;)

**Comment by StrikerRUS** [comment]
I'm confused by `const`/`non-const` params mismatch in C API functions.

**Comment by guolinke** [comment]
For the non pointer arguments, I think we can unify them to the non constant types.

**Comment by AlbertoEAF** [comment]
@StrikerRUS good catch! I had const mismatches even between the .c and .h in the function signatures which made things extremely weird.

@guolinke I put instead everything const just because many were lacking const when they could be. Now I think it's really easy to interpret from the user's viewpoint. Only the input booster - which will be modified - and output pointers, are non-const.

**Comment by AlbertoEAF** [comment]
@guolinke do you think it's ready to merge?

Thank you

**Comment by guolinke** [comment]
Yeah, looks good to me

**Pull request merged**
