### PR TITLE
[python-package] Add type hints to init for LGBMModel

### PR DESCRIPTION
**Pull request by seanytak**
Adds
- Type hints for [init of LGBMModel](https://github.com/microsoft/LightGBM/blob/189a80181eb9e3e739a5f508a953ec6351be9dad/python-package/lightgbm/sklearn.py#L351) per #3756

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Thanks very much for the contribution! These changes look great to me.

**Comment by jameslamb** [comment]
oh wait! I just noticed one thing.

It seems that these commits are not signed with an email address associated with your GitHub account, so when this is merged your account might not be credited in https://github.com/microsoft/LightGBM/graphs/contributors.

I believe that has happened since the commits don't have your profile pic on them.

image

This probably means you need to set your email address in your `~/.gitconfig` to one associated with your GitHub account. See https://github.com/microsoft/LightGBM/pull/3607#issuecomment-735358654 and https://github.com/uptake/pkgnet/pull/284#pullrequestreview-518230330 for some tips on how to do that, if you are not familiar with it.

It's not necessary for this PR, we just want to be sure you get credit for your work!

**Review by StrikerRUS — APPROVED** [review]
LGTM, thanks!

**Comment by seanytak** [comment]
> oh wait! I just noticed one thing.
> 
> It seems that these commits are not signed with an email address associated with your GitHub account, so when this is merged your account might not be credited in https://github.com/microsoft/LightGBM/graphs/contributors.
> 
> I believe that has happened since the commits don't have your profile pic on them.
> 
> image
> 
> This probably means you need to set your email address in your `~/.gitconfig` to one associated with your GitHub account. See [#3607 (comment)](https://github.com/microsoft/LightGBM/pull/3607#issuecomment-735358654) and [uptake/pkgnet#284 (review)](https://github.com/uptake/pkgnet/pull/284#pullrequestreview-518230330) for some tips on how to do that, if you are not familiar with it.
> 
> It's not necessary for this PR, we just want to be sure you get credit for your work!

Thanks for the heads up! Had my gitconfig set to a different domain

**Comment by jameslamb** [comment]
> Thanks for the heads up! Had my gitconfig set to a different domain

no problem! It happens haha

We'll merge this once the CI jobs finish. Thanks again for contributing, and we hope you'll contribute more in the future 🙌

**Pull request merged**
