### PR TITLE
[python] add try/except in __del__

### LINKED ISSUE #1093: [Python] AttributeError: 'Booster' object has no attribute 'network'
## Environment info
Operating System: Windows Server 2012 R2 Standard
CPU: Intel Xeon CPU X5650 @ 2.67GHZ
C++/Python/R version: Python 3.6, pip installed LightGBM 2.0.11

## Error Message:
```
Exception ignored in: <bound method Booster.__del__ of <lightgbm.basic.Booster object at 0x0000004A00609BE0>>
Traceback <most recent call last>:
  File "C:\Continuum\Anaconda3\lib\site-package\lightgbm\basic.py", line 1351, in __del__
    if self.network:
AttributeError: 'Booster' object has no attribute 'network'
```
The code seems running through but throws this exception at the very end. There is no traceback to the code so not sure where it gets wrong. There is no exception when running the code on other Windows PC (Windows 7).

The code is only using LightGBM for prediction with a model read from a Pickle file:

```Python
def predict(model, data):
    pred_prob = pd.Series(model.predict_proba(data)[:, 1], name='pred_prob')
    pred = pd.Series(model.predict(data), name='pred')
    LOGGER.info("Prediction Success")
    LOGGER.info("{:d} True Out Of {:d} Total ({:.2f}%)".format(
        int(pred.sum()), len(pred), pred.sum()/len(pred)*100))
    return pred_prob, pred
```

And later use ```Lime``` to plot an Explainer:
```Python
def ......
            cat_features = [x_cols.index(i) for i in cat_cols]
            predict_fn = lambda x: model.predict_proba(x).astype(float)
            explainer = lime.lime_tabular.LimeTabularExplainer(
                np.array(data),
                feature_names=x_cols,
                class_names=['False', 'True'],
                categorical_features=cat_features,
                categorical_names=cat_cols)
            neg_samples = np.random.choice(np.reshape(np.asarray(np.where(
                pred_prob < 0.2)), -1), 5, False)
            pos_samples = np.random.choice(np.reshape(np.asarray(np.where(
                pred_prob > 0.8)), -1), 5, False)
```

Please help to figure out where causes this exception.

Thank you!

### PR DESCRIPTION
**Pull request by wxchan**
fix #1093 

I tested some cases, should work fine.

### CODE REVIEW

**Comment by wxchan** [comment]
@StrikerRUS I am not sure either.

**Comment by StrikerRUS** [comment]
Maybe @guolinke can help to assess the level of danger?

**Comment by guolinke** [comment]
@wxchan @StrikerRUS I think it is okay. 
However, I think it is better to print the exception message

**Comment by wxchan** [comment]
@guolinke I think all error msg will be something like:
```
Exception ignored in: <bound method Booster.__del__ of <lightgbm.basic.Booster object at >>
AttributeError: 'NoneType' object has no attribute 'network'
```
which are confusing and meaningless.

**Comment by guolinke** [comment]
@wxchan can we except that exception, and print others ?

**Comment by ClimbsRocks** [comment]
For what it's worth, printing exceptions makes logs really difficult to parse. If it's an ignored exception, and you really want the user to know, I think that `warnings` are more appropriate than printing a bunch of lines that look an awful lot like exceptions when grepping through logs.

**Comment by wxchan** [comment]
seems gpu tests fail

```
Saving to: ‘AMD-SDK.tar.bz2’

    [ <=>                                   ] 44,134      --.-K/s   in 0.03s   

2017-12-09 08:26:41 (1.57 MB/s) - ‘AMD-SDK.tar.bz2’ saved [44134]

bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
sh: 0: Can't open AMD-APP-SDK*.sh
chmod: cannot access ‘/home/travis/AMDAPPSDK/bin/x86_64/clinfo’: No such file or directory
.travis/test.sh: line 11: /home/travis/AMDAPPSDK/bin/x86_64/clinfo: No such file or directory
```

**Comment by wxchan** [comment]
@huanzhang12 the gpu tests on master is somehow broken, can you help fix it?

**Comment by guolinke** [comment]
@huanzhang12 you can create another PR to fix GPU test issue. Thanks !

**Comment by huanzhang12** [comment]
@guolinke fixed in PR #1113

**Pull request merged**
