### PR TITLE
Remove silent param from demo and regenerate Rd files

### PR DESCRIPTION
**Pull request by Laurae2**
Fixes :
* Issue #913 (`lgb.get.eval.result` Rd example)
* Fix some spaces in examples
* Remove silent parameter from demo

### CODE REVIEW

**Comment by Laurae2** [comment]
@StrikerRUS any idea why Travis fails? https://travis-ci.org/Microsoft/LightGBM/jobs/281863464

**Comment by StrikerRUS** [comment]
@Laurae2 Phantom errors on Travis side. Just click **Rebuild** (if you have rights at Travis site) or push some fake commit to trigger new build.

They [reported ](https://blog.travis-ci.com/2017-09-22-macos-update) that OSX builds are more stable now. Nevertheless, we can see that not...

**Comment by guolinke** [comment]
@Laurae2 you can merge it by yourself if you think it is ready.

**Comment by Laurae2** [comment]
@guolinke It seems I can't:

image

**Pull request merged**
