### PR TITLE
[CUDA] Add Poisson regression objective for cuda_exp and refactor objective functions for cuda_exp

### PR DESCRIPTION
**Pull request by shiyu1994**
Add Poisson regression objective for cuda_exp. We noticed that for Poisson regression, the results of `test_regression` in `test_engine.py` is slightly worse than CPU version. We conjecture there's still minor difference between details of `cuda_exp` and `cpu`. We will record it in an issue for now and fix the gap later on.

### CODE REVIEW

**Comment by shiyu1994** [comment]
@jameslamb It seems that the Static Analysis are failing in all CI jobs for R code. Could you please help to check? Thanks.

**Comment by jameslamb** [comment]
@shiyu1994 I already put up a pull request yesterday to fix that: https://github.com/microsoft/LightGBM/pull/5485

Please, when you see a CI issue that is unrelated to your changes, first look for an open issue or pull request with the label `blocking` to see if it's already being worked on.

**Comment by shiyu1994** [comment]
With commit [2e31f9e](https://github.com/microsoft/LightGBM/pull/5486/commits/2e31f9e28fdcc8281932fadecef648ef133d235e), the previously recorded difference between the performance of `cuda_exp` and `cpu` versions will be removed. In other words, this PR is to close #5487 and #5470. The difference was because that initial score was not correctly used.

**Comment by shiyu1994** [comment]
> With commit [2e31f9e](https://github.com/microsoft/LightGBM/pull/5486/commits/2e31f9e28fdcc8281932fadecef648ef133d235e), the previously recorded difference between the performance of `cuda_exp` and `cpu` versions will be removed. In other words, this PR is to close #5487 and #5470. The difference was because that initial score was not correctly used.

Sorry. I found that these differences are not closed. My previous observation was based on CPU version...

**Comment by jameslamb** [comment]
@shiyu1994 now that recent CI issues have been addressed, I just pushed https://github.com/microsoft/LightGBM/pull/5486/commits/29d573524a09288620849f427ee663135ca7763b updating this with `master` for you 👋

**Comment by shiyu1994** [comment]
The self-hosted CUDA machine has a driver issue again. Reboot the machine and reopen this PR.

**Comment by guolinke** [comment]
@shiyu1994 ping me when this PR is ready

**Comment by shiyu1994** [comment]
@guolinke Some segment faults are failing. Will fix them soon. BTW, this PR refactors the cuda objective classes into a more elegant format. So it does not only add an objective and there will be more code changes.

**Comment by jameslamb** [comment]
@shiyu1994 I'm seeing those same segfaults on the `Linux_` jobs over on https://github.com/microsoft/LightGBM/pull/5588. I don't think they're related to the code in this PR.

I've been trying different things on #5588 and so far haven't been able to fix it 😭 .

**Comment by jameslamb** [comment]
@shiyu1994 I just updated this to latest `master`. Now that #5580 has been merged, hopefully you won't see other CI issues.

**Comment by shiyu1994** [comment]
Close and reopen to trigger ci test.

**Comment by shiyu1994** [comment]
@jameslamb Thanks for your help!

**Comment by shiyu1994** [comment]
@guolinke This is ready for review.

**Review by guolinke — APPROVED** [review]
LGTM

**Pull request merged**
