### PR TITLE
[python] remove outdated code

### PR DESCRIPTION
**Pull request by StrikerRUS**

### CODE REVIEW

**Comment by wxchan** [comment]
Isn't just 2.0.11 now? I think it should be pushed to a 2.0.12 developing branch?

**Comment by StrikerRUS** [comment]
@wxchan 
@guolinke removed `max_bin` which had the same warning: https://github.com/Microsoft/LightGBM/pull/1083#issuecomment-346927947

**Comment by guolinke** [comment]
@wxchan 2.0.11 was realased.  the master brach is going to 2.0.12

**Comment by wxchan** [comment]
ok, got it.

**Comment by wxchan** [comment]
what about the max_bin parameter?

**Pull request merged**
