### PR TITLE
[R-package] Add lgb.convert from smart matrix building

### LINKED ISSUE #557: [R] auto convert factor to categorical feature
We already have this in python-package. I think we can add it to the R package as well.
@Laurae2 can you help for this ?

### PR DESCRIPTION
**Pull request by Laurae2**
Fix #557

Done:

- [x] Method 1 
- NO ~~Method 2~~
- [x] Function doc
- [x] Example (simple use case)
- NO ~~Example doc (more detailed use case)~~
- [x] Update docs to roxygen 6.0.1
- [x] Work for both integer or numeric output (edge cases)
- [x] Work for characters
- [x] Work for factors
- [x] Add transformer

Method 1 (only for dense):

* Parse factors -> numeric
* Parse characters -> numeric
* ~~Keep data as dense, but convert to matrix format~~

~~Method 2 (default, only for dense):~~

* ~~Parse characters -> factor~~
* ~~Parse factors -> one hot encoding~~
* ~~Convert data to sparse~~

Example code:

```r
library(lightgbm)
data(iris)
str(iris)
str(lgb.prepare(data = iris)) # Convert all factors/chars to integer
```

```r
> data(iris)
> str(iris)
'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
> str(lgb.prepare(data = iris)) # Convert all factors/chars to integer
'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : int  1 1 1 1 1 1 1 1 1 1 ...
```

And also:

```r
>   data(iris)
>   str(iris)
'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
>   new_iris <- lgb.prepare_rules(data = iris) # Autoconverter
>   str(new_iris$data)
'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : int  1 1 1 1 1 1 1 1 1 1 ...
>   data(iris) # Erase iris dataset
>   iris$Species[1] <- "NEW FACTOR" # Introduce junk factor (NA)
Warning message:
In `[<-.factor`(`*tmp*`, 1, value = c(NA, 1L, 1L, 1L, 1L, 1L, 1L,  :
  invalid factor level, NA generated
>   newer_iris <- lgb.prepare_rules(data = iris, rules = new_iris$rules)
>   newer_iris$data[1, ] # Species became 0 as it is an unknown factor
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2       0
>   newer_iris$data[1, 5] <- 1 # Put back real initial value
>   all.equal(new_iris$data, newer_iris$data)
[1] TRUE
>   data(iris) # Erase iris dataset
> personal_rules <- list(Species = c("setosa" = 3L,
+                                      "versicolor" = 2L,
+                                      "virginica" = 1L))
>   newest_iris <- lgb.prepare_rules(data = iris, rules = personal_rules)
>   str(newest_iris$data) # SUCCESS!
'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : int  3 3 3 3 3 3 3 3 3 3 ...
```

### CODE REVIEW

**Comment by Laurae2** [comment]
@guolinke Leaving the user the need to convert to matrix, it's documented ("It must be converted to a matrix format (as.matrix) for input in lgb.Dataset.")

I also updated docs to roxygen 6.0.1

**Comment by guolinke** [comment]
@Laurae2 
Is the conversion rule the same when change the data?
for example, If I use a different data for the prediction, can it keep the same mapping as the training data?

**Comment by Laurae2** [comment]
@guolinke no, must bind training/testing data first, convert all together. If the user wants to be able to convert new data, he/she must create a proper data converter and store the list of all rules for conversion.

I can try to add rule sets. (don't merge yet)

**Comment by guolinke** [comment]
@Laurae2 
okay, In python-package version, we append the conversion rule to the model file, so that we can keep it the same.

**Comment by Laurae2** [comment]
@guolinke Added rules, you can check the example.

**Comment by guolinke** [comment]
@Laurae2 
Will ```prepare2``` and ```prepare_ruler2``` be really used ?

**Comment by Laurae2** [comment]
@guolinke There are existing C++ wrappers (not LightGBM) where if you input only numeric input it causes crash. For instance, xgboost in the past could not build any matrix from integer inputs (they fixed all integer-only matrices recently).

Integers and numerics are not strictly identical in memory, sometimes causing issues when given to C/C++. They are only here for compatibility purposes (like `cbind2`, `rbind2`, etc.). So I think they still have a potential use, for edge cases.

**Comment by szilard** [comment]
FYI LightGBM actually crashed when I used in `as.integer(as.factor(d_train_test[[k]]))` instead of `as.numeric(as.factor(d_train_test[[k]]))` because all other variables were integer, no doubles:
https://github.com/szilard/GBM-perf/blob/6f9aaeb27ac8d7ac7792254403c4d657357317ae/run/3-lightgbm2.R#L17

When all other features are integers and we use `as.integer` and then `as.matrix`, the matrix is a matrix of integers and causes crash.

**Pull request merged**
