### PR TITLE
[ci] place all CI helpers under the .ci folder and use - instead of _ in their names

### PR DESCRIPTION
**Pull request by StrikerRUS**
Simplify repo's structure in the following way:
1. Move all CI scripts under `.ci` folder
2. use `-` instead of `_` in scripts' names to ensure their correct ordering

`breaking` tag due to "public" `build-r.R` script.

### CODE REVIEW

**Review by borchero — APPROVED** [review]
What's the benefit of this change? :smile:

**Comment by StrikerRUS** [comment]
@borchero Simplification of the repo's structure. All helper scripts used in our CI are placed in one directory. Newcomers won't struggle deducing the difference between `helpers` and `.ci` folders, for example.

**Comment by borchero** [comment]
@StrikerRUS ok, I only briefly looked at the file changes before and it seemed like it would _only_ include renames from snake case to kebab case. I see that it actually moves three files :smile:

I guess (1) moving files makes a lot of sense, I'm not too sure about (2) changing the file names but I don't really mind.

**Review by jameslamb — CHANGES_REQUESTED** [review]
I support the idea of removing `helpers/` and just consolidating everything into `ci/`. That will definitely reduce a bit of friction.

I also support preferring `-` to `_`, as it requires one less keypress (it's a minor thing, but still nice!).

However.... I think we should keep `build_r.R` using snake_case. As you noted, it sort of is "public". It's the documented, preferred entry point for building custom variations of the R package (like with GPU support). I don't support breaking peoples' builds in exchange for a bit more consistency in the naming of scripts.

**Comment by StrikerRUS** [comment]
@jameslamb 

> I think we should keep `build_r.R` using snake_case.

Reverted in d0dbc6382c915d117b950b8e2f6ea1122185fdad.

**Review by jameslamb — APPROVED** [review]
great, thank you

**Pull request merged**
