### PR TITLE
add_DLL_path

### PR DESCRIPTION
**Pull request by HudsonHuang**
Following this guide ：https://github.com/Microsoft/LightGBM/wiki/Installation-Guide

When installing python-package, the default DLL path on my system (Windows 7,Visual Studio 2012,x64 with MPI), is "../../windows/x64/Release/lightgbm.dll".

Using default setting may cause an error of not founding any dlls.

### CODE REVIEW

**Comment by guolinke** [comment]
can you clear up these commits?

**Comment by Laurae2** [comment]
@HudsonHuang are you targeting specifically v1, master, or both branches?

If you target both branches, you need to make separate pull requests.

**Comment by HudsonHuang** [comment]
@Laurae2 emmm...I am not sure, maybe I should just make a pull to tests branch ? And I am going to clean the commet and request again.

**Comment by guolinke** [comment]
@HudsonHuang 
it seems you don't push any new commits.

**Comment by Laurae2** [comment]
@HudsonHuang You must push to your own LightGBM repository to add commits proposed to the main branches on this repository via Pull Requests.

Also, this PR is on the wrong branch, unless you are really expecting to push to our (frozen) v1 branch.

**Pull request closed without merging**
