### PR TITLE
[python-package] fix mypy error about missing type hint in dask.py

### PR DESCRIPTION
**Pull request by jameslamb**
Contributes to #3867.

This PR fixes one `mypy` error in `dask.py`.

> python-package/lightgbm/dask.py:933: error: Need type annotation for "out"

Confirmed that this suppresses these warnings by running the following.

```shell
mypy \
    --exclude='python-package/compile/|python-package/build' \
    --ignore-missing-imports \
    python-package/
```

### CODE REVIEW

**Comment by jmoralez** [comment]
I think the first time `out` is populated in https://github.com/microsoft/LightGBM/blob/b94577d05cd08a6a9147bff16395d442866cb511/python-package/lightgbm/dask.py#L945 it's actually `List[List[dask_Array]]`, where each entry has as many items as there are partitions. Then the contents get overwritten in https://github.com/microsoft/LightGBM/blob/b94577d05cd08a6a9147bff16395d442866cb511/python-package/lightgbm/dask.py#L959 where the partitions get concatenated and the elements become `List[dask_Array]`.

I think variables changing types is a big no-no for `mypy` so maybe we could define two variables here?

**Comment by jameslamb** [comment]
> it's actually`List[List[dask_Array]]`

ooooooo you're right! I missed that `.append()`. Fixed in https://github.com/microsoft/LightGBM/pull/4840/commits/006a271fe8b4d4352b751b385b0b8319a6357684.

> where the partitions get concatenated and the elements become `List[dask_Array]`.
> I think variables changing types is a big no-no for `mypy` so maybe we could define two variables here?

You're generally right about `mypy` not liking it when code overwrites a variable with a value of a different type than it was initialized with. Fixed in https://github.com/microsoft/LightGBM/pull/4840/commits/32f40dec3dc7813ca5649459598bcac3c2150f7c.

**Review by jmoralez — APPROVED** [review]

**Comment by jameslamb** [comment]
just re-ran the R-package jobs, let's see if the MiKTeX issue (https://github.com/microsoft/LightGBM/issues/4005#issuecomment-983235895) was fixed overnight

**Comment by jameslamb** [comment]
🎉 CI seems happy again! 

e.g. from [this Windows build](https://github.com/microsoft/LightGBM/runs/4383385794?check_suite_focus=true)

> The downloaded binary packages are in
	C:\Users\runneradmin\AppData\Local\Temp\RtmpwpHjaj\downloaded_packages
Downloading https://github.com/microsoft/LightGBM/releases/download/v2.0.12/miktexsetup-4.0-x64.zip
Setting up MiKTeX
Installing MiKTeX
Done installing MiKTeX

**Pull request merged**
