### PR TITLE
[R-package] Remove non-beneficial parallelization

### PR DESCRIPTION
**Pull request by david-cortes**
The R wrapper makes usage of OMP parallel clauses for operations like converting from one data type to another.

In a regular amd64 platform, these clauses would not make the operations faster, since these operations (assuming https://github.com/microsoft/LightGBM/pull/6208 gets merged beforehand) are so fast that speed of execution is given by how fast it can read data from RAM, and having multiple threads reading from RAM (as far as desktop amd64 is concerned) does not make those reads any faster.

This PR switches the clause from parallel to `simd` which would be more appropriate for `amd64`, but is unlikely to make a difference in most cases since there aren't dedicated SIMD instructions for all these operations.

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Thanks for this!

I hadn't seen `#pragma omp simd` before, but based on my read of these:

* https://www.ibm.com/docs/en/xl-c-and-cpp-linux/16.1.0?topic=pdop-pragma-omp-simd
* https://www.openmp.org/spec-html/5.0/openmpsu42.html

I agree that it's more appropriate than multi-threading for these particular loops. Assuming CI doesn't uncover any portability issues, I support this.

**Review by jameslamb — CHANGES_REQUESTED** [review]
In the MSVC jobs, I see the following compilation errors:

> C:\Users\runneradmin\RtmpuUk2KH\Rbuild1ed04e141067\lightgbm\src\src\lightgbm_R.cpp(230,9): error C7660: 'simd': requires '-openmp:experimental' command line option(s) [C:\Users\runneradmin\RtmpuUk2KH\Rbuild1ed04e141067\lightgbm\src\build\lightgbm_capi_objs.vcxproj]

I see that with both Visual Studio 2019 ([build link](https://github.com/microsoft/LightGBM/actions/runs/7344120232/job/19995549132))) and Visual Studio 2022 ([build link](https://github.com/microsoft/LightGBM/actions/runs/7344120232/job/19995549210)).

I found some details on this at https://learn.microsoft.com/en-us/cpp/build/reference/openmp-enable-openmp-2-0-support?view=msvc-170.

Could you please just guard these so they'll be ignored when compiling with MSVC?

Similar to what XGBoost does: https://github.com/dmlc/xgboost/blob/a197899161fa70e681101de4232745fdfe737804/R-package/src/xgboost_R.cc#L403-L405

```cpp
#ifndef _MSC_VER
#pragma omp simd
#endif
```

**Comment by david-cortes** [comment]
Added.

But on second thought, these aren't going to do anything in most cases, so I've replaced the loops altogether and switched vectors to unique pointers where possible.

**Review by jameslamb — APPROVED** [review]
Looks great to me. I'm confident in this based on the passing tests...these code paths are all well-covered.

Thanks very much.

**Pull request merged**
