### PR TITLE
[fix] change the destructor of ScoreUpdater to virtual (fixes #5400)

### LINKED ISSUE #5400: Compilation warning `warning: delete called on non-final 'LightGBM::ScoreUpdater' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]`
```
[ 10%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/boosting/gbdt_model_text.cpp.o
In file included from /__w/1/s/src/boosting/gbdt.cpp:5:
In file included from /__w/1/s/src/boosting/gbdt.h:8:
In file included from /__w/1/s/include/LightGBM/boosting.h:8:
In file included from /__w/1/s/include/LightGBM/config.h:15:
In file included from /__w/1/s/include/LightGBM/meta.h:11:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/memory:80:
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:81:2: warning: delete called on non-final 'LightGBM::ScoreUpdater' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
        delete __ptr;
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:292:4: note: in instantiation of member function 'std::default_delete<LightGBM::ScoreUpdater>::operator()' requested here
          get_deleter()(std::move(__ptr));
          ^
/__w/1/s/src/boosting/gbdt.cpp:25:7: note: in instantiation of member function 'std::unique_ptr<LightGBM::ScoreUpdater, std::default_delete<LightGBM::ScoreUpdater> >::~unique_ptr' requested here
GBDT::GBDT()
      ^
[ 12%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/boosting/gbdt_prediction.cpp.o
```

I guess these warning and notes were introduced in #5279.

@shiyu1994

### PR DESCRIPTION
**Pull request by shiyu1994**
This is to fix #5400.

### CODE REVIEW

**Comment by jameslamb** [comment]
@shiyu1994 please add one of the labels from https://github.com/microsoft/LightGBM/blob/c7102e56b246cc5cd73d9787b2c837c0bc384d1e/.github/release-drafter.yml#L3 to every pull request you open, so it will be correctly categorized in the release notes

**Comment by jameslamb** [comment]
also @shiyu1994 I noticed you created this PR from your branch...can you please just create branches here in `microsoft/LightGBM`?

That makes it easier for other maintainers to help and collaborate, e.g. avoids issues like #5371.

**Comment by shiyu1994** [comment]
@jameslamb Thanks. Will always create a branch on microsoft/LightGBM in the future.

**Comment by jameslamb** [comment]
Sorry @shiyu1994 , it looks like `valgrind` job is timing out. I'm not sure why, but it has been a few weeks since we last ran that job and I know there have been some significant changes on `master` in that time.

I opened #5414 increasing the timeout, hopefully that will help.

**Comment by jameslamb** [comment]
@shiyu1994 the `valgrind` test is now failing for what looks like a real reason, not a timeout.

```text
==4762== 352 bytes in 1 blocks are possibly lost in loss record 152 of 2,904
==4762==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==4762==    by 0x40147D9: calloc (rtld-malloc.h:44)
==4762==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==4762==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==4762==    by 0x4DF4834: allocate_stack (allocatestack.c:430)
==4762==    by 0x4DF4834: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==4762==    by 0x575B1EF: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==4762==    by 0x5751A10: GOMP_parallel (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==4762==    by 0x16C99F47: OMP_NUM_THREADS() (openmp_wrapper.h:22)
==4762==    by 0x16FE6E64: OMP_SET_NUM_THREADS(int) (openmp_wrapper.h:29)
==4762==    by 0x16FDB3AC: LGBM_DatasetCreateFromCSC (c_api.cpp:1462)
==4762==    by 0x1700C83C: LGBM_DatasetCreateFromCSC_R (lightgbm_R.cpp:183)
==4762==    by 0x4953D8A: R_doDotCall (dotcode.c:627)
==4762==    by 0x495ED3E: do_dotcall (dotcode.c:1284)
==4762==    by 0x499E245: Rf_eval (eval.c:851)
```

([build link](https://github.com/microsoft/LightGBM/runs/7787830516?check_suite_focus=true))

That might not be from this PR (it has been a while since we have run `r-valgrind`), but it should be fixed. Given that it's coming from `LGBM_DatasetCreateFromCSC`, I suspect it might be related to #5344, but not sure.

Can you please look into it?

**Comment by shiyu1994** [comment]
@jameslamb I did not find any potential memory linkage introduced by the changes of `LGBM_DatasetCreateFromCSC` from #5344. I noticed that there's one false positive case documented about `LGBM_DatasetCreateFromCSC` 
https://github.com/microsoft/LightGBM/blob/9489f878b3568e70b441e5df602483e116f24cc6/.ci/test_r_package_valgrind.sh#L48-L63.
Is it related to the new error message? They seem quite similar.

**Comment by jameslamb** [comment]
oh wow @shiyu1994 you are right! Very nice attention to detail!!

This looks like EXACTLY that same issue, even the same stack trace. I guess the test is failing because the "possibly lost" went from 336 bytes.

https://github.com/microsoft/LightGBM/blob/9489f878b3568e70b441e5df602483e116f24cc6/.ci/test_r_package_valgrind.sh#L49

to 352 (https://github.com/microsoft/LightGBM/pull/5403#issuecomment-1217956439)

The fact that it's exactly 16 bytes is interesting. I wonder if maybe, for example, some change from `int16`  to `int32` or something somewhere is causing this? That could be coming from a change in libomp version, compiler version, or something else...I think it's ok just to increase the limit in the test. I'll put up a PR to do that.

**Comment by jameslamb** [comment]
🎉 glad `valgrind` is passing now!

whenever @guolinke is able to review and approve this, let's merge it.

**Review by guolinke — APPROVED** [review]

**Comment by jameslamb** [comment]
I wanted to check that this fixed the warning from #5400, but unfortunately the build logs are already gone from Azure.

image

So I was going to merge `master` into this and push a commit, but I can't because this is from your fork.

Closing and re-opening to re-trigger CI.

**Review by jameslamb — APPROVED** [review]
Checked the logs for several different CI jobs and I don't see any warnings after:

```text
[ 11%] Building CXX object CMakeFiles/lightgbm_objs.dir/src/boosting/gbdt_model_text.cpp.o
```

Thanks for the fix!

**Pull request merged**
