### PR TITLE
Add python things to .gitignore

### PR DESCRIPTION
**Pull request by henry0312**

### CODE REVIEW

**Comment by henry0312** [comment]
I agreed the contribution license agreement.

**Comment by guolinke** [comment]
@henry0312 , It seems the Labels will auto change to ```cla-signed``` if you finish the CLA..
I am not sure what happen, can you try sign again?

**Comment by henry0312** [comment]
@guolinke I tried again.

image

**Comment by henry0312** [comment]
thank you.

**Pull request merged**
