### PR TITLE
Update StringArray.i

### PR DESCRIPTION
**Pull request by Shahil093**
Two new functions have been added:

StringArrayHandle_append_string: This function appends a new string to the existing StringArray. It takes the handle of the StringArray and the content of the string to be appended. The function returns 0 on success and -1 in case of failure.

StringArrayHandle_clear: This function clears the content of the StringArray. It takes the handle of the StringArray and removes all the stored strings.

### CODE REVIEW

**Comment by Shahil093** [comment]
@microsoft-github-policy-service agree

**Comment by Shahil093** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks for your interest in LightGBM but what is the purpose of this? How does it improve LightGBM?

**Comment by Shahil093** [comment]
StringArrayHandle_append_string: This function appends a new string to the existing StringArray. It takes the handle of the StringArray and the content of the string to be appended. The function returns 0 on success and -1 in case of failure.

StringArrayHandle_clear: This function clears the content of the StringArray. It takes the handle of the StringArray and removes all the stored strings.

These are the features which add new features to it.

**Comment by Shahil093** [comment]
he code snippet provided earlier is a SWIG interface file that wraps the StringArray class for usage in the LightGBM project.

**Comment by jameslamb** [comment]
>  the code snippet provided earlier is a SWIG interface file that wraps the StringArray class for usage in the LightGBM project

That does not explain how these added methods improve LightGBM.

And in fact these changes do not even compile successfully on macOS ([link](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=14760&view=logs&j=cc4f6880-f145-596b-2c6c-97595b94be65&t=03d7e388-77db-592f-837b-c883b0fffc53)), Linux ([link](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=14760&view=logs&j=535e9539-0564-5d34-2431-da2644b83c50&t=7cfc64df-bff4-5eef-5deb-8ea58a924da8)), or Windows ([link](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=14760&view=logs&j=457fb6cd-b9a6-52d5-ab83-9fdcfc761c31&t=302dfe64-6e46-5035-7255-9ce91154684d)) 

```text
[ 96%] Building CXX object CMakeFiles/_lightgbm_swig.dir/java/lightgbmlibJAVA_wrap.cxx.o
/Users/runner/work/1/s/build/java/lightgbmlibJAVA_wrap.cxx:967:57: error: no member named 'append' in 'StringArray'
        return reinterpret_cast<StringArray *>(handle)->append(std::string(content));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
/Users/runner/work/1/s/build/java/lightgbmlibJAVA_wrap.cxx:977:50: error: no member named 'clear' in 'StringArray'
        reinterpret_cast<StringArray *>(handle)->clear();
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
2 errors generated.
make[2]: *** [CMakeFiles/_lightgbm_swig.dir/java/lightgbmlibJAVA_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/_lightgbm_swig.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX executable /Users/runner/work/1/s/lightgbm
[ 98%] Built target lightgbm
make: *** [all] Error 2
```

I'm closing this.

------

From this, #5911, and your recent GitHub history, it appears to me that you're just getting started learning how to contribute to open source projects. Welcome!

Please:

* follow the advice and read the links provided in https://github.com/google/guava/pull/6525#issuecomment-1571544495 
* try to test your changes locally before opening pull requests
* stop opening pull requests here with changes whose benefit you cannot explain

**Pull request closed without merging**
