### PR TITLE
Optimal split for categorical feature

### PR DESCRIPTION
**Pull request by guolinke**
refer to #699 

add 3 parameters:  `max_cat_group`, `max_cat_threshold` and `cat_smooth` .

Accuracy comparison:
before:
```
[LightGBM] [Info] Trained a tree with leaves=31 and max_depth=13
[LightGBM] [Info] Iteration:100, valid_1 auc : 0.737741
[LightGBM] [Info] 33.623861 seconds elapsed, finished iteration 100
[LightGBM] [Info] Finished training
```

after:
```
[LightGBM] [Info] Trained a tree with leaves=31 and max_depth=10
[LightGBM] [Info] Iteration:100, valid_1 auc : 0.74848
[LightGBM] [Info] 46.467845 seconds elapsed, finished iteration 100
[LightGBM] [Info] Finished training
```

command: ```lightgbm.exe data=dataexpo.train test=dataexpo.test metric=auc app=binary categorical_column=0,1,2,4,5,6```
dataset is from this repo: https://github.com/szilard/GBM-perf 

to-do:

- [x]  Add tests
- [x]  Update docs
- [x]  Improve split speed

### CODE REVIEW

**Comment by guolinke** [comment]
@wxchan 
can you help to check the new if-else code ?

**Comment by wxchan** [comment]
@guolinke ok. I think you can add a test case with categorical features into tests/cpp_test/.

**Comment by guolinke** [comment]
@wxchan 
can you help to refine the if-else code, to let it can use bitset to speed up the prediction of categorical features ?

**Comment by wxchan** [comment]
@guolinke I may take some time to read current changes. I can start this weekend.

**Comment by guolinke** [comment]
@wxchan 
The main logic is in here: https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/tree.h#L212-L227 
Now it is naive solution that need to compare all thresholds.

**Pull request merged**
