### PR TITLE
Clean codes for python-package; dump model to JSON

### PR DESCRIPTION
**Pull request by wxchan**
Used for python or other package to make calculations on model. 

I created another branch after Microsoft/python-package, which will be merged into this branch after python-package finished. So you can review this PR after that.

The tree is dumped as tree structure, for example:
```
{
    "tree_index": 0,
    "tree_structure": {
        "split_feature": 25,
        "right_child": {
            "leaf_parent": 0,
            "leaf_value": 0.0177513,
            "leaf_index": 1
        },
        "left_child": {
            "split_feature": 25,
            "right_child": {
                "split_feature": 26,
                "right_child": {
                    "leaf_parent": 2,
                    "leaf_value": 0.0350313,
                    "leaf_index": 3
                },
                "left_child": {
                    "leaf_parent": 2,
                    "leaf_value": 0.0213992,
                    "leaf_index": 2
                },
                "split_index": 2,
                "internal_value": 0.657011,
                "threshold": 0.7745,
                "split_gain": 30.3472
            },
            "left_child": {
                "leaf_parent": 1,
                "leaf_value": 0.0206436,
                "leaf_index": 0
            },
            "split_index": 1,
            "internal_value": 0.596097,
            "threshold": 0.5925,
            "split_gain": 45.18
        },
        "split_index": 0,
        "internal_value": 0,
        "threshold": 1.0895,
        "split_gain": 65.198
    },
    "num_leaves": 4
}
```

### CODE REVIEW

**Comment by wxchan** [comment]
I came across a problem.

I add functions as follow:

src/c_api.cpp:
[LGBM_BoosterDumpModel](https://github.com/wxchan/LightGBM/blob/python-package/src/c_api.cpp#L712-L718):
```
DllExport int LGBM_BoosterDumpModel(BoosterHandle handle,
  const char** out_str) {
  API_BEGIN();
  Booster* ref_booster = reinterpret_cast<Booster*>(handle);
  *out_str = ref_booster->DumpModel().c_str();
  API_END();
}
```

[Booster::DumpModel](https://github.com/wxchan/LightGBM/blob/python-package/src/c_api.cpp#L151-L153):
```
std::string DumpModel() {
  return boosting_->DumpModel();
}
```

[python-package/lightgbm/basic.py](https://github.com/wxchan/LightGBM/blob/python-package/python-package/lightgbm/basic.py#L997-L1002):
```
def dump_model(self):
  tmp_model = ctypes.c_char_p()
  _safe_call(_LIB.LGBM_BoosterDumpModel(self.handle, ctypes.byref(tmp_model)))
  print(tmp_model.value[:100]) # check the output
```

And the output in last line is:
```
b'\x01\x00\x00\x00\x00\x00\x00\x00\xd0\xa5\x1b\x00\x01\x00\x00\x00\x95s\x00
\x00\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xfflabel_index":0,\n"max_f
eature_idx":99,\n"objective":"binary",\n"sigmoid'
```
Why this happens?

**Comment by guolinke** [comment]
@wxchan , the reason is you returning pointer of temporary memory(```ref_booster->DumpModel().c_str()```). 
The solution:
1. allocate a str_buf in python, and copy from c_str. https://github.com/Microsoft/LightGBM/blob/python-package/python-package/lightgbm/basic.py#L1070-L1075
2. use a template class to manage these temporary resource, like xgboost do:
https://github.com/dmlc/xgboost/blob/master/src/common/thread_local.h
https://github.com/dmlc/xgboost/blob/master/src/c_api/c_api.cc#L186-L200
https://github.com/dmlc/xgboost/blob/master/src/c_api/c_api.cc#L668-L678
However, these resources only will be freed when application quit.

I think pre-allocate the buffer in the python is a better solution. But it is hard to decide the buffer len. May be you can pass the buffer len of python as well, and return actual len.
If buffer len is smaller than actual len, you do nothing in c_api and re-allocate the buffer in python then call again.

**Comment by wxchan** [comment]
[Fixed with 1st solution](https://github.com/wxchan/LightGBM/blob/python-package/python-package/lightgbm/basic.py#L998-L1017). Buffer len is set to 2^20 now, for reference, with num_leaf=15 and num_tree=100, the actual len is around 2^18.

**Comment by wxchan** [comment]
@guolinke model loaded from file cannot dump to json now(cause segmentation fault), any clue why?

**Comment by guolinke** [comment]
i think some fields are not loaded from file. e.g. threshold_in_bin_

**Comment by wxchan** [comment]
@guolinke I find the reason, to calculate feature importance needs train_data_->feature_names(). I am going to remove feature importance in dumped string for now.

**Comment by guolinke** [comment]
@wxchan I see. It seem We should load feature_names_ as well when load model from file. 
(So we should save feature_names_ to file as well)
I will add this into categorical-feature-support branch. 
And we can continue to provide interface of set feature name and get feature importance.

**Comment by guolinke** [comment]
it seems travis is down... I will merge this after some reviews.

**Comment by wxchan** [comment]
@guolinke Feature importance is not needed in dumped string. To use another interface will be fine.

I was doing some small updates with `commit --amend`, but I finished now. It should also solves #102 .

**Pull request merged**
