### PR TITLE
[R-install] Make CMakeLists.txt relative

### LINKED ISSUE #1678: Install R package error ( Windows10 )
## Environment info
Windows 10 x64
R version 3.5.1(Path)
Rtools34 (Path)
VS 2017
Cmake(Path)

## Running following command in RStudio

```
devtools::install_github("Laurae2/lgbdl", force = TRUE)
library(lgbdl)
lgb.dl(commit = "master",
compiler = "vs",
repo = "https://github.com/Microsoft/LightGBM",
cores =6,
r35 = true)
```

## Error message

```
* installing *source* package 'lightgbm' ...
** libs
c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-35~1.1/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c R_init.c -o R_init.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o lightgbm.dll tmp.def R_init.o -LC:/R/R-35~1.1/bin/x64 -lR
installing via 'install.libs.R' to C:/R/R-3.5.1/library/lightgbm
 eval(ei, envir) error : Copying CMakeLists failed
* removing 'C:/R/R-3.5.1/library/lightgbm'
In R CMD INSTALL
[1] FALSE
Warning message:
In install.packages(file.path(lgb_git_dir, "LightGBM", "R-package",  :
  installation of package ‘C:/Users/Kline/AppData/Local/Temp/Rtmpwb0XlY/LightGBM/R-package’ had non-zero exit status
```
I found the error message "Copying CMakeLists failed" in the following URL (line 20),
but I don't know how to fix it. Please help me. 
<https://github.com/Microsoft/LightGBM/blob/master/R-package/src/install.libs.R>
```
# Move in CMakeLists.txt
if (!file.copy("../inst/bin/CMakeLists.txt", "CMakeLists.txt", overwrite = TRUE)){
  stop("Copying CMakeLists failed")
}
```

### PR DESCRIPTION
**Pull request by BruceZhaoR**
fix #1678
@Laurae2  please cc.

### CODE REVIEW

**Comment by jameslamb** [comment]
@StrikerRUS @Laurae2 how should I interpret the `Microsoft.LightGBM` CI check failure? Seems like it it not related to the code, but I don't really understand what that check is doing.

**Comment by StrikerRUS** [comment]
Two checks fail even to start (0.0 milliseconds duration). I've restarted all `Microsoft.LightGBM` jobs.

**Comment by jameslamb** [comment]
Thanks @StrikerRUS , looks like everything passed!

**Comment by jameslamb** [comment]
Before we build, I need to try running on my Mac. I am confused how you could drop the reference to `inst/bin` and have this still work.

@BruceZhaoR I will merge this tomorrow! Thanks again for the fix

**Comment by BruceZhaoR** [comment]
@jameslamb your are right! It looks like the `lgb.dl` function doesn't copy the `CmakeLists.txt` into the `R-package/src/inst` dir.  I will close the PR.

**Pull request closed without merging**
