### PR TITLE
[docs] generate parameters description from config file. Final stage

### PR DESCRIPTION
**Pull request by StrikerRUS**
This is continuation of #1417.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@guolinke Maybe it's time for the new release?

**Comment by StrikerRUS** [comment]
@guolinke I want to clarify in docs which parameters are available only in CLI version. Can you please help me with list of them?

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L85
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L97
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L140
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L146
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L398
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L402
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L409
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L413
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L418
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L425
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L463
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L467
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L472
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L483
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L491
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L500
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L509
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L559
https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L564

**Comment by guolinke** [comment]
@StrikerRUS Thank you so much. 
I think `two_round` can be used in python-package, when the input data is a file. 
And the `enable_load_from_binary`, `label_column` , ... , and so on can be used in python-package as well.

**Comment by StrikerRUS** [comment]
@guolinke Oh, I see...
Then maybe it's better to make another PR for marking CLI-only params just to not mix up things.

**Pull request merged**
