### PR TITLE
[python] add option to disable openmp in python package build

### PR DESCRIPTION
**Pull request by guolinke**

### CODE REVIEW

**Comment by StrikerRUS** [comment]
Seems that something is wrong with `pandas` on CI.

**Comment by guolinke** [comment]
@StrikerRUS 
it seems there is another problem when creating conda env.
```
2018-10-25T05:18:01.7842400Z # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
2018-10-25T05:18:01.7842690Z 
2018-10-25T05:18:01.7843010Z     Traceback (most recent call last):
2018-10-25T05:18:01.7844350Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
2018-10-25T05:18:01.7844620Z         return func(*args, **kwargs)
2018-10-25T05:18:01.7845240Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/cli/main.py", line 78, in _main
2018-10-25T05:18:01.7845340Z         exit_code = do_call(args, p)
2018-10-25T05:18:01.7846090Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
2018-10-25T05:18:01.7846220Z         exit_code = getattr(module, func_name)(args, parser)
2018-10-25T05:18:01.7846920Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/cli/main_update.py", line 14, in execute
2018-10-25T05:18:01.7847450Z         install(args, parser, 'update')
2018-10-25T05:18:01.7848140Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/cli/install.py", line 253, in install
2018-10-25T05:18:01.7848240Z         handle_txn(unlink_link_transaction, prefix, args, newenv)
2018-10-25T05:18:01.7848890Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/cli/install.py", line 282, in handle_txn
2018-10-25T05:18:01.7848990Z         unlink_link_transaction.execute()
2018-10-25T05:18:01.7849640Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/link.py", line 223, in execute
2018-10-25T05:18:01.7849740Z         self.verify()
2018-10-25T05:18:01.7850300Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/common/io.py", line 46, in decorated
2018-10-25T05:18:01.7850870Z         return f(*args, **kwds)
2018-10-25T05:18:01.7851670Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/link.py", line 200, in verify
2018-10-25T05:18:01.7851870Z         self.prepare()
2018-10-25T05:18:01.7852440Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/link.py", line 192, in prepare
2018-10-25T05:18:01.7852620Z         stp.remove_specs, stp.update_specs)
2018-10-25T05:18:01.7853210Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/link.py", line 282, in _prepare
2018-10-25T05:18:01.7853820Z         mkdir_p(transaction_context['temp_dir'])
2018-10-25T05:18:01.7854430Z       File "/usr/local/miniconda/lib/python3.7/site-packages/conda/gateways/disk/__init__.py", line 60, in mkdir_p
2018-10-25T05:18:01.7854520Z         makedirs(path)
2018-10-25T05:18:01.7854690Z       File "/usr/local/miniconda/lib/python3.7/os.py", line 221, in makedirs
2018-10-25T05:18:01.7854780Z         mkdir(name, mode)
2018-10-25T05:18:01.7855400Z     PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/.condatmp'
```

**Comment by guolinke** [comment]
it seems we still need to hack the permission to update conda in azure pipeline.

**Comment by StrikerRUS** [comment]
Yeah, it's seems to be so 😕

**Comment by StrikerRUS** [comment]
I suppose we should wait for conda is being repaired before fixing permission error on Azure, right?

**Comment by StrikerRUS** [comment]
For tracking the issue:
https://github.com/matplotlib/matplotlib/issues/12626
https://github.com/pandas-dev/pandas/issues/23319

**Comment by StrikerRUS** [comment]
@guolinke These [changes](https://github.com/Microsoft/LightGBM/compare/StrikerRUS-patch-1) produces the following warnings on Linux:
```
Preparing transaction: ...working... done
2018-10-27T17:39:22.8353794Z Verifying transaction: ...working... done
2018-10-27T17:40:03.9381033Z Executing transaction: ...working... done
2018-10-27T17:40:05.2978123Z -- The C compiler identification is GNU 4.8.4
2018-10-27T17:40:05.3582289Z -- The CXX compiler identification is GNU 4.8.4
2018-10-27T17:40:05.3657789Z -- Check for working C compiler: /usr/bin/cc
2018-10-27T17:40:05.4134767Z -- Check for working C compiler: /usr/bin/cc -- works
2018-10-27T17:40:05.4144464Z -- Detecting C compiler ABI info
2018-10-27T17:40:05.4597333Z -- Detecting C compiler ABI info - done
2018-10-27T17:40:05.4700003Z -- Detecting C compile features
2018-10-27T17:40:05.6144307Z -- Detecting C compile features - done
2018-10-27T17:40:05.6181971Z -- Check for working CXX compiler: /usr/bin/c++
2018-10-27T17:40:05.6706822Z -- Check for working CXX compiler: /usr/bin/c++ -- works
2018-10-27T17:40:05.6714974Z -- Detecting CXX compiler ABI info
2018-10-27T17:40:05.7238842Z -- Detecting CXX compiler ABI info - done
2018-10-27T17:40:05.7341966Z -- Detecting CXX compile features
2018-10-27T17:40:05.9271846Z -- Detecting CXX compile features - done
2018-10-27T17:40:05.9301159Z -- Configuring done
2018-10-27T17:40:05.9451830Z -- Generating done
2018-10-27T17:40:05.9460397Z -- Build files have been written to: /__w/1/s/build
2018-10-27T17:40:05.9801516Z Scanning dependencies of target _lightgbm
2018-10-27T17:40:05.9861955Z [  3%] Building CXX object CMakeFiles/_lightgbm.dir/src/c_api.cpp.o
2018-10-27T17:40:05.9872254Z [  6%] Building CXX object CMakeFiles/_lightgbm.dir/src/lightgbm_R.cpp.o
2018-10-27T17:40:05.9878160Z [  9%] Building CXX object CMakeFiles/_lightgbm.dir/src/application/application.cpp.o
2018-10-27T17:40:05.9895595Z [ 12%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/boosting.cpp.o
2018-10-27T17:40:09.5265389Z [ 15%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt.cpp.o
2018-10-27T17:40:14.1225901Z [ 18%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_model_text.cpp.o
2018-10-27T17:40:14.3467650Z [ 21%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_prediction.cpp.o
2018-10-27T17:40:17.2711982Z [ 25%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/prediction_early_stop.cpp.o
2018-10-27T17:40:17.7545651Z [ 28%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/bin.cpp.o
2018-10-27T17:40:18.1033996Z [ 31%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config.cpp.o
2018-10-27T17:40:18.3841745Z [ 34%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config_auto.cpp.o
2018-10-27T17:40:22.1788694Z [ 37%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/dataset.cpp.o
2018-10-27T17:40:22.7338363Z [ 40%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/dataset_loader.cpp.o
2018-10-27T17:40:24.8311473Z [ 43%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/file_io.cpp.o
2018-10-27T17:40:26.0711350Z [ 46%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/json11.cpp.o
2018-10-27T17:40:30.6107865Z [ 50%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/metadata.cpp.o
2018-10-27T17:40:30.9345304Z [ 53%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/parser.cpp.o
2018-10-27T17:40:31.6904347Z [ 56%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/tree.cpp.o
2018-10-27T17:40:31.7427764Z [ 59%] Building CXX object CMakeFiles/_lightgbm.dir/src/metric/dcg_calculator.cpp.o
2018-10-27T17:40:36.0986910Z [ 62%] Building CXX object CMakeFiles/_lightgbm.dir/src/metric/metric.cpp.o
2018-10-27T17:40:36.1046021Z [ 65%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_mpi.cpp.o
2018-10-27T17:40:36.1094865Z [ 68%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linker_topo.cpp.o
2018-10-27T17:40:36.1384897Z [ 71%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_socket.cpp.o
2018-10-27T17:40:40.1778763Z [ 75%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/network.cpp.o
2018-10-27T17:40:40.1801234Z [ 78%] Building CXX object CMakeFiles/_lightgbm.dir/src/objective/objective_function.cpp.o
2018-10-27T17:40:40.2225814Z [ 81%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.o
2018-10-27T17:40:43.5905521Z [ 84%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/feature_parallel_tree_learner.cpp.o
2018-10-27T17:40:44.7825542Z [ 87%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o
2018-10-27T17:40:44.8706029Z [ 90%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/serial_tree_learner.cpp.o
2018-10-27T17:40:46.5719510Z /__w/1/s/src/treelearner/serial_tree_learner.cpp: In member function ‘virtual void LightGBM::SerialTreeLearner::BeforeTrain()’:
2018-10-27T17:40:46.5720017Z /__w/1/s/src/treelearner/serial_tree_learner.cpp:325:19: warning: unused variable ‘loop_size’ [-Wunused-variable]
2018-10-27T17:40:46.5720359Z        data_size_t loop_size = end - begin;
2018-10-27T17:40:46.5720435Z                    ^
2018-10-27T17:40:46.5729308Z /__w/1/s/src/treelearner/serial_tree_learner.cpp: In member function ‘virtual bool LightGBM::SerialTreeLearner::BeforeFindBestSplit(const LightGBM::Tree*, int, int)’:
2018-10-27T17:40:46.5731386Z /__w/1/s/src/treelearner/serial_tree_learner.cpp:400:17: warning: unused variable ‘loop_size’ [-Wunused-variable]
2018-10-27T17:40:46.5731699Z      data_size_t loop_size = end - begin;
2018-10-27T17:40:46.5731773Z                  ^
2018-10-27T17:40:46.6090436Z [ 93%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/tree_learner.cpp.o
2018-10-27T17:40:47.1670595Z [ 96%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/voting_parallel_tree_learner.cpp.o
2018-10-27T17:40:52.3317600Z At global scope:
2018-10-27T17:40:52.3320116Z cc1plus: warning: unrecognized command line option "-Wno-ignored-attributes" [enabled by default]
2018-10-27T17:40:53.3351320Z [100%] Linking CXX shared library ../lib_lightgbm.so
2018-10-27T17:40:53.4654727Z [100%] Built target _lightgbm
```
and errors on macOS:
```
Preparing transaction: ...working... done
2018-10-27T17:40:22.6749250Z Verifying transaction: ...working... done
2018-10-27T17:40:26.2637920Z Executing transaction: ...working... done
2018-10-27T17:40:30.6451370Z ls: /usr/local/Cellar/libomp/*/lib: No such file or directory
2018-10-27T17:40:31.7445830Z -- The C compiler identification is AppleClang 8.1.0.8020041
2018-10-27T17:40:31.8447620Z -- The CXX compiler identification is AppleClang 8.1.0.8020041
2018-10-27T17:40:31.8564550Z -- Check for working C compiler: /Applications/Xcode_8.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
2018-10-27T17:40:32.6600530Z -- Check for working C compiler: /Applications/Xcode_8.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
2018-10-27T17:40:32.6609660Z -- Detecting C compiler ABI info
2018-10-27T17:40:32.7983530Z -- Detecting C compiler ABI info - done
2018-10-27T17:40:32.8071810Z -- Detecting C compile features
2018-10-27T17:40:33.2602900Z -- Detecting C compile features - done
2018-10-27T17:40:33.2661980Z -- Check for working CXX compiler: /Applications/Xcode_8.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
2018-10-27T17:40:33.4079100Z -- Check for working CXX compiler: /Applications/Xcode_8.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
2018-10-27T17:40:33.4213540Z -- Detecting CXX compiler ABI info
2018-10-27T17:40:33.5666670Z -- Detecting CXX compiler ABI info - done
2018-10-27T17:40:33.5715510Z -- Detecting CXX compile features
2018-10-27T17:40:34.4295750Z -- Detecting CXX compile features - done
2018-10-27T17:40:34.4405710Z -- Configuring done
2018-10-27T17:40:34.4838220Z -- Generating done
2018-10-27T17:40:34.4913400Z -- Build files have been written to: /Users/vsts/agent/2.140.2/work/1/s/build
2018-10-27T17:40:34.6115170Z Scanning dependencies of target _lightgbm
2018-10-27T17:40:34.6359260Z [  3%] Building CXX object CMakeFiles/_lightgbm.dir/src/c_api.cpp.o
2018-10-27T17:40:34.6367970Z [  6%] Building CXX object CMakeFiles/_lightgbm.dir/src/lightgbm_R.cpp.o
2018-10-27T17:40:34.6472180Z [  9%] Building CXX object CMakeFiles/_lightgbm.dir/src/application/application.cpp.o
2018-10-27T17:40:34.6573730Z [ 12%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/boosting.cpp.o
2018-10-27T17:40:35.2730010Z In file included from /Users/vsts/agent/2.140.2/work/1/s/src/lightgbm_R.cpp:5:
2018-10-27T17:40:35.2830770Z In file included from /Users/vsts/agent/2.140.2/work/1/s/include/LightGBM/utils/text_reader.h:4:
2018-10-27T17:40:35.2932310Z /Users/vsts/agent/2.140.2/work/1/s/include/LightGBM/utils/pipeline_reader.h:34:27: error: implicit instantiation of undefined template 'std::__1::vector<char, std::__1::allocator<char> >'
2018-10-27T17:40:35.3031870Z     auto buffer_process = std::vector<char>(buffer_size);
2018-10-27T17:40:35.3132520Z                           ^
2018-10-27T17:40:35.3233460Z /Applications/Xcode_8.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:200:29: note: template is declared here
2018-10-27T17:40:35.3334120Z class _LIBCPP_TYPE_VIS_ONLY vector;
2018-10-27T17:40:35.3386500Z                             ^
2018-10-27T17:40:35.3390130Z In file included from /Users/vsts/agent/2.140.2/work/1/s/src/lightgbm_R.cpp:5:
2018-10-27T17:40:35.3390220Z In file included from /Users/vsts/agent/2.140.2/work/1/s/include/LightGBM/utils/text_reader.h:4:
2018-10-27T17:40:35.3391300Z /Users/vsts/agent/2.140.2/work/1/s/include/LightGBM/utils/pipeline_reader.h:36:24: error: implicit instantiation of undefined template 'std::__1::vector<char, std::__1::allocator<char> >'
2018-10-27T17:40:35.3391420Z     auto buffer_read = std::vector<char>(buffer_size);
2018-10-27T17:40:35.3391770Z                        ^
2018-10-27T17:40:35.3391880Z /Applications/Xcode_8.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:200:29: note: template is declared here
2018-10-27T17:40:35.3392020Z class _LIBCPP_TYPE_VIS_ONLY vector;
2018-10-27T17:40:35.3392110Z                             ^
2018-10-27T17:40:35.5845230Z 2 errors generated.
2018-10-27T17:40:35.5911020Z make[3]: *** [CMakeFiles/_lightgbm.dir/src/lightgbm_R.cpp.o] Error 1
2018-10-27T17:40:35.5912040Z make[3]: *** Waiting for unfinished jobs....
2018-10-27T17:40:40.8544830Z make[2]: *** [CMakeFiles/_lightgbm.dir/all] Error 2
2018-10-27T17:40:40.8546600Z make[1]: *** [CMakeFiles/_lightgbm.dir/rule] Error 2
2018-10-27T17:40:40.8548710Z make: *** [_lightgbm] Error 2
```
Full logs: https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=766&view=logs (`Regular` tasks)

**Comment by guolinke** [comment]
@StrikerRUS can you try my fixes in branch: https://github.com/Microsoft/LightGBM/tree/nomp-err ?

**Comment by StrikerRUS** [comment]
Perfect! Thanks!

Only 
```
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
```
left on macOS, but it's unrelated.

**Pull request merged**
