### PR TITLE
Add msvc conformance check

### PR DESCRIPTION
**Pull request by Zhaojun-Liu**
From https://github.com/microsoft/LightGBM/pull/6232#issuecomment-1853234696.

Add option `/permissive-` for MSVC conformance check.

### CODE REVIEW

**Comment by jameslamb** [comment]
Thanks for this! Glad to see the tests all pass when using this flag.

Instead of unconditionally adding it to `CMAKE_CXX_FLAGS`, could you do something like the following?

```cmake
if(BUILD_CPP_TEST)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /permissive-")
endif()
```

That way, it'll cause build failures here in the project's automated tests that would help to catch issues like #6230, but won't prevent regular users of the project from being able to compile LightGBM.

**Comment by Zhaojun-Liu** [comment]
> Thanks for this! Glad to see the tests all pass when using this flag.
> 
> Instead of unconditionally adding it to `CMAKE_CXX_FLAGS`, could you do something like the following?
> 
> ```cmake
> if(BUILD_CPP_TEST)
>     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /permissive-")
> endif()
> ```
> 
> That way, it'll cause build failures here in the project's automated tests that would help to catch issues like #6230, but won't prevent regular users of the project from being able to compile LightGBM.

**Comment by jameslamb** [comment]
> I pushed the new changes, you can check it

This branch still has `/permissive-` being added unconditionally inside an `if(MSVC)` blocks. Please put it inside an `if(BUILD_CPP_TEST)`.

> I don't quite understand what the function of adding if(BUILD_CPP_TEST) condition is

`/permissive-` causes compilation to fail if any code is found that doesn't conform with the stated target C++ standard.

As described in https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170, what MSVC can detect and how well it detects that changes with each new release of Visual Studio.

I'm asking you to only apply that flag inside an `if(BUILD_CPP_TEST)` block here so that we only catch such conformance issues **here in LightGBM's tests**, but don't risk those errors leading to compilation errors for LightGBM users using other versions of Visual Studio.

Code detected as "non-conforming" by that compiler flag isn't necessarily problematic for users.

**Comment by jameslamb** [comment]
> Please put it inside an if(BUILD_CPP_TEST).

Sorry, my mistake, I didn't scroll up far enough. Thank you for moving it there.

**Review by jameslamb — APPROVED** [review]

**Comment by Zhaojun-Liu** [comment]
> > Please put it inside an if(BUILD_CPP_TEST).
> 
> Sorry, my mistake, I didn't scroll up far enough. Thank you for moving it there.

You are welcome 😃.

**Comment by Zhaojun-Liu** [comment]
> `/permissive-` causes compilation to fail if any code is found that doesn't conform with the stated target C++ standard.
> 
> As described in https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170, what MSVC can detect and how well it detects that changes with each new release of Visual Studio.
> 
> I'm asking you to only apply that flag inside an `if(BUILD_CPP_TEST)` block here so that we only catch such conformance issues **here in LightGBM's tests**, but don't risk those errors leading to compilation errors for LightGBM users using other versions of Visual Studio.
> 
> Code detected as "non-conforming" by that compiler flag isn't necessarily problematic for users.

Thank you for your detailed and patient explanation ❤️ .

**Comment by jameslamb** [comment]
I'll merge this, thanks again for the help!

We'd love to have you contribute more to LightGBM if you are interested! You can `@` me on any open issue if you see one that looks interesting, or email me if you'd like some help identifying things to work on.

**Pull request merged**
