### PR TITLE
[refactor] SWIG - Split pointer manipulation to individual .i file

### PR DESCRIPTION
**Pull request by AlbertoEAF**
To make SWIG interface declarations more readable,
pointer manipulation methods were split to a separate module.

### CODE REVIEW

**Comment by AlbertoEAF** [comment]
Hello @imatiach-msft , as you are the core maintainer of SWIG, can you review this one?

I just moved the existing code to a separate file and added a brief overview.

**Review by imatiach-msft — APPROVED** [review]
LGTM!

**Comment by AlbertoEAF** [comment]
@guolinke can we merge this?

**Comment by jameslamb** [comment]
Could you please update this PR to the latest `master`? We recently learned that our CI was missing one of the checks that replicates CRAN (#3585 ), and added a new R CI job (#3588). Sorry for the inconvenience.

**Review by guolinke — APPROVED** [review]

**Pull request merged**
