### PR TITLE
Stylistic changes r package

### PR DESCRIPTION
**Pull request by kirillseva**
I'm still having trouble compiling the package on Mac OS X so I didn't get a chance to use the library for anything good yet. However, I went through and combed the R codebase according to Hadley's style guide.

Would love to help set up R-package tests on Travis in a follow up PR if there's demand for it.

Changes:
* Refactored the `R-package` codebase to look more R-like
* Fixed broken tests
* Added two flags and an import to the c++ codebase in order to stop getting `undeclared template base_string` on Mac (however now I'm getting a new error)

```
* installing *source* package ‘lightgbm’ ...
** libs
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../..//include -DUSE_SOCKET -Wno-deprecated-declarations -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include     -std=c++11 -fopenmp -fPIC  -Wall -mtune=core2 -g -O2 -c lightgbm-all.cpp -o lightgbm-all.o
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../..//include -DUSE_SOCKET -Wno-deprecated-declarations -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include     -std=c++11 -fopenmp -fPIC  -Wall -mtune=core2 -g -O2 -c lightgbm_R.cpp -o lightgbm_R.o
clang++ -std=c++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o lightgbm.so ./lightgbm-all.o ./lightgbm_R.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm/libs
** R
** data
** demo
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm/libs/lightgbm.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm/libs/lightgbm.so, 6): Symbol not found: ___kmpc_atomic_float8_add
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm/libs/lightgbm.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm/libs/lightgbm.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm’
Error: Command failed (1)
```

### CODE REVIEW

**Comment by kirillseva** [comment]
@guolinke tests pass on my ubuntu machine

**Comment by guolinke** [comment]
@kirillseva you can try to disable flag ```-fopenmp```  if using clang. 
BTW, you can re-genera the doc by roxygen2 and update them as well.

**Comment by kirillseva** [comment]
Oh, right, that's why I wanted to be able to compile it! Will do in a jiffy.

**Comment by kirillseva** [comment]
@guolinke removed `-fopenmp`
```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm/libs/lightgbm.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm/libs/lightgbm.so, 6): Symbol not found: _omp_get_num_threads
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm/libs/lightgbm.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm/libs/lightgbm.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/lightgbm’
Error: Command failed (1)
```

**Comment by guolinke** [comment]
ok, I see, I will fix it now.

**Comment by guolinke** [comment]
@kirillseva I don't have a osx to test it. But i can compile without openmp in windows.. 
Did you delete the old ```.o``` files before you compile the new one? 
you can also try to remove all ```omp_set...``` and ```omp_get...``` in the code, and seem what happens.

**Comment by chivee** [comment]
@kirillseva  did you trying gcc rather than clang?

**Comment by kirillseva** [comment]
@chivee currently struggling with my package manager to install gcc :/ this PR can still go through - I was able to compile with gcc on an ubuntu machine, and the changeset is applicable to the R package code mostly

**Pull request merged**
