### PR TITLE
[python-package] prefix is_numpy_1d_array with _

### PR DESCRIPTION
**Pull request by Madnex**
Contributes to https://github.com/microsoft/LightGBM/issues/5313

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Thanks for contributing to LightGBM!

The CI failures are not something you need to worry about. We are currently working through some instability in the project's CI (see #5510) and will come back to merge this after those are resolved. Sorry for the inconvenience.

**Comment by jameslamb** [comment]
@Madnex ok, the project's CI issues have been fixed (#5510).

Sorry for the inconvenience, but can you please merge the latest changes from `master` into this branch? If CI succeeds after that, we'll merge this.

Thanks again for contributing to LightGBM!

**Comment by Madnex** [comment]
Thanks! I merged it 👍

**Comment by jameslamb** [comment]
Thanks again for this!

@Madnex in the future, I strongly recommend that you create a branch on your fork, instead of committing directly to `master` and then opening a pull request from there.

Now that I've merged this, your `master` will have commits on it that aren't on LightGBM's `master` here, and vice versa.

If you want to keep contributing (and I hope you do!), the easiest way to fix that is probably just to:

* delete your fork of LightGBM
* re-fork LightGBM
* submit all future pull requests from a _branch_ that you cut off of `master`, like this

```shell
git clone --recursive https://github.com/Madnex/LightGBM.git
cd LightGBM
git checkout -b some-feature
```

👋 cheers and have a good weekend!

**Comment by Madnex** [comment]
Thanks for the tipp @jameslamb ! Will do and prepare the next PR :)

**Pull request merged**
