### PR TITLE
Support monotone constraint

### PR DESCRIPTION
**Pull request by guolinke**
for #14 

ping @alexvorobiev @AbdealiJK @aldanor @redditur for the tests.

### CODE REVIEW

**Comment by mayer79** [comment]
On https://github.com/mayer79/partialPlot there is a simple partial dependence plot function in R that also works for lightGBM (see regression examples). With monotone constraints, the curves would be expected to be monotone.

**Comment by mayer79** [comment]
@guolinke tested on R-Windows-VC-CPU with the following promising results for diamonds properties on log-price

### Without constraints
no_constraints

### With `monotone_constraints = '0,1,1,0,1,-1'`

constrained

### Problems/Comments

- `lgb.unloader(wipe = TRUE)` is required now whenever the parameters are to be changed

- During prediction, I get the message "[LightGBM] [Warning] Unknown parameter: NA"

- I tested one example with a constrained categorical variable. It seems to be (correctly) ignored.

**Comment by guolinke** [comment]
@mayer79 thanks very much, it seems the monotone constraint is working. 
@Laurae2 any ideas about these R's errors ?

**Comment by mayer79** [comment]
@guolinke: this will be an inherently useful parameter in real-world applications where users can play around with input parameters. Big thanks for making it run.

**Comment by redditur** [comment]
@guolinke: thanks for doing this. I've had a look through the code and the logic seems correct to me. I've also ran some tests and everything seems to work as expected.

Given this is a non-trivial addition to LightGBM, it would probably make sense to bump the version; to 2.1.1 perhaps?

**Comment by UserQuestions** [comment]
Is this in a state that would be easy for me to build and use?  I have an application that might be a good test.

**Comment by junegit** [comment]
Is the algorithm for Light GBM  same as of xgboost to enforce monotonicity? Is it global or local ?
Also can one of the expert helps me in understanding line [L412-417](https://github.com/dmlc/xgboost/blob/master/src/tree/param.h#L412).  from xgboost.  Why "w" is bounded- upper and lower. How this helps to maintain Monotonicity. Line 457 - Why "mid" is used? Is any whitepaper on the monotonic constraints in Light GM available?

**Pull request merged**
