### PR TITLE
[R] Correcting lgb.prepare output comment

### PR DESCRIPTION
**Pull request by dah33**

### CODE REVIEW

**Comment by Laurae2** [comment]
Please update the .Rd files with roxygen2.

**Comment by jameslamb** [comment]
@dah33 thanks for doing this! Echoing @Laurae2 , can you please run `Rscript -e "devtools::document()` from the root of the R package to re-generate the documentation? Then we will merge this up.

**Comment by StrikerRUS** [comment]
ping @dah33

**Comment by Laurae2** [comment]
@jameslamb It seems it's not straightforward anymore to create documentation for the R-package.

Something as simple like this doesn't seem to work anymore:

```r
library(devtools)
setwd("E:/GitHub/LightGBM/R-package")
devtools::document()
```

```sh
> devtools::document()
Updating lightgbm documentation
Loading lightgbm
Re-compiling lightgbm
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "E:\GitHub\LightGBM\R-package"  \
  --library="C:\Users\Laurae\AppData\Local\Temp\RtmpOUA4AK\devtools_install_8e94312939c5" --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec --no-multiarch --no-test-load --preclean 

* installing *source* package 'lightgbm' ...
** libs
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=native -c R_init.c -o R_init.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o lightgbm.dll tmp.def R_init.o -LC:/PROGRA~1/R/R-35~1.0/bin/x64 -lR
installing via 'install.libs.R' to C:/Users/Laurae/AppData/Local/Temp/RtmpOUA4AK/devtools_install_8e94312939c5/lightgbm
Error in eval(ei, envir) : Copying CMakeLists failed
* removing 'C:/Users/Laurae/AppData/Local/Temp/RtmpOUA4AK/devtools_install_8e94312939c5/lightgbm'
In R CMD INSTALL
Error: Command failed (1)
```

**Comment by jameslamb** [comment]
@dah33 I've rebased this to current `master`. I'll add the `.Rd` file change next and then merge if everything builds.

Thanks again for contributing and we hope you'll contribute more in the future!

**Comment by jameslamb** [comment]
I've updated all the documentation and pushed onto this PR. 

@dah33 I had to downgrade `devtools 1.13.6` to get around the issue klutometis/roxygen#822 that I mentioend in #1830 .

Steps to reproduce:

```
Rscript -e "remove.packages('devtools')"
wget https://cran.r-project.org/src/contrib/Archive/devtools/devtools_1.13.6.tar.gz -O devtools.tar.gz
R CMD INSTALL devtools.tar.gz
```

**Pull request merged**
