### PR TITLE
[MRG] re-write test cases: remove global template

### PR DESCRIPTION
**Pull request by wxchan**
The test cases are not quite readable with global template, it's unfriendly for new contributors. And it sometimes messes up with global variables unexpectedly.

### CODE REVIEW

**Comment by wxchan** [comment]
@guolinke btw, I think the default early stopping round should be 0 instead of -1; the index of best score is `best_iteration - 1`, which should be -1 if not meets early stopping

**Comment by guolinke** [comment]
@wxchan I don't got it. 
using ```0``` is ok, but what is problem of using ```-1``` ?

**Comment by wxchan** [comment]
@guolinke we can directly use eval_result[best_iteration - 1] to get best_score (eval_result[-1] is the last element of eval_result list); but I am a little messed up with default best_iteration, default early stopping and the default num_iteration for prediction, not sure which one should be changed.

**Comment by guolinke** [comment]
you want to use ```eval_result[-1 - early_stopping_round]``` to get the best_score ? 

I think you can open a PR and adapt your change, and we can discuss how to change them.

**Comment by wxchan** [comment]
@guolinke I think only changing default best_iteration = 0 is ok, a simple example:

```
# coding: utf-8
import lightgbm as lgb
from sklearn.datasets import load_boston
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

X, y = load_boston(True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
params = {
    'learning_rate': 0.1,
    'metric': 'l2',
    'verbose': -1
}
lgb_train = lgb.Dataset(X_train, y_train)
lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train)

# meet early stopping criterion
evals_result = {}
gbm = lgb.train(params, lgb_train,
                num_boost_round=100,
                valid_sets=lgb_eval,
                verbose_eval=False,
                early_stopping_rounds=5,
                evals_result=evals_result)
ret = mean_squared_error(y_test, gbm.predict(X_test))
ret2 = mean_squared_error(y_test, gbm.predict(X_test, num_iteration=gbm.best_iteration))
print(ret, ret2, gbm.best_iteration, evals_result['valid_0']['l2'][gbm.best_iteration - 1])

# change early_stopping_rounds = 10
# not meet early stopping criterion
evals_result = {}
gbm = lgb.train(params, lgb_train,
                num_boost_round=100,
                valid_sets=lgb_eval,
                verbose_eval=False,
                early_stopping_rounds=10,
                evals_result=evals_result)
ret = mean_squared_error(y_test, gbm.predict(X_test))
ret2 = mean_squared_error(y_test, gbm.predict(X_test, num_iteration=gbm.best_iteration))
print(ret, ret2, gbm.best_iteration, evals_result['valid_0']['l2'][gbm.best_iteration - 1])
```
output:
```
7.00593043978 7.00593043978 61 7.00593042305
6.62207310513 6.62207310513 -1 6.62833727028
```
`evals_result['valid_0']['l2'][gbm.best_iteration - 1]` not equal to `ret` here; instead, it's the result of num_boost_round-2 rounds

if change default gbm.best_iteration = 0:
```
7.00593043978 7.00593043978 61 7.00593042305
6.62207310513 6.62207310513 0 6.62207310293
```

**Pull request merged**
