### PR TITLE
Speed up saving and loading model

### PR DESCRIPTION
**Pull request by guolinke**
1. reduce many overheads in saving and loading
2. multi-threading save and load
3. still use text format. Binary format will be added after this PR.

Both saving and loading are about 10x faster now.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@guolinke **Protobuf Support** is still in `docs/Installation-Guide.rst`.

**Comment by guolinke** [comment]
@StrikerRUS I just realize use max_bin in lgb.Dataset argument isn't a good idea.
This will break the sklearn users, they will not be able to set max_bin any more, since sklearn interfaces don't have lgb.dataset .

**Comment by StrikerRUS** [comment]
@guolinke we've scheduled removing it in 2.0.12 version.

**Comment by guolinke** [comment]
@StrikerRUS will we remove it from argument ?

**Comment by StrikerRUS** [comment]
@guolinke Yeah, leave only in params.
https://github.com/Microsoft/LightGBM/blob/750a11b08cba9adcd05e6bcb92d30495783572da/python-package/lightgbm/basic.py#L645-L648

**Comment by guolinke** [comment]
@StrikerRUS 
I am confused by the warning of travis outputs. 
Why the max_bin warning are always output without set or not set it ?

**Comment by StrikerRUS** [comment]
@guolinke Your last commit successfuly removed the warning about `max_bin` from `test_basic.py`.

**Comment by guolinke** [comment]
@StrikerRUS our next version is v2.0.12, so I will remove the max_bin argument directly. 
BTW, it seems v2.0.11 will always print many warnings.

**Comment by StrikerRUS** [comment]
>BTW, it seems v2.0.11 will always print many warnings

Only in case of `max_bin` is not `None`. So users will be ready to pass `max_bin` through `params`.

**Comment by guolinke** [comment]
@wxchan @StrikerRUS 
It seems there are some warnings about categorical features, when use validation data. I think they also can be removed.

> Only in case of max_bin is not None. So users will be ready to pass max_bin through params.

If user uses sklearn interface, the warning will always output. When using sklearn interface, max_bin are set both in param dict and argument.

**Comment by StrikerRUS** [comment]
@guolinke 
> When using sklearn interface, max_bin are set both in param dict and argument.

Yeah. I think it was OK, because users now should pass `max_bin` via `params` even in sklearn.

**Comment by wxchan** [comment]
@guolinke I think there is some bug about warning of categorical features, you can remove it.

**Comment by StrikerRUS** [comment]
@guolinke please remove `max_bin` argument from sklearn's `LGBMModel` too.

**Comment by guolinke** [comment]
@wxchan I am not very sure about these warning. I think it is better for you to fix it.

**Pull request merged**
