### PR TITLE
[R-package] fix typo in R installation instructions

### PR DESCRIPTION
**Pull request by daviddalpiaz**
Fixes typo to allow for copy-paste installation of R package.

### CODE REVIEW

**Comment by jameslamb** [comment]
@daviddalpiaz thanks for using `LightGBM` and for contributing here!  Sorry, but this issue you've found is my mistake. Our goal was to make all of the artifact names kebob case (`lightgbm-{version}-r-cran.tar.gz`),  but since we haven't done #3283 I'm making them manually, and made a mistake.

I just uploaded the 3.0.0rc1 release with the kebob-case name, so the instructions will be correct. I left the snake_case one up there to not break anyone's code.

Now that we've released 3.0.0, could you change this PR to reference version 3.0.0?

https://github.com/microsoft/LightGBM/releases/download/v3.0.0/lightgbm-3.0.0-r-cran.tar.gz

**Comment by daviddalpiaz** [comment]
Huh. I could have sworn in looked for the R release of 3.0.0, but guess I missed it! Thanks for all the hard work. Hoping for CRAN soon so I can encourage my students to use LightGBM!

**Comment by jameslamb** [comment]
> Huh. I could have sworn in looked for the R release of 3.0.0, but guess I missed it! Thanks for all the hard work. Hoping for CRAN soon so I can encourage my students to use LightGBM!

I just added it last night :grinning: 

we are so so so close to CRAN, I can't wait til we don't have to make people deal with this. Thanks for being patient with us, for using LightGBM, and for coming here to contribute!

**Review by jameslamb — APPROVED** [review]
looks good! I'll merge this as soon as it builds

**Comment by daviddalpiaz** [comment]
Excellent! Thanks again!

**Pull request merged**
