### PR TITLE
[WIP] [python] add predict contrib to python

### PR DESCRIPTION
**Pull request by wxchan**

### CODE REVIEW

**Comment by wxchan** [comment]
@guolinke @slundberg can you help check the failed test about predict_contrib, do I use it in a wrong way?

**Comment by slundberg** [comment]
I'll be away for a couple days, but I'll check it out on Tue. I just found an issue with some of the null trees that get added to represent a constant offset for regression, but nothing that would cause a seg fault yet.

**Comment by slundberg** [comment]
It looks like `leaf_depth_` is not loaded from a saved model, but only populated during the split process. Since I was testing using Julia c_api calls I didn't catch this (and try to access to elements in this array).

To fix this we need to recompute the depth of the leaves and not assume it is already computed. I think this should happen on model load, since it doesn't make sense to have the model in a different state after loading than just after training.

**Comment by wxchan** [comment]
move to #861 . close.

**Pull request closed without merging**
