### PR TITLE
[R-package] remove unnecessary comments

### PR DESCRIPTION
**Pull request by jameslamb**
This PR proposes removing some comments in the R package that I think are unnecessary.

There are a lot of things like this in the R code:

```r
    # return ret
    return(ret)
```

Comments like this don't add any understanding of the code, but they do make it slightly harder to read and possibly lead to false positives when using `git grep` or similar tools to search through the codebase for things.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@jameslamb 
Could you please fix some typos from #2912 in this PR as well?

I believe it is not "loss" but "metric" or "evaluation function".
https://github.com/microsoft/LightGBM/blob/d4325c5a4428b120d8611b6cba9b821f3a5f3b12/R-package/R/lgb.cv.R#L121


``structture``, ``higher_bettter``
https://github.com/microsoft/LightGBM/blob/d4325c5a4428b120d8611b6cba9b821f3a5f3b12/R-package/R/lgb.cv.R#L595


Same as above for `loss`
https://github.com/microsoft/LightGBM/blob/d4325c5a4428b120d8611b6cba9b821f3a5f3b12/R-package/R/lgb.train.R#L98


Maybe
```
assign(x = ACCUMULATOR_NAME, value = 0.0, envir = .GlobalEnv)
```
?
https://github.com/microsoft/LightGBM/blob/d4325c5a4428b120d8611b6cba9b821f3a5f3b12/R-package/tests/testthat/test_basic.R#L15-L16

**Comment by jameslamb** [comment]
@StrikerRUS sure, I agree with all those! Just pushed them: https://github.com/microsoft/LightGBM/pull/3356/commits/727fe46e45e8af3bf8a3abad7ddbcfc807299bcd

**Comment by StrikerRUS** [comment]
@jameslamb Thank you!

**Review by StrikerRUS — COMMENTED** [review]
LGTM! I agree that those removed comments don't add any value. But I guess that actual approval should come from anyone who is reading/writing R code.

**Review by guolinke — APPROVED** [review]

**Pull request merged**
