### PR TITLE
add an advanced python example

### PR DESCRIPTION
**Pull request by wxchan**
Include:
- Set feature names
- Directly use categorical features without one-hot encoding
- Load model file to continue training
- Decay learning rates (with lambda function)
- Self-defined objective function
- Self-defined eval metric
- Callback function

Also clean some error message.

### CODE REVIEW

**Comment by gugatr0n1c** [comment]
Hi @wxchan, many thx to example to change objective. Can you please help me out with this?
I would to use as objective:

objc = (2/3) * (Abs[y_true - y_pred])^(3/2) as more robust version for regression tasks

grad should be as follow as I remember derivatives right..:

grad = sign(y_true-y_pred) * Abs[y_true-y_pred]^(1/2) 

hessian = sign(y_true-y_pred) * 1/2 * Abs[y_true-y_pred]^(-1/2) * sign(y_true-y_pred) = 0.5 * Abs[y_true - y_pred]^(-0.5)

so according to your code, my objective function is as follows? Is this correct? Can I use numpy inside?
many thx

def objc32(preds, train_data):
    labels = train_data.get_label()
    grad = np.sign(preds - labels) * np.absolute(preds - labels)**0.5
    hess = 0.5 * np.absolute(preds - labels)**(-0.5)
    return grad, hess

**Comment by guolinke** [comment]
I think some other things we can do in python package is:
1. documents, include Get Started, and interface details. Maybe can use some tools to generate markdown format documents.
2. refine feval functions.

**Comment by wxchan** [comment]
@guolinke About documents, I think [MkDocs](http://www.mkdocs.org/) can do the job. What's your plan on feval functions?

**Comment by wxchan** [comment]
@gugatr0n1c I think it's right, honestly I am bad at calculus.

**Comment by guolinke** [comment]
@wxchan I will start to do it today.
BTW, can you help to generate some documents inside python-package folder, and create some PR ? Thanks.

**Pull request merged**
