### PR TITLE
[python-package] add type hints on Dataset constructors

### PR DESCRIPTION
**Pull request by jameslamb**
Contributes to #3756.
Contributes to #3867.

Adds type hints on some methods in `Dataset` which don't currently have them.

### Notes for Reviewers

I'm beginning work on the "array-like" inputs in LightGBM's Python API, per https://github.com/microsoft/LightGBM/issues/3756#issuecomment-907622141.

This is a first step towards that.

### CODE REVIEW

**Comment by jmoralez** [comment]
WDYT about defining a type for the dataset handle like in https://github.com/microsoft/LightGBM/blob/0a5c5838eb679a43fc45443f71adf31ec506de22/include/LightGBM/c_api.h#L29

**Comment by jameslamb** [comment]
> WDYT about defining a type for the dataset handle like in

Can you be more specific about what you're proposing for the Python side and what the benefit would be? I don't understand.

**Comment by jmoralez** [comment]
Something like:
```python
DatasetHandle = ctypes.c_void_p

def __init_from_np2d(
    self,
    mat: np.ndarray,
    params_str: str,
    ref_dataset: Optional[DatasetHandle]
) -> "Dataset":
```

**Comment by jameslamb** [comment]
ah ok, so just for documentation purposes? Yeah that works for me! I'll make that change here.

**Comment by jameslamb** [comment]
updated in https://github.com/microsoft/LightGBM/pull/5458/commits/00b447789224c1c9aafcd4f393c3ce741e2ce6de

thanks for the suggestion!

**Comment by jameslamb** [comment]
😬 

> This is a scheduled macOS-10.15 brownout. The macOS-10.15 environment is deprecated and will be removed on September 30th, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5583

image

Azure DevOps build link: https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=13407&view=logs&j=382e14e0-e893-5ccd-73ac-68042457c8d8

Refer to #5391.

We have #5396 to fix this, but it's blocked by #5390, which is blocked by the need to switch to a new image for building wheels with a more recent version of glibc (https://github.com/microsoft/LightGBM/issues/5390#issuecomment-1221214158).

As that error message says, we have until September 30th to get this all done.

I'll prioritize changing that image and start working on it today.

**Pull request merged**
