### PR TITLE
[python] enforce a floor of Python 3.6 (fixes #5004)

### LINKED ISSUE #5004: [python-package] “python_requires” should be set with “>=3.5”, as lightgbm 3.3.2 is not compatible with all Python versions.
## Description
Currently, the keyword argument **python_requires** of **setup()** is not set, and thus it is assumed that this distribution is compatible with all Python versions. 
However, I found it is not compatible with **Python 2**. My local Python version is 2.7, and I encounter the following error when executing _“pip install lightgbm”_ 

```
Collecting lightgbm
  Downloading lightgbm-3.3.2.tar.gz (1.5 MB)
     |████████████████████████████████| 1.5 MB 233 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-O0hSCR/lightgbm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-O0hSCR/lightgbm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-TZ3SVN
         cwd: /tmp/pip-install-O0hSCR/lightgbm/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-O0hSCR/lightgbm/setup.py", line 38
        def find_lib() -> List[str]:
                       ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I noticed that **setup.py** used the syntax feature **Type Hints**. The feature is only compatible with Python 3, resulting in installation failure of lightgbm in Python 2.7.

Way to fix:
modify **setup()** in **setup.py,** add **python_requires** keyword argument:
```python
setup(…
     python_requires=">=3.5"
     …)
```
Thanks for your attention.
Best regrads,
PyVCEchecker

### PR DESCRIPTION
**Pull request by PyVCEchecker**
Fixes #5004.
Replaces #5005.

Add python_requires='>=3.6' for setup().

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Makes sense to me! Thanks for doing this!

I have two small notes for when you make future open source contributions.

1. I recommend creating a new branch from your fork, instead of directly committing to `master` there. That makes it possible to work on multiple pull requests at once, and ensures that there will never be commits on `master` of your fork that don't exist on the upstream project.
2. I've added `(fixes #5004)` to the title of this PR, so that the corresponding issue will be automatically closed when this is merged.

**Review by StrikerRUS — APPROVED** [review]
@PyVCEchecker Thanks a lot for this contribution, LGTM!

**Comment by StrikerRUS** [comment]
@jmoralez My position is that LightGBM should be as much permissive as possible. This is by the way not only my personal position, but historically supported general policy in this repo. Absence of artificial restrictions allows to run LightGBM in a wide range of different environments and hence increase its' popularity among users. As an example, I can name Dockerized Linux artifacts building in Ubuntu 14, CI jobs with Visual Studio 2015a and CUDA 9.0. There are a lot of cases of restricted environments which users cannot update for different reasons. I believe it's important to let users at least try to run LightGBM in such environments.

**Comment by jameslamb** [comment]
> My position is that LightGBM should be as much permissive as possible. 

I 100% agree with @StrikerRUS on this. Libraries like LightGBM should use as few ceilings / floors on language version and dependencies as possible.

In this case, I supported a floor of `python>=3.6` because with the use of type hints and f-strings throughout the package, older versions of Python don't even recognize the package as syntactically-valid Python code.

In case it helps describe my personal opinion on this better, I summarized some thoughts on this for library dependencies (not language version) over here: https://github.com/snowflakedb/snowflake-connector-python/pull/604#discussion_r562821349

**Pull request merged**
