### PR TITLE
python: use pytest for tests

### PR DESCRIPTION
**Pull request by henry0312**
https://docs.pytest.org/

This is the first commit of #261.
(I'm very sorry for too late starting)

I swithed nose to pytest (cf. #483).

### CODE REVIEW

**Comment by wylqq312715289** [comment]
dtest = lgb.Dataset('./data/libsvm.txt')
print dtest.num_feature()
======================= why error ================================
File "*******/basic.py", line 1158, in num_feature
    raise LightGBMError("Cannot get num_feature before construct dataset")
lightgbm.basic.LightGBMError: Cannot get num_feature before construct dataset
=================================================================
libsvm.txt like that:
1 0:0.4252040763188015 1:0.7234269439819614 2:0.2198664831534287
1 0:0.7855499009996039 1:0.2287907401631696 2:0.3954096899617033
0 0:0.8977085012657007 1:0.002568578519813736 2:0.7981754619557275
1 0:0.7754389449922868 1:0.3873931079206858 2:0.8511552221119321
1 0:0.9060812199464807 1:0.5049698598167162 2:0.3665523656418372
1 0:0.7289170144780479 1:0.6992288710470674 2:0.3380542718713656
1 0:0.02080155085980295 1:0.6404016217285756 2:0.4987680927973108
1 0:0.19294150321891 1:0.3788979348122099 2:0.2526684496343294
0 0:0.7324288183843998 1:0.8110061405511925 2:0.6875312345800412
0 0:0.6657764530014816 1:0.8326680735896242 2:0.7874407980610832

**Comment by wylqq312715289** [comment]
dtest = lgb.Dataset('./data/libsvm.txt')
print dtest.num_feature()
======================= why error ================================
File "*******/basic.py", line 1158, in num_feature
raise LightGBMError("Cannot get num_feature before construct dataset")
lightgbm.basic.LightGBMError: Cannot get num_feature before construct dataset

libsvm.txt like that:
1 0:0.4252040763188015 1:0.7234269439819614 2:0.2198664831534287
1 0:0.7855499009996039 1:0.2287907401631696 2:0.3954096899617033
0 0:0.8977085012657007 1:0.002568578519813736 2:0.7981754619557275
1 0:0.7754389449922868 1:0.3873931079206858 2:0.8511552221119321
1 0:0.9060812199464807 1:0.5049698598167162 2:0.3665523656418372
1 0:0.7289170144780479 1:0.6992288710470674 2:0.3380542718713656
1 0:0.02080155085980295 1:0.6404016217285756 2:0.4987680927973108
1 0:0.19294150321891 1:0.3788979348122099 2:0.2526684496343294
0 0:0.7324288183843998 1:0.8110061405511925 2:0.6875312345800412
0 0:0.6657764530014816 1:0.8326680735896242 2:0.7874407980610832

**Comment by wylqq312715289** [comment]
import lightgbm as lgb
dtest = lgb.Dataset('./data/libsvm.txt')
print dtest.num_feature()
======================= why error ================================
File "*******/basic.py", line 1158, in num_feature
raise LightGBMError("Cannot get num_feature before construct dataset")
lightgbm.basic.LightGBMError: Cannot get num_feature before construct dataset
==================================================================
libsvm.txt like that:
1 0:0.4252040763188015 1:0.7234269439819614 2:0.2198664831534287
1 0:0.7855499009996039 1:0.2287907401631696 2:0.3954096899617033
0 0:0.8977085012657007 1:0.002568578519813736 2:0.7981754619557275
1 0:0.7754389449922868 1:0.3873931079206858 2:0.8511552221119321
1 0:0.9060812199464807 1:0.5049698598167162 2:0.3665523656418372
1 0:0.7289170144780479 1:0.6992288710470674 2:0.3380542718713656
1 0:0.02080155085980295 1:0.6404016217285756 2:0.4987680927973108
1 0:0.19294150321891 1:0.3788979348122099 2:0.2526684496343294
0 0:0.7324288183843998 1:0.8110061405511925 2:0.6875312345800412
0 0:0.6657764530014816 1:0.8326680735896242 2:0.7874407980610832

**Comment by wylqq312715289** [comment]
import lightgbm as lgb
dtest = lgb.Dataset('./data/libsvm.txt')
print dtest.num_feature()
======================= why error ================================
File "*******/basic.py", line 1158, in num_feature
raise LightGBMError("Cannot get num_feature before construct dataset")
lightgbm.basic.LightGBMError: Cannot get num_feature before construct dataset
===========================?=======================================
libsvm.txt like that:
1 0:0.4252040763188015 1:0.7234269439819614 2:0.2198664831534287
1 0:0.7855499009996039 1:0.2287907401631696 2:0.3954096899617033
0 0:0.8977085012657007 1:0.002568578519813736 2:0.7981754619557275
1 0:0.7754389449922868 1:0.3873931079206858 2:0.8511552221119321
1 0:0.9060812199464807 1:0.5049698598167162 2:0.3665523656418372
1 0:0.7289170144780479 1:0.6992288710470674 2:0.3380542718713656
1 0:0.02080155085980295 1:0.6404016217285756 2:0.4987680927973108
1 0:0.19294150321891 1:0.3788979348122099 2:0.2526684496343294
0 0:0.7324288183843998 1:0.8110061405511925 2:0.6875312345800412
0 0:0.6657764530014816 1:0.8326680735896242 2:0.7874407980610832

**Comment by henry0312** [comment]
@wylqq312715289 what is this?

**Comment by guolinke** [comment]
@wxchan can you help to review this ?

**Comment by henry0312** [comment]
I guess he may be busy 🤔

**Comment by guolinke** [comment]
@henry0312 I take a look and think it is okay to merge first. 😄

**Pull request merged**
