### PR TITLE
Update StringArray.i

### PR DESCRIPTION
**Pull request by Shahil093**
Here's the updated code with the new features added

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Is the only goal of this pull request to add a blank line to `swig/StringArray.i`? If so, I don't support merging this, and would ask that you please close it. We generally prefer to reserve whitespace-only changes for maintainers, to avoid cluttering the history in the git blame.

**Comment by jameslamb** [comment]
I'm closing this due to lack of response. We're always grateful for contributions in this project, but please don't open another PR like this that only changes whitespace.

**Comment by Shahil093** [comment]
assign me this i just didn't get notification

**Comment by jameslamb** [comment]
Assign you what? All this PR does is add a blank line to a file.

**Comment by Shahil093** [comment]
> Assign you what? All this PR does is add a blank line to a file.

i have updated check here
https://github.com/microsoft/LightGBM/pull/5919

**Pull request closed without merging**
