### PR TITLE
[R-package] manage Dataset and Booster handles as R external pointers (fixes #3016)

### LINKED ISSUE #3016: [R-package] Factor out custom R interface to lib_lightgbm
## Summary

The R  package calls a C++ library (`lib_lightgbm.so`) with the  R function `.Call()`.  Doing this requires an interface to map R data types to C data types and back. Right now we do not use the [SEXP ("S expression") interface that ships with R's built-in headers](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#System-and-foreign-language-interfaces).

So far our custom implementation has worked well, but there is a risk that future versions of R  will not work with it.

To close this issue, remove `R_object_helper.h`, including `LGBM_SER` and  `LGBM_SE`. Replace them with the corresponding symbols from `R.h`, `Rinternals.h`, and the other R built-in headers.

It is likely possible to do this in pieces....it does not have to be a single pull request.

## Motivation

This may not be strictly necessary to get to CRAN, but it will bring the R package into tighter compatibility with the R build tools, so should improve the chances we'll be able to support new  versions of R with no changes.

I _suspect_, though I don't know for sure, that this would also resolve these warnings we're getting from some compilers:

image

See https://github.com/microsoft/LightGBM/pull/3009#issuecomment-617219336 and

### PR DESCRIPTION
**Pull request by jameslamb**
Fixes #3016.

Contributes to #4208, might help with #4034.

## Description

When the R package calls functions from the C++ side that create persistent objects in memory, like a Dataset  or Booster, it stores a pointer to the memory address of such objects in a "handle". Today, these handles are stored in a double on 64-bit systems and as an int32 on 32-bit systems.

https://github.com/microsoft/LightGBM/blob/f83180883a51729af9562ccac7b450c6da79a04a/R-package/R/utils.R#L9-L15

Today, the R package uses LightGBM's custom R-to-C interface to manage these handles. This can lead to issues like #4208, and generally exposes LightGBM to compatibility problems if new versions of R introduce changes that require corresponding changes in that custom interface.

This PR proposes replacing that custom management of "handles" with R's built-in pattern for such things. R's C API has a concept called "external pointers" designed for exactly this purpose.

From https://cran.r-project.org/doc/manuals/r-release/R-exts.html#External-pointers-and-weak-references

> External pointer SEXPs are intended to handle references to C structures such as ‘handles’

## Notes for Reviewers

This only fixes #3016 if is is merged after #4256.

The "References" section below contains links to the resources that helped me to understand these concepts better, and they might help reviewers to understand these changes.

### References

* https://cran.r-project.org/doc/manuals/r-release/R-exts.html#External-pointers-and-weak-references
* https://cran.r-project.org/doc/manuals/r-release/R-exts.html#An-external-pointer-example
* https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#SEXPTYPEs
* http://adv-r.had.co.nz/C-interface.html#c-data-structures
* https://github.com/dmlc/xgboost/blob/e41619b1fc6152d4392896c6caf9a0dc960c5558/R-package/src/xgboost_R.cc
* https://stackoverflow.com/a/26671781/3986677

### CODE REVIEW

**Comment by StrikerRUS** [comment]
Wonderful!
Unfortunately, this PR doesn't fix the following compilation warning
```
/home/runner/work/LightGBM/LightGBM/lightgbm.Rcheck/00_pkg_src/lightgbm/src/src/lightgbm_R.cpp:720:52: warning: cast between incompatible function types from ‘SEXPREC* (*)(SEXP)’ {aka ‘SEXPREC* (*)(SEXPREC*)’} to ‘DL_FUNC’ {aka ‘void* (*)()’} [-Wcast-function-type]
```
as it was suspected in https://github.com/microsoft/LightGBM/issues/3016#issue-605212323
> I *suspect*, though I don't know for sure, that this would also resolve these warnings we're getting from some compilers:

Any ideas why it doesn't and whether we should create a separate issue for these warnings as this PR is closing #3016?

**Comment by jameslamb** [comment]
> Any ideas why it doesn't and whether we should create a separate issue for these warnings as this PR is closing #3016?

Please create a separate issue for it and I can investigate it (and document which specific combinations of operating system + R version + compiler + installation method it occurs for) in the future.

**Comment by jameslamb** [comment]
> Please create a separate issue for it and I can investigate it

@StrikerRUS I'm back at a computer now so I can make this issue.

**Comment by jameslamb** [comment]
created https://github.com/microsoft/LightGBM/issues/4273 to track the compiler warning

**Review by StrikerRUS — CHANGES_REQUESTED** [review]
Very nice PR!
Please consider checking some my questions and cleanup suggestions below.

**Comment by StrikerRUS** [comment]
Hmmm, valgrind test is failing due to the time limit.
```
The job running on runner GitHub Actions 78 has exceeded the maximum execution time of 120 minutes.
```
Rerunning...

**Comment by jameslamb** [comment]
whew, seems that it succeeded.

Total duration of https://github.com/microsoft/LightGBM/actions/runs/833251558 was 1 hour, 50 minutes, 46 seconds.

I think that if we see timeout issues again in the future, we should increase the allowed time by another 30 minutes.

**Comment by StrikerRUS** [comment]
> I think that if we see timeout issues again in the future, we should increase the allowed time by another 30 minutes.

Agree.

**Review by StrikerRUS — APPROVED** [review]
Woo-hoo! Thank you!

**Comment by jameslamb** [comment]
Excited about this one!!

**Pull request merged**
