### PR TITLE
fix many cpp lint errors

### PR DESCRIPTION
**Pull request by guolinke**
refer to #1990

### CODE REVIEW

**Comment by guolinke** [comment]
BTW, this will have some conflicts with other PRs.
@StrikerRUS I think we should merge this ASAP.

**Comment by guolinke** [comment]
@StrikerRUS yeah, but it seems the reinterpret_cast is the only way, and it actually equals to c style cast.

**Comment by guolinke** [comment]
@StrikerRUS BTW, as `json11` is not maintained by us, we can disable the lint check over it.

**Comment by StrikerRUS** [comment]
@guolinke Yes, but why?.. As it's not a "submodule" (as `compute`) it falls into situation when it's maintained by no one. I think it's not right. Seems that the license allows to modify it. I remember there were some dangerous warnings from cpplint for `json11`.

**Comment by guolinke** [comment]
Okay, I think we won't modify it, so we can keep it as it is. However, if these warnings are easy to fix, we could fix it directly.

**Pull request merged**
