### PR TITLE
simplify Dataset class

### PR DESCRIPTION
**Pull request by wxchan**
What I did is to move _InnerDataset.__int__ into Dataset as _lazy_init, turn every _InnerDataset(...) into _lazy_init(...).

### CODE REVIEW

**Comment by wxchan** [comment]
I did not change any Dataset api.

**Comment by guolinke** [comment]
@wxchan I found reset_parameters callback is not effect for cv.
Can you add support for this? 
also can check parameter in the callback.

**Comment by guolinke** [comment]
@wxchan Currently implementation of reset parameters is not efficient too.
https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/callback.py#L122-L130
it will reset many times if passed multi parameters. 
I think you can join these key-value pair and call reset_parameters only one time.

**Comment by wxchan** [comment]
@guolinke reset_parameters callback is not effect when `callbacks=[reset_parameters(...)]`? or you mean add another argument?

**Comment by guolinke** [comment]
@wxchan the reason is we only reset parameters for ```env.model``, not for ```env.cvfolds```.

**Comment by wxchan** [comment]
@guolinke can you see my comments at https://github.com/Microsoft/LightGBM/commit/65d55194bc984a850f0694653cd2f3f32562f5cc? I saw you reset HEAD. 

`self._is_construct` came from old method `self._is_construct()`, I think it should not appear at set_label etc. now.

**Comment by guolinke** [comment]
@wxchan I think using an additional variable to store _is_constructed less maintainable. 
I change it back to a function now.

**Pull request merged**
