### PR TITLE
Use gcc-7 on OSX

### PR DESCRIPTION
**Pull request by henry0312**
Homebrew updated gcc to 7.1.
https://github.com/Homebrew/homebrew-core/commit/0387fe46e9ce9fe4a14dbce9d31d70f5824ff830
https://github.com/Homebrew/homebrew-core/commit/0ab90d39e3ca786c9f0b2fb44c2fd29880336cd2

### CODE REVIEW

**Comment by guolinke** [comment]
@henry0312 
can you try to update https://github.com/Microsoft/LightGBM/wiki/Installation-Guide#osx as well ?

**Comment by henry0312** [comment]
@guolinke updated the wiki.

**Comment by henry0312** [comment]
Oh, I don't know how to install for R-package...

**Comment by guolinke** [comment]
@henry0312 OK. it seems not need to update R's installation.

**Pull request merged**
