### PR TITLE
[R-package] [docs] fix broken plots in pkgdown site (fixes #3276)

### LINKED ISSUE #3276: [R-package] plots are broken in R documentation
See https://github.com/microsoft/LightGBM/pull/3270#issuecomment-668579806 and the comments that follow it.

The plots on these pages are broken:

* https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.plot.importance.html
* https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.plot.interpretation.html

image

This might be the result of the fact that we use a very old R version (3.5.1) in build in the site. See `docs/conf.py`.

### PR DESCRIPTION
**Pull request by jameslamb**
#3276 documents some issues rendering plots in examples for the R package's documentation site, at https://lightgbm.readthedocs.io/en/latest/R/reference/.

I think that this is caused by the use of an older R version. This PR proposes fixing that by upgrading to R 4.0.3. It seems that R 4.0.3 packages are now available from conda-forge (thanks to the hard work of @xhochy and other https://github.com/conda-forge/r-base-feedstock maintainers).

This PR also simplifies our setup on RTD in a few ways:

* removes unnecessary dependency `testthat`
* removes unnecessary setting of `repos` option
* builds the entire env in one step (instead of installing anaconda and conda-forge packages separately) 

### Notes for Reviewers

I tested locally with the following code, on an Ubuntu 18.04 laptop using `conda` 4.8.4:

```shell
conda create \
    -q \
    -y \
    -c conda-forge \
    -n r_env \
        cmake=3.14.0=h52cb24c_0 \
        r-base=4.0.3=hc603457_2 \
        r-data.table=1.13.2=r40h0eb13af_0 \
        r-jsonlite=1.7.1=r40hcdcec82_0 \
        r-matrix=1.2_18=r40h7fa42b6_3 \
        r-pkgdown=1.6.1=r40h6115d3f_0 \
        r-roxygen2=7.1.1=r40h0357c0b_0

export R_LIBS="$CONDA_PREFIX/lib/R/library"
Rscript build_r.R
cd R-package
Rscript -e "roxygen2::roxygenize(load = 'installed')"
Rscript -e "pkgdown::build_site( \
        lazy = FALSE \
        , install = FALSE \
        , devel = FALSE \
        , examples = TRUE \
        , run_dont_run = TRUE \
        , seed = 42L \
        , preview = FALSE \
        , new_process = TRUE \
    ) \
    "
```

At least locally, the plots look ok now

image

image

### CODE REVIEW

**Comment by jameslamb** [comment]
@StrikerRUS I created this from a LightGBM branch so we can test. Can you please enable RTD builds for it?

Thank you!

**Comment by StrikerRUS** [comment]
@jameslamb 
> Can you please enable RTD builds for it?

Sure, done!

**Comment by jameslamb** [comment]
looks like the RTD build passed: https://readthedocs.org/projects/lightgbm/builds/12229562/

and looks like the plots are fixed!

https://lightgbm.readthedocs.io/en/fix-r-plots//R/reference/lgb.plot.importance.html

image

https://lightgbm.readthedocs.io/en/fix-r-plots//R/reference/lgb.plot.interpretation.html

image

**Comment by StrikerRUS** [comment]
@jameslamb 
Very nice indeed! Could you please bump CMake version in this PR as well as you are updating all installed packages?

**Comment by jameslamb** [comment]
> @jameslamb
> Very nice indeed! Could you please bump CMake version in this PR as well as you are updating all installed packages?

sure!

**Comment by jameslamb** [comment]
upgraded to 3.18.2 in https://github.com/microsoft/LightGBM/pull/3508/commits/22f9dcb8b5b7afb3c39a98b7b470c1fbb8dd61ae, let's see if it works

**Comment by jameslamb** [comment]
This worked with the newer `CMake`:

✅ https://readthedocs.org/projects/lightgbm/builds/12234522/

https://lightgbm.readthedocs.io/en/fix-r-plots//R/reference/lgb.plot.importance.html

image

https://lightgbm.readthedocs.io/en/fix-r-plots//R/reference/lgb.plot.interpretation.html

image

I'll merge this and delete the branch once CI passes

**Review by StrikerRUS — APPROVED** [review]
Great! Thanks for the fix!

**Pull request merged**
