### PR TITLE
release v4.3.0

### PR DESCRIPTION
**Pull request by jameslamb**
### Release checklist:

Copied from #6191, with a few changes.

*before merge*

- [x] Update [VERSION.txt](https://github.com/microsoft/LightGBM/blob/master/VERSION.txt) number.
- [x] Update version in [Appveyor config file](https://github.com/microsoft/LightGBM/blob/master/.appveyor.yml).
- [x] Update version in [`configure` file of R-package](https://github.com/microsoft/LightGBM/blob/master/R-package/configure): `/gha run r-configure`.
- [x] Change `development.mode` from `unreleased` to `release` in [pkgdown config file](https://github.com/microsoft/LightGBM/blob/master/R-package/pkgdown/_pkgdown.yml).
- [x] Update version in `python-package/pyproject.toml`
- [x] Add release branch to [RTD versions](https://readthedocs.org/projects/lightgbm/versions/), trigger a new build, check docs
- [x] All docs for new behavior have Sphinx `versionadded::` annotations ([docs on those](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded))
    - *nothing in this release requires those*
- [x] All new parameters in `config.h` have `*New in version {version}*` comments added
    - *no new parameters added in `config.h` in this release*
- [x] Run the valgrind checks with `/gha run r-valgrind` ([docs link](https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#valgrind)) 
- [x] manually test Python and R packages on M1/M2 Mac

PRs that should be merged before releasing:

None

*after merge*

- [ ] Push `v*` tag to trigger `GitHubRelease` action at Azure Pipelines.
- [ ] Update [`stable` tag at GitHub](https://github.com/microsoft/LightGBM/releases/tag/stable).
- [ ] Add release notes from `release-drafter` to the automatically-created GitHub release, convert it from `Draft` to published.
- [ ] Add new tag to [RTD versions](https://readthedocs.org/projects/lightgbm/versions/) and trigger a new build.
- [ ] Upload release to [CRAN](https://cran.r-project.org/package=lightgbm)
- [ ] Remove the release branch from RTD versions
- [ ] Upload release to [test PyPI](https://test.pypi.org/project/lightgbm/)
- [ ] Upload release to [PyPI](https://pypi.org/project/lightgbm/).
- [ ] Update [cran-comments.md](https://github.com/microsoft/LightGBM/blob/master/R-package/cran-comments.md) when new release is accepted on CRAN.
- [ ] Upload release to [NuGet](https://www.nuget.org/packages/LightGBM/).
- [ ] Update version and commit hash in [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/l/lightgbm.rb) ([docs](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md#to-submit-a-version-upgrade-for-the-foo-formula))
- [ ] put up another PR incrementing development version here in GitHub (example: #6090)

### Notes for Reviewers

I believe this should be `v4.3.0` instead of `v4.2.1` because of the two breaking changes:

* #6260
* #6246

This release is being put up so soon after `v4.2.0` mainly to try to prevent CRAN from archiving the package

### CODE REVIEW

**Comment by jameslamb** [comment]
Since all of the R tests (including `valgrind` and a few I submitted via rhub) are passing here, I've built the CRAN package and submitted it to CRAN as v4.3.0.

Submitted with this note:

> *This version contains changes which we believe will fix the issues reported in CRAN's 'clang18' checks (https://www.stats.ox.ac.uk/pub/bdr/clang18/lightgbm.log). We've tested those changes using images from rhub (https://github.com/microsoft/LightGBM/pull/6265), configured based on CRAN's "Additional Issues" notes at https://cran.r-project.org/web/checks/check_issue_kinds.html.*

In the future I don't want to do that outside of the normal release process with approvals and review, but I thought it was necessary to act quickly given the short deadline from CRAN.

**Comment by jameslamb** [comment]
> I've built the CRAN package and submitted it to CRAN as v4.3.0

Happy to say the package was accepted to CRAN! The `clang18` check warning is gone at https://cran.r-project.org/web/checks/check_results_lightgbm.html and the package is passing almost all of CRAN's checks (just `r-patched-linux-x84_64` has not been run yet).

Updated `cran-comments.md` in https://github.com/microsoft/LightGBM/pull/6277/commits/63d71f6e741275e4ec73d5e2feefccbf3a931467.

> there are some non-R CI failures blocking this PR

Documented in #6282.

Investigating in #6283.

**Comment by jameslamb** [comment]
> Add release branch to [RTD versions](https://readthedocs.org/projects/lightgbm/versions/), trigger a new build, check docs

docs build for this release is passing: https://readthedocs.org/projects/lightgbm/builds/23200920/

and the docs look good to me:

* https://lightgbm.readthedocs.io/en/release-v4.3.0/
* https://lightgbm.readthedocs.io/en/release-v4.3.0/R/reference/

**Comment by jameslamb** [comment]
> ... test on M1/M2 Mac

The R package is passing CRAN's checks on an `arm64` mac: https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/lightgbm-00install.html

I'll test on my M2 laptop in a bit (just waiting on some software updates).

**Comment by jameslamb** [comment]
@guolinke @jmoralez @shiyu1994 @borchero could you please take a look and let me know if you agree with releasing the current state of this branch (which is up to date with `master`) as v4.3.0?

**Review by jmoralez — APPROVED** [review]

**Comment by jameslamb** [comment]
Built and tested the Python package on my M2 Mac (macOS Sonoma 14.3) tonight.

```shell
sh build-python.sh bdist_wheel --nomp
pip install dist/lightgbm*.whl
pytest tests/python_package_test
```

I used `--nomp` because I was finding deadlocks that I think might have been caused by different `libomp` being found at build time vs. runtime (https://github.com/microsoft/LightGBM/issues/4229#issuecomment-1871489569).

All tests except the Arrow ones passed. The Arrow tests all failed.

<details><summary>logs (click me)</summary>

```text
=========================================== short test summary info ============================================
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_fuzzy[<lambda>-dataset_params0] - AssertionError: assert False
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_fuzzy[<lambda>-dataset_params1] - AssertionError: assert False
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_fuzzy[<lambda>-dataset_params2] - AssertionError: assert False
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_fuzzy[<lambda>-dataset_params3] - AssertionError: assert False
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_fuzzy[<lambda>-dataset_params4] - AssertionError: assert False
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_fuzzy[<lambda>-dataset_params5] - AssertionError: assert False
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_fields_fuzzy - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type0-array-label_data0] - TypeError: Wrong type(Int8Array) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type0-chunked_array-label_data1] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type0-chunked_array-label_data2] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type0-chunked_array-label_data3] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type1-array-label_data0] - TypeError: Wrong type(Int16Array) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type1-chunked_array-label_data1] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type1-chunked_array-label_data2] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type1-chunked_array-label_data3] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type2-array-label_data0] - TypeError: Wrong type(Int32Array) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type2-chunked_array-label_data1] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type2-chunked_array-label_data2] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type2-chunked_array-label_data3] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type3-array-label_data0] - TypeError: Wrong type(Int64Array) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type3-chunked_array-label_data1] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type3-chunked_array-label_data2] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type3-chunked_array-label_data3] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type4-array-label_data0] - TypeError: Wrong type(UInt8Array) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type4-chunked_array-label_data1] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type4-chunked_array-label_data2] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type4-chunked_array-label_data3] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type5-array-label_data0] - TypeError: Wrong type(UInt16Array) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type5-chunked_array-label_data1] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type5-chunked_array-label_data2] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type5-chunked_array-label_data3] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type6-array-label_data0] - TypeError: Wrong type(UInt32Array) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type6-chunked_array-label_data1] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type6-chunked_array-label_data2] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type6-chunked_array-label_data3] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type7-array-label_data0] - TypeError: Wrong type(UInt64Array) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type7-chunked_array-label_data1] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type7-chunked_array-label_data2] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type7-chunked_array-label_data3] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type8-array-label_data0] - TypeError: Wrong type(FloatArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type8-chunked_array-label_data1] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type8-chunked_array-label_data2] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type8-chunked_array-label_data3] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type9-array-label_data0] - TypeError: Wrong type(DoubleArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type9-chunked_array-label_data1] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type9-chunked_array-label_data2] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_labels[arrow_type9-chunked_array-label_data3] - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_weights_none - TypeError: Wrong type(Int64Array) for weight.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_weights[arrow_type0-array-weight_data0] - TypeError: Wrong type(FloatArray) for weight.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_weights[arrow_type0-chunked_array-weight_data1] - TypeError: Wrong type(ChunkedArray) for weight.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_weights[arrow_type0-chunked_array-weight_data2] - TypeError: Wrong type(ChunkedArray) for weight.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_weights[arrow_type0-chunked_array-weight_data3] - TypeError: Wrong type(ChunkedArray) for weight.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_weights[arrow_type1-array-weight_data0] - TypeError: Wrong type(DoubleArray) for weight.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_weights[arrow_type1-chunked_array-weight_data1] - TypeError: Wrong type(ChunkedArray) for weight.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_weights[arrow_type1-chunked_array-weight_data2] - TypeError: Wrong type(ChunkedArray) for weight.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_weights[arrow_type1-chunked_array-weight_data3] - TypeError: Wrong type(ChunkedArray) for weight.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type0-array-group_data0] - TypeError: Wrong type(Int8Array) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type0-chunked_array-group_data1] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type0-chunked_array-group_data2] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type0-chunked_array-group_data3] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type1-array-group_data0] - TypeError: Wrong type(Int16Array) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type1-chunked_array-group_data1] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type1-chunked_array-group_data2] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type1-chunked_array-group_data3] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type2-array-group_data0] - TypeError: Wrong type(Int32Array) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type2-chunked_array-group_data1] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type2-chunked_array-group_data2] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type2-chunked_array-group_data3] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type3-array-group_data0] - TypeError: Wrong type(Int64Array) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type3-chunked_array-group_data1] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type3-chunked_array-group_data2] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type3-chunked_array-group_data3] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type4-array-group_data0] - TypeError: Wrong type(UInt8Array) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type4-chunked_array-group_data1] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type4-chunked_array-group_data2] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type4-chunked_array-group_data3] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type5-array-group_data0] - TypeError: Wrong type(UInt16Array) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type5-chunked_array-group_data1] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type5-chunked_array-group_data2] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type5-chunked_array-group_data3] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type6-array-group_data0] - TypeError: Wrong type(UInt32Array) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type6-chunked_array-group_data1] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type6-chunked_array-group_data2] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type6-chunked_array-group_data3] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type7-array-group_data0] - TypeError: Wrong type(UInt64Array) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type7-chunked_array-group_data1] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type7-chunked_array-group_data2] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_groups[arrow_type7-chunked_array-group_data3] - TypeError: Wrong type(ChunkedArray) for group.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type0-array-init_score_data0] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type0-chunked_array-init_score_data1] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type0-chunked_array-init_score_data2] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type0-chunked_array-init_score_data3] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type1-array-init_score_data0] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type1-chunked_array-init_score_data1] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type1-chunked_array-init_score_data2] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type1-chunked_array-init_score_data3] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type2-array-init_score_data0] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type2-chunked_array-init_score_data1] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type2-chunked_array-init_score_data2] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type2-chunked_array-init_score_data3] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type3-array-init_score_data0] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type3-chunked_array-init_score_data1] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type3-chunked_array-init_score_data2] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type3-chunked_array-init_score_data3] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type4-array-init_score_data0] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type4-chunked_array-init_score_data1] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type4-chunked_array-init_score_data2] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type4-chunked_array-init_score_data3] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type5-array-init_score_data0] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type5-chunked_array-init_score_data1] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type5-chunked_array-init_score_data2] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type5-chunked_array-init_score_data3] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type6-array-init_score_data0] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type6-chunked_array-init_score_data1] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type6-chunked_array-init_score_data2] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type6-chunked_array-init_score_data3] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type7-array-init_score_data0] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type7-chunked_array-init_score_data1] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type7-chunked_array-init_score_data2] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type7-chunked_array-init_score_data3] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type8-array-init_score_data0] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type8-chunked_array-init_score_data1] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type8-chunked_array-init_score_data2] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type8-chunked_array-init_score_data3] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type9-array-init_score_data0] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type9-chunked_array-init_score_data1] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type9-chunked_array-init_score_data2] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_array[arrow_type9-chunked_array-init_score_data3] - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_dataset_construct_init_scores_table - TypeError: init_score must be list, numpy 1-D array or pandas Series.
FAILED tests/python_package_test/test_arrow.py::test_predict_regression - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_predict_binary_classification - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_predict_multiclass_classification - TypeError: Wrong type(ChunkedArray) for label.
FAILED tests/python_package_test/test_arrow.py::test_predict_ranking - TypeError: Wrong type(ChunkedArray) for label.
==================== 133 failed, 540 passed, 33 skipped, 2 xfailed, 147 warnings in 40.24s ====================
```

</details>

I don't think the changeset in v4.3.0 here is the cause of either of these issues, and they seem limited to the `arm64` Macs.

I don't think they should delay this release, and that we can focus on fixing them (and various other macOS support issues) in the next release.

**Review by shiyu1994 — APPROVED** [review]

**Comment by shiyu1994** [comment]
LGTM. Thanks!

**Comment by jameslamb** [comment]
Thanks all! I'll continue with the release.

**Comment by jameslamb** [comment]
Ran the following to create the `v4.3.0` tag and update the `stable` tag.

```shell
git fetch upstream --tags
git tag -d stable
git push upstream :refs/tags/stable
git tag stable
git tag v4.3.0
git push upstream stable v4.3.0
```

*(NOTE: I alias this repo to `upstream` and my fork to `origin` in my `git` settings)*

https://github.com/microsoft/LightGBM/tags

image

That triggered an Azure DevOps build which should create the release automatically:https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=15709&view=results. This takes around 90 minutes (because of the QEMU CI job).

I'll do the remaining tasks tomorrow.

**Comment by jameslamb** [comment]
`v4.3.0` release has been created: https://github.com/microsoft/LightGBM/releases/tag/v4.3.0

**Comment by jameslamb** [comment]
> Update version and commit hash in [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/l/lightgbm.rb)

https://github.com/Homebrew/homebrew-core/pull/160920

**Comment by jameslamb** [comment]
> Upload release to [test PyPI](https://test.pypi.org/project/lightgbm/)
> Upload release to [PyPI](https://pypi.org/project/lightgbm/).

This is done, and tested that the wheels installed from there work (on my intel mac).

image

https://pypi.org/project/lightgbm/#files

**Comment by jameslamb** [comment]
> Add new tag to [RTD versions](https://readthedocs.org/projects/lightgbm/versions/) and trigger a new build.

These are done. v4.3.0 now available on readthedocs.

* successful build:https://readthedocs.org/projects/lightgbm/builds/23238180/
* version-pinned docs:
  - https://lightgbm.readthedocs.io/en/v4.3.0/
  - https://lightgbm.readthedocs.io/en/v4.3.0/R/reference/

**Comment by jameslamb** [comment]
> Upload release to [NuGet](https://www.nuget.org/packages/LightGBM/).

done

**Comment by jameslamb** [comment]
> put up another PR incrementing development version here in GitHub 

#6287

And with that, this release is done. Thanks everyone!

**Comment by jameslamb** [comment]
For future reference... I added some code snippets to the PR description here to hopefully make it a little easier to cut the ext release.

Maybe in the future if we start releasing more frequently, it'd make sense to check those into the repo.

**Pull request merged**
