### PR TITLE
Fix calculation of number of bins in FindGroup

### LINKED ISSUE #3339: [Bug] LightGBMError: bin size 257 cannot run on GPU
I'm getting the following error while running the latest LightGBM GPU using these params:

```
params = {
            'device_type': 'gpu',
            'gpu_device_id': 0,
            'gpu_platform_id': 0,
            'gpu_use_dp': 'false',
            'max_bin': 255
}
```

on Google Colab using this Kaggle dataset: https://www.kaggle.com/c/ieee-fraud-detection. I'm dropping all the categorical variables:

`LightGBMError: bin size 257 cannot run on GPU`

### PR DESCRIPTION
**Pull request by CVPaul**
Fixes #3339.

The calculation method for num_total_bin used during Exclusive Feature Bundling

[LightGBM/src/io/dataset.cpp](https://github.com/microsoft/LightGBM/blob/665c47313d6938a8d80559c824073a142c8bd870/src/io/dataset.cpp#L134)

Line 134 in [665c473](https://github.com/microsoft/LightGBM/commit/665c47313d6938a8d80559c824073a142c8bd870)

 (bin_mappers[fidx]->GetDefaultBin() == 0 ? -1 : 0); 
doesn't align completely with the way num_total_bin is calculated during the creation of a FeatureGroup
[LightGBM/include/LightGBM/feature_group.h](https://github.com/microsoft/LightGBM/blob/665c47313d6938a8d80559c824073a142c8bd870/include/LightGBM/feature_group.h#L68)

Line 68 in [665c473](https://github.com/microsoft/LightGBM/commit/665c47313d6938a8d80559c824073a142c8bd870)

 if (bin_mappers_[i]->GetMostFreqBin() == 0) { 
As a result, the max_bin_per_group (=256) is working during Bundling, but it is not working when creating the FeatureGroup. When I replaced the GetDefaultBin() at dataset.cpp#L134 with GetMostFreqBin(), the issue was resolved.

### CODE REVIEW

**Comment by CVPaul** [comment]
> 

@microsoft-github-policy-service agree

**Comment by jameslamb** [comment]
@shiyu1994 could you please edit the title of this to make it more informative in the release notes? I would, but I don't really understand the effect of this PR.

**Comment by Borda** [comment]
this would be great to have in any release soon, please :pray:

**Review by shiyu1994 — APPROVED** [review]

**Comment by fillipemadureira** [comment]
> this would be great to have in any release soon, please 🙏

I've just come across this issue. No release with this solution yet??

**Comment by borchero** [comment]
Unfortunately, we are currently battling CI issues (cf. https://github.com/microsoft/LightGBM/pull/6425). Once we got our GPU runners working again, we are planning to prepare another release -- this will likely happen in the early part of May.

**Review by yuhorun — APPROVED** [review]

**Pull request merged**
