### PR TITLE
[WIP][docs] clarify CLI-only parameters and rework parameters section in Quick-Start guide

### PR DESCRIPTION
**Pull request by StrikerRUS**
Refer to https://github.com/Microsoft/LightGBM/pull/1421#issuecomment-394354696.

I think that we can just give a reference to the parameters and highlight where to find the most important ones instead of copy-pasting the part of the params' description in `Quick-Start.rst`.

@guolinke 
Is this list on CLI-only params correct now? Please correct me.

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L85

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L97

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L140

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L146

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L398

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L402

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L409

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L413

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L418

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L425

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L559

https://github.com/Microsoft/LightGBM/blob/c0147cbe626abc7b1bee25a3b5893b3441fe0251/include/LightGBM/config.h#L564

### CODE REVIEW

**Comment by guolinke** [comment]
@StrikerRUS maybe we should fix the check-the-doc test first

**Comment by StrikerRUS** [comment]
@guolinke Done! Please check the list above.

**Comment by StrikerRUS** [comment]
@guolinke I wanted to add notes about CLI-only params in this PR. So what about the list above? Have you checked it?

**Comment by guolinke** [comment]
yeah, already check it

**Comment by StrikerRUS** [comment]
@guolinke Thanks! Then I'll send new PR to add notes.

**Pull request merged**
