### PR TITLE
[ci] apply cpplint to cpp tests

### PR DESCRIPTION
**Pull request by StrikerRUS**

### CODE REVIEW

**Comment by StrikerRUS** [comment]
Only one issue left:
```
tests/cpp_test/test_chunked_array.cpp:42:  Is this a non-const reference? If so, make const or use a pointer: ChunkedArray<int> &ca  [runtime/references] [2]
```

Please help fix it.

**Comment by StrikerRUS** [comment]
@AlbertoEAF Could you please help with this https://github.com/microsoft/LightGBM/pull/4092#issuecomment-804032948 when have time?
You can checkout `cpplint` branch and make PR against it.

**Comment by StrikerRUS** [comment]
Thanks to @AlbertoEAF , this PR is ready for review.

**Review by jameslamb — APPROVED** [review]
looks good to me, and I agree with applying `cpplint` to the tests in `tests/cpp_test`.

**Pull request merged**
