### PR TITLE
[R-package] Handle integer types more accurate in R-to-C interface

### PR DESCRIPTION
**Pull request by StrikerRUS**
Fix compilation warnings like the following one
```
C:\Users\runneradmin\RtmpMzXGiG\R.INSTALL11384d93526b\lightgbm\src\src\lightgbm_R.cpp(670,3): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\Users\runneradmin\RtmpMzXGiG\R.INSTALL11384d93526b\lightgbm\src\build\_lightgbm.vcxproj]
```

Checked all `Rf_asInteger` and `INTEGER` calls and tried to bring data types in the consistency with original ones from 
https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/c_api.h.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
Cannot verify proposed changes due to
```
Setting up MiKTeX
miktexsetup.exe: Couldn't connect to server
miktexsetup.exe: Data: code="7", url="https://api2.miktex.org/hello"
```
and those compilation warnings were presented only in MSVC jobs. So leaving this PR in a draft for some time to let MiKTeX get healthy.

**Comment by jameslamb** [comment]
oh no! I can at least pull this PR and test things in my local environment with R. Hopefully the MiKTeX issues are resolved quickly this time :grimacing:

**Comment by StrikerRUS** [comment]
Thank you very much! I remember you don't have an easy access to Windows environment. I think there is no rush at all.

**Comment by StrikerRUS** [comment]
Ha, look! MSVC R-package jobs are already green! Let me check logs right now then.

**Comment by StrikerRUS** [comment]
Tail ( because there are dozens of warnings from Eigen library) of the compilation logs from current `master`'s `r-package (windows-2016, MSVC, R 3.6, cmake)` CI job:
```
  tree_learner.cpp


  voting_parallel_tree_learner.cpp


  c_api.cpp


  lightgbm_R.cpp


C:\Users\runneradmin\RtmpaswVvL\R.INSTALL116c16fe3eaf\lightgbm\src\src\lightgbm_R.cpp(677): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\Users\runneradmin\RtmpaswVvL\R.INSTALL116c16fe3eaf\lightgbm\src\build\_lightgbm.vcxproj]


C:\Users\runneradmin\RtmpaswVvL\R.INSTALL116c16fe3eaf\lightgbm\src\src\lightgbm_R.cpp(681): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\Users\runneradmin\RtmpaswVvL\R.INSTALL116c16fe3eaf\lightgbm\src\build\_lightgbm.vcxproj]


C:\Users\runneradmin\RtmpaswVvL\R.INSTALL116c16fe3eaf\lightgbm\src\src\lightgbm_R.cpp(700): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\Users\runneradmin\RtmpaswVvL\R.INSTALL116c16fe3eaf\lightgbm\src\build\_lightgbm.vcxproj]


C:\Users\runneradmin\RtmpaswVvL\R.INSTALL116c16fe3eaf\lightgbm\src\src\lightgbm_R.cpp(704): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\Users\runneradmin\RtmpaswVvL\R.INSTALL116c16fe3eaf\lightgbm\src\build\_lightgbm.vcxproj]


     Creating library C:/Users/runneradmin/RtmpaswVvL/R.INSTALL116c16fe3eaf/lightgbm/src/Release/lib_lightgbm.lib and object C:/Users/runneradmin/RtmpaswVvL/R.INSTALL116c16fe3eaf/lightgbm/src/Release/lib_lightgbm.exp


  _lightgbm.vcxproj -> C:\Users\runneradmin\RtmpaswVvL\R.INSTALL116c16fe3eaf\lightgbm\src\Release\lib_lightgbm.dll


Found library file: C:\Users\runneradmin\RtmpaswVvL\R.INSTALL116c16fe3eaf/lightgbm/src/Release/lib_lightgbm.dll to move to D:/a/LightGBM/LightGBM/RLibrary/00LOCK-lightgbm/00new/lightgbm/libs/x64

Removing 'build/' directory
```

And the same from this PR:
```
  tree_learner.cpp


  voting_parallel_tree_learner.cpp


  c_api.cpp


  lightgbm_R.cpp


     Creating library C:/Users/runneradmin/RtmpSU9vCA/R.INSTALLa1c49706a09/lightgbm/src/Release/lib_lightgbm.lib and object C:/Users/runneradmin/RtmpSU9vCA/R.INSTALLa1c49706a09/lightgbm/src/Release/lib_lightgbm.exp


  _lightgbm.vcxproj -> C:\Users\runneradmin\RtmpSU9vCA\R.INSTALLa1c49706a09\lightgbm\src\Release\lib_lightgbm.dll


Found library file: C:\Users\runneradmin\RtmpSU9vCA\R.INSTALLa1c49706a09/lightgbm/src/Release/lib_lightgbm.dll to move to D:/a/LightGBM/LightGBM/RLibrary/00LOCK-lightgbm/00new/lightgbm/libs/x64

Removing 'build/' directory
```

**Comment by jameslamb** [comment]
> I remember you don't have an easy access to Windows environment. I think there is no rush at all.

Ha yes, I have a laptop from 2014 running Windows 10. The only things I have on it are things for use on this project: Visual Studio, CMake, git, RStudio, R, and Rtools, but it usually takes 20-30 minutes of installing updates when I turn it on, just because I use it so infrequently.

**Review by jameslamb — APPROVED** [review]
This is a nice cleanup, thank you! I checked logs and don't see these warnings any more.

By the way, this made me think. We should have done this a LONG time ago and I apologize for not doing it sooner...could you add your name to the list of co-authors at https://github.com/microsoft/LightGBM/blob/c629cb0b6bd2830894b710cbd4d8241b82ac3105/R-package/DESCRIPTION? Up to you if you'd like to do it in this PR or a separate one, either is ok with me.

**Comment by StrikerRUS** [comment]
> could you add your name to the list of co-authors

Oh, thank you!
Could you please advise what type of `role` should I choose? `ctb`?

> "ctb"
(Contributor) Use for authors who have made smaller contributions (such as code patches etc.) but should not show up in the package citation.

**Comment by jameslamb** [comment]
@StrikerRUS I would support either `aut` or `ctb`, whichever you are more comfortable with.

I think you have made more contributions to the R package than others who are already listed as `aut` in that file, and that `aut` is more appropriate.

From https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf

> "aut" (Author): Full authors who have made substantial contributions to the package and
should show up in the package citation.

**Pull request merged**
