### PR TITLE
chore: update dataset_loader.cpp

### PR DESCRIPTION
**Pull request by eltociear**
intial -> initial

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
thanks very much for taking the time to contribute! 

I found a few more cases of this particular typo:

```shell
git grep intial
```

Could you please fix those too?

**Comment by borchero** [comment]
@jameslamb we could think about adding [typos](https://github.com/crate-ci/typos) as a pre-commit hook. It minimizes false positives by using a list of well-known typos rather than defining a dictionary of valid words :smile:

**Comment by jameslamb** [comment]
@borchero oh very cool, I hadn't seen that before! Let's try it, it looks great. Could you put up a separate PR?

I'll merge this one as-is without waiting to fix the other couple uses of `intial`, so @eltociear can get their first contribution here and so we don't have to wait on this to add that pre-commit check.

**Review by jameslamb — APPROVED** [review]

**Comment by jameslamb** [comment]
thanks for taking the time to contribute, come back any time!

**Pull request merged**
