### PR TITLE
[cmake] switch to FindCUDAToolkit

### PR DESCRIPTION
**Pull request by characat0**
Cmake 3.17 introduced FindCUDAToolkit and deprecated FindCUDA, when cross compiling on linux, we found some weird behaviour, like having to run two or even three configure steps (https://github.com/JuliaPackaging/Yggdrasil/pull/8593 with LightGBM for Julia) (https://github.com/JuliaPackaging/Yggdrasil/pull/4554#discussion_r831155780, Torch had the same issue).
Switching to FindCUDAToolkit should make this easier.

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Thank you so much for this! I strongly support this change.

As it says in https://cmake.org/cmake/help/latest/module/FindCUDA.html

> To find and use the CUDA toolkit libraries manually, use the [FindCUDAToolkit](https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#module:FindCUDAToolkit) module instead [of `FindCUDA`]. It works regardless of the CUDA language being enabled.

**Comment by jameslamb** [comment]
Double-checked the build logs and this looks like it's working great.

```text
...
-- The CUDA compiler identification is NVIDIA 11.8.89
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
...
-- Found CUDAToolkit: /usr/local/cuda/include (found suitable version "11.8.89", minimum required is "11.0") 
...
[2/74] Building CUDA object CMakeFiles/histo_16_64_256-fulldata_sp_const.dir/src/treelearner/kernels/histogram_16_64_256.cu.o
[3/74] Building CXX object CMakeFiles/lightgbm_objs.dir/src/boosting/prediction_early_stop.cpp.o
[4/74] Building CUDA object CMakeFiles/histo_16_64_256_sp.dir/src/treelearner/kernels/histogram_16_64_256.cu.o
[5/74] Building CUDA object CMakeFiles/histo_16_64_256_sp_const.dir/src/treelearner/kernels/histogram_16_64_256.cu.o
[6/74] Building CUDA object CMakeFiles/histo_16_64_256-fulldata_sp.dir/src/treelearner/kernels/histogram_16_64_256.cu.o
...
```

([build link](https://github.com/microsoft/LightGBM/actions/runs/9120186718/job/25077071630?pr=6457))

Based on that, all the other passing CI, and my own understanding of `FindCUDA()` vs. `FindCUDAToolkit()`, I'm confident merging this.

@shiyu1994 if you come back to this and disagree please let me know and we can change / revert it before the release (#6439).

**Comment by jameslamb** [comment]
@characat0 thanks again, come back and contribute any time!

**Comment by characat0** [comment]
Thanks for remembering @jameslamb, always a pleasure

**Pull request merged**
