### PR TITLE
[docs] [ci] encourage use of `cmake --build`

### PR DESCRIPTION
**Pull request by jameslamb**
Contributes to #6350, and just generally to the goal of making it easier to develop against LightGBM.

Proposes replacing this pattern:

```shell
mkdir build
cd build
cmake -DSOME_OPTION=ON -DOTHER_OPTION=OFF ..
make -j2 _lightgbm
```

with this

```shell
cmake -B build -S . -DSOME_OPTION=ON -DOTHER_OPTION=OFF
cmake --build build --target _lightgbm -j2
```

### Benefits of this change

* simpler to read and write (no worrying about `mkdir` vs. `mkdir -p`, or `cd`-ing to the right place and passing a path like `..`)
* works regardless of the generator chosen (e.g. you could switch from `-G "Unix Makefiles"` to `-G "Ninja"` and not need to change the build command)

### Notes for Reviewers

In case you're not familiar with this pattern in CMake, see the following:

* https://cliutils.gitlab.io/modern-cmake/chapters/intro/running.html
* https://stackoverflow.com/questions/71723171/cmake-build-vs-make-what-the-difference

### CODE REVIEW

**Review by borchero — APPROVED** [review]
LGTM but I'm no `cmake` expert :smile:

**Comment by jameslamb** [comment]
Thanks @borchero !

> I'm no `cmake` expert

Let's get one more review from @shiyu1994  / @guolinke

**Comment by guolinke** [comment]
one quick question: can we  use `make` to build after this change?

**Comment by jameslamb** [comment]
> can we use make to build after this change?

Definitely! This would work:

```shell
cmake -B build -S .
make -j2 -C build _lightgbm
```

The `cmake --build` form is just slightly more general... it'll work regardless of what generator you chose. Like this:

```shell
cmake -B build -S .
cmake --build build

cmake -B build -S . -G Ninja
# this still works
#
# otherwise, would have to do 'ninja ...'
cmake --build build
```

**Review by guolinke — APPROVED** [review]

**Comment by jameslamb** [comment]
Thank you both!

**Pull request merged**
