### PR TITLE
[docs] generate parameters description from config file. Stage 2

### PR DESCRIPTION
**Pull request by StrikerRUS**
This is continuation of #1409.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@guolinke It seems that with new config file this check was lost
https://github.com/Microsoft/LightGBM/blob/497e60ed144007d051bcdfc8bdb36d4f2f5ff681/src/io/config.cpp#L307

**Comment by guolinke** [comment]
@StrikerRUS 
it is moved to https://github.com/Microsoft/LightGBM/blob/master/src/io/config.cpp#L174-L176

**Comment by StrikerRUS** [comment]
@guolinke I'm not sure this is fair replacement of previous check. I mean, at present there is no check if both `valid_data_filenames` and `valid` are specified by user.

**Comment by guolinke** [comment]
@StrikerRUS got it, we can add this checking at that place (config.cpp) too.

**Comment by StrikerRUS** [comment]
@guolinke Please take a look to new commits:
added missed `CHECK` into `config,cpp` and aliases in **Core Parameters** section.
Fixed #1412.

**Pull request merged**
