### PR TITLE
[python][ci] start to support Python 3.7

### PR DESCRIPTION
**Pull request by StrikerRUS**
GPU task fails with Python 3.7. I suppose it's due to the miss of the `boost` library for py37 at conda.

Drop Python 3.4 task as misleading because there are no packages for it at conda and conda silently replaces `3.4 -> 3.7` ([log](https://travis-ci.org/Microsoft/LightGBM/jobs/415410861)) in this case (Travis scenario). Appveyor has pinned Miniconda versions and in this case conda doesn't replace missed version with the newest one, but simply crashes:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.4*
  - python-graphviz -> python 3.5*
Use "conda info <package>" to see the dependencies for each package.
Command exited with code 1
```

### CODE REVIEW

**Comment by henry0312** [comment]
Hum, why not test with both Python 3.6 and 3.7?

**Comment by StrikerRUS** [comment]
@henry0312 Sorry, didn't get it. Python 3.6 is tested here:
```
TASK=gpu METHOD=pip PYTHON_VERSION=3.6
```

**Comment by henry0312** [comment]
@StrikerRUS Isn't a test with cpu and Python 3.6 needed?

**Comment by StrikerRUS** [comment]
What do you think about such change?
```
TASK=regular PYTHON_VERSION=3.6
```

Python 3.7 will be evaluated in `bdist` tsk

**Comment by henry0312** [comment]
This depends on which versions we have more priority over.
As for me, I prefer `TASK=regular PYTHON_VERSION=3.6` until release of Python 3.7.1.

**Comment by StrikerRUS** [comment]
Is it OK now?

**Pull request merged**
