### PR TITLE
[ci][R-package] fix cleanup permissions

### PR DESCRIPTION
**Pull request by StrikerRUS**
From RTD builds
```
Warning: file 'lightgbm/cleanup' did not have execute permissions: corrected
```

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
This failure in the cmake builds:

```
** using staged installation
** libs
Warning: no source files found
```

Could be fixed by adding `cleanup` to this list, I think: https://github.com/microsoft/LightGBM/blob/master/build_r.R#L128

**Comment by StrikerRUS** [comment]
OK, this change breaks every build. So weird, but I have no time to dig deeper. Closing, that original warning doesn't look scary.

**Comment by StrikerRUS** [comment]
@jameslamb Ah, so nice timing for comment! But you was 0.00001sec faster! 😄

**Comment by jameslamb** [comment]
Haha no problem. I can open another PR to remove that warning some time this week. I have some time to experiment with it.

**Comment by StrikerRUS** [comment]
@jameslamb Thanks! I think it's suuuper minor 🙂

**Pull request closed without merging**
