### PR TITLE
[docs] Added the links to the libraries used.

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@KOLANICH Can you please sign the CLA?

Also, please see this: https://github.com/Microsoft/LightGBM/blob/master/docs/GPU-Targets.rst#gpu-targets-table (a note for the table) and fix markdown to make Travis happy.

**Comment by KOLANICH** [comment]
>On Windows, OpenCL is included in AMD graphics driver.

Yes, but

1 In my case OpenCL.dll from driver lacked some exported functions, so there were problems with linking and working. After I have replaced OpenCL.dll in %SYSTEM32% with the one from APP SDK, everything started working.
2 For compilation https://github.com/KhronosGroup/OpenCL-Headers can be used, though I still prefer APP SDK, because it is shipped with a compiler and examples.

> AMD APP SDK is deprecated.

OpenCL itself is dying. It's inconvenient to use (manual setup, though there are frameworks doing this for us), it's deprecated by Apple, it's not supported by most of computation networks frameworks, new implementations of CUDA for non-NVIDIA GPUs target Vulkan rather than OpenCL.

**Comment by StrikerRUS** [comment]
@KOLANICH Thanks a lot for sharing your valuable experience and information! There is a separate open [issue](#768) for GPU-version improvements.

**Comment by StrikerRUS** [comment]
ping @huanzhang12

**Comment by KOLANICH** [comment]
>It is likely to be inside the mingw installation folder (I don't have Windows machine at this time so I cannot verify).

They can be unpacked anywhere, but one will have to provide the paths to them into the corresponding CMake variables. Everything is as usual.

**Comment by huanzhang12** [comment]
@KOLANICH sounds good. Could you just add a sentence on that? Just tell the users to set the CMAKE path variables according to the unpacked directory.

**Comment by KOLANICH** [comment]
This is usually applied not only to Boost, but to all third-party libs having a CMake module to be discovered.

**Comment by KOLANICH** [comment]
>is there any problem with it?

* The page doesn't work without JS enabled. Knowing M$ I don't want to enable JS on it.
* Why should I? MIT license is permissive enough, so no objection to distribute my contribution under it. 
* I strongly dislike dealing with any legal documents and prefer not to sign any.

So

>Can you please sign the CLA?

I'm sorry, but no. I don't care about copyright as much as needed to keep me out of any kegal trouble, and wish it to be abolished, so feel free to close the PR and add the links and everything else you feel needed yourself from your account and your name, I don't object, act as if my contribution was under [CC0](https://creativecommons.org/publicdomain/zero/1.0/). If my contribution is needed, it would be added anyway without any CLAs. If it is not needed, it is a bad idea to merge it.

**Comment by StrikerRUS** [comment]
@KOLANICH Got it! Thanks for the explanation.
Unsigned CLA doesn't allow maintainers to merge a PR:
image

ping @guolinke @chivee for the situation around the CLA.

**Comment by StrikerRUS** [comment]
ping @guolinke

**Comment by guolinke** [comment]
Thanks so much and understand.
However, we cannot merge the PR without CLA, as I cannot represent Microsoft to make this decision... 😢

**Comment by Laurae2** [comment]
@guolinke We can recreate the PR on our side as mentioned by @KOLANICH.

**Comment by StrikerRUS** [comment]
Doesn't work, still waiting the CLA. I've reopened this PR from my account: #1962.

**Pull request closed without merging**
