### PR TITLE
[MRG] [python] check params for num_boost_round & early_stopping_rounds

### LINKED ISSUE #793: early_stopping_rounds is ignored in python interface when specified via parameters dict
The parameter early_stopping_rounds is ignored when it is set via the parameters dictionary but it works fine when it is explicitly specified in the call lgb.train. I think this should be fixed or the documentation needs a note that this parameter is ignored in the python interface (like the note for num_iterations in http://lightgbm.readthedocs.io/en/latest/Parameters.html)

Here is a code example:

```
import lightgbm as lgb
import numpy as np
import pandas as pd

n=1000
X = np.random.randint(1000, size=(n,2))
y = X[:,0]+X[:,1] + np.random.normal(size=n)

Xtrain, ytrain = X[:int(.5*n),:], y[:int(.5*n)]
Xval, yval = X[int(.5*n):,:], y[int(.5*n):]

ds_train = lgb.Dataset(Xtrain, ytrain)
ds_val = lgb.Dataset(Xval, yval)

params = {'objective':'regression_l2',  'metric':'rmse', 'learning_rate':.01,'early_stopping_rounds':10}
gbm = lgb.train(params, ds_train, valid_sets=[ds_val, ds_train], categorical_feature=[1],verbose_eval=20,num_boost_round=1000)
print("=============================================")
gbm = lgb.train(params, ds_train, valid_sets=[ds_val, ds_train], categorical_feature=[1],verbose_eval=20,num_boost_round=1000,early_stopping_rounds=10)

```

### PR DESCRIPTION
**Pull request by wxchan**
fix #793

### CODE REVIEW

**Comment by guolinke** [comment]
@wxchan 
current problems of categorical feature in python:
- used by param dict
  + cannot auto converting from feature name to feature indices
- used by argument of Dataset or lgb.train
  + cannot accept the multi-str form, (like `"1,2,3"`)

I think it is better to unify these parameters.

**Comment by wxchan** [comment]
@guolinke I think it can be done in another pr.

**Comment by guolinke** [comment]
@Laurae2 can you help to enable this feature in R ?

**Comment by Laurae2** [comment]
@guolinke Yes when I'll have time tomorrow I think.

**Pull request merged**
