### PR TITLE
[python][docs] reworked predict method in sklearn wrapper and docs improvements

### PR DESCRIPTION
**Pull request by StrikerRUS**
Inspired by [this](https://github.com/Microsoft/LightGBM/issues/1340#issuecomment-385902024).

While writing tests I've found some inconsistency between default value of param in C++ code and sklearn wrapper:
```
bagging_freq, default=0, type=int, alias=subsample_freq

subsample_freq : int, optional (default=1)
```

Also sklearn description says: "Frequence of subsample, <=0 means no enable.", but on C++ side there is a validation `CHECK(bagging_freq >= 0);`

@guolinke Which side should be fixed?

Even after bringing the consistency in `subsample_freq` tests fail. For instance, after first `predict` we have
```
res_engine[0][0]
>>> 0.0013241289219269466
res_sklearn[0][0]
>>> 0.0013241290058445348
```

Also, is there any way to test `pred_parameter` works? As I understand, there is no validation for keywords in `Booster.predict()`.

### CODE REVIEW

**Comment by guolinke** [comment]
Thanks @StrikerRUS , just fix the `bagging_freq`. 
Do you try to use the same `num_threads` (n_jobs) when test bagging ? 
for the `pred_parameter`, i think there are num_threads, and some parameters for the early stopping in prediction.

**Comment by StrikerRUS** [comment]
@guolinke 

>just fix the bagging_freq.

Sorry, didn't understand. Which default value is correct for `bagging_freq`: 0 or 1?

>Do you try to use the same num_threads (n_jobs) when test bagging ?

Unfortunately, even without bagging and with one thread results are the same as were:
```
import lightgbm as lgb
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                    test_size=0.2, random_state=42)

gbm = lgb.train({'objective': 'multiclass',
                 'num_class': 3,
                 'subsample_freq': 0,
                 'verbose': -1,
                 'num_threads': 1},
                lgb.Dataset(X_train, y_train))
clf = lgb.LGBMClassifier(subsample_freq=0,
                         verbose=-1,
                         n_jobs=1).fit(X_train, y_train)

res_engine = gbm.predict(X_test, pred_parameter={'num_threads': 1})
res_sklearn = clf.predict_proba(X_test, other_params={'num_threads': 1})

np.testing.assert_allclose(res_engine, res_sklearn)  # Fails
```

**Comment by StrikerRUS** [comment]
@guolinke Another one inconsistency:
https://github.com/Microsoft/LightGBM/blob/04d37f9b38cb851c5201081c2b8289eb0ecbca02/src/io/config.cpp#L457

description:
```
max_drop, default=50, type=int
   <=0 means no limit
```

**Comment by guolinke** [comment]
@StrikerRUS 
Default value is `0`. 
Can you try the binary or regression ?

**Comment by StrikerRUS** [comment]
@guolinke 
>Default value is 0.

Thanks! Got it.

>Can you try the binary or regression ?

Sure, will do it later today.

**Comment by StrikerRUS** [comment]
@guolinke With regression task test is passed. But it's because by default `rtol=1e-7` and the difference is in 8th digit:
```
res_engine[0]
>>> 26.02584259652531
res_sklearn[0]
>>> 26.025842568222647
```

Test code:
```
import lightgbm as lgb
import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

boston = load_boston()
X_train, X_test, y_train, y_test = train_test_split(boston.data, boston.target,
                                                    test_size=0.2, random_state=42)

gbm = lgb.train({'objective': 'regression',
                 'subsample_freq': 0,
                 'verbose': -1,
                 'num_threads': 1},
                lgb.Dataset(X_train, y_train))
clf = lgb.LGBMRegressor(subsample_freq=0,
                         verbose=-1,
                         n_jobs=1).fit(X_train, y_train)

res_engine = gbm.predict(X_test, pred_parameter={'num_threads': 1})
res_sklearn = clf.predict(X_test, other_params={'num_threads': 1})

np.testing.assert_allclose(res_engine, res_sklearn, rtol=1e-9)  # Fails
```

I think it's abnormal behavior and something is wrong...

Also please take a look to shapes of return values in docstrings- I'm not sure about them.

**Comment by guolinke** [comment]
@StrikerRUS 
I think there are still some parameter inconsistent. 
can you print `params` in this function ? https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L1266

**Comment by guolinke** [comment]
@StrikerRUS I found the problem is caused by `learning_rate`.
when set `learning_rate=0.1` in lgb.train, they are the same.
```python
import lightgbm as lgb
import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

boston = load_boston()
X_train, X_test, y_train, y_test = train_test_split(boston.data, boston.target,
                                                    test_size=0.2, random_state=42)

gbm = lgb.train({'objective': 'regression',
                 'subsample_freq': 0,
                 'verbose': -1,
                 'learning_rate': 0.1,
                 'num_threads': 1},
                lgb.Dataset(X_train, y_train))
clf = lgb.LGBMRegressor(subsample_freq=0,
                         verbose=-1,
                         n_jobs=1).fit(X_train, y_train)

res_engine = gbm.predict(X_test)
res_sklearn = clf.predict(X_test)

np.testing.assert_allclose(res_engine, res_sklearn, rtol=1e-9)  # Fails
```

**Comment by guolinke** [comment]
@StrikerRUS you can merge from master branch, it should fix this problem.

**Comment by StrikerRUS** [comment]
@guolinke Thanks!
Could you please clarify why the change float -> double solved the problem?

**Comment by guolinke** [comment]
@StrikerRUS 
I think it is because "0.1 != 0.1f" in cpp.

**Comment by guolinke** [comment]
@StrikerRUS now we have `pred_parameter` and `other_params` . I think these naming is confusing. Can we unify them with one naming rule? 
BTW, can we also enable them in **kwargs, without put it in dict parameter ?

**Comment by StrikerRUS** [comment]
Interesting about ` 0.1f != 0.1`… Sure, will try `**kwargs`.

**Comment by StrikerRUS** [comment]
>BTW, can we also enable them in **kwargs, without put it in dict parameter ?

Done!

**Pull request merged**
