### PR TITLE
[python-package] Add `progress_bar` callback using tqdm

### PR DESCRIPTION
**Pull request by 34j**
Use tqdm to display training progress and metrics and, if necessary, early_stopping results. tqdm does not need to be installed and is compatible with the existing code.

Example:
```python
X_train, X_test, y_train, y_test = train_test_split(...)
gbm = lgb.LGBMRegressor()
early_stopping_callback = lgb.early_stopping(stopping_rounds=50)
callback = lgb.progress_bar("rich", early_stopping_callback=early_stopping_callback)
gbm.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    callbacks=[early_stopping_callback, callback],
)
```

image

```python
X_train, X_test, y_train, y_test = train_test_split(...)
gbm = lgb.LGBMRegressor()
early_stopping_callback = lgb.early_stopping(stopping_rounds=50)
callback = lgb.progress_bar(early_stopping_callback=early_stopping_callback)
gbm.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    callbacks=[early_stopping_callback, callback],
)
```

image
I tried `sys.stderr.flush()` and so on, but the output was inevitably broken when using `tqdm.std.tqdm`.

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks for the suggestion! But I don't support adding this much complexity and maintenance burden to the project in exchange for a progress bar.

I'd welcome the addition of this callback as *documentation*, like in https://github.com/microsoft/LightGBM/tree/master/examples/python-guide, but not as an addition to the project's public API which needs to be maintained.

@jmoralez what do you think?

**Comment by jameslamb** [comment]
> there are so many LightGBM extension packages in this world that users get confused

What is this a reference to? Can you share some links to what you mean by "LightGBM extension packages"?

**Comment by jameslamb** [comment]
> the Black formatting just adds lines and does not change the existing code

`lightgbm` does not `black`. I'm not sure what this comment is referring to.

> I don't think adding documentation or merging would make any difference in the maintenance burden

This is not true. Here are some examples of things that could be avoided if this change were only made in `examples/`:

* it wouldn't be necessary to make the callback serializable with `pickle`
* it wouldn't be necessary to hardcode a list of specific `tqdm` classes
* `lightgbm` would not pick up a new optional dependency on `tqdm` and need to support a wide range of versions of that library
* installing `types-tqdm` in CI wouldn't be necessary

---

Nothing in `lightgbm` makes the use of a callback such as the one proposed impossible today.

This PR is proposing going further than "make it possible", instead proposing "please make it a new part of the public API of the package", which comes with the maintenance burden of continuing to guarantee that the code works in the wide range of operating systems and Python versions LightGBM supports.

I am not convinced that the inconvenience of not having such code available via `pip install lightgbm` is so great that this should be added to the library and maintained here.

If you choose to answer the request in https://github.com/microsoft/LightGBM/pull/5867#pullrequestreview-1414652160 for some specific examples of the claim "there are so many LightGBM extension packages in this world that users get confused", that might change my opinion.

If another maintainer like @jmoralez makes a convincing case for adding something like this to the library, that might change my opinion.

But as of now, I am -1 on including this code in LightGBM.

I'd *consider* adding a simpler version of it (for example, without the hard-coded list of `tqdm` classes) in `examples/`.

**Comment by 34j** [comment]
I have given up on PR and created a package that addresses #5867, #4805, #3313 / #5808 at once and would appreciate if you could add it to the examples.

**Comment by jameslamb** [comment]
> I have given up on PR and created a package

Alright, I'll close this.

> would appreciate if you could add it to the examples. https://github.com/34j/lightgbm-callbacks

At this time, it doesn't look to me like that project is being used by many people (according to https://pypistats.org/packages/lightgbm-callbacks) or that it's doing something so significantly different from what's possible with LightGBM that it should be added to https://github.com/microsoft/LightGBM#external-unofficial-repositories.

If that changes in the future, I'd happily consider a PR to add a mention of it to https://github.com/microsoft/LightGBM#external-unofficial-repositories.

If you'd like to answer the question I posed at https://github.com/microsoft/LightGBM/pull/5867#issuecomment-1536241916 with several examples, I'd also consider a callbacks-for-the-Python-package-specific section of the project's documentation at https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst.

**Pull request closed without merging**
