### PR TITLE
[ci] fix check-docs error with AMD support website (fixes #3529)

### LINKED ISSUE #3529: [ci] broken link to AMD docs
For at least the last two days, I have seen the `check-docs` task on Travis persistently failing with this error:

```text
URL        `https://www.amd.com/en/support'
Name       `AMDGPU-Pro'
Parent URL file:///home/travis/build/microsoft/LightGBM/docs/_build/html/GPU-Tutorial.html, line 209, col 69
Real URL   https://www.amd.com/en/support
Check time 60.145 seconds
Result     Error: ReadTimeout: HTTPSConnectionPool(host='www.amd.com', port=443): Read timed out. (read timeout=60)
```

When I try to hit this link from my laptop, I get a 403

```shell
curl -I https://www.amd.com/en/support
```

> Download-Link
HTTP/2 403
server: AkamaiGHost
mime-version: 1.0
content-type: text/html
content-length: 344
expires: Thu, 05 Nov 2020 05:44:11 GMT
date: Thu, 05 Nov 2020 05:44:11 GMT
set-cookie: pmuser_country=us; expires=Thu, 19-Nov-2020 05:44:11 GMT
content-security-policy: frame-ancestors 'self' https://amd.pathfactory.com

But when I navigate to it in a browser, I have no issues.

image

That link is in `GPU-Tutorial`: https://github.com/microsoft/LightGBM/blame/cf69591b68c68a78ea4064e6941b8270b8a00eef/docs/GPU-Tutorial.rst#L194

### Troubleshooting Notes

I did find this discussion that looks related: https://stackoverflow.com/a/36174489/3986677. From other research, seeing `server: AkamaiGHost` makes me think that some security software involved in serving amd.com is rejecting requests from automated tools.

### PR DESCRIPTION
**Pull request by jameslamb**
Trying to fix #3529 .

> URL        `https://www.amd.com/en/support'
Name       `AMDGPU-Pro'
Parent URL file:///home/travis/build/microsoft/LightGBM/docs/_build/html/GPU-Tutorial.html, line 209, col 69
Real URL   https://www.amd.com/en/support
Check time 60.145 seconds
Result     Error: ReadTimeout: HTTPSConnectionPool(host='www.amd.com', port=443): Read timed out. (read timeout=60)

I'm looking at the `linkchecker` configuration options here: https://wummel.github.io/linkchecker/man5/linkcheckerrc.5.html.

~The first thing I'm trying is setting a user-agent to something recognizable and mainstream like `Mozilla/5.0`. If that doesn't work, I'll try explicitly ignoring this link during checking, to unblock all other PRs.~

### CODE REVIEW

**Comment by jameslamb** [comment]
Ok setting user-agents to browser user-agents did not work for me.

Since this broken link does seem to work in browsers, I think we should just ignore it in linkchecker to unblock PRs.

**Comment by jameslamb** [comment]
Ok here are the things I tried in `docs/.linkcheckerrc` that did not fix the issue:

* adding `useragent="Mozilla/5.0"`
* adding `useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6)"`
* adding `.*amd\.com.*` to `ignore`
* setting `sslverify=1`

I think we should just remove this problematic link. It's only a very general link to the AMD support homepage, so I think users will have to probably use a search engine to find the AMDGPU driver download anyway.

**Comment by StrikerRUS** [comment]
Instead of removal we can simply ignore that link. I think it will be better. Refer for example to https://github.com/microsoft/LightGBM/commit/0197dba0613c46316518ef022e18a110025a1c59#diff-d862344dbe4be0e1a0091c9c210380aac53676e2c6f1dbac96ec3904ba38c172.

**Comment by jameslamb** [comment]
> Instead of removal we can simply ignore that link. I think it will be better. Refer for example to [0197dba#diff-d862344dbe4be0e1a0091c9c210380aac53676e2c6f1dbac96ec3904ba38c172](https://github.com/microsoft/LightGBM/commit/0197dba0613c46316518ef022e18a110025a1c59#diff-d862344dbe4be0e1a0091c9c210380aac53676e2c6f1dbac96ec3904ba38c172) (old Intel support page was in our list for some time).

I tried that and it didn't work:  https://github.com/microsoft/LightGBM/pull/3530/commits/54604183ceb91518cf2a39cf8592f16b6ab40d7e

I think maybe because we have a timeout issue, and the "ignore" might be about filtering errors after the fact. Or maybe there's a typo in my commit, let me know if you think that's what happened

**Comment by StrikerRUS** [comment]
>I tried that and it didn't work: 5460418

Are you sure that **all** AMD links are affected by this issue?

Lets just add `https://www.amd.com/en/support` for now and it will allow to unblock our CI. WDYT?

**Comment by jameslamb** [comment]
> > I tried that and it didn't work: [5460418](https://github.com/microsoft/LightGBM/commit/54604183ceb91518cf2a39cf8592f16b6ab40d7e)
> 
> Are you sure that **all** AMD links are affected by this issue?
> 
> Lets just add `https://www.amd.com/en/support` for now and it will allow to unblock our CI. WDYT?

I have no idea but the point I'm making in https://github.com/microsoft/LightGBM/pull/3530#issuecomment-722618817 is that even adding `amd.com` to the config **still did not fix the `check-docs` task**

**Comment by StrikerRUS** [comment]
I believe there was a mistake in regex for AMD site, because this one I've just tested filters fine: 
https://github.com/microsoft/LightGBM/commit/c0daa03911e508b1ae67ade876f68e606318df95
https://travis-ci.org/github/microsoft/LightGBM/jobs/741729670

**Comment by jameslamb** [comment]
interesting! Maybe it's a bug in linkchecker that your regex can't start with a `.*`.

mine (failed): `.*/amd\.com.*`
yours (successful): `http.*amd.com/.*`

Anyway, thanks! I'll put the link back and make this change right now. I think once this is merged, the next PR we should merge is https://github.com/microsoft/LightGBM/pull/3523 to help with other CI.

**Review by StrikerRUS — APPROVED** [review]
Thanks!

**Comment by StrikerRUS** [comment]
Probably the thing was in `\.`...

**Comment by jameslamb** [comment]
We use that escaping in the other line in that config though

`pythonapi/lightgbm\..*\.html.*`

**Comment by jameslamb** [comment]
so many CI problems! These are timeouts from `conda`

image

**Pull request merged**
