### PR TITLE
Add Logo to readme

### PR DESCRIPTION
**Pull request by guolinke**

### CODE REVIEW

**Comment by guolinke** [comment]
it looks like
image

**Comment by guolinke** [comment]
in black mode (achieving by changing the background color in Browser), by using the black font 

image

**Review by StrikerRUS — APPROVED** [review]
Finally we have a logo! Woohoo! 🎉

**Comment by StrikerRUS** [comment]
@guolinke Please upload source files of the logo.

**Comment by guolinke** [comment]
@StrikerRUS 
What is "source"? We have the high-resolution png logo in the repo.

**Comment by StrikerRUS** [comment]
> What is "source"?

I meant vector image from which `png` files were generated. I see you've posted one in Slack. Thank you!

**Pull request merged**
