### PR TITLE
added feature importance to JSON dump 

### PR DESCRIPTION
**Pull request by StrikerRUS**
Part of #2604.

Implementation is copied from `SaveModelToString` without sorting.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@guolinke WDYT about allowing to specify feature importance type in dump / save function? Seems that it will break the existing compatibility for C API.

**Comment by guolinke** [comment]
@StrikerRUS could you explain it with more details?

**Comment by StrikerRUS** [comment]
@guolinke I mean, at present, feature importance is always dumped with `importance_type=0`:
https://github.com/microsoft/LightGBM/blob/edb9149c13fe5a901898db525c22b441f0db6e49/src/boosting/gbdt_model_text.cpp#L63
https://github.com/microsoft/LightGBM/blob/edb9149c13fe5a901898db525c22b441f0db6e49/src/boosting/gbdt_model_text.cpp#L333

Will be it useful to allow to specify importance type during saving / dumping model?

**Comment by guolinke** [comment]
As we have standalone FeatureImportance API
https://github.com/microsoft/LightGBM/blob/516bd37a28a0dfa7c2bc4a24587dbbcb8a697eb2/src/c_api.cpp#L1563-L1574

I think adding `importance_type` to dump/save is not very necessary.

**Comment by StrikerRUS** [comment]
Agree! Especially, given that it requires C API breakage.

**Comment by StrikerRUS** [comment]
> WDYT about allowing to specify feature importance type in dump / save function? Seems that it will break the existing compatibility for C API.

Implemented in #3220.

**Pull request merged**
