### PR TITLE
[refactor] Reduce code duplication in c_api.cpp

### PR DESCRIPTION
**Pull request by AlbertoEAF**
Remove code duplication in c_api.cpp through use of templates.

### CODE REVIEW

**Comment by AlbertoEAF** [comment]
Can someone review? :)

**Comment by AlbertoEAF** [comment]
I wonder if we should move the helper methods to a new file `c_api_helpers.cpp` + `c_api_helpers.h` and declare only the methods that we need from such helpers as the CSC_RowIterator and not the auxiliary methods to implement those such as the low level template methods.

**Review by AlbertoEAF — COMMENTED** [review]
I wonder if we should add those 2 extra files (helpers apart from public API methods), or keep everything in the same file as it is - simpler, and less code.

**Comment by AlbertoEAF** [comment]
I thought again and don't see splitting this into separate files as that useful.

@guolinke can you review?

**Comment by jameslamb** [comment]
Could you please update this PR to the latest `master`? We recently learned that our CI was missing one of the checks that replicates CRAN (#3585 ), and added a new R CI job (#3588). Sorry for the inconvenience.

**Review by guolinke — APPROVED** [review]
LGTM

**Pull request merged**
