### PR TITLE
[python-package] prefix c_int_array and c_float_array with _

### PR DESCRIPTION
**Pull request by OmarManzoor**
Contributes to #5313

### CODE REVIEW

**Comment by jameslamb** [comment]
closing and re-opening to try to get the warning from the CLA bot to go away (sorry @OmarManzoor ).

**Comment by jameslamb** [comment]
@OmarManzoor , can you please add a comment exactly like this one? 

https://github.com/microsoft/LightGBM/pull/5545#issuecomment-1280395907

I'm so sorry about that. We don't control the CLA bot (it is something Microsoft-wide, configured by people at Microsoft who don't work on this repo).

I hope that after you do this, you won't have to again.

**Review by jameslamb — APPROVED** [review]
Thanks very much for doing this!

**Comment by OmarManzoor** [comment]
@microsoft-github-policy-service agree

**Comment by jameslamb** [comment]
Thanks @OmarManzoor ! I'll manually re-run the failing CI job (not related to this PR's changes) and then merge this.

**Pull request merged**
