### PR TITLE
[in progress] c_api

### PR DESCRIPTION
**Pull request by guolinke**
In progress now. Open this to discuss during development.

### CODE REVIEW

**Comment by chivee** [comment]
refer to #34 for discussion

**Comment by chivee** [comment]
@guolinke , please don't mix function naming with camelCase and under_score_case.

**Comment by guolinke** [comment]
@chivee It seems most of export functions have a prefix of "XXX_" .. 
also refer to https://github.com/Microsoft/Multiverso/blob/master/include/multiverso/c_api.h#L29

**Comment by chivee** [comment]
@guolinke , could you make this an dev branch, so that I can reach the code too.

**Pull request merged**
