### PR TITLE
Fix PR #1879

### PR DESCRIPTION
**Pull request by Laurae2**
This PR fixes PR #1879.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@Laurae2 Please run [this file](https://github.com/microsoft/LightGBM/blob/master/helpers/parameter_generator.py) locally to update docs in rst format.

Refer to https://github.com/microsoft/LightGBM/tree/master/docs#documentation

> List of parameters and their descriptions in Parameters.rst is generated automatically from comments in config file by this script.

**Comment by StrikerRUS** [comment]
Echoing meaningful comment here from the original PR
> https://github.com/Microsoft/LightGBM/blob/59f10453dc4a3841339702524124063fa5db6870/src/treelearner/serial_tree_learner.cpp#L351
BTW, should it be unsigned?

**Comment by StrikerRUS** [comment]
@Laurae2 Please update the description here too:
https://github.com/microsoft/LightGBM/blob/1c27a15e42f0076492fcc966b9dbcf9da6042823/python-package/lightgbm/sklearn.py#L155

**Comment by Laurae2** [comment]
@StrikerRUS fixed

**Comment by StrikerRUS** [comment]
@Laurae2 Thanks! Fix for CI tests is in the latest `master`, please rebase.

**Comment by StrikerRUS** [comment]
What about that comment from original PR?
https://github.com/microsoft/LightGBM/pull/2155#issuecomment-490441325

**Pull request merged**
