### PR TITLE
[python-package] add plot tree

### PR DESCRIPTION
**Pull request by wxchan**
move from #258

### CODE REVIEW

**Comment by wxchan** [comment]
#171

**Comment by run2** [comment]
Hi @wxchan . When I use 
ax = lgb.plot_tree(gbm, tree_index=1, figsize=(20, 8), show_info=['split_gain'])
plt.show()

I am getting this error. Should I open a bug ?

ValueError                                Traceback (most recent call last)
<ipython-input-205-d21302d8c8a2> in <module>()
      9 
     10 print('Plot 84th tree...')  # one tree use categorical feature to split
---> 11 ax = lgb.plot_tree(bst3, tree_index=1, figsize=(20, 8), show_info=['split_gain'])
     12 plt.show()

/usr/local/lib/python3.5/dist-packages/lightgbm/plotting.py in plot_tree(booster, ax, tree_index, figsize, graph_attr, node_attr, edge_attr, show_info)
    416         node_attr=node_attr,
    417         edge_attr=edge_attr,
--> 418         show_info=show_info
    419     )
    420 

/usr/local/lib/python3.5/dist-packages/lightgbm/plotting.py in create_tree_digraph(booster, tree_index, show_info, name, comment, filename, directory, format, engine, encoding, graph_attr, node_attr, edge_attr, body, strict)
    365                          name=name, comment=comment, filename=filename, directory=directory,
    366                          format=format, engine=engine, encoding=encoding, graph_attr=graph_attr,
--> 367                          node_attr=node_attr, edge_attr=edge_attr, body=body, strict=strict)
    368 
    369     return graph

/usr/local/lib/python3.5/dist-packages/lightgbm/plotting.py in _to_graphviz(tree_info, show_info, feature_names, name, comment, filename, directory, format, engine, encoding, graph_attr, node_attr, edge_attr, body, strict)
    290                     format=format, engine=engine, encoding=encoding, graph_attr=graph_attr,
    291                     node_attr=node_attr, edge_attr=edge_attr, body=body, strict=strict)
--> 292     add(tree_info['tree_structure'])
    293 
    294     return graph

/usr/local/lib/python3.5/dist-packages/lightgbm/plotting.py in add(root, parent, decision)
    274                 l_dec, r_dec = 'is', "isn't"
    275             else:
--> 276                 raise ValueError('Invalid decision type in tree model.')
    277             add(root['left_child'], name, l_dec)
    278             add(root['right_child'], name, r_dec)

ValueError: Invalid decision type in tree model.

**Comment by wxchan** [comment]
@run2 I think it's because recently change of categorical features. @guolinke what are current decision types?

**Comment by guolinke** [comment]
@wxchan 
you can search the "GetDecisionType(decision_type_[index], kCategoricalMask)" . I remember it use the lowest bit to represent .

**Comment by run2** [comment]
Hi - resolved by modifying code in plotting.py to 
            if root['decision_type'] == '<=':
                l_dec, r_dec = '<=', '>'
            elif root['decision_type'] == '=':
                l_dec, r_dec = '=', "!="
            else:
                raise ValueError('Invalid decision type in tree model. ' + root['decision_type'] + ' XXX ')

Opened new issue https://github.com/Microsoft/LightGBM/issues/798.

**Pull request merged**
