### PR TITLE
applied isort and black to python code for consistent styling and imports sorting order

### PR DESCRIPTION
**Pull request by zyxue**
A consistent styling and import sorting order improves code readability

This PR just applies two widely used python formatting tools, isort and black, to the python code in lightgbm

https://github.com/PyCQA/isort
https://github.com/psf/black

No code logic should have been changed.

### CODE REVIEW

**Review by jameslamb — COMMENTED** [review]
Thanks for taking the time to contribute to LightGBM!

But this type of PR that touches this much code for only style reasons should be left to maintainers. While investigating issues, we sometimes use the [git blame](https://docs.github.com/en/github/managing-files-in-a-repository/tracking-changes-in-a-file) to see who most recently touched some piece of code, and then sometimes `@` that person for a second opinion. Having a large PR like this that touches many lines for only style reasons would make that more difficult.

We use `pycodestyle` and `pydocstyle` in this project to provide some minimal linting on Python code (https://github.com/microsoft/LightGBM/blob/fd094d2719a04b984b376a665b6c3e5e1aff2967/.ci/test.sh#L60-L61), but have avoided adopting `isort` or `black` so far. If you believe this project would benefit from such changes you are welcome to [open an issue](https://github.com/microsoft/LightGBM/issues) describing why, but I believe it should be a maintainer like @StrikerRUS who applies such changes.

If you're looking for ways to contribute, we'd welcome your help on some of the open issues. The "good first issues" list is a good place to start: https://github.com/microsoft/LightGBM/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22.

I'll leave the final decision on this to @StrikerRUS , but I'm -1 on this change.

**Comment by zyxue** [comment]
>While investigating issues, we sometimes use the git blame to see who most recently touched some piece of code, and then sometimes @ that person for a second opinion. Having a large PR like this that touches many lines for only style reasons would make that more difficult.

I see. I'm refactoring the code mainly to understand it better. I'm trying to get an idea if it's possible to adopt the tree implementation in lightgbm for the [ngboost](https://stanfordmlgroup.github.io/projects/ngboost/) algorithm.

Your concern makes sense to me. Please feel free to close the PR if you think it would make it too difficult to trace down the output of `git blame`.

**Comment by StrikerRUS** [comment]
I'll be happy to see adoption of `isort` for LightGBM's Python codebase! I remember I was willing to do it some years ago...
But it will be better if adoption of `isort` will be in a form of "1 PR - 1 file". It will significantly improve review process.
@zyxue Could you please create an umbrella issue for adopting `isort` with checklist containing every `.py` file that should be refactored. Please refer to https://github.com/microsoft/LightGBM/issues/3732#issuecomment-760985106 as an example. And feel free to prepare first PR.

Speaking about `black`, I'd better stick to `pycodestyle`. `black` is overstrict, IMHO.

@zyxue Thank you very much for your actually already done work!

**Comment by zyxue** [comment]
>black is overstrict, IMHO.
I see. Just share my experience, if the editor is set up to rerun black/isort upon each save, then I don't need to worry much about code formatting anymore and only focus on the code logic. It's actually quite liberating.

Yes, I can try to isort one file at a time.

**Pull request closed without merging**
