### PR TITLE
v3.0.0 release

### PR DESCRIPTION
**Pull request by guolinke**

### CODE REVIEW

**Comment by guolinke** [comment]
@StrikerRUS @jameslamb 
It seems most version field is updated, do I miss anything?

**Comment by jameslamb** [comment]
I don't see any changes, so maybe there is nothing left for this PR?

image

**Comment by guolinke** [comment]
@jameslamb yeah. I can tag the master branch to v3.0.0 directly.

**Comment by jameslamb** [comment]
sounds good! Everything is ready for that for R

**Comment by guolinke** [comment]
@StrikerRUS I uploaded the pypi and nuget package. for the homebrew, I don't know how to update it. could you help with it?

**Comment by StrikerRUS** [comment]
@guolinke 
> for the homebrew, I don't know how to update it. could you help with it?

Sure!

**Comment by StrikerRUS** [comment]
> for the homebrew, I don't know how to update it. could you help with it?
>> Sure!

@ankane just did it. Thank you very much!

https://github.com/Homebrew/homebrew-core/pull/60469

**Comment by ankane** [comment]
np, meant cc you

**Pull request closed without merging**
