### PR TITLE
[ci] fail R macOS CI jobs earlier when installations fail

### PR DESCRIPTION
**Pull request by jameslamb**
#5128 describes an issue where:

* `brew install` of a required dependency fails
* the CI job does not fail
* building LightGBM, running tests, etc. all happen
* a much later step (`R CMD check` for the R package) fails, because it's missing that dependency from Homebrew

This PR proposes adding some `exit -1` calls to the main CI script for for R-package jobs, so that those jobs will fail earlier when such issues occur in the future.

Benefits of this:

* less work required to find the root cause of issues (since the problem will be near the end of logs)
* jobs will exit sooner, meaning less time occupying a spot in the repo's limited GitHub Actions queue (https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits)

### CODE REVIEW

**Comment by jameslamb** [comment]
Going to move this back to "draft" while investigating the latest error

> installer: Error - the package path specified was invalid: '/Users/runner/work/LightGBM/LightGBM/R.pkg'.
Error: Process completed with exit code 255.

But hey, at least in https://github.com/microsoft/LightGBM/runs/5826439843?check_suite_focus=true, `basictex` was installed successfully, so maybe #5128 is fixed!

**Comment by jameslamb** [comment]
😱  it looks like the `R.pkg` we were installing was removed!

```shell
curl -I https://cran.r-project.org/bin/macosx/R-4.1.2.pkg
```

```text
HTTP/1.1 404 Not Found
Date: Tue, 05 Apr 2022 01:51:31 GMT
Server: Apache
Vary: accept-language,accept-charset
Accept-Ranges: bytes
Content-Type: text/html; charset=utf-8
Content-Language: en
```

But because there was no `|| exit -1`  on the line installing it, CI jobs didn't fail.

https://github.com/microsoft/LightGBM/blob/d811f3a074d30924a88aebe93eea66df70ecb7dc/.ci/test_r_package.sh#L79

And those jobs just silently fell back to the R version already available from GitHub Actions (https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md).

For example, look at this `r-package (macOS-10.15, clang, R 4.1, cmake)` job from two days ago: https://github.com/microsoft/LightGBM/runs/5800165206?check_suite_focus=true

R installation failed:

```text
...
installer: Error - the package path specified was invalid: '/Users/runner/work/LightGBM/LightGBM/R.pkg'.
...
```

But the job continued, and you can see that the job used R 4.1.3, the version installed by default by GitHub Actions for this runner ([link](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md)).

```text
* using R version 4.1.3 (2022-03-10)
```

Pushed https://github.com/microsoft/LightGBM/pull/5129/commits/43d60f658d6103c98dcbd516a28fb8ff31489eb6, targeting https://cran.r-project.org/bin/macosx/base/ for R 4.x builds so this doesn't happen again.

**Comment by StrikerRUS** [comment]
yikes!

Thanks for fixing this!

Can this error be related to #4990?

**Review by StrikerRUS — APPROVED** [review]

**Comment by jameslamb** [comment]
> Can this error be related to https://github.com/microsoft/LightGBM/issues/4990?

ah!!! I bet you're right! I can try that later (updating those jobs to `macOS-latest`). I think it's very very likely that they're related.

**Pull request merged**
