### PR TITLE
Allow the minimal feature to 1 in column sampling

### PR DESCRIPTION
**Pull request by guolinke**

### CODE REVIEW

**Comment by guolinke** [comment]
@jameslamb the R's tests are not stable?

**Comment by jameslamb** [comment]
> @jameslamb the R's tests are not stable?

ok this is very bad. @btrotta has been seeing these issues on #3136 too

image

The R tests rely on downloading some LaTeX things from a CTAN mirror at University of Illinois. I pegged it to one mirror because we were getting such inconsistent behavior from the main CTAN download links.

Let me try changing mirrors, sorry for the inconvenience.

**Comment by jameslamb** [comment]
I've opened #3198 to investigate this, looking into it now.

**Comment by jameslamb** [comment]
ok @guolinke I think #3199 will fix it!

**Pull request merged**
