### PR TITLE
dockerfile for cli-only on GPU

### PR DESCRIPTION
**Pull request by rsdmse**
A new dockerfile for CLI-only on GPU that uses multistage build to reduce the final image size from 2.6 GB to 104 MB (base image `nvidia/opencl` instead of `nvidia/cuda`).

The container was benchmarked on our HPC platform (Rivanna cluster, University of Virginia) using [this tutorial](https://lightgbm.readthedocs.io/en/latest/GPU-Tutorial.html#dataset-preparation). It took 33 seconds for 50 iterations on a GPU, compared to 92 seconds without GPU.

See issue #3286 for details.

### CODE REVIEW

**Comment by rsdmse** [comment]
I need to check with my supervisor on #4 of the Agreement.

**Comment by rsdmse** [comment]
How to correct 12072.6 of travis-ci?

**Comment by rsdmse** [comment]
The `distroless` container passed the tutorial with the same performance on our GPU. It may need some further scrutiny by the community since I'm not very familiar with LightGBM. If it works well I can replace `opencl` in this PR with `distroless`.

**Comment by guolinke** [comment]
@rsdmse is this pr WIP?

**Comment by rsdmse** [comment]
@guolinke `docker/gpu/dockerfile-cli.opencl` is ready. I don't know if distroless is of interest. If yes, I can commit another dockerfile `docker/gpu/dockerfile-cli.distroless`.

**Comment by rsdmse** [comment]
We're required to add a line "Copyright (c) 2020 The Rector and Visitors of the University of Virginia" so I'm afraid this won't work with the CLA?

**Comment by rsdmse** [comment]
I guess the easy way is to add a link in the docker README to our rivanna-docker repo (MIT license), if this is of interest.
Sorry I didn't foresee the red tape.

**Comment by StrikerRUS** [comment]
> Or if it's ok to insert an MIT license in the Dockerfile, I can reopen the PR. Just let me know.

I guess it is OK to insert MIT licence in the docker file, especially since LightGBM has MIT licence as well. @guolinke What is your decision?

**Comment by guolinke** [comment]
like the json11, https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/utils/json11.h , I think we can insert the different entity name at the beginning of the file.

**Comment by rsdmse** [comment]
Thanks guys. I just need to check with the university about item 6 of the CLA.

**Comment by rsdmse** [comment]
Unfortunately, we're unable to proceed unless item 9 of the CLA is dropped.
> Governing Law/Jurisdiction. This Agreement is governed by the laws of the State of Washington, and the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County, Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all defenses of lack of personal jurisdiction and forum non-conveniens.

**Comment by StrikerRUS** [comment]
@rsdmse Ah, it a pity! I guess it is not possible to drop any items from the CLA since it comes from Microsoft and isn't specific to LightGBM repo but general for all Microsoft GitHub repos. 😢 

@guolinke please correct me

**Comment by rsdmse** [comment]
I have an idea. Instead of contributing, you can just take our [Dockerfile](https://github.com/uvarc/rivanna-docker/blob/master/lightgbm/3.0.0/Dockerfile) from our GitHub repo (MIT license). I can insert the license into the Dockerfile, and just in case you can reference our repo:
https://github.com/uvarc/rivanna-docker
Does this work for you?

**Comment by rsdmse** [comment]
The previous Dockerfile is 3.0.0 on `distroless` (no shell; 15 MB). This one is 2.3.1 on `nvidia/opencl` (105 MB):
https://github.com/uvarc/rivanna-docker/blob/master/lightgbm/2.3.1/Dockerfile
Both are CLI-only.

**Comment by StrikerRUS** [comment]
@rsdmse 
> Does this work for you?

I think it is good option! @guolinke WDYT?

We have a `stable` tag which is updated after each release. Is it possible to use it instead of hardcoded version?
https://github.com/microsoft/LightGBM/releases/tag/stable
https://github.com/microsoft/LightGBM/blob/7744757a52c349e9b6e3907043581d507142d9ea/docker/dockerfile-cli#L13

**Comment by rsdmse** [comment]
Sure, I have prepared 2 separate Dockerfiles for you to copy over:
https://github.com/uvarc/rivanna-docker/tree/master/lightgbm
The stable branch is cloned by using your quoted command. I also cleaned up some other minor stuff. I tested the containers on our GPU to make sure they work.

If you need to make other adjustments, please feel free to edit them in your repo.

(We hard coded the version since we need to keep track of that on our HPC platform.)

**Comment by guolinke** [comment]
@rsdmse @StrikerRUS Thanks, this is a good solution.

**Pull request closed without merging**
