### PR TITLE
[ci] [R-package] allow more possibly-lost warnings from valgrind

### PR DESCRIPTION
**Pull request by jameslamb**
Contributes to the `v4.2.0` release (#6191).

The latest `valgrind` build showed 1,056 bytes "possibly lost", all from code paths that create threads w/ `pthread_create`. (https://github.com/microsoft/LightGBM/pull/6191#issuecomment-1846240329)

In the past, CRAN has allowed some of these as false positives. (https://github.com/microsoft/LightGBM/pull/6191#issuecomment-1846502740)

This PR proposes modifying the test script for that job to acknowledge that this set of findings from `valgrind` are allowed.

### Notes for Reviewers

It would be better to suppress *specific* cases instead of do text-parsing to enforce a maximum number of "possibly lost" reported bytes... but that will take a bit more time to develop. I've documented it in #6231 and put `good first issue` on it to try to increase the likelihood that someone comes and contributes that.

### CODE REVIEW

**Comment by jameslamb** [comment]
Could I please get a review on this this week? This is the last PR I think needs to be done before we put up release v4.2.0 (#6191). I'd like to get that release out this week, to get that quantized training fix (#5994) out to more users.

**Review by jmoralez — APPROVED** [review]
Approving to unblock, hopefully someone else reviews this.

**Comment by jameslamb** [comment]
Thanks @jmoralez ! I'm going to merge this to continue with testing the release candidate.

For what it's worth, the R package has been up for 11 days now and CRAN has not reported any `valgrind` issues yet.

image

https://cran.r-project.org/web/checks/check_results_lightgbm.html

**Pull request merged**
