### PR TITLE
[R-package] Update remaining internal function calls to use keyword arguments

### LINKED ISSUE #3390: [R-package] use keyword arguments for all internal function calls
## Summary

Today in the R package, there are a lot of internal function calls which use only positional arguments. Change them to use keyword arguments for extra safety.

I've added this issue to provide a small, focused contribution opportunity for [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/) participants. If you are an experienced open source contributor, please leave this for beginners and consider contributing [on a different backlog item](https://github.com/microsoft/LightGBM/issues).

## Motivation

Using positional arguments in internal code is dangerous, because it can allow mistakes to slip through or can lead to confusing errors.

This is especially dangerous for cases where the values you'd pass to two parameters take on similar values. For example, in `lightgbm()`, `eval_freq` and `early_stopping_rounds` are both positive integers and can take on similar values. You might not known, unless you're very careful, that you accidentally specified them in the wrong order.

## How to Contribute

To help with this issue, propose a pull request which replaces uses of positional arguments in the R package with keyword arguments.

That means changing calls like this:

```r
# before
folds <- generate.cv.folds(
    nfold
    , nrow(data)
    , stratified
    , getinfo(data, "label")
    , getinfo(data, "group")
    , params
)

# after
folds <- generate.cv.folds(
    nfold = nfold
    , nrows = nrow(data)
    , stratified = stratified
    , label = getinfo(data, "label")
    , group = getinfo(data, "group")
    , params = params
)
```

1. Only change code in `R-package/R/`
1. Before submitting your PR, re-generate the documentation. Be sure you have `{roxygen2}` 7.1.1 installed. If you have any issues with this, just ask when you submit your PR and I can regenerate the docs for you
    ```shell
    sh build-cran-package.sh
    R CMD INSTALL --with-keep.source lightgbm_3.*.tar.gz
    cd R-package
    Rscript -e "roxygen2::roxygenize(load = 'installed')"
    ```
1. Do not modify any calls to `lgb.call()`
1. Do not worry about any function calls from the standard library (like `print()`,  `length()`, `is.character()`, etc.)
1. If adding these arguments makes lines too long, use comma-first style with one argument per line
    ```r
    result <- some_function(
        arg1 = TRUE
        , arg2 = 4
        , arg3 = "hello"
        , ...
    )
    ```

Refer to #3391 as an example. If you have any questions, tag me on this issue and I can help.

## Assignments

~If you are interested, please comment on this issue and indicate which file in `R-package/R/` you'd like to help on. **PLEASE ONLY TAKE ONE FILE**, so that multiple people can use this as a learning experience.~

~This issue is not urgent, so you can claim a file now and not contribute until [Hacktoberfest](https://hacktoberfest.digitalocean.com/) begins on October 1st.~

The list below tracks the assignments and completions so far.

* ~aliases.R~
* ~callback.R~ - @philip-khor (#3430) 
* ~lgb.Booster.R~ - @Pey-crypto (#3496)
* lgb.Dataset.R  - @zenggyu (#3617)
* ~lgb.Predictor.R~ - @AnshuTrivedi (#3464) 
* lgb.convert_with_rules.R - @zenggyu (#3617)
* lgb.cv.R - @zenggyu (#3617)
* lgb.importance.R - @zenggyu (#3617)
* lgb.interprete.R - @zenggyu (#3617)
* ~lgb.model.dt.tree.R~ - @zenggyu (#3605)
* lgb.plot.importance.R - @zenggyu (#3617)
* lgb.plot.interpretation.R - @zenggyu (#3617)
* ~lgb.train.R~ - @iadi7ya (#3452)
* lgb.unloader.R - @zenggyu (#3617)
* ~lightgbm.R~
* metrics.R - @zenggyu (#3617)
* readRDS.lgb.Booster.R - @zenggyu (#3617)
* ~removed.R~
* saveRDS.lgb.Booster.R - @zenggyu (#3617)
* ~utils.R~ - @mfrasco6 (#3604) 

Thanks for contributing to `LightGBM`!

### PR DESCRIPTION
**Pull request by zenggyu**
Closes #3390 .

I didn't edit the following `.R` files because all internal function calls in these files are already using keyword arguments:

- lgb.plot.importance.R
- lgb.unloader.R
- metrics.R
- readRDS.lgb.Booster.R
- saveRDS.lgb.Booster.R

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks for doing this!  These changes all look great. Could you please also add keyword arguments for these other calls?

Let me know if you get stuck and need help, some of these are R6 objects way nested in the attributes of other R6 objects.

**`lgb.Dataset.R`**

- `self$set_categorical_feature()`
- `self$set_colnames()`
- `private$set_predictor()`
- `x$set_colnames()`
- `lgb.is.Dataset()`
- `dataset$set_categorical_feature()`
- `dataset$set_reference()`
- `dataset$save_binary()`

**`lgb.convert_with_rules.R`**

- `.get_column_classes()`

**`lgb.cv.R`**

- `Predictor$new()`
- `lgb.check_interaction_constraints()`
- `data$update_params()`
- `data$.__enclos_env__$private$set_predictor()`
- `data$set_colnames()`
- `data$set_categorical_feature()`
- `categorize.callbacks()`

**Comment by zenggyu** [comment]
OK!

**Comment by zenggyu** [comment]
So I used regular expression to find all functions defined in `.R` files, then used those function names to find all function calls and inspected them one by one. I have updated almost every function call which uses positional arguments instead of keyword arguments. There is one exception though. In `lgb.cv.R` and `lgb.train.R`, there are these function calls:

```r
for (f in cb$pre_iter) {
   f(env)
}
```

I think `f()` comes from `categorize.callbacks()` in the `callback.R` file, and its one and only argument is `x`. However, I am not sure. Is this correct? Do you want me to update these function calls as well?

**Review by jameslamb — APPROVED** [review]
This looks great, thanks so much! You can ignore the `f(env)` things in `callbacks.R`.

The only CI job that's failing is the `check-docs` task on Travis, which isn't related to your changes. It just fails sometimes. I manually restarted it. Once that succeeds, I'll merge this.

Thanks for all the hard work! Come back and contribute any time!

**Pull request merged**
