### PR TITLE
[R-package] Add warning for MSVCP140.dll missing

### LINKED ISSUE #610: [R-package] Docs: add warning for MSVCP140.dll missing
To add to docs: warning for MSVCP140.dll missing when using precompiled DLL on a machine without Microsoft C++ Build Tools.

image

### PR DESCRIPTION
**Pull request by Laurae2**
Fixes #610 ([R-package] Docs: add warning for MSVCP140.dll missing)

### CODE REVIEW

**Comment by guolinke** [comment]
Actually, it has 2 kinds of MSVCP dlls. 
MSVCP120 for visual studio 2013, MSVCP140 for visual studio 2015 ( and visual studio 2017 ). 

BTW, your dll is compiled by vs 2017 ? 
if yes, maybe this is better: 
https://go.microsoft.com/fwlink/?LinkId=746572

**Comment by Laurae2** [comment]
@guolinke Yes it was compiled with Visual Studio 2017.

Which one should be used for Visual Studio 2013?

**Comment by guolinke** [comment]
@Laurae2 
vc2013: https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package

**Comment by Laurae2** [comment]
@guolinke This should be OK now. You can check if I put the correct ones.

**Pull request merged**
