### PR TITLE
[CI] fix R's installation

### PR DESCRIPTION
**Pull request by guolinke**

### CODE REVIEW

**Comment by jameslamb** [comment]
@guolinke what was the cause for this?

**Comment by guolinke** [comment]
@jameslamb I don't know, the master branch builds suddenly failed.

**Comment by jameslamb** [comment]
ok no problem. I'm worried that this is going to result in us getting a different R version than the one we want, but if it fixes a problem it's ok to leave it for a while and see how it goes. I'll keep an eye on the logs.

**Comment by guolinke** [comment]
@jameslamb you can refer to https://github.com/microsoft/LightGBM/runs/953772345#step:4:375

**Comment by guolinke** [comment]
BTW, seems some R's tests are stuck forever.

**Comment by jameslamb** [comment]
ugh, weird!

It does look like it's working ok on `master`.

On `r-package (ubuntu-latest, gcc, R 3.6, cmake)` (https://github.com/microsoft/LightGBM/runs/953865741)

> dpkg: warning: downgrading r-base-dev from 4.0.2-1.1804.0 to 3.6.3-1bionic
Preparing to unpack .../11-r-base-dev_3.6.3-1bionic_all.deb ...
Unpacking r-base-dev (3.6.3-1bionic) over (4.0.2-1.1804.0) ...

and on `r-package (r-package (ubuntu-latest, gcc, R 4, cmake))` (https://github.com/microsoft/LightGBM/runs/953865780):

> r-base-dev is already the newest version (4.0.2-1.1804.0).
r-base-dev set to manually installed.

**Pull request merged**
