### PR TITLE
cast data_index as size_t in cuda_row_data to avoid integer overflow

### PR DESCRIPTION
**Pull request by SiNZeRo**
related to https://github.com/microsoft/LightGBM/issues/5705

@shiyu1994

### CODE REVIEW

**Review by guolinke — APPROVED** [review]

**Comment by shiyu1994** [comment]
@SiNZeRo Thanks. Rerun the ci job to pass the randomly failed setting.

**Comment by jameslamb** [comment]
I've manually re-triggered CI, will merge this when it is successful.

@SiNZeRo does this FIX #5705 for you? Can we close that issue when this is merged?

**Comment by SiNZeRo** [comment]
> 

yes, this PR is intended to resolve this issue.

**Comment by jameslamb** [comment]
great, thank you

**Pull request merged**
