### PR TITLE
install ca certificates package on ubuntu image

### PR DESCRIPTION
**Pull request by gmaliar**
`wget` and `git` fail to fetch files due to missing certificates

### CODE REVIEW

**Comment by jameslamb** [comment]
Thanks @gmaliar . More context for reviews...

running `docker build -t lgbpy -f dockerfile-python .` runs for a while and then hits the following:

```
Setting up patch (2.7.5-1ubuntu0.16.04.2) ...
Setting up dpkg-dev (1.18.4ubuntu1.6) ...
Setting up build-essential (12.1ubuntu2) ...
Setting up liberror-perl (0.17-1.2) ...
Setting up git-man (1:2.7.4-0ubuntu1.6) ...
Setting up git (1:2.7.4-0ubuntu1.6) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
--2019-11-08 16:39:04--  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.201.79, 104.18.200.79, 2606:4700::6812:c94f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.201.79|:443... connected.
ERROR: cannot verify repo.continuum.io's certificate, issued by 'CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB':
  Unable to locally verify the issuer's authority.
To connect to repo.continuum.io insecurely, use `--no-check-certificate'.
The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends         cmake         build-essential         gcc         g++         git         wget &&     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh &&     /bin/bash Miniconda3-latest-Linux-x86_64.sh -f -b -p $CONDA_DIR &&     export PATH="$CONDA_DIR/bin:$PATH" &&     conda config --set always_yes yes --set changeps1 no &&     conda install -q -y numpy scipy scikit-learn pandas &&     git clone --recursive --branch stable --depth 1 https://github.com/Microsoft/LightGBM &&     cd LightGBM/python-package && python setup.py install &&     apt-get autoremove -y && apt-get clean &&     conda clean -a -y &&     rm -rf /usr/local/src/*' returned a non-zero code: 5
```

@gmaliar I'm hesitant to turn off verification. I did find ContinuumIO/anaconda-issues#670 where people reported a similar issue, and saw [this suggestion](https://github.com/ContinuumIO/anaconda-issues/issues/670#issuecomment-227704041) and [this suggestion](https://github.com/ContinuumIO/anaconda-issues/issues/670#issuecomment-245142880).

Could you check if explicitly adding `ca-certificates` to our `apt-get install` block in `dockerfile-python` alleviates the issue?

**Comment by gmaliar** [comment]
Hey @jameslamb immediately after I issued this pr I thought about the alternative of just installing the ca certificates, I think that it's the better approach I will try it out and fix the pr.
Thanks a lot for the review!

**Comment by gmaliar** [comment]
@jameslamb it worked out well.

**Comment by StrikerRUS** [comment]
@gmaliar Thanks a lot for finding and fixing the issue!
Do we need this fix for our other docker files?

**Comment by gmaliar** [comment]
Hi @StrikerRUS I've verified all additional Dockerfiles and found that only the cli had to have the additional missing ca certificates package (R and gpu images).
Additionally, I've verified and there is not need to `update-ca-certificates` after it is installed so I've removed it.

**Comment by jameslamb** [comment]
> LGTM! Thanks!
> 
> I guess, for the rest docker images, it's done in their parent images.

yeah at least for R, it is in the base images:  https://github.com/rocker-org/rocker/blob/master/r-base/Dockerfile#L25

**Pull request merged**
