### PR TITLE
add gpu test on osx

### PR DESCRIPTION
**Pull request by wxchan**
#658

### CODE REVIEW

**Comment by wxchan** [comment]
@guolinke @huanzhang12 all the test case fail with error `lightgbm.basic.LightGBMError: b'Invalid Work Group Size'`. Do you know how to fix it?

**Comment by huanzhang12** [comment]
@wxchan On OSX, for the CPU target, Apple's OpenCL implementation only supports a trivial work group size of [1,1,1]. The GPU kernels in LightGBM requires a work group size of [1,1,256], thus it is impossible to run them on the CPU target using Apple's OpenCL. Apple has no intention to fix this.

One possible way to automatically test the GPU code is to install pocl on OSX, as suggested here:
https://github.com/clMathLibraries/clFFT/issues/84

**Comment by guolinke** [comment]
@wxchan any plan to fix this ?

**Comment by wxchan** [comment]
@guolinke didn't figure out how to fix it yet. The same procedure works on my mac.

**Comment by huanzhang12** [comment]
@wxchan On a real Mac, OpenCL can run on a real GPU (intel/nvidia), so it works. But in travisCI, there is no real GPU; only the CPU OpenCL device can be used. Apple's default OpenCL CPU driver is very limited and is not compatible with the GPU code.

You can try to install pocl (an open source OpenCL implementation for CPU device) on your Mac and see if that works. If it works, you can try to put it into travis.

**Comment by wxchan** [comment]
@huanzhang12 thanks for explanation. Do you know how to use installed pocl instead of origin OpenCL? It still uses default `/System/Library/Frameworks/OpenCL.framework`.

**Comment by huanzhang12** [comment]
@wxchan I have no idea on how it works on OSX. However I think in general we should link lightgbm against the newly compiled pocl instead of system OpenCL, and probably set up environment variable like `DYLD_LIBRARY_PATH` before running.

**Comment by wxchan** [comment]
I don't have much time working on this recently. Close it for now.

I think it's a little complex to use pocl, it requires installing several dependencies. The total test time is often over 20 mins before running test cases. Btw, I check some Deep Learning library such as pytorch or tensorflow, they don't have gpu test on osx either.

**Pull request closed without merging**
