### PR TITLE
python: use nose for tests

### PR DESCRIPTION
**Pull request by henry0312**
http://nose.readthedocs.io/en/latest/index.html

This is the first commit of https://github.com/Microsoft/LightGBM/issues/261.
(I'm very sorry for too late starting)

### CODE REVIEW

**Comment by guolinke** [comment]
@wxchan can you review this ?

**Comment by henry0312** [comment]
I rebased the current master to fix conflict.

**Comment by wxchan** [comment]
do we need nose and rednose in requirement.txt?

**Comment by henry0312** [comment]
@wxchan no, however it is useful (https://github.com/Microsoft/LightGBM/pull/483/files#diff-354f30a63fb0907d4ad57269548329e3R36)

**Comment by kmike** [comment]
just FYI: nose is almost unmaintained now, last release was in 2015, last commit was a year ago, developers created nose2 which also haven't got traction. I believe most nose users are switching to pytest these days, which is much better supported.

**Comment by henry0312** [comment]
I'll check nose2 and pytest.

**Comment by henry0312** [comment]
I think nose is enough for LightGBM, because

1. The Python official document introduces still nose (not nose2)  
    https://docs.python.org/3.6/library/unittest.html  
    https://docs.python.org/3.5/library/unittest.html
    https://docs.python.org/2.7/library/unittest.html
2. The tests of LightGBM use official unittest (see above links), and nose just provides some features on official unittest, which I need in https://github.com/Microsoft/LightGBM/issues/261.
3. In my experience, I haven't faced any problem as long as I use it normally.

**Comment by kmike** [comment]
Yeah, nose is a proven workhorse, and likely it'll work fine. My point is that pytest has all the same benefits (it is mentioned in python docs, provides similar features and similar ease of use - it can even run nose tests), and its last release was in 2017, not in 2015, so it can be a more future-proof choice.

**Pull request closed without merging**
