### PR TITLE
[c_api] Improve ANSI compatibility by avoiding <stdbool.h>

### PR DESCRIPTION
**Pull request by drewmiller**
Mentioned in https://github.com/microsoft/LightGBM/issues/4609, these edits improve ANSI C compatibility by removing reliance on stdbool.h. These edits may cause a compiler warning for existing code which passes a `_Bool` pointer as `out`. However, given the brief tenure of ANSI C compatibility, it seems unlikely there will be much breakage.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
Kindly ping @drewmiller

**Comment by drewmiller** [comment]
> Kindly ping @drewmiller

Apologies for the delay. Will make the change this weekend.

**Comment by StrikerRUS** [comment]
No problem, please take your time. I just wanted to make sure you didn't forget about this PR.

**Review by StrikerRUS — APPROVED** [review]

**Review by jameslamb — APPROVED** [review]
Thanks @drewmiller !

**Pull request merged**
