### PR TITLE
Suppress categorical warning (fixes #3379)

### LINKED ISSUE #3379: [python] suppress the warning about categorical feature override
```
C:\ProgramData\Anaconda3\lib\site-packages\lightgbm\basic.py:1555: UserWarning: categorical_feature in Dataset is overridden.
New categorical_feature is ['C01', 'C02', 'C03', 'C04', 'C05', 'C06', 'C07', 'C08', 'C09', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'C22', 'C23', 'C24', 'C25', 'C26']
  'New categorical_feature is {}'.format(sorted(list(categorical_feature))))
C:\ProgramData\Anaconda3\lib\site-packages\lightgbm\basic.py:1286: UserWarning: Overriding the parameters from Reference Dataset.
  warnings.warn('Overriding the parameters from Reference Dataset.')
C:\ProgramData\Anaconda3\lib\site-packages\lightgbm\basic.py:1098: UserWarning: categorical_column in param dict is overridden.
  warnings.warn('{} in param dict is overridden.'.format(cat_alias))
```
`categorical_column` could be set in both `lgb.train` and `lgb.Dataset` . But this warning seems always show up if setting  `categorical_column`. I think this is quite annoying.

### PR DESCRIPTION
**Pull request by hzy46**
To fix #3379

### CODE REVIEW

**Comment by shiyu1994** [comment]
Close and reopen this PR to retrigger ci tests after the fix of #4769.

**Review by shiyu1994 — APPROVED** [review]
LGTM. Approve given that all tests are passed. Thank you!

**Comment by StrikerRUS** [comment]
Hmm, I'm very surprised that just closing-reopening made all tests to pass!
The base branch of this PR still lacks our recently merged workaround (#4770) for stuck Dask tests, but CI status is all-green. Strange...

https://github.com/hzy46/LightGBM/blob/suppress_warning_of_categorical_feature/.ci/test.sh#L117

image


cc @jameslamb @jmoralez

**Comment by jmoralez** [comment]
Seems like the jobs took into account the incorporated restrictions ([linux regular](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=11462&view=logs&j=c28dceab-947a-5848-c21f-eef3695e5f11&t=fa158246-17e2-53d4-5936-86070edbaacf&l=73), [linux sdist](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=11462&view=logs&j=02a2c3ba-81f8-54e3-0767-5d5adbb0daa9&t=720ee3fa-96d4-5b47-dbf4-01607b74ade2&l=76), [linux bdist](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=11462&view=logs&j=fb919173-48b9-522d-5342-9a59a13eb10b&t=7fcbeee5-d4c1-571c-8072-1d5874591254&l=73)). I was surprised as well.

**Comment by jameslamb** [comment]
I think it might be related to https://github.com/microsoft/LightGBM/pull/4678#discussion_r734215404

The code run in CI might not have been "this branch" but "this branch merged with `master`".

**Pull request merged**
