### PR TITLE
[ci] Use Ubuntu 22.04 as `ubuntu-latest` at CI (fixes #5186)

### LINKED ISSUE #5186: [ci] run Azure DevOps Linux_latest jobs on ubuntu:latest
## Summary

The changes from #5174 should be reverted, and `Linux_latest` CI jobs on Azure Devops should use the `ubuntu:latest` image (currently Ubuntu 22.04).

## Description

While working on #5169, I ran into an issue where the `Linux_latest` jobs running on Azure DevOps started failing.

Determined that this was because the `ubuntu:latest` tag on DockerHub moved from Ubuntu 20.04 to Ubuntu 22.04 (https://github.com/microsoft/LightGBM/pull/5169#issuecomment-1107139143).

#5174 temporarily pinned those jobs to `ubuntu:20.04` so that development on the project was no longer blocked.

## References

I believe that #5106 needs to be addressed to add this support. I think I almost have a reproducible example and potential fixes for that (https://github.com/microsoft/LightGBM/issues/5106#issuecomment-1107346250), but I've been traveling a lot recently and haven't had time to submit a pull request.

If this isn't addressed by whenever GitHub moves the `ubuntu-latest` virtual machine image for GitHub Actions to Ubuntu 22.04, more jobs will start failing (https://github.com/microsoft/LightGBM/pull/5174#issuecomment-1107645045). I don't know when that might happen.

### PR DESCRIPTION
**Pull request by StrikerRUS**
Fixes #5186.

Depends on https://github.com/actions/virtual-environments/issues/5490 when `ubuntu-22.04` will become the default Ubuntu on GitHub Actions.

### CODE REVIEW

**Comment by jameslamb** [comment]
Updated this to latest `master` of LightGBM tonight. It still failed on R jobs looking for a specific `autoconf` version, because `ubuntu-latest` on GitHub Actions is still Ubuntu 20.04.

But only for a few more days!

From https://github.com/actions/runner-images/issues/6399

> Ubuntu 22.04 is ready to be the default version for the "ubuntu-latest" label in GitHub Actions and Azure DevOps.

> This change will be rolled out over a period of several weeks beginning in October, 3. We plan to complete the migration by December, 1.

**Comment by jameslamb** [comment]
The date for "Ubuntu 22.04 is the default `ubuntu-latest` on GitHub Actions" just got pushed back from December 1, 2022 to March 1, 2023: https://github.com/actions/runner-images/issues/6399#issuecomment-1330879103.

**Comment by jameslamb** [comment]
Based on some recent comments on that upstream tracking issue, it seems like GitHub's plan is "from now until March 2023, slowly increase the number of runners for which `ubuntu-latest` gives you Ubuntu 22.04".

For example:

* https://github.com/actions/runner-images/issues/6399#issuecomment-1343542153
* https://github.com/actions/runner-images/issues/6399#issuecomment-1333373768

I see evidence of this on recent builds in #5619 too...some `ubuntu-latest` GitHub Actions jobs are getting Ubuntu 22.04.

image

([build link](https://github.com/microsoft/LightGBM/actions/runs/3654388221/jobs/6174766181))

This is a REALLY long time to not know which environment a job is going to get 😕 .

So for now, to minimize disruption to LightGBM's CI, I've pushed commits here replacing all uses of `ubuntu-latest` on Azure DevOps and GitHub Actions to `ubuntu-22.04`.

**Comment by jmoralez** [comment]
Is the `IN_UBUNTU_LATEST_CONTAINER` variable only set in Azure?

**Comment by jameslamb** [comment]
> Is the IN_UBUNTU_LATEST_CONTAINER variable only set in Azure?

Yep! That's a LightGBM-specific thing, and only used on Azure. Maybe we should rethink that.

Specifically, maybe we should try to switch the R jobs to running in an `ubuntu:22.04` container instead of just bare on the GitHub Actions `ubuntu-latest` VM.

**Comment by jmoralez** [comment]
I think the issue is with clang 14, I'm able to reproduce this locally installing that version from conda:
 ```bash
mamba install -y "clang==14.0"
conda deactivate && conda activate $ENV # to refresh the path
export CXX=$(which clang)
export CC=$CXX
mkdir build && cd build # from repo root
cmake ..
```
I get:
```
CMake Error at /home/jose/mambaforge/envs/lightgbm/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
Call Stack (most recent call first):
  /home/jose/mambaforge/envs/lightgbm/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/jose/mambaforge/envs/lightgbm/share/cmake-3.24/Modules/FindOpenMP.cmake:545 (find_package_handle_standard_args)
  CMakeLists.txt:163 (find_package)
```
I'll keep looking, just wanted to share in case this helps you.

**Comment by jmoralez** [comment]
I think we need `apt-get install libomp-14-dev` for clang14.

**Comment by jameslamb** [comment]
@jmoralez I don't think that's correct.

The most recent runs I pushed just installing `libomp-dev` ([link](https://github.com/microsoft/LightGBM/actions/runs/3700586066/jobs/6269144099)) failed like this:

```text
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

Which means we haven't yet actually tested that installing `libomp-dev` (no version number) works.

I appreciate the help, but could you please experiment on a different branch instead of pushing commits here? I'm in the middle of testing here on this one.

**Comment by jmoralez** [comment]
Sure, sorry. Can you please just let those two runs finish to see if they succeed?

**Comment by jameslamb** [comment]
> Can you please just let those two runs finish to see if they succeed?

Sure, I won't cancel them.

**Comment by jmoralez** [comment]
Done, I've canceled the rest. Sorry again, thought you were done for the day.

**Comment by jameslamb** [comment]
No prob no prob! We're both here visiting a @StrikerRUS PR anyway 😂

**Comment by jameslamb** [comment]
Looks like just installing `libomp-dev` on the `clang` R builds worked!

Builds: https://github.com/microsoft/LightGBM/actions/runs/3701050842/jobs/6270018989

I think that's preferable to using something with a version number like `libomp-14-dev`, because it improves the changes of that line not needing to be changed to run this script on other Linux distributions (e.g., on a future Ubuntu 24.04 or something).

<hr>

I'm going to open this up for review, since I know it's blocking: https://github.com/microsoft/LightGBM/pull/5612#issuecomment-1352201347

I'm also going to open another draft PR to work on trying to move the R package Linux jobs into containers. Will explain in that other PR why I think that's preferable.

**Comment by jameslamb** [comment]
Ah wait sorry, the `Linux_latest` jobs on Azure are all failing: https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=14008&view=logs&j=275189f9-c769-596a-7ef9-49fb48a9ab70&t=1fb0a3dd-ad11-527b-ef3d-485324b146c4

I'll move this back to draft and keep experimenting.

**Review by jmoralez — APPROVED** [review]
Maybe we could set an env variable in the R package workflow to hold the value of ubuntu latest and just use that everywhere ([example](https://docs.github.com/en/actions/learn-github-actions/environment-variables#using-contexts-to-access-environment-variable-values)),  that way the next time we'd just change that. Approving because that's just nice to have and can be done later.

**Comment by jmoralez** [comment]
Oh, took too long to review and missed the comment.

**Comment by jameslamb** [comment]
Alright I'm gonna stop for tonight. Hopefully the CUDA, QEMU, and Appveyor jobs will end up succeeding.

@jmoralez @shiyu1994 if you get back to this PR before me and see everything passing, merge it. Otherwise, I'll do that tomorrow. Thanks for the help!

**Pull request merged**
