### PR TITLE
Script to translate the model file to PMML

### PR DESCRIPTION
**Pull request by rmhasan**
This pull request is for issue Microsoft/LightGBM#31. I created a script pmml.py located inside the pmml directory. It takes the LightGBM_model.txt file generated by the lightGBM executable and translates each tree description inside to a pmml file. The script creates a directory if it does not exist and puts the files there. If the directory does exist then it asks the user to move it. The pmml files have been validated with it's xsd schema. More information on the schema can be found [here](http://dmg.org/pmml/v4-3/GeneralStructure.html). I also ran one of the pmml files as an input model to jpmml-evaluator. And it successfully took an input csv file and processed and scored each row inside. For more information how to use jpmml-evaluator, please look at the README.md file inside the pmml directory.

### CODE REVIEW

**Comment by guolinke** [comment]
@rmhasan  Did you sign the CLA ? 
@wxchan can you help to review this?

**Comment by wxchan** [comment]
Shouldn't this extension somehow look like [this](https://github.com/jpmml/jpmml-xgboost)?

**Comment by rmhasan** [comment]
@guolinke I signed the CLA

**Comment by rmhasan** [comment]
@wxchan, Im not sure how you mean it should look like that. Can you elaborate. When I was talking to @guolinke we decided on writing a python script that parses the LightGBM_model.txt file and outputs pmml files. You can everything we discussed at #31 .

**Comment by wxchan** [comment]
Sorry, I am not familiar with pmml, I thought it will be more like a (maven) package. Maybe @damienrj and @Alexkevin in #31 can help review it, is it what they want?

Anyway, to begin with, some simple suggestions:
1. clean your commit message, because it's a separated extension, people may read this pr in the future to understand what you do step by step. It'd better be merged all into one(it will count one commit anyway, just open a new local branch and pull with rebase)
2. your indent is too large, replacing it with 4 spaces will be better, use some text processor.

**Comment by rmhasan** [comment]
@wxchan You want me to rebase everything into one commit?

**Comment by rmhasan** [comment]
@wxchan  Hi I rebased the repository. Now its all in one commit.

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by guolinke** [comment]
@rmhasan what is the float precision in output pmml now?

**Comment by rmhasan** [comment]
@guolinke I read what ever is in the LightGBM_model.txt into a Decimal object, then I convert it into a string and print it out to the pmml file. It should maintain the precision of the variable printed to the LightGBM_model.txt file.

**Comment by guolinke** [comment]
@rmhasan OK, I will merge it now.

**Pull request merged**
