### PR TITLE
[cmake] always target Windows SDK v10.x when using Visual Studio generators (fixes #6448)

### LINKED ISSUE #6448: CMake `__BUILD_FOR_R` fails to find R source files
The CMake build has an option to build for R which was working some versions ago, at least under windows:
https://github.com/microsoft/LightGBM/blob/6e78e697f8e27d4bbf493a0ebd9134c3254a2ecd/CMakeLists.txt#L23

Building with this option by calling `cmake` directly with `-D__BUILD_FOR_R=1 -DCMAKE_R_VERSION=<version>` without using the `build_r.R` script is not working anymore, since it assumes that the R package files are under the same directory as the rest of the source files:
```
CMake Error at CMakeLists.txt:358 (add_library):
  Cannot find source file:

    src/lightgbm_R.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:358 (add_library):
  No SOURCES given to target: _lightgbm


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Building with the latest MSVC using the CI script `build_r.R` under the VS developer console is not working either, since it doesn't recognize all the installed versions - for example, if I use vs2022 in windows 10, I get this error as it tries to look for a windows 8.1 version (note that this doesn't happen when calling `cmake` directly):
```
installing via 'install.libs.R' to C:/Users/david/AppData/Local/R/win-library/4.3/00LOCK-lightgbm/00new/lightgbm
Trying 'Visual Studio 16 2019'
-- Configuring incomplete, errors occurred!
CMake Error at CMakeLists.txt:33 (PROJECT):
See also "C:/Users/david/AppData/Local/Temp/Rtmpk3gflg/R.INSTALLafc1e183436/lightgbm/src/build/CMakeFiles/CMakeOutput.log".
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.



Trying 'Visual Studio 15 2017'
-- Configuring incomplete, errors occurred!
CMake Error at CMakeLists.txt:33 (PROJECT):
See also "C:/Users/david/AppData/Local/Temp/Rtmpk3gflg/R.INSTALLafc1e183436/lightgbm/src/build/CMakeFiles/CMakeOutput.log".
  Generator

    Visual Studio 15 2017

  could not find any instance of Visual Studio.



Trying 'Visual Studio 14 2015'
-- Configuring incomplete, errors occurred!
CMake Error at CMakeLists.txt:33 (PROJECT):
See also "C:/Users/david/AppData/Local/Temp/Rtmpk3gflg/R.INSTALLafc1e183436/lightgbm/src/build/CMakeFiles/CMakeOutput.log".
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    MSBuild version 17.9.8+b34f75857 for .NET Framework
    Build started 5/6/2024 7:21:50 PM.

    Project "C:\Users\david\AppData\Local\Temp\Rtmpk3gflg\R.INSTALLafc1e183436\lightgbm\src\build\CMakeFiles\3.24.3\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\david\AppData\Local\Temp\Rtmpk3gflg\R.INSTALLafc1e183436\lightgbm\src\build\CMakeFiles\3.24.3\VCTargetsPath.vcxproj]
    Done Building Project "C:\Users\david\AppData\Local\Temp\Rtmpk3gflg\R.INSTALLafc1e183436\lightgbm\src\build\CMakeFiles\3.24.3\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\david\AppData\Local\Temp\Rtmpk3gflg\R.INSTALLafc1e183436\lightgbm\src\build\CMakeFiles\3.24.3\VCTargetsPath.vcxproj" (default target) (1) ->
    (Desktop_PlatformPrepareForBuild target) ->
      C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\david\AppData\Local\Temp\Rtmpk3gflg\R.INSTALLafc1e183436\lightgbm\src\build\CMakeFiles\3.24.3\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00Warning in eval(ei, envir) :.15


  Exit code: 1




  Building with Visual Studio failed. Attempting with MSYS2
CMake Error: Error: generator : MSYS Makefiles
Does not match the generator used previously: Visual Studio 14 2015
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
CMake Error: Error: generator : MSYS Makefiles
Does not match the generator used previously: Visual Studio 14 2015
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Error in .run_shell_command("cmake", c(cmake_args, "..")) :
  Command failed with exit code: 1
* removing 'C:/Users/david/AppData/Local/R/win-library/4.3/lightgbm'
Error in .run_shell_command(install_cmd, install_args) :
  Command failed with exit code: 1
Execution halted
```

### PR DESCRIPTION
**Pull request by jameslamb**
Fixes #6448

Related to #5884.

Helps with #6213.

Proposes always targeting v10.x of the Windows SDK in CMake builds using the Visual Studio generators.

### How I tested this

Building the R package, using Visual Studio 17 2022, on my Windows laptop running Windows 10 Home Edition.

```shell
Rscript build_r.R --no-build-vignettes
```

With rtools44 (https://cran.r-project.org/bin/windows/Rtools/rtools44/rtools.html) on PATH.

Without this change, `CMake` targets via 8.1 of the Windows SDK and detects the wrong Windows version.

```text
Trying 'Visual Studio 17 2022'
-- Selecting Windows SDK version 8.1 to target Windows 6.2.9200.
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:28 (project):
-- Configuring incomplete, errors occurred!
  No CMAKE_C_COMPILER could be found.
```

That causes all of the Visual Studio and then the MSBuild solutions to fail, and therefore installation of the R package to fail.

With this change, it correctly targets v10 of the Windows SDK.

```text
installing via 'install.libs.R' to C:/Users/James/Documents/R/win-library/4.4/00LOCK-lightgbm/00new/lightgbm
Trying 'Visual Studio 17 2022'
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.
-- The C compiler identification is MSVC 19.33.31630.0
-- The CXX compiler identification is MSVC 19.33.31630.0
...
```

### References

* https://discourse.cmake.org/t/problem-differences-in-detected-default-windowssdk-on-two-different-machines/2585/6
* https://cmake.org/cmake/help/latest/variable/CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION.html
* https://gitlab.kitware.com/cmake/cmake/-/issues/25413
* https://discourse.cmake.org/t/selecting-windows-sdk-8-1/7822/3
* https://stackoverflow.com/questions/73673196/python-cmake-chooses-wrong-windows-sdk-version
* https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_PLATFORM.html#visual-studio-platform-selection
* https://stackoverflow.com/a/59514792/3986677
* https://stackoverflow.com/a/45693321/3986677

### CODE REVIEW

**Comment by david-cortes** [comment]
@jameslamb Thanks for looking into this.

Some questions:
* What happens if the platform is windows 11 or windows server?
* Does lightgbm make any usage of the windows OS API that would make it require linkage to the windows SDK? As far as I am aware, all the functionalities for things like GPU, distributed training, etc. are handled by linking to external dependencies.

**Comment by jameslamb** [comment]
> What happens if the platform is windows 11 or windows server?

Good question!

My understanding is that v10 of the SDK supports Windows 11 and most versions of Windows Server.

See "Supported Operating Systems" here: https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/.

For example, the R-package MSVC tests here are targeting Windows Server 2019 and Windows 2022.

https://github.com/actions/runner-images?tab=readme-ov-file#available-images

https://github.com/microsoft/LightGBM/blob/20f20928f016e197da74f104a76870c5883cc778/.github/workflows/r_package.yml#L92-L107

> Does lightgbm make any usage of the windows OS API that would make it require linkage to the windows SDK?

Not 100% sure (Windows-specific development is not something I have a lot of experience in), but I think that winsock2, for example, comes through the Windows SDK.

https://github.com/microsoft/LightGBM/blob/20f20928f016e197da74f104a76870c5883cc778/src/network/socket_wrapper.hpp#L22-L24

https://learn.microsoft.com/en-us/windows/win32/winsock/creating-a-basic-winsock-application

If you see some other alternative to simplify LightGBM's Windows builds here I'd welcome it.

**Comment by david-cortes** [comment]
It compiles correctly with msvc after this PR, but with some caveats: if compiling for a second time, it hangs indefinitely without issuing any message (just stuck in `installing the package to build vignettes`). It looks like it requires killing the whole console application and then launching a new one in order to successfully install for a second time. Not sure if it has anything to do with the changes here though.

**Comment by jameslamb** [comment]
> It looks like it requires killing the whole console application and then launching a new one in order to successfully install for a second time.

Oh interesting, I haven't seen that before. I'm not sure what the cause of that might be.

You can skip building the vignettes (and therefore compiling the library twice) by passing `--no-build-vignettes`:

```shell
Rscript build_r.R --no-build-vignettes
```

We have vignette-building on by default so that the package tarball that's produced is suitable to pass to `R CMD check --as-cran`. But for work like #6213 where you're primarily interested in just compiling the library and using it or running the unit tests, the vignettes are unnecessary.

**Comment by jameslamb** [comment]
@guolinke or @shiyu1994 could you help with a review of this?

**Review by guolinke — APPROVED** [review]
LGTM

**Pull request merged**
