### PR TITLE
[docs] fix GUI-only instructions for building with Visual Studio

### PR DESCRIPTION
**Pull request by ArtificialZeng**

### CODE REVIEW

**Comment by ArtificialZeng** [comment]
or otherwise it will report a bug like this:https://github.com/microsoft/LightGBM/issues/5495

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks!

Yes, I can confirm that the zip archive linked to from this section doesn't contain the contents of `git` submodules, and this section's instructions therefore don't work.

These instructions were written AT LEAST 5 years ago (https://github.com/microsoft/LightGBM/blame/3eb68e85e99a221b04c0e19eb262e41e210f3da1/docs/Installation-Guide.rst#L59, #945), and maybe even longer back. I suspect that they were written prior to the first `git` submodule being introduced in April 2017 (#368), and have been broken since then. Thanks for catching it!

-----

However, I don't think the proposed fix is the best option.

For people who are already comfortable using `git`, I think the "From Command Line" option should be preferred, and that this "With GUI" option should be reserved for only using pointing and clicking.

I think we should alter the "With GUI" instructions so that the point users to the zip archive attached to each release, which does include all the submodules (as described in https://github.com/microsoft/LightGBM/issues/5038#issuecomment-1103394333)

That would mean that the "With GUI" instructions are insufficient for building versions of LightGBM other than released versions, but I think that's acceptable in exchange for minimizing the maintenance burden required to keep this documentation up to date. "You have to use `git` if you want to build an unreleased version" seems ok to me.

So instead of this, can you instead please change these instructions to something like the following:

```text
2. Navigate to https://github.com/microsoft/LightGBM/releases. Choose the release you'd like to build, and download the file with a name like ``LightGBM-complete_source_code_tar_gz.tar.gz``.
```

Would you like to make that change? If you'd prefer not to, I'm happy to open a pull request and `@` you in it for a review.

**Review by StrikerRUS — CHANGES_REQUESTED** [review]
I absolutely agree with @jameslamb's suggestion above!

> and maybe even longer back. I suspect that they were written prior to the first `git` submodule being introduced in April 2017 (#368), and have been broken since then. 

Just small clarification: instructions are broken since introducing `fmt` and `fast_double_parser` dependencies (#3405, merged 8 Dec 2020), because `compute` dependency is needed only for GPU-version and it cannot be compiled via GUI.

> That would mean that the "With GUI" instructions are insufficient for building versions of LightGBM other than released versions

To overcome this, we can include those archives in our nightly builds and redirect users to them.

**Comment by jameslamb** [comment]
It's been a few months without response here, so I'm going to close this in favor of #5649.

Thanks for your interest in LightGBMM, @ArtificialZeng ! We hope you'll consider coming back and contributing in the future when you have more time.

**Pull request closed without merging**
