### PR TITLE
[ci] [R-package] fix clang 15 warning about unqualified calls (fixes #5661)

### LINKED ISSUE #5661: [CRAN] unqualified call to 'std::move'
## Description
I got another email from CRAN on 1st Jan for the warning message about using `std::move`.

```
[????????? [ripley@stats.ox.ac.uk](mailto:ripley@stats.ox.ac.uk) ????????? https://aka.ms/LearnAboutSenderIdentification?????????????]

Dear maintainer,

Please see the problems shown on
<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcran.r-project.org%2Fweb%2Fchecks%2Fcheck_results_lightgbm.html&data=05%7C01%7Cyushi2%40microsoft.com%7C49c424fd62d04f5b8b4f08daebe41f99%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638081662299407642%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nUv6e%2FkMPULboNqb%2BRsp8uJgpeM%2FkBNeCt3%2FmGwtKFk%3D&reserved=0>.

Please correct before 2023-01-15 to safely retain your package on CRAN.

The CRAN Team
```

For the ease of access, the URL is copied below
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcran.r-project.org%2Fweb%2Fchecks%2Fcheck_results_lightgbm.html&data=05%7C01%7Cyushi2%40microsoft.com%7C49c424fd62d04f5b8b4f08daebe41f99%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638081662299407642%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nUv6e%2FkMPULboNqb%2BRsp8uJgpeM%2FkBNeCt3%2FmGwtKFk%3D&reserved=0

### PR DESCRIPTION
**Pull request by jameslamb**
Fixes #5661.

* uses `std::move()` explicitly instead of a `using` declaration, to satisfy `clang`'s `-Wunqualified-std-cast-call` warning
* upgrades to `clang` 15 in the `r-devel-debian-clang` job, to more closely match CRAN's environment (see https://github.com/r-hub/rhub-linux-builders/issues/63#issuecomment-1371392773)

### Notes for Reviewers

The installation commands I'm proposing are based on https://apt.llvm.org/llvm.sh, the installation script recommended at https://apt.llvm.org/.

I think copying that stuff in here is safer than downloading a script from the internet and running it on every run.

### CODE REVIEW

**Comment by jameslamb** [comment]
🎉 adding `clang-15` to the CI job, I was able to exactly replicate the issue reported on CRAN.

https://github.com/microsoft/LightGBM/actions/runs/3842093698/jobs/6543052842

I'll continue by pushing a fix to LightGBM here. Now we'll have high confidence that if that job passes here, it'll pass on CRAN too.

**Review by shiyu1994 — APPROVED** [review]
LGTM. Thanks for the fix.

**Comment by jameslamb** [comment]
Thanks @shiyu1994 ! I'll open a PR for a v3.3.5 release tonight.

**Pull request merged**
