### PR TITLE
can't load libsvm file to dataset

### PR DESCRIPTION
**Pull request by wylqq312715289**
import lightgbm as lgb
dtest = lgb.Dataset('./data/libsvm.txt')
print dtest.num_feature()
======================= why error ================================
File "*******/basic.py", line 1158, in num_feature
raise LightGBMError("Cannot get num_feature before construct dataset")
lightgbm.basic.LightGBMError: Cannot get num_feature before construct dataset
===========================?=======================================
libsvm.txt like that:
1 0:0.4252040763188015 1:0.7234269439819614 2:0.2198664831534287
1 0:0.7855499009996039 1:0.2287907401631696 2:0.3954096899617033
0 0:0.8977085012657007 1:0.002568578519813736 2:0.7981754619557275
1 0:0.7754389449922868 1:0.3873931079206858 2:0.8511552221119321
1 0:0.9060812199464807 1:0.5049698598167162 2:0.3665523656418372
1 0:0.7289170144780479 1:0.6992288710470674 2:0.3380542718713656
1 0:0.02080155085980295 1:0.6404016217285756 2:0.4987680927973108
1 0:0.19294150321891 1:0.3788979348122099 2:0.2526684496343294
0 0:0.7324288183843998 1:0.8110061405511925 2:0.6875312345800412
0 0:0.6657764530014816 1:0.8326680735896242 2:0.7874407980610832

### CODE REVIEW

**Comment by guolinke** [comment]
@wylqq312715289 
you want to open a issue ? 
before you call ```num_feature()```, you should call ```dtest.construct()``` .

**Comment by wylqq312715289** [comment]
dtrain = lgb.Dataset('./data/svmlight.txt')
dtest = lgb.Dataset('./data/svmlight.txt')
#help(dtrain)
dtrain.construct();
dtest.construct();
print dtrain.num_feature()
======================new error ==================
 dtrain.construct();
  File "/home/wangyulong/.pyenv/versions/2.7.11/lib/python2.7/site-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 792, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "/home/wangyulong/.pyenv/versions/2.7.11/lib/python2.7/site-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 651, in _lazy_init
    ctypes.byref(self.handle)))
  File "/home/wangyulong/.pyenv/versions/2.7.11/lib/python2.7/site-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 47, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: No usable features in data file ./data/svmlight.txt
=========================== error ================================

**Comment by wylqq312715289** [comment]
@guolinke 
dtrain = lgb.Dataset('./data/svmlight.txt')
dtest = lgb.Dataset('./data/svmlight.txt')
#help(dtrain)
dtrain.construct();
dtest.construct();
print dtrain.num_feature()
======================new error ==================
dtrain.construct();
File "/home/wangyulong/.pyenv/versions/2.7.11/lib/python2.7/site-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 792, in construct
categorical_feature=self.categorical_feature, params=self.params)
File "/home/wangyulong/.pyenv/versions/2.7.11/lib/python2.7/site-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 651, in _lazy_init
ctypes.byref(self.handle)))
File "/home/wangyulong/.pyenv/versions/2.7.11/lib/python2.7/site-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 47, in _safe_call
raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: No usable features in data file ./data/svmlight.txt
=========================== error ================================

**Comment by guolinke** [comment]
@wylqq312715289 
it seems the format of file ./data/svmlight.txt is wrong. 
can you check it ?

**Pull request closed without merging**
