### PR TITLE
[docs] updated Microsoft GitHub URL

### PR DESCRIPTION
**Pull request by guolinke**

### CODE REVIEW

**Comment by guolinke** [comment]
The `Microsoft` in repo URL changed to 'microsoft', and cause this problem.

**Comment by StrikerRUS** [comment]
😮 Just out of curiosity, don't you know why?

I think we need to adjust other links too. I can help a little bit later.

**Comment by StrikerRUS** [comment]
Huh, seems that `Microsoft` had something like a "gold status" at Travis: all jobs started at the same time immediately after a commit. After this change jobs started to spawn with some delay after a commit and their number are limited with 10 now like for other projects.

**Comment by guolinke** [comment]
@StrikerRUS I guess the paid Travis plan of Microsoft ended, for Microsoft encourages Azure DevOps now...

**Comment by StrikerRUS** [comment]
@guolinke It's a pity... Now we have no unlimited jobs neither on Travis, nor on Azure 😢

**Comment by StrikerRUS** [comment]
BTW, please check Slack when you have time.

**Comment by StrikerRUS** [comment]
Lucky us! Seems that Travis instant unlimited jobs are back.

**Pull request merged**
