### PR TITLE
bump version for development

### PR DESCRIPTION
**Pull request by guolinke**

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]

**Comment by StrikerRUS** [comment]
@jameslamb Could you please help with updating `R-package/configure`?

**Comment by jameslamb** [comment]
> @jameslamb Could you please help with updating `R-package/configure`?

sure, just pushed: https://github.com/microsoft/LightGBM/pull/3568/commits/2e346b0860fdd525dc723f85d47bdd6642af104d

**Comment by StrikerRUS** [comment]
@jameslamb Thanks!

**Comment by StrikerRUS** [comment]
Seems Travis stopped sending statuses.

**Pull request merged**
