### PR TITLE
[R-package] removed horizontal whitespace (fixes #1642)

### LINKED ISSUE #1642: [R-Package] Horizontal whitespace in R source files
There is a bunch of miscellaneous trailing whitespace in the R source files. This causes distracting line diffs for those who have editors set to squash it. See discussion in #1635 .

Completing this issue means going through all the R files and removing that whitespace.

### PR DESCRIPTION
**Pull request by jameslamb**
Addressed the annoying horizontal-whitespace thing we discussed on #1635

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@jameslamb Could you please also fix this one in `R-package/tests/testthat/test_parameters.R `?

image

**Comment by jameslamb** [comment]
@StrikerRUS oh sure! I forgot "no newline" checks. Yes I can do that

**Comment by jameslamb** [comment]
fixed

**Comment by StrikerRUS** [comment]
Many thanks!

**Comment by jameslamb** [comment]
@StrikerRUS what's the protocol you usually follow? Can I merge after 1 approval? Is it case-by-case (like maybe I can merge this one since it's only whitespace)?

**Pull request merged**
