### PR TITLE
v3.2.0 release

### PR DESCRIPTION
**Pull request by guolinke**
This is a stable release.
The next release may is 4.0.0, for many breaking changes. And it may take a long time to finish. 
So it better to fix the critical bugs in 3.2.0.

Please list the PR need to be merged in this release.

### CODE REVIEW

**Comment by jameslamb** [comment]
> Please list the PR need to be merged in this release.

**Dask**

The Dask interface doesn't need to be perfect for 3.2.0 and it's ok for it to have only limited functionality, but there are some Dask items I'd still like to get done before releasing 3.2.0. Since there has never been a release with Dask in it, I want to put in enough thought and work that we have some confidence that breaking changes won't be necessary in the future.

This is the minimal list of issues I'd like to be done before 3.2.0, to feel confident in that release:

* [ ] decide how Dask client is provided (#3808)
* [ ] tutorial documentation for Dask (#3814)
* [ ] document how to save a Dask model (#3838)
* [ ] Dask API docs (#3871)
* [ ] add type hints in Dask docs (#3866)
* [ ] BUG: DaskLGBMClassifier very slow and not using CPU (#3797)
* [ ] BUG: DaskRegressor.fit() fails on Dask DataFrame / Series (#3861)

I'm able to spend some time at work working on this, but I still expect that it would take 1-3 weeks for these to get done. It's only me and @StrikerRUS working on the Dask package and reviewing each others' PRs (with occasional contributions from outside contributors). Is that ok, or do you want to get 3.2.0 out sooner?

**R package**

There are no features or bugs for the R package that I think absolutely need to be done before a 3.2.0 release.

**Comment by guolinke** [comment]
@jameslamb no hurry, we can take the time. 
@shiyu1994 I think we can setup a dev branch for 4.0.0, and maybe some PRs could merge to dev branch first. then rebase to master after 3.2.0 release.

**Comment by StrikerRUS** [comment]
> Please list the PR need to be merged in this release.

I'm making items that I think definitely should be fixed in `3.2.0` as **bold**.

### Core
- [ ] #2613
- [ ] #2604
- [ ] **BUG #3778**
- [ ] **BUG #3761**
- [ ] **BUG #3679**
- [ ] #3637
- [ ] BUG #3447

### Java
- [ ] #2392
- [ ] #2363
- [ ] #2943


### R-package
- [ ] BUG #3513
- [ ] **CI BUG #3469**

### GPU
- [ ] BUG #2648
- [ ] BUG #3870
- [ ] BUG #3624
- [ ] BUG #3475
- [ ] BUG #3339
- [ ] BUG #3030
- [ ] BUG #2793

### CUDA
- [ ] #3428

**Comment by StrikerRUS** [comment]
### Release checklist:

- [ ] Update [VERSION.txt](https://github.com/microsoft/LightGBM/blob/master/VERSION.txt) number.
- [ ] Update version in [Appveyor config file](https://github.com/microsoft/LightGBM/blob/master/.appveyor.yml).
- [ ] Update version in [`configure` file of R-package](https://github.com/microsoft/LightGBM/blob/master/R-package/configure).
- [ ] Run R valgrind checks after all PRs are merged
- [ ] Run R Solaris checks after all PRs are merged
- [ ] Push commit with `v*` tag to trigger `GitHubRelease` action at Azure Pipelines.
- [ ] Convert automatic GitHub release from `Draft` to normal one.
- [ ] Update [`stable` tag at GitHub](https://github.com/microsoft/LightGBM/releases/tag/stable).
- [ ] Upload release to [PyPI](https://pypi.org/project/lightgbm/).
- [ ] Upload release to [CRAN](https://cran.r-project.org/package=lightgbm).
- [ ] Update `cran-comments.md` when 3.1.1 is accepted on CRAN
- [ ] Upload release to [NuGet](https://www.nuget.org/packages/LightGBM/).
- [ ] Update version and hash in [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lightgbm.rb).

**Comment by shiyu1994** [comment]
> @jameslamb no hurry, we can take the time.
> @shiyu1994 I think we can setup a dev branch for 4.0.0, and maybe some PRs could merge to dev branch first. then rebase to master after 3.2.0 release.

Ok. Maybe 4.0.0 can include category encoding, symmetric trees, and the on-going efficiency optimizations.

**Comment by guolinke** [comment]
@shiyu1994 it seems this release still need some time. You can create a dev branch, and merge your PRs to that branch first.

**Comment by jameslamb** [comment]
I'm sorry, but I just found another serious issue in the Dask package: https://github.com/microsoft/LightGBM/issues/3918. It's my next priority, and I think it needs to be fixed before the release.

**Comment by StrikerRUS** [comment]
@jameslamb May I ask you a question? Why do you think that documentation PRs should block new release? All our docs are available online and can be updated independently from source code that is being uploaded to differente package managers with each release. We don't have any "snapshots" for docs...

**Comment by jameslamb** [comment]
> @jameslamb May I ask you a question? Why do you think that documentation PRs should block new release?

This period right now, before the release, is the only chance we'll ever have to freely break the API of `lightgbm.dask` with minimal user impact. Once that module is part of a formal release, we have to be much more hesitant about breaking changes.

The particular issues I've linked (#3814, #3838) are about high-level documentation of the interface. We might find some inconsistencies in the Dask API during creation and review on those PRs, and if those things come up then we'll have the opportunity to change them.

And anyway, there are 4 other non-Dask issues you've said "definitely" should be fixed (https://github.com/microsoft/LightGBM/pull/3872#issuecomment-769004782) before the release, right?

**Comment by StrikerRUS** [comment]
@jameslamb 
> We might find some inconsistencies in the Dask API during creation and review on those PRs

I see, makes sense!

> And anyway, there are 4 other non-Dask issues you've said "definitely" should be fixed (#3872 (comment)) before the release, right?

I said "I think" they should, because I cannot say just "they should" given that I'm not able to help fixing them 🙂 . So it's up to who is able to fix them decide whether they will or will not be in `3.2.0`.

Anyway, it was just my curiosity why docs should block new release. Now I get it that writing docs may help spot API problems.

**Comment by shiyu1994** [comment]
Hi @StrikerRUS and @jameslamb , thank you for the hard work. For the 3 bold core BUG's, #3761 is a numerical problem due to different computing strategy of col-wise and row-wise of LightGBM. And #3679 should have been fixed for the CPU version. We're waiting for response from #3778 for a reproducible example.

**Comment by StrikerRUS** [comment]
@shiyu1994 
> #3761 is a numerical problem due to different computing strategy of col-wise and row-wise of LightGBM

Can we have any workaround for this? If no, then I believe we should document that `deterministic=true` should be used together with either `force_col_wise=true` or `force_row_wise=true`. Otherwise, there is no guarantee of determinism.

**Comment by shiyu1994** [comment]
@StrikerRUS Yes, I agree that we should document this in the description of `deterministic` parameter.

**Comment by StrikerRUS** [comment]
@shiyu1994 
> And #3679 should have been fixed for the CPU version.

Then feel free to close that issue. For GPU version we have a separate open issue: #2793.

**Comment by AlbertoEAF** [comment]
Hello, I believe https://github.com/microsoft/LightGBM/pull/3942 must be merged before the 3.2.0 release too, as the new model-file reading code didn't handle nan and inf values in the model file (regression).

**Comment by jameslamb** [comment]
I wanted to give an update on the Dask issues I mentioned in https://github.com/microsoft/LightGBM/pull/3872#issuecomment-768794191.

Based on the conversation in #3797 so far, I no longer think it needs to be closed before releasing. The other two Dask issues still open (#3814, #3838) would be closed by PR #4030, which is just awaiting review.

I don't believe that any of the other in-progress Dask contributions need to make it into this release.

<hr>

For the R package, I'm working on #3469 right now. I think it's ok for a fix for that to not make it into the release.

There have been some other R bugs opened recently (#4045, #4034, #4007) but I don't believe any of them have to be fixed before this release. They were all opened by people using v3.1.1 from CRAN, so they don't represent regressions introduced by new changes. I don't want to delay 3.2.0 any later waiting for those to be fixed.

**Comment by jameslamb** [comment]
Now that #3814 has been merged, everything that I'd like to get into the release for Dask and the R package has been merged.

I've updated this branch with the latest changes from `master`. I'm going to run the `r-solaris` and `r-valgrind` checks to see if there are any issues, but they'll have to be run again after we merge #3942 and a fix for #3778.

**Comment by jameslamb** [comment]
@guolinke @StrikerRUS I think we're close to being able to release, right? I saw the new "Important PRs submitted later than creating this list but nothing prevents them to be included in the release" in https://github.com/microsoft/LightGBM/pull/3872#issuecomment-769004782 but I'm not convinced we need to wait for those two things to merge before releasing.

I'm not really sure what the failing job on AppVeyor means. https://ci.appveyor.com/project/guolinke/lightgbm/builds/38250026

> Build version 3.2.0 already existed and a random string was appended to its version to avoid collision. Update next build number or change version format.

**Comment by StrikerRUS** [comment]
> I'm not really sure what the failing job on AppVeyor means

`{build}` autoincrement placeholder is missed in Appveyor version.

**Comment by guolinke** [comment]
I think it is okay to release now. 
WDYT, @StrikerRUS ?

**Comment by guolinke** [comment]
BTW,  @StrikerRUS  and @shiyu1994 , do you have a pypi account? I will add you to the LightGBM's admin so that you can release on it there as well.

**Comment by shiyu1994** [comment]
My pypi username is shiyu1994.

**Comment by StrikerRUS** [comment]
> BTW, @StrikerRUS and @shiyu1994 , do you have a pypi account?

StrikerRUS

> I think it is okay to release now.
    WDYT, @StrikerRUS ?

I'd better wait a little bit for merging #4043 as a bug fix and #3997 as an enhancement that will allow Feedzai and MMLSpark start using the upcoming `3.2.0` release (https://github.com/microsoft/LightGBM/pull/3997#issuecomment-791969953) and not to wait a next one `4.0.0` that is expected to take a much time to be prepared.
But it looks like `2 vs 1`:

>  I saw the new "Important PRs submitted later than creating this list but nothing prevents them to be included in the release" in https://github.com/microsoft/LightGBM/pull/3872#issuecomment-769004782 but **I'm not convinced we need to wait for those two things to merge before releasing**.

**Comment by AlbertoEAF** [comment]
> I'd better wait a little bit for merging #4043 as a bug fix and #3997 as an enhancement that will allow Feedzai and MMLSpark start using the upcoming `3.2.0` release ([#3997 (comment)](https://github.com/microsoft/LightGBM/pull/3997#issuecomment-791969953)) and not to wait a next one `4.0.0` that is expected to take a much time to be prepared.

If you are in a hurry I can finish #3997 today after work, it's pretty basic to finish.

**Comment by guolinke** [comment]
@StrikerRUS @shiyu1994 
I had added them, please check the invitation. 
Feel free to create the release once you feel it is ready.

**Comment by StrikerRUS** [comment]
@guolinke 

> I had added them, please check the invitation.

Many thanks! Accepted.

We also have to upload new releases to NuGet. Would you also like to delegate this responsibility to someone from maintainers?

**Comment by jameslamb** [comment]
Whenever we're ready, I can submit the R package. Like last time, I'll submit to CRAN and say it's "on behalf of" you @guolinke , and then CRAN will send you an email asking you to confirm.

**Comment by StrikerRUS** [comment]
Well, I don't want to delay the release anymore.
Let's follow our plan for the release process if no one has any objections: https://github.com/microsoft/LightGBM/pull/3872#issuecomment-769008314.

**Comment by jameslamb** [comment]
Sounds good to me! I support releasing

**Comment by guolinke** [comment]
> We also have to upload new releases to NuGet. Would you also like to delegate this responsibility to someone from maintainers?

Oh, I forget that. Would you like to take responsibility for the Nuget package? You can give me your username if yes.

> Well, I don't want to delay the release anymore.
Agree, let us draft the release!

**Review by StrikerRUS — APPROVED** [review]

**Comment by jameslamb** [comment]
@guolinke @StrikerRUS I think https://github.com/microsoft/LightGBM/releases/tag/untagged-2f6d71c67863a8bdabe5 needs to be edited to have name `v3.2.0` and that release should be used to generate the `v3.2.0` tag, right?

Right now the release at https://github.com/microsoft/LightGBM/releases/tag/v3.2.0 doesn't have a changelog.

image

**Comment by StrikerRUS** [comment]
Homebrew formula is broken: https://github.com/Homebrew/homebrew-core/pull/73665.

Seem that the reason is in GitHub attaches repo sources without submodules: 

image


I'll modify attached files with downloaded sources.

**Comment by StrikerRUS** [comment]
@jameslamb Azure Pipelines automatically creates new release with appropriate tag.

I think I should copy-paste changelog there.

**Comment by jameslamb** [comment]
I just submitted 3.2.0 to CRAN, using the package generated by https://github.com/microsoft/LightGBM/pull/3872#issuecomment-803660027.

image

@guolinke you should receive an email.

> Please note that the submission is not completed until it is confirmed by the maintainer (via a link in the e-mail), who may need to check the spam folder.

I'll open a PR with the `cran-comments.md` file updates when we hear back from CRAN, and will upload the CRAN package to the release when we resolve https://github.com/microsoft/LightGBM/pull/3872#issuecomment-804083153.

**Comment by StrikerRUS** [comment]
Changelog fixed now:

image


With new push to `master` release drafter will create new untagged draft release (`3.2.1`, it doesn't respect our `VERSION.txt`).

**Comment by jameslamb** [comment]
great, thanks! I just uploaded `lightgbm-3.2.0-r-cran.tar.gz`

**Comment by StrikerRUS** [comment]
> I'll modify attached files with downloaded sources.

Hmm, I can't do that!

These files (`Source code (zip)` and `Source code (tar.gz)`) cannot be edited!

image


image


What should we do?..

**Comment by StrikerRUS** [comment]
Hmm, "nice"!..

> My repo has a submodule, when i create a release, the tar/zip file generated doesn’t include the submodule.

> This is not currently possible through GitHub.
   https://github.community/t/create-release-that-contains-submodule/1329/2

**Comment by StrikerRUS** [comment]
> What should we do?..

OK. I've uploaded correct files to the release (`LightGBM-3.2.0-complete_source_code_zip.zip` and `LightGBM-3.2.0-complete_source_code_tar_gz.tar.gz`). We should automate it, btw.

P.S. Now I know how to create `.tar.gz` in Windows: https://stackoverflow.com/questions/10773880/how-to-create-tar-gz-archive-file-in-windows#comment59759781_10773880  🤣

**Comment by jameslamb** [comment]
thanks for doing that!

**Comment by StrikerRUS** [comment]
PyPI release has been uploaded and tested.
Cool that embedded GPU-support is working!

image

**Comment by StrikerRUS** [comment]
@guolinke 

> Oh, I forget that. Would you like to take responsibility for the Nuget package? You can give me your username if yes.

OK, I can do that. Just registered account at NuGet: StrikerRUS

**Comment by guolinke** [comment]
@StrikerRUS @jameslamb Thank you so much!

@StrikerRUS had added you in Nuget.
image

**Comment by jameslamb** [comment]
it looks like `{lightgbm}` 3.2.0 has been accepted to CRAN!

https://cran.r-project.org/web/packages/lightgbm/index.html

but none of the CRAN checks have run yet (notice they are all 3.1.1)

image

https://cran.r-project.org/web/checks/check_results_lightgbm.html

I'll check back over the next few days and update `cran-comments.md`.

**Comment by StrikerRUS** [comment]
I hope I've done NuGet package publishing right. All I've done was clicking "Upload" section and choosing new `.nupkg` file from attachments of the release.

image


@guolinke Should we fix this warning for next release?
```
 We found the following issue(s):
The <licenseUrl> element is deprecated. Consider using the <license> element instead. Learn more.
We recommend that you fix these issues and upload a new package. Read more
```

image

**Comment by lostmygithubaccount** [comment]
does homebrew need to be updated somehow? I'm still seeing 3.1.1:

image

**Comment by StrikerRUS** [comment]
@lostmygithubaccount 
> does homebrew need to be updated somehow?

Yes, refer to https://github.com/microsoft/LightGBM/pull/3872#issuecomment-804087682 and https://github.com/Homebrew/homebrew-core/pull/73665.

**Comment by StrikerRUS** [comment]
@jameslamb I don't remember `r-devel-windows-x86_64-gcc10-UCRT` CRAN flavor. Looks like something new, right?

image


image


https://www.r-project.org/nosvn/winutf8/ucrt3/CRAN/checks/gcc10-UCRT/README.txt

Luckily, we are passing checks there! 🙂

**Comment by jameslamb** [comment]
Yep! It's experimental.

**Comment by StrikerRUS** [comment]
Looks like it is fixing the following our issue:


> Now, that test runs on all operating systems, but on Windows we expect the feature names in `Booster$dump_model()` to be changed.
   https://github.com/microsoft/LightGBM/pull/3647#issuecomment-752329515

> The main purpose of this toolchain is to allow UTF-8 as the
current native encoding on Windows, which would be a major step in fixing
most encoding problems R users encounter on Windows.

**Comment by StrikerRUS** [comment]
@guolinke @jameslamb @ankane
Seems that we have some problems with continuing to distribute LightGBM via Homebrew: 
https://github.com/Homebrew/homebrew-core/pull/73665#issuecomment-805872901.

**Comment by ankane** [comment]
Surprised it's an issue for header-only libraries. One approach I've seen other projects take is have a CMake flag to use system dependencies (for instance, LibTorch has `-DUSE_SYSTEM_LIBS` - https://github.com/pytorch/pytorch/blob/90bbe0b38bf5248a567bf4f8b7525612e06b641c/CMakeLists.txt#L343).

**Comment by StrikerRUS** [comment]
They just updated the formula: https://github.com/Homebrew/homebrew-core/pull/73665#pullrequestreview-635952357.

**Pull request merged**
