### PR TITLE
[ci] fix MSVC warning about builds in temp directory

### PR DESCRIPTION
**Pull request by StrikerRUS**
Currently this fix is applied only to R-package builds.
This PR proposes adding this fix to all Windows builds.

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build.
```
https://ci.appveyor.com/project/guolinke/lightgbm/builds/50283647/job/bo2wb8ejurn0b0k6#L798

### CODE REVIEW

**Comment by StrikerRUS** [comment]
Checked all Windows builds: no warning.

**Review by jameslamb — DISMISSED** [review]
Thanks! I agree, this should have always been in `test_windows.ps1` and not specific to the R package.

I've restarted the failing CI jobs for you.

I also edited the title to "MSVC" instead of "MSVS". I think it's more common to use "MSVC" when referring to the compiler and "MSVS" when referring to the IDE. That is typically what we've done here in LightGBM. But please change it back if you disagree, I don't think the distinction is too important.

**Comment by StrikerRUS** [comment]
Hmm, some builds failed with the following error:
```
        # check that model text has all expected param entries
        for param_str in all_param_entries:
>           assert param_str in model_txt_from_file
E           AssertionError: assert '[force_(col|row)_wise: 1]' in ...
```

I guess it can be somehow related to persistent mounts across builds (#6465, #6416)... Will investigate this.

**Comment by StrikerRUS** [comment]
> Hmm, some builds failed with the following error:

Wait! They are all Linux jobs, not Windows ones... 🤔

**Comment by StrikerRUS** [comment]
> Hmm, some builds failed with the following error:

Ok, found the root cause!

Jobs are failing because lightgbm is installed from PyPI not from source there.
#6574 fixes this problem. I'll mark that PR as `blocking`.

**Review by jameslamb — APPROVED** [review]
This looks great, thanks!

Hopefully THIS is the last "things left behind in the build directory" issue we have 😂

**Pull request merged**
