### PR TITLE
support clang with openmp in vsts-ci test

### PR DESCRIPTION
**Pull request by guolinke**

### CODE REVIEW

**Comment by guolinke** [comment]
BTW, if a user want to use the binaries built by us, with clang with openmp, what dependency is needed for the user? 
only `brew install libomp` ?

**Comment by StrikerRUS** [comment]
@guolinke 
>only brew install libomp ?

I believe in this.

What do you think about this idea? https://github.com/Microsoft/LightGBM/issues/1523#issuecomment-405010860

If you want to change the library in wheel at PyPI, I think it'll be very painful for users. I mean, everyone already know that they need the latest **gcc** to run LightGBM. Changing the easiest (and most common, I believe) way to install LightGBM from `brew install gcc` to `brew install libomp` will produce a lot of issues here. For instance, remember the case when we  switched compiling the library for PyPI from `gcc-7` to `gcc-8`.

BTW, what ring LightGBM is? https://github.com/MicrosoftDocs/vsts-docs/issues/610#issuecomment-415412630 
Does VSTS PR check available for us?

**Comment by guolinke** [comment]
can we add some log or warnings when user install wheel?

**Comment by StrikerRUS** [comment]
@guolinke Seems to be that no...

https://github.com/pypa/pip/issues/2933#issuecomment-290407667

**Comment by guolinke** [comment]
@StrikerRUS It seems install `libopm` is much easier than `gcc`. 
Moreover, users doesn't need to install the specific version of gcc.
So I prefer to change to clang in osx. 

Maybe we can have a detailed release note from now, and tell user what changes since last release.

**Comment by StrikerRUS** [comment]
@guolinke 
>It seems install libopm is much easier than gcc.

That's for sure!

> So I prefer to change to clang in osx.

Me too. But I want find the way to make this change less painful for users.

I'm worrying about that a lot of users used to install gcc and then install LightGBM. After changing to Apple Clang all of them will start to post issues, because they even don't know where to read about recent changes, except digging into commits history. In addition, all other internet resources (StackOverflow, Kaggle, personal blogs, etc) will suggest them installation with gcc 😢

**Comment by guolinke** [comment]
@StrikerRUS maybe one temporal solution is giving some warnings in python-package when import LightGBM, if detecting the host os is macOS ?

**Comment by StrikerRUS** [comment]
@guolinke Yeah, good idea!

**Pull request merged**
