### PR TITLE
[R-package] Temporary workaround for not modifying global OMP config

### PR DESCRIPTION
**Pull request by david-cortes**
ref #4705

This is a temporary workaround to avoid modifying the global OpenMP user configuration for the whole R process when running `lgb.train`. This PR should be reverted once issue #4705 is fixed properly.

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks for your proposal, but I don't support introducing a new required dependency to the R package for this purpose.

Instead of this fix that benefits only the R package, and even then only one part of it (i.e. not other multi-threaded operations like prediction and `Dataset` construction), if you're interested in seeing LightGBM's behavior here change, please work with @guolinke and @shiyu1994 on #4705 to implement something at the C++ level that all users of LightGBM will benefit from.

**Comment by david-cortes** [comment]
In #4705, @guolinke suggested a workaround like this. It does BTW fix the issue for dataset construction when it happens inside `lgb.train`.

**Comment by shiyu1994** [comment]
I agree that such changes should be made in C++ so that both R and Python packages can leverage the workaround. I can help to do that.

**Comment by jameslamb** [comment]
> both R and Python packages

Thanks @shiyu1994 . For the benefit of everyone reading this PR, I just want to clarify...when I refer to wrappers of LightGBM's C++ code, I don't only mean the R and Python package in this repo. I also mean SynapseML (formerly MMLSpark), the Java interface generated with SWIG, `LightGBM.NET`, and the other projects listed at https://github.com/microsoft/LightGBM#external-unofficial-repositories.

Based on this discussion, I'm going to close this PR.

@david-cortes thanks very much for documenting #4705 and for helping this project try to address it!

**Pull request closed without merging**
