### PR TITLE
Remove template parameters from copy constructor

### PR DESCRIPTION
**Pull request by hgminh95**
Contributes to #6033

C++23 no longer allow template parameters in constructor

### CODE REVIEW

**Comment by hgminh95** [comment]
@microsoft-github-policy-service agree

**Review by jameslamb — COMMENTED** [review]
Thanks for this! I've edited the description to link to #6033.

With this change, were you able to compile LightGBM using the C++23 standard? Or is this just one step towards that?

Either way, we appreciate the help!

**Review by jameslamb — APPROVED** [review]
Makes sense to me, based on my read of e.g. https://stackoverflow.com/a/63514123/3986677 and the bits of the C++20 standard linked from it.

Thanks for the help!

**Comment by hgminh95** [comment]
> With this change, were you able to compile LightGBM using the C++20 (or even better, C++23 standard)? Or is this just one step towards that?

Can confirm I can compile with C++23, gcc-12. However, it requires me to remove the __mm_malloc macros - https://github.com/microsoft/LightGBM/issues/4331 (but this seem be a GCC)

**Comment by jameslamb** [comment]
Ok interesting, thank you for that! I don't recall the history for these `_mm_malloc` macros:

https://github.com/microsoft/LightGBM/blob/3d386be29bb9e8032e9acaec7c831133928fbeba/include/LightGBM/utils/common.h#L41-L55

Maybe @StrikerRUS or @guolinke will remember why they were added in #2699.

**Comment by guolinke** [comment]
sometimes we need the memory allocation with aligned address, like https://github.com/microsoft/LightGBM/blob/484283202be456800abc3ba57039e8028536d593/include/LightGBM/cuda/vector_cudahost.h#L41-L60

**Comment by jameslamb** [comment]
Ah got it, thank you! Ok I'll investigate this further. Maybe some headers have changed in newer versions of compilers.

**Pull request merged**
