### PR TITLE
Partially resolve [CLI] Categorical: Read string and convert to int on the fly #789 (closed in favour #2303)

### PR DESCRIPTION
**Pull request by Dinara301**
Hi team! 
I extensively used create_tree_digraph function and found that there is no way to show categorical features values as they were initially before the internal encoding. It seems that there should be a possibility to decode these categorical variables to be displayed with their initial values in graph. 
I've found issue #789 connected to this problem. It's also included in #2302 feature requests issue.

For now it's only fixed for the "create_tree_digraph" function with decode_categorical as optional parameter set by default to False.

Please let me know if this is reasonable feature and fix.

### CODE REVIEW

**Comment by jameslamb** [comment]
Thanks very much for the idea and pull request, @Dinara301 .

Before we consider this, can you please sign the CLA (https://github.com/microsoft/LightGBM/pull/4658#issuecomment-938614669)? Please let us know if you have any questions or concerns.

**Comment by Dinara301** [comment]
> Thanks very much for the idea and pull request, @Dinara301 .
> 
> Before we consider this, can you please sign the CLA ([#4658 (comment)](https://github.com/microsoft/LightGBM/pull/4658#issuecomment-938614669))? Please let us know if you have any questions or concerns.

@jameslamb Thank you, I've signed CLA.

**Comment by jameslamb** [comment]
Sorry for the VERY long delay @Dinara301 ! We apologize for taking so long to respond to you. I'm here to help move this forward and answer any questions you have.

Are you still interested in pursuing this feature? If so, please do the following:

1. merge the latest changes from `master`  into this branch
2. please provide a small, self-contained reproducible example that we could run which demonstrates this behavior.
3. please provide at least one screenshot showing what the plots will look like as of these changes

Thanks for helping to improve LightGBM!

**Comment by jameslamb** [comment]
I'm going to close this PR due to lack of activity.

@Dinara301 if you decide in the future that you'd like to pursue this idea, please open a new pull request. Thanks for your interest in LightGBM.

**Pull request closed without merging**
