### PR TITLE
fix bug in parallel learning

### PR DESCRIPTION
**Pull request by guolinke**
ping @imatiach-msft

### CODE REVIEW

**Comment by guolinke** [comment]
BTW, this is a temporary fix, and will increase communication cost. 
It needs more works to reduce the communication cost, and i will try it recently.

**Comment by imatiach-msft** [comment]
@guolinke let me try this branch right now to see if it fixes the issue

**Comment by imatiach-msft** [comment]
@guolinke getting error on build:

/home/ilya/LightGBM/src/treelearner/data_parallel_tree_learner.cpp: In member function ‘void LightGBM::DataParallelTreeLearner<TREELEARNER_T>::Split(LightGBM::Tree*, int, int*, int*)’:
/home/ilya/LightGBM/src/treelearner/data_parallel_tree_learner.cpp:281:5: error: ‘smaller_leaf_splits_’ was not declared in this scope
     smaller_leaf_splits_->Init(*left_leaf, this->data_partition_.get(),
     ^
/home/ilya/LightGBM/src/treelearner/data_parallel_tree_learner.cpp:284:5: error: ‘larger_leaf_splits_’ was not declared in this scope
     larger_leaf_splits_->Init(*right_leaf, this->data_partition_.get(),
     ^
/home/ilya/LightGBM/src/treelearner/data_parallel_tree_learner.cpp:289:5: error: ‘smaller_leaf_splits_’ was not declared in this scope
     smaller_leaf_splits_->Init(*right_leaf, this->data_partition_.get(),
     ^
/home/ilya/LightGBM/src/treelearner/data_parallel_tree_learner.cpp:292:5: error: ‘larger_leaf_splits_’ was not declared in this scope
     larger_leaf_splits_->Init(*left_leaf, this->data_partition_.get(),
     ^

**Comment by imatiach-msft** [comment]
oh, I think it should be this->larger_leaf_splits_->…
let me try that..

**Comment by imatiach-msft** [comment]
that seems to have fixed it, I can build now

**Comment by imatiach-msft** [comment]
this fixed almost all tests except two:

image


[LightGBM] [Fatal] Check failed: (best_split_info.right_count) > (0) at /home/ilya/LightGBM/src/treelearner/serial_tree_learner.cpp, line 713 .

20/03/01 22:28:57 WARN LightGBMClassifier: LightGBM reached early termination on one worker, stopping training on worker. This message should rarely occur
[LightGBM] [Fatal] Socket recv error, code: 104
20/03/01 22:28:57 WARN LightGBMClassifier: LightGBM reached early termination on one worker, stopping training on worker. This message should rarely occur

364 was not less than 0
ScalaTestFailureLocation: com.microsoft.ml.spark.lightgbm.split1.VerifyLightGBMClassifier$$anonfun$17 at (VerifyLightGBMClassifier.scala:289)
org.scalatest.exceptions.TestFailedException: 364 was not less than 0

and another test with similar failure:

[LightGBM] [Fatal] Check failed: (best_split_info.left_count) > (0) at /home/ilya/LightGBM/src/treelearner/serial_tree_learner.cpp, line 709 .

20/03/01 22:28:59 WARN LightGBMClassifier: LightGBM reached early termination on one worker, stopping training on worker. This message should rarely occur
[LightGBM] [Fatal] Socket recv error, code: 104
20/03/01 22:28:59 WARN LightGBMClassifier: LightGBM reached early termination on one worker, stopping training on worker. This message should rarely occur
[LightGBM] [Info] Finished linking network in 0.676823 seconds
[LightGBM] [Info] Finished linking network in 0.257676 seconds
20/03/01 22:29:01 WARN LightGBMClassifier: LightGBM worker encountered empty partition, for best performance ensure no partitions empty
20/03/01 22:29:01 WARN LightGBMClassifier: LightGBM worker encountered empty partition, for best performance ensure no partitions empty

**Comment by imatiach-msft** [comment]
"BTW, this is a temporary fix, and will increase communication cost.
It needs more works to reduce the communication cost, and i will try it recently."

@guolinke no rush, this is not urgent at all, please take your time to resolve the issue properly.
I just encountered this when trying to fix (https://github.com/microsoft/LightGBM/issues/2615), but then I noticed it was not due to my changes but rather latest master, and then I noticed other users had this issue or some similar errors as well.

**Comment by guolinke** [comment]
@imatiach-msft it seems the error is raised for nodes without any data?

**Comment by imatiach-msft** [comment]
@guolinke good catch, in the second test one of the two partitions are empty on the two models that are compared (for one of 3 metrics), but this shouldn't error out as I just exclude those partitions during training.  I don't think the first test had an empty partition.  I've tried running the second test several times and I'm seeing surprisingly inconsistent behavior that I don't have a firm grasp on.  Sometimes it is failing on the metric validation logic, sometimes it is passing, and sometimes it is just getting stuck.

**Comment by imatiach-msft** [comment]
for past 3 runs I am seeing it getting stuck, this is the sample output in case it helps:

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/03/01 23:11:50 WARN Utils: Your hostname, ilya-Virtual-Machine resolves to a loopback address: 127.0.1.1; using 192.168.0.30 instead (on interface eth1)
20/03/01 23:11:50 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
20/03/01 23:11:50 INFO SparkContext: Running Spark version 2.4.3
20/03/01 23:11:51 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
20/03/01 23:11:51 INFO SparkContext: Submitted application: VerifyLightGBMClassifier
20/03/01 23:11:51 INFO SparkContext: Spark configuration:
spark.app.name=VerifyLightGBMClassifier
spark.driver.maxResultSize=6g
spark.logConf=true
spark.master=local[*]
spark.sql.shuffle.partitions=20
spark.sql.warehouse.dir=file:/home/ilya/mmlspark/spark-warehouse
20/03/01 23:11:51 INFO SecurityManager: Changing view acls to: ilya
20/03/01 23:11:51 INFO SecurityManager: Changing modify acls to: ilya
20/03/01 23:11:51 INFO SecurityManager: Changing view acls groups to: 
20/03/01 23:11:51 INFO SecurityManager: Changing modify acls groups to: 
20/03/01 23:11:51 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ilya); groups with view permissions: Set(); users  with modify permissions: Set(ilya); groups with modify permissions: Set()
20/03/01 23:11:51 INFO Utils: Successfully started service 'sparkDriver' on port 46778.
20/03/01 23:11:51 INFO SparkEnv: Registering MapOutputTracker
20/03/01 23:11:51 INFO SparkEnv: Registering BlockManagerMaster
20/03/01 23:11:51 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/03/01 23:11:51 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/03/01 23:11:51 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-dd840be0-c16c-4668-8b62-3a2480c97b70
20/03/01 23:11:52 INFO MemoryStore: MemoryStore started with capacity 1257.9 MB
20/03/01 23:11:52 INFO SparkEnv: Registering OutputCommitCoordinator
20/03/01 23:11:52 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/03/01 23:11:52 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://192.168.0.30:4040
20/03/01 23:11:52 INFO Executor: Starting executor ID driver on host localhost
20/03/01 23:11:52 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36297.
20/03/01 23:11:52 INFO NettyBlockTransferService: Server created on 192.168.0.30:36297
20/03/01 23:11:52 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/03/01 23:11:52 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 192.168.0.30, 36297, None)
20/03/01 23:11:52 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.0.30:36297 with 1257.9 MB RAM, BlockManagerId(driver, 192.168.0.30, 36297, None)
20/03/01 23:11:52 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 192.168.0.30, 36297, None)
20/03/01 23:11:52 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 192.168.0.30, 36297, None)
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Warning] [LightGBM] [Info] Trying to bind port 12402...
[LightGBM] [Info] Binding port 12402 succeeded
Set TCP_NODELAY failed
[LightGBM] [Info] Trying to bind port 12406...
[LightGBM] [Info] Binding port 12406 succeeded
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Listening...
[LightGBM] [Info] Listening...
[LightGBM] [Warning] [LightGBM] [Warning] Set TCP_NODELAY failed
Set TCP_NODELAY failed
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Connected to rank 1
[LightGBM] [Info] Connected to rank 0
[LightGBM] [Info] Local rank: 0, total number of machines: 2
[LightGBM] [Info] Local rank: 1, total number of machines: 2
[LightGBM] [Warning] metric is set=, metric= will be ignored. Current value: metric=
[LightGBM] [Warning] metric is set=, metric= will be ignored. Current value: metric=
[LightGBM] [Warning] [LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad resultsStarting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results

[LightGBM] [Info] Number of positive: 98, number of negative: 779
[LightGBM] [Info] Number of positive: 98, number of negative: 779
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001073 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 62
[LightGBM] [Info] Number of data points in the train set: 459, number of used features: 11
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003119 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 62
[LightGBM] [Info] Number of data points in the train set: 418, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.105263 -> initscore=-2.140066
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.117647 -> initscore=-2.014903
[LightGBM] [Info] Start training from score -2.077485
[LightGBM] [Info] Start training from score -2.077485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Fatal] Check failed: (best_split_info.left_count) > (0) at /home/ilya/LightGBM/src/treelearner/serial_tree_learner.cpp, line 709 .

20/03/01 23:12:02 WARN LightGBMClassifier: LightGBM reached early termination on one worker, stopping training on worker. This message should rarely occur
[LightGBM] [Info] Finished linking network in 0.254094 seconds

**Comment by imatiach-msft** [comment]
sorry, just realized the test is using rand() in several places without a seed, which is causing random partitioning of data.  I think that accounts for why the behavior is so different from run to run.  I will add a seed to make it reproducible in the same way every time.

**Comment by guolinke** [comment]
@imatiach-msft I update another fix, could you try it again?

**Comment by imatiach-msft** [comment]
@guolinke yes, this PR seems to have fixed all of the issues, thank you for the quick fix!

**Comment by imatiach-msft** [comment]
I do still see one test fail but I think it is a different issue, I will just ignore it for now and will look into it later

**Pull request merged**
