### PR TITLE
[docs] Update badge for Link checks workflow

### PR DESCRIPTION
**Pull request by StrikerRUS**
`master`:
image

`docs/badge`:
image

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
thank you!! I had looked into this a few weeks ago and couldn't figure out how to make it actually reflect the latest run.

**Comment by StrikerRUS** [comment]
I simply used badge creation wizard 😄 

image

**Comment by jameslamb** [comment]
Thank you! I didn't know that existed, actually 😬

**Comment by StrikerRUS** [comment]
Something went wrong with QEMU build and it reached 3h limit.

2 hours were spent here downloading Docker:
```
2024-07-24T13:30:04.0207276Z 90d53af341dc: Download complete
2024-07-24T15:42:27.8147148Z 35c87b9aae29: Verifying Checksum
```

I forgot my password from ``@hotmail``, so I'm unable to re-trigger the build 🤦‍♂️. Will update the branch to trigger new builds.

**Pull request merged**
