### PR TITLE
[python] fix python memory leak

### LINKED ISSUE #839: Memory leak
Memory leak happens with the current HEAD of master (f1e3ab923cc6d296c95d28afb3c883dce0119628).
With v2.0.4, memory leak doesn't happen.

## Environment info

Operating System: Ubuntu 16.04.3
CPU: Intel Xeon E5-2623 v3
C++/Python/R version: gcc 5.4.0 and Python 3.6.1

## Reproducible examples

```python
import numpy
from lightgbm import LGBMRegressor

x_data = numpy.random.randint(0, 100, size=(10000, 100))
y_data = numpy.random.randint(0, 5, size=10000)

for i in range(10000):
    print(i)
    gbm = LGBMRegressor()
    gbm.fit(x_data, y_data)
    del gbm
```

## Steps to reproduce

1. Just run the above code

### PR DESCRIPTION
**Pull request by guolinke**
fix #839

### CODE REVIEW

**Comment by guolinke** [comment]
@henry0312 can you try this ?

**Comment by henry0312** [comment]
I'll try.

**Comment by guolinke** [comment]
@henry0312  sorry, wait a minute, it is not working now.

**Comment by henry0312** [comment]
ping @wxchan 
(please review)

@guolinke yeah.
I just faced the problem:

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    gbm.fit(x_data, y_data)
  File "/home/tsukasa_omoto/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/sklearn.py", line 493, in fit
    callbacks=callbacks)
  File "/home/tsukasa_omoto/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/sklearn.py", line 391, in fit
    callbacks=callbacks)
  File "/home/tsukasa_omoto/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/engine.py", line 226, in train
    booster = Booster()
  File "/home/tsukasa_omoto/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/basic.py", line 1289, in __init__
    raise TypeError('Need at least one training dataset or model file to create booster instance')
TypeError: Need at least one training dataset or model file to create booster instance
```

**Comment by guolinke** [comment]
@henry0312 I think it works now

**Comment by henry0312** [comment]
I'll try when I get home.

2017年8月16日(水) 20:07 Guolin Ke <notifications@github.com>:

**Comment by henry0312** [comment]
https://github.com/Microsoft/LightGBM/pull/840/commits/226e0ce30b2c0df838fe090fca8b95ee8b4f3c74 fixes the memory leaks.
However, I don't know whether the fix is right or not, so it's better for @wxchan to check it.

**Comment by guolinke** [comment]
@wxchan  comments ?

**Pull request merged**
