### PR TITLE
[python] migrate to pathlib in conf.py

### PR DESCRIPTION
**Pull request by StrikerRUS**
Contributes to #4416.

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Seems good to me! But just to check, could you please also temporarily enable builds of this branch at https://readthedocs.org/projects/lightgbm/builds/ and build this branch there?

**Comment by StrikerRUS** [comment]
Agree. Done.

**Comment by StrikerRUS** [comment]
Looks OK.
https://lightgbm.readthedocs.io/en/pathlib/
https://lightgbm.readthedocs.io/en/pathlib/R/reference/

**Review by jameslamb — APPROVED** [review]
Thanks for building on RTD. Looks good to me!

**Pull request merged**
