### PR TITLE
Added dump_model() to simple_example.py

### PR DESCRIPTION
**Pull request by PPACI**
The example pages have the following description for "simple_example.py"

simple_example.py:
* Construct Dataset
* Basic train and predict
* Eval during training
* Early stopping
* Save model to file
* **Dump model to json format**
* Feature importances

But the dump part was missing from the file

### CODE REVIEW

**Comment by wxchan** [comment]
dump model has unknown bug, it's removed until the bug is found.

check: https://github.com/Microsoft/LightGBM/pull/860#discussion_r135139711

**Comment by guolinke** [comment]
@wxchan i think the bug is solved. The single-leaf tree is adding to the first tree as a bias now.

**Comment by wxchan** [comment]
@guolinke which commit do you refer to?

**Comment by guolinke** [comment]
@wxchan 
https://github.com/Microsoft/LightGBM/commit/6d0eae0c7b369f5bc023b00b21a56e98fc1bf7ba

**Comment by wxchan** [comment]
@guolinke ok. The bug is still in single-leaf tree?

@PPACI can you help move it to somewhere in advanced_example.py and clean Readme.md? I think it's not necessary to put in simple_example.py.

**Comment by PPACI** [comment]
It should be possible yes. Will try to do that tomorrow.

**Comment by guolinke** [comment]
@wxchan I remember the test is failed for the single-leaf tree. Now we avoid it.

**Pull request merged**
