### PR TITLE
[ci] bump CUDA version from `11.6.2` to `11.7.0` at CI 

### PR DESCRIPTION
**Pull request by StrikerRUS**

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
sounds good!

**Comment by StrikerRUS** [comment]
@shiyu1994 Current Ubuntu version that is used on the self-hosted CUDA runner is 18.04.

This is quite old version. We use 20.04 as the `latest` version in this repo's CI and [are in progress of migrating to the 22.04 one](https://github.com/microsoft/LightGBM/pull/5288).

Could you please update Ubuntu on the self-hosted CUDA machine to the 22.04 version?

If it's hard or requires a lot of time, please at least update NVIDIA drivers in the current OS because container with the latest CUDA fails to start with the following error:

```
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.7, please update your driver to a newer version, or use an earlier cuda container: unknown.
```

**Comment by StrikerRUS** [comment]
@guolinke Maybe you still have an access to the CUDA runner or know someone in Microsoft who can do this https://github.com/microsoft/LightGBM/pull/5287#issuecomment-1159597587?

**Comment by guolinke** [comment]
I am afraid that I don't have permission. Ping @shiyu1994 for help.

**Comment by shiyu1994** [comment]
Sorry for the late response. Will handle this right now.

**Comment by shiyu1994** [comment]
@StrikerRUS Will use a VM with Ubuntu 20.04 work? We created the self-hosted CUDA runner with Azure Portal. I've checked the available OS images in our Azure Portal Subscription when creating a VM and only 20.04 is available. Perhaps 22.04 has not been supported yet.

**Comment by guolinke** [comment]
@shiyu1994 you can update the driver first.

**Comment by StrikerRUS** [comment]
@shiyu1994 
> Perhaps 22.04 has not been supported yet.

Ubuntu 22.04 is on public beta right now.
https://github.com/actions/virtual-environments/issues/5490

Probably it's not available via GUI.

> maybe I can upgrade the NVIDIA driver for now.

Yes, please do this. It should be a quick workaround.

**Comment by StrikerRUS** [comment]
Ping @shiyu1994 for 
> If 20.04 does not work, maybe I can upgrade the NVIDIA driver for now.

> Yes, please do this. It should be a quick workaround.

**Comment by jameslamb** [comment]
@shiyu1994 can you please help with this?

**Comment by shiyu1994** [comment]
Sure. I'm trying with that. Thanks for your reminder.

**Comment by shiyu1994** [comment]
I've upgrade the NVIDIA Driver version on the self-hosted CUDA runner to `nvidia-driver-515`. Now CUDA 11.7 container can successfully run.
image

**Comment by shiyu1994** [comment]
Close and reopen due to HTTP error.

**Comment by shiyu1994** [comment]
It seems that we encounter a random failure in dask tests.

```bash
=================================== FAILURES ===================================
_____ test_network_params_not_required_but_respected_if_given[regression] ______

task = 'regression', listen_port = 13030
cluster = LocalCluster(e5dd6bee, 'tcp://127.0.0.1:44383', workers=2, threads=4, memory=7.77 GiB)

    @pytest.mark.parametrize('task', tasks)
    def test_network_params_not_required_but_respected_if_given(task, listen_port, cluster):
        with Client(cluster) as client:
            _, _, _, _, dX, dy, _, dg = _create_data(
                objective=task,
                output='array',
                chunk_size=10,
                group=None
            )
    
            dask_model_factory = task_to_dask_factory[task]
    
            # rebalance data to be sure that each worker has a piece of the data
            client.rebalance()
    
            # model 1 - no network parameters given
            dask_model1 = dask_model_factory(
                n_estimators=5,
                num_leaves=5,
            )
            dask_model1.fit(dX, dy, group=dg)
            assert dask_model1.fitted_
            params = dask_model1.get_params()
            assert 'local_listen_port' not in params
            assert 'machines' not in params
    
            # model 2 - machines given
            workers_hostname = _get_workers_hostname(cluster)
            n_workers = len(client.scheduler_info()['workers'])
            open_ports = lgb.dask._find_n_open_ports(n_workers)
            dask_model2 = dask_model_factory(

```

**Pull request merged**
