### PR TITLE
[Python-package]: Fix RandomState issue #376

### PR DESCRIPTION
**Pull request by Laurae2**
Refer to issue #376 for the solution.

Explanation: https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html

Demo Python code:

```python
import numpy as np

np.random.RandomState(1).permutation(10)
Out: array([2, 9, 6, 4, 0, 3, 1, 7, 8, 5])

np.RandomState(1).random.permutation(10)
Traceback (most recent call last):

  File "<ipython-input-5-d2d1cb7145c9>", line 1, in <module>
    np.RandomState(1).random.permutation(10)

AttributeError: module 'numpy' has no attribute 'RandomState'
```

### CODE REVIEW

**Comment by wxchan** [comment]
the bug raised by #365 

do we need to add a test case for it?

**Comment by Laurae2** [comment]
I added a test case, but I think (for R and Python package -related) we should ask users to provide test code for each PR to check/inspect if it works or not (and if they can, to add test or demo cases). We have many demo examples for that.

@guolinke opinion about test cases and demo cases on PRs?

Concretely, for instance if someone were to do again #365, the user should either:

* Add a demo case with results printed
* Add a test case (currently not available for R, we need someone who has enough time to setup Travis for R)

so we don't have to have someone test it after meged on the master branch and see it does not work, like issue #376.

**Comment by wxchan** [comment]
@Laurae2 agree.

**Comment by guolinke** [comment]
@Laurae2 sure, agree.

**Pull request merged**
