### PR TITLE
[R-package] minor improvements on weight demo

### PR DESCRIPTION
**Pull request by jmoralez**
Removes some extra lines that aren't necessary after #5204 and makes minor modifications to the weight descriptions.

### CODE REVIEW

**Comment by StrikerRUS** [comment]
While we're on it, maybe transform this demo into a [vignette](https://github.com/microsoft/LightGBM/tree/master/R-package/vignettes) as a part of #1944?

**Review by jameslamb — APPROVED** [review]
Thanks for doing this! I agree with @StrikerRUS 's suggestion to consider converting this demo to a vignette, but I also think we should just merge this and that that can be a separate PR if you have time / interest.

**Comment by jmoralez** [comment]
Yeah I have #1944 on my todo list, mainly to get more familiar with the full R-package. But I'll probably pick that up later, I'm currently focusing on the items of #5153.

**Comment by jameslamb** [comment]
Thank you! Totally agree with that approach @jmoralez

**Pull request merged**
