### PR TITLE
[python] Use first_metric_only flag for early_stopping function.

### PR DESCRIPTION
**Pull request by matsuken92**
In order to apply early stopping with only first metric, applying first_metric_only flag for early_stopping function.

### CODE REVIEW

**Comment by matsuken92** [comment]
The following error may be CI environment problem on appveyor.  TravisCI and Azure DevOps have same issue.   How to deal with it to solve...?

https://ci.appveyor.com/project/guolinke/lightgbm/builds/23063424/job/7unpekbvoh1gwt3r
```
jupyter nbconvert --ExecutePreprocessor.timeout=180 --to notebook --execute --inplace *.ipynb
Traceback (most recent call last):
  File "C:\Miniconda36-x64\envs\test-env\Scripts\jupyter-nbconvert-script.py", line 6, in <module>
    from nbconvert.nbconvertapp import main
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\__init__.py", line 7, in <module>
    from . import postprocessors
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\postprocessors\__init__.py", line 5, in <module>
    from .serve import ServePostProcessor
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\postprocessors\serve.py", line 19, in <module>
    class ProxyHandler(web.RequestHandler):
  File "C:\Miniconda36-x64\envs\test-env\lib\site-packages\nbconvert\postprocessors\serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
Command exited with code 1
```

**Comment by guolinke** [comment]
@StrikerRUS can you help to review this? Thank you!

**Comment by StrikerRUS** [comment]
@matsuken92 Thanks for your contribution! Can you please write a test for the enhancement you are proposing? I think it'll be rather straightforward with self-defined dummy metrics.

**Comment by StrikerRUS** [comment]
I went ahead and added simple test and updated docs with info about the new feature.

**Comment by guolinke** [comment]
one question:
when there are multi validation sets, the training will stop when any of them met early stopping? or just the first validation set?

**Comment by StrikerRUS** [comment]
I think that the behavior with multiple valid sets should remain unchanged:
> Early stopping requires at least one set in ``valid_sets``. If there is more than one, it will use all of them except the training data:

**Comment by guolinke** [comment]
@StrikerRUS @matsuken92 I think this implementation is only for the first metric of first validation set.

**Comment by StrikerRUS** [comment]
Then it should be addressed in #2127 to preserve documented behavior, I think.

**Pull request merged**
