### PR TITLE
[R-package] suppress Wcast-function-type warning in CMake-based gcc and MinGW builds (fixes #4273)

### LINKED ISSUE #4273: [R-package] gcc warning on CMake-based builds: 'cast between incompatible function types'
## Description

Building the R package with `CMake`-based installation (https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#install) and `gcc` (or `MINGW` on Windows results in the following compiler warnings:

```text
/private/var/folders/xq/wktq4zdx4jd3qdpk34d28m940000gn/T/Rtmp7sAM9p/R.INSTALL71b1ac713c8/lightgbm/src/src/lightgbm_R.cpp:722:41: warning: cast between incompatible function types from 'SEXPREC* (*)(LGBM_SE, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)' {aka 'SEXPREC* (*)(LGBM_SER*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*)'} to 'DL_FUNC' {aka 'void* (*)()'} [-Wcast-function-type]
  722 |   {"LGBM_BoosterPredictForMat_R"      , (DL_FUNC) &LGBM_BoosterPredictForMat_R      , 11},
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/xq/wktq4zdx4jd3qdpk34d28m940000gn/T/Rtmp7sAM9p/R.INSTALL71b1ac713c8/lightgbm/src/src/lightgbm_R.cpp:723:41: warning: cast between incompatible function types from 'SEXPREC* (*)(LGBM_SE, SEXP, SEXP, SEXP)' {aka 'SEXPREC* (*)(LGBM_SER*, SEXPREC*, SEXPREC*, SEXPREC*)'} to 'DL_FUNC' {aka 'void* (*)()'} [-Wcast-function-type]
  723 |   {"LGBM_BoosterSaveModel_R"          , (DL_FUNC) &LGBM_BoosterSaveModel_R          , 4},
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/xq/wktq4zdx4jd3qdpk34d28m940000gn/T/Rtmp7sAM9p/R.INSTALL71b1ac713c8/lightgbm/src/src/lightgbm_R.cpp:724:41: warning: cast between incompatible function types from 'SEXPREC* (*)(LGBM_SE, SEXP, SEXP)' {aka 'SEXPREC* (*)(LGBM_SER*, SEXPREC*, SEXPREC*)'} to 'DL_FUNC' {aka 'void* (*)()'} [-Wcast-function-type]
  724 |   {"LGBM_BoosterSaveModelToString_R"  , (DL_FUNC) &LGBM_BoosterSaveModelToString_R  , 3},
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/xq/wktq4zdx4jd3qdpk34d28m940000gn/T/Rtmp7sAM9p/R.INSTALL71b1ac713c8/lightgbm/src/src/lightgbm_R.cpp:725:41: warning: cast between incompatible function types from 'SEXPREC* (*)(LGBM_SE, SEXP, SEXP)' {aka 'SEXPREC* (*)(LGBM_SER*, SEXPREC*, SEXPREC*)'} to 'DL_FUNC' {aka 'void* (*)()'} [-Wcast-function-type]
  725 |   {"LGBM_BoosterDumpModel_R"          , (DL_FUNC) &LGBM_BoosterDumpModel_R          , 3},
```

One such warning is generated for each entry in this list of routines:

https://github.com/microsoft/LightGBM/blob/08d1ce4bbf9391f5cc945f5f015840f4a57774a6/R-package/src/lightgbm_R.cpp#L684

## Reproducible example

Follow https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#install, using `gcc` on Mac or Linux, or MinGW on Windows.

This warning does not appear to show up when using `MSVC` or `clang`.

This warning does not appear when using the CRAN-based installation method (https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#installing-the-cran-package).

I've observed this warning with  `gcc` 10, on both R 3.6.3  and R 4.0.5.

## Additional Comments

* based on these previous discussions:
    - https://github.com/microsoft/LightGBM/pull/4265#issuecomment-836760440
    -  https://github.com/microsoft/LightGBM/issues/3016#issue-605212323
    - https://github.com/microsoft/LightGBM/pull/3009#issuecomment-617219336
* the following searches on the unofficial CRAN mirror at github.com/cran can be used to inspect how other packages that use a C++ source file (`.cc` or `.cpp`) instead of a CC source file (`.c`) do this
    - https://github.com/search?q=R_CallMethodDef+org%3Acran+filename%3A*.cpp
    - https://github.com/search?q=R_CallMethodDef+org%3Acran+filename%3A*.cc

### PR DESCRIPTION
**Pull request by jameslamb**
This PR fixes #4273. It proposes suppressing this warning on CMake-based builds of the R package using `gcc` or `MinGW`:

```text
warning: cast between incompatible function types from 'SEXPREC* (*)(LGBM_SE, SEXP, SEXP)' {aka 'SEXPREC* (*)(LGBM_SER*, SEXPREC*, SEXPREC*)'} to 'DL_FUNC' {aka 'void* (*)()'} [-Wcast-function-type]
```

This PR proposes suppressing this warning specifically for the portion of `lightgbm_R.cpp` that handles routine registration. The pattern used in {lightgbm} is exactly the same one used in many other R packages on CRAN (https://github.com/search?q=R_CallMethodDef+org%3Acran+filename%3A*.cpp), and the extensive unit tests covering the package give me confidence that this isn't causing any issues.

I think that removing this warning is useful because it remove unnecessary noise from users' logs and might prevent users who are trying to debug installations issues from spending time focused on warnings that are not actually problematic.

### Notes for reviewers

See #4273 for more details on this warning.

See https://cran.r-project.org/doc/manuals/r-release/R-exts.html#useDynLib and the description in #4155 for more background information on how routine registration in R packages works.

CRAN does have a rule preventing the of pragmas that suppress warnings, but the pragmas introduced in this PR will be removed when preparing a CRAN package.

https://github.com/microsoft/LightGBM/blob/08d1ce4bbf9391f5cc945f5f015840f4a57774a6/build-cran-package.sh#L94

### CODE REVIEW

**Comment by jameslamb** [comment]
I've converted this back to a draft. It seems `R CMD check` is unhappy with the use of this pragma.

All CMake-based builds from https://github.com/microsoft/LightGBM/pull/4274/checks?check_run_id=2550215720 are failing with this warning.

```text
* checking pragmas in C/C++ headers and code ... WARNING

File which contains non-portable pragma(s)

  'src/src/lightgbm_R.cpp'

File which contains pragma(s) suppressing diagnostics:

  'src/src/lightgbm_R.cpp'
```

The `MinGW` + R 3.6 build (but not the `MinGW` + R 4.0 build) also has this warning:

```text
D:\a\LightGBM\LightGBM\lightgbm.Rcheck\00_pkg_src\lightgbm\src\src\lightgbm_R.cpp:684:32: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]

 #pragma GCC diagnostic ignored "-Wcast-function-type"
```

link: https://github.com/microsoft/LightGBM/pull/4274/checks?check_run_id=2550215720

and `clang` builds have this

```text
/home/runner/work/LightGBM/LightGBM/lightgbm.Rcheck/00_pkg_src/lightgbm/src/src/lightgbm_R.cpp:684:32: warning: unknown warning group '-Wcast-function-type', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wcast-function-type"
                               ^
1 warning generated.
```

link: https://github.com/microsoft/LightGBM/pull/4274/checks?check_run_id=2550215599

So now I think that maybe it would be better to suppress this from the CMake side (but only for the R package).

**Comment by jameslamb** [comment]
Ok I think this has successfully suppressed this warning, and this PR is ready for review.

* `gcc` build on Linux: https://github.com/microsoft/LightGBM/pull/4274/checks?check_run_id=2550765412
* `gcc` build on Mac: https://github.com/microsoft/LightGBM/pull/4274/checks?check_run_id=2550765499
* `MinGW` build on Windows: https://github.com/microsoft/LightGBM/pull/4274/checks?check_run_id=2550765617

**Comment by StrikerRUS** [comment]
@jameslamb 
Is this PR ready for review or supposed to be revised after the discussion with @david-cortes  in #4273?

**Comment by jameslamb** [comment]
I think it can be reviewed. I interpreted the most recent comment in that discussion, https://github.com/microsoft/LightGBM/issues/4273#issuecomment-840198834 , as saying "ok actually it's not related to use or missing use of `extern C`", so I can't think of other things to try.

Given the wide range of operating system + R version + compiler versions the R package is tested against, I'm fairly confident that this warning can be ignored and that it would improve the user experience to suppress it.

**Review by StrikerRUS — APPROVED** [review]
I've checked all CI logs to make sure that proposed if condition doesn't leave uncovered cases.
And I'm OK to ignore this warning.

**Comment by jameslamb** [comment]
> I've checked all CI logs to make sure that proposed if condition doesn't leave uncovered cases.
> And I'm OK to ignore this warning.

ok thanks very much!

**Pull request merged**
