### PR TITLE
Add `make install` rules

### PR DESCRIPTION
**Pull request by henry0312**

### CODE REVIEW

**Comment by guolinke** [comment]
@henry0312  can you provide the function about and the reason to do this?

**Comment by henry0312** [comment]
@guolinke This PR allows us to install bin, lib and includes where we want, instead of the root directory of LightGBM repository.
Some users would like to install lightgbm to a location in `$PATH`.

Example:

```sh
$ mkdir build; cd build

$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tsukasa_omoto/.ghq/github.com/henry0312/LightGBM/build

$ make -j install
Scanning dependencies of target lightgbm
Scanning dependencies of target _lightgbm
<snip...>
[ 97%] Linking CXX shared library ../../lib_lightgbm.so
[ 97%] Built target _lightgbm
[100%] Linking CXX executable ../../lightgbm
[100%] Built target lightgbm
Install the project...
-- Install configuration: ""
-- Installing: /home/tsukasa_omoto/local/bin/lightgbm
-- Installing: /home/tsukasa_omoto/local/lib/lib_lightgbm.so
-- Up-to-date: /home/tsukasa_omoto/local/include/LightGBM
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/tree.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/tree_learner.h
-- Up-to-date: /home/tsukasa_omoto/local/include/LightGBM/utils
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/utils/array_args.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/utils/common.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/utils/threading.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/utils/text_reader.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/utils/pipeline_reader.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/utils/random.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/utils/log.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/c_api.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/boosting.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/network.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/dataset.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/metric.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/dataset_loader.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/meta.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/feature.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/config.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/application.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/bin.h
-- Installing: /home/tsukasa_omoto/local/include/LightGBM/objective_function.h
```

**Comment by guolinke** [comment]
What will happen if forget to set ```-DCMAKE_INSTALL_PREFIX=...``` ?

**Comment by henry0312** [comment]
The default value of `CMAKE_INSTALL_PREFIX` is `/usr/local`.
(Note: bin, lib and include will be installed only when run `make install`)

**Comment by guolinke** [comment]
I see. Thanks very much.

**Pull request merged**
