### PR TITLE
[docs][R-package] Update the explanation of num_threads (fixes #4192)

### LINKED ISSUE #4192: [R-package] Quick question about num of thread
Hi, Thank you for making lightGBM in R!

I am using LightGBM in R and have a quick question about the `num_thread`. 

According to the [manual](https://lightgbm.readthedocs.io/en/latest/R/reference/lightgbm.html), the number of threads is the physical core of CPU. But usually what I have seen in my R code, set the num thread is equal to num_thread - 1 such as

```r
cores <- parallel::detectCores() -1
cores
```

So if we have 4 core, use 3 for parallel and 1 for the controller. Is this applied to LightGBM too? So if I have 4 physical core of CPU and set the number of thread as 3?

### PR DESCRIPTION
**Pull request by issactoast**
Hi @jameslamb 

Here is the PR related to the issue #4192. Please check out the update!

Best,
Issac

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks very much for this!

Sorry I didn't check earlier, but there are two other places with this same bit of documentation. Can you please update these as well?

* https://github.com/microsoft/LightGBM/blob/69d02e387a6f4516b991665c9f6ac1378c695492/R-package/R/lgb.cv.R#L48
* https://github.com/microsoft/LightGBM/blob/69d02e387a6f4516b991665c9f6ac1378c695492/R-package/R/lgb.train.R#L21

**Comment by issactoast** [comment]
@jameslamb Sure, will do that, but just wonder what's the difference between LightGBM/lightgbm_r and LightGBM/R-package? I know the latter is the r package but what's the lightgbm_r? That folder has the same three files lgb.cv.R, lgb.train.R, and lightgbm.R

**Comment by jameslamb** [comment]
Oh sure, I can explain. The R package wraps C/C++ code stored in `src/`, `include/`, and `external_libs/`. So to build the R package, you have to copy all that code into the correct location inside the R package's file structure.

To do that, the R build scripts (`build-cran-package.sh` for autoconf-based builds and `build_r.R` for CMake-based builds) create a new folder, `lightgbm_r`, and copy `R-package/` plus all those C/C++ files into it at build time. I think it will be clearer if you inspect those build scripts.

`lightgbm_r` is not actually checked into the repo, as it is ignored by `gitignore`. So you do not need to change aything in that directory.

Let me know if you have other questions! We'd love to have you contribute more to the R package in the future of you're interested, and understanding this setup might help you do that.

**Comment by issactoast** [comment]
Thank you for the explanation! Yes, I would like to add some contributions to the LGBM if I could! :) I will ask if I have some questions related to the package!

**Review by jameslamb — APPROVED** [review]
Looks great, thanks very much!

**Pull request merged**
