### PR TITLE
Continued work on position unbiased ranking

### PR DESCRIPTION
**Pull request by shiyu1994**
This is to replace #4531.

### CODE REVIEW

**Comment by jameslamb** [comment]
@shiyu1994 it's been 8 months since the last commit on this PR. Are you interested in pursuing it still? If you think it's valuable but don't have time yourself to work on it, could you find someone else at Microsoft who might be able to help?

**Comment by jameslamb** [comment]
Updating my question from https://github.com/microsoft/LightGBM/pull/5393#issuecomment-1445218688.

@shiyu1994 it's now been **almost a year** since the last commit on this PR. Are you interested in pursuing it still? If you think it's valuable but don't have time yourself to work on it, could you find someone else at Microsoft who might be able to help? And how does it relate to #5929 ?

I'm trying to help but from the conversation in #5929, it feels to me like maybe you have a plan for learning-to-rank in LightGBM that's being discussed in private places and that I'm not aware of.

**Comment by shiyu1994** [comment]
@jameslamb This PR and #5929 are two different approaches to support unbiased ranking. The underlying algorithms are different. We think the method in #5929 is better. So, we prioritize that PR.

**Comment by jameslamb** [comment]
Got it, ok thanks!

Could we add a link to this PR in the list of feature requests (#2302) and close it for now? Since it's not actively being worked on.

**Comment by shiyu1994** [comment]
> Got it, ok thanks!
> 
> Could we add a link to this PR in the list of feature requests (#2302) and close it for now? Since it's not actively being worked on.

Sure.

**Pull request closed without merging**
