### PR TITLE
[docs] Add alt text on images in index.rst

### PR DESCRIPTION
**Pull request by marcelonieva7**
Add alt text to logo image, as part of #4028

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Thanks for doing this!

I edited the title of this pull request to make it more specific. I also added a link to https://github.com/microsoft/LightGBM/issues/4028 in the PR description. When you make a contribution related to a discussion in an existing issue, it's useful to link to that issue so maintainers have enough context to understand why you're proposing the change.

**Comment by jameslamb** [comment]
Do not worry about the failing job `CUDA Version / cuda 10.0 pip (linux, clang, Python 3.8) (pull_request)`. It is unrelated to your changes, and I'll handle fixing it.

**Review by StrikerRUS — APPROVED** [review]

**Comment by jameslamb** [comment]
@marcelonieva7 I apologize for the inconvenience, but could you please merge in the latest changes from `master`? We recently merged some fixes for failing continuous integration jobs (#4032). We can merge this as soon as that's done.

**Comment by jameslamb** [comment]
I just updated this branch with the latest changes from `master`. Will merge this once CI jobs pass.

**Comment by jameslamb** [comment]
Thanks very much for your contribution!

**Pull request merged**
