### PR TITLE
fix load model bug from mape objective

### LINKED ISSUE #1461: "Unknown objective type name: mape" for sklearn api on regression task
The `LGBMRegressor.fit` method seems to malfunction when objective is `mape`.

## Environment info
Operating System:
macOS 10.12.3
Python version: 3.6.1

## Error Message:
```
LightGBMError                             Traceback (most recent call last)
<ipython-input-8-6d3a4e240b5c> in <module>()
      2         eval_set=[(X_test, y_test)],
      3         eval_metric='l1',
----> 4         early_stopping_rounds=5)

~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/sklearn.py in fit(self, X, y, sample_weight, init_score, eval_set, eval_names, eval_sample_weight, eval_init_score, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
    612                                        verbose=verbose, feature_name=feature_name,
    613                                        categorical_feature=categorical_feature,
--> 614                                        callbacks=callbacks)
    615         return self
    616

~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/sklearn.py in fit(self, X, y, sample_weight, init_score, group, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_group, eval_metric, early_stopping_rounds, verbose, feature_name
, categorical_feature, callbacks)
    467                               verbose_eval=verbose, feature_name=feature_name,
    468                               categorical_feature=categorical_feature,
--> 469                               callbacks=callbacks)
    470
    471         if evals_result:

~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep
_training_booster, callbacks)
    223         booster.best_score[dataset_name][eval_name] = score
    224     if not keep_training_booster:
--> 225         booster._load_model_from_string(booster._save_model_to_string(), False)
    226         booster.free_dataset()
    227     return booster

~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/basic.py in _load_model_from_string(self, model_str, verbose)
   1679             c_str(model_str),
   1680             ctypes.byref(out_num_iterations),
-> 1681             ctypes.byref(self.handle)))
   1682         out_num_class = ctypes.c_int(0)
   1683         _safe_call(_LIB.LGBM_BoosterGetNumClasses(

~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/basic.py in _safe_call(ret)
     46     """
     47     if ret != 0:
---> 48         raise LightGBMError(_LIB.LGBM_GetLastError())
     49
     50

LightGBMError: b'Unknown objective type name: mape'
```

## Reproducible examples

```py
# coding: utf-8
# pylint: disable = invalid-name, C0111
import lightgbm as lgb
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV

# load or create your dataset
print('Load data...')
df_train = pd.read_csv('../regression/regression.train', header=None, sep='\t')
df_test = pd.read_csv('../regression/regression.test', header=None, sep='\t')

y_train = df_train[0].values
y_test = df_test[0].values
X_train = df_train.drop(0, axis=1).values
X_test = df_test.drop(0, axis=1).values

print('Start training...')
# train
gbm = lgb.LGBMRegressor(objective='regression',
                        num_leaves=31,
                        learning_rate=0.05,
                        n_estimators=20)
gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric='l1',
        early_stopping_rounds=5)

# The above is the example directly from the repo.
# The following codes just have the objective changed to `mape`  

gbm = lgb.LGBMRegressor(objective='mape',
                        num_leaves=31,
                        learning_rate=0.05,
                        n_estimators=20)
gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric='l1',
        early_stopping_rounds=5)
```

## Steps to reproduce

1. Run the example code.
2. The model is training without problem, printing eval_metric each round
3. But at the end of the training, it will throw error and the result is not saved

### PR DESCRIPTION
**Pull request by guolinke**
fix #1461

### CODE REVIEW

**Comment by everdark** [comment]
Hi, 

Thanks for the quick response to the issue I opened (https://github.com/Microsoft/LightGBM/issues/1461)
Just want to provide some more information on the patch.
I re-compile and install the package using this patch but it results in another error:

```
[LightGBM] [Warning] Using self-defined objective function
[LightGBM] [Fatal] No object function provided
---------------------------------------------------------------------------
LightGBMError                             Traceback (most recent call last)
<ipython-input-7-6e87b65b1198> in <module>()
      1 gbm.fit(X_train, y_train,
      2         eval_set=[(X_test, y_test)],
----> 3         early_stopping_rounds=5)

~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/sklearn.py in fit(self, X, y, sample_weight, init_score, eval_set, eval_names, eval_sample_weight, eval_init_score, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
    632                                        verbose=verbose, feature_name=feature_name,
    633                                        categorical_feature=categorical_feature,
--> 634                                        callbacks=callbacks)
    635         return self
    636

~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/sklearn.py in fit(self, X, y, sample_weight, init_score, group, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_group, eval_metric, early_stopping_rounds, verbose, feature_nam$
, categorical_feature, callbacks)
    472                               verbose_eval=verbose, feature_name=feature_name,
    473                               categorical_feature=categorical_feature,
--> 474                               callbacks=callbacks)
    475
    476         if evals_result:

~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, kee$
_training_booster, callbacks)
    202                                     evaluation_result_list=None))
    203
--> 204         booster.update(fobj=fobj)
    205
    206         evaluation_result_list = []

~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/basic.py in update(self, train_set, fobj)
   1526             _safe_call(_LIB.LGBM_BoosterUpdateOneIter(
   1527                 self.handle,
-> 1528                 ctypes.byref(is_finished)))
   1529             self.__is_predicted_cur_iter = [False for _ in range_(self.__num_dataset)]
   1530             return is_finished.value == 1

~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lightgbm/basic.py in _safe_call(ret)
     47     """
     48     if ret != 0:
---> 49         raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
     50
     51

LightGBMError: No object function provided
```

It seems that now the training is not started at all since it consider there should be a customized loss function (but in fact there is none).

**Comment by guolinke** [comment]
BTW, the code actually didn't run to that function you edited, which is called after training finished.
The objective for training is constructed at: https://github.com/Microsoft/LightGBM/blob/bced66834cd70f3edc4cd7696fd02bc3fd944429/src/objective/objective_function.cpp#L10-L47 

I think there are some compiling issue, can you try to delete and then re-install python-package?

**Comment by everdark** [comment]
@guolinke I `pip uninstall` the package before re-install it using setup.py on the edited local branch.
I do edit both functions in `objective_function.cpp` to have the same order. And yes I run the sample code as in https://github.com/Microsoft/LightGBM/issues/1461

**Comment by guolinke** [comment]
@everdark just run it without error in Windows, with this fix:
image

BTW, I run it in the root of LightGBM folder, instead of LightGBM/python-package, since there is a `lightgbm` folder there, which may cause the import error.

**Comment by guolinke** [comment]
@everdark please let me know if the issue still not fixed.

**Pull request merged**
