### PR TITLE
fix RF's bug with MAPE & support RF with multi-class

### LINKED ISSUE #881: Multi-class Random forest support
I suppose I missed to specify some parameter, but I can't figure which one.

```
from lightgbm.sklearn import LGBMClassifier
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target

clf = LGBMClassifier(boosting_type='rf', bagging_fraction=0.5, feature_fraction=0.5)
clf.fit(X, y)
```

Error:
```
---------------------------------------------------------------------------
LightGBMError                             Traceback (most recent call last)
<ipython-input-1-734db61b74f4> in <module>()
      7 
      8 clf = LGBMClassifier(boosting_type='rf', bagging_fraction=0.5, feature_fraction=0.5)
----> 9 clf.fit(X, y)

C:\Program Files\Anaconda3\lib\site-packages\lightgbm\sklearn.py in fit(self, X, y, sample_weight, init_score, eval_set, eval_names, eval_sample_weight, eval_init_score, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
    557                                         verbose=verbose, feature_name=feature_name,
    558                                         categorical_feature=categorical_feature,
--> 559                                         callbacks=callbacks)
    560         return self
    561 

C:\Program Files\Anaconda3\lib\site-packages\lightgbm\sklearn.py in fit(self, X, y, sample_weight, init_score, group, eval_set, eval_names, eval_sample_weight, eval_init_score, eval_group, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
    405                               verbose_eval=verbose, feature_name=feature_name,
    406                               categorical_feature=categorical_feature,
--> 407                               callbacks=callbacks)
    408 
    409         if evals_result:

C:\Program Files\Anaconda3\lib\site-packages\lightgbm\engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
    178     """construct booster"""
    179     try:
--> 180         booster = Booster(params=params, train_set=train_set)
    181         if is_valid_contain_train:
    182             booster.set_train_data_name(train_data_name)

C:\Program Files\Anaconda3\lib\site-packages\lightgbm\basic.py in __init__(self, params, train_set, model_file, silent)
   1251                 train_set.construct().handle,
   1252                 c_str(params_str),
-> 1253                 ctypes.byref(self.handle)))
   1254             """save reference to data"""
   1255             self.train_set = train_set

C:\Program Files\Anaconda3\lib\site-packages\lightgbm\basic.py in _safe_call(ret)
     46     """
     47     if ret != 0:
---> 48         raise LightGBMError(_LIB.LGBM_GetLastError())
     49 
     50 

LightGBMError: b'Check failed: num_tree_per_iteration_ == 1 at d:\\users\\nekit\\downloads\\test\\lightgbm\\python-package\\lightgbm\\src\\boosting\\rf.hpp, line 41 .\n'
```

All params:
```
{'bagging_fraction': 0.5,
 'boosting_type': 'rf',
 'colsample_bytree': 1,
 'feature_fraction': 0.5,
 'learning_rate': 0.1,
 'max_bin': 255,
 'max_depth': -1,
 'min_child_samples': 10,
 'min_child_weight': 5,
 'min_split_gain': 0,
 'n_estimators': 10,
 'n_jobs': -1,
 'num_leaves': 31,
 'objective': 'multiclass',
 'random_state': 0,
 'reg_alpha': 0,
 'reg_lambda': 0,
 'silent': True,
 'subsample': 1,
 'subsample_for_bin': 50000,
 'subsample_freq': 1}
```

### LINKED ISSUE #1579: dart and random forest cannot correctly use MAPE objective
I'm trying to use random forest and dart to make regression prediction.
Due to competition requirement, I shifted my labels by 2, range from 0-1 shifted to 2-3.
(like the original label is 0.4, now it's 2.4)
However, when I use random forest/dart as boosting, MAE/mape as objective to make prediction, the prediction still falls in the range of 0-1.
I tried random forest as boosting, rmse as objective. The result successfully fell into the range of 2-3.
I tried gbdt as boosting. The result also successfully fell into the range of 2-3.

Below is my parameter, I change rf to gbdt for test.

params = {
      'task'                 : 'train',
      'boosting_type'        : 'rf',
      'objective'            : 'mape',
      'learning_rate'        : 0.01,
      'metric'               : {'mape'},
      'n_estimators'         : 500,
      'num_leaves'           : 5000,
      'max_depth'            : 10,
      'feature_fraction'     : 0.8,
      'feature_fraction_seed': 2,
      'bagging_fraction'     : 0.8,
      'min_data_in_leaf'     : 1,
      'verbose'              : 0,
      'bagging_freq'         : 1,
      'early_stopping_round': 500
    }
C++/Python/R version:
python 36

I think there might be something not going well between tree models and MAE/MAPE objective?
Help appreciated!

### PR DESCRIPTION
**Pull request by guolinke**
fix #1579 
fix #881

### CODE REVIEW

**Comment by guolinke** [comment]
@zhongxurpac and @LucasMaron 
can you help to test the RF's result ? 
For the dart, I am not sure why it will have this issue, can you provide some re-produce samples ?

**Comment by guolinke** [comment]
result comparison:
gbdt:
```
>>> X, y = load_boston(True)
>>> params = {
...     'boosting_type': 'gbdt',
...     'objective': 'mape',
...     'verbose': -1,
...     'bagging_freq': 1,
...     'bagging_fraction': 0.8,
...     'feature_fraction': 0.8,
...     'boost_from_average': False,
... }
>>> y_mean = y.mean()
>>> print(y_mean)
22.5328063241
>>> lgb_train = lgb.Dataset(X, y)
>>> evals_result = {}
>>> gbm = lgb.train(params, lgb_train,
...                 num_boost_round=100,
...                 verbose_eval=False,
...                 evals_result=evals_result)
>>> pred = gbm.predict(X)
>>> pred_mean = pred.mean()
>>> print(pred_mean)
21.6314628123
```

rf
```
>>> X, y = load_boston(True)
>>> params = {
...     'boosting_type': 'rf',
...     'objective': 'mape',
...     'verbose': -1,
...     'bagging_freq': 1,
...     'bagging_fraction': 0.8,
...     'feature_fraction': 0.8,
...     'boost_from_average': False,
... }
>>> y_mean = y.mean()
>>> print(y_mean)
22.5328063241
>>> lgb_train = lgb.Dataset(X, y)
>>> evals_result = {}
>>> gbm = lgb.train(params, lgb_train,
...                 num_boost_round=100,
...                 verbose_eval=False,
...                 evals_result=evals_result)
>>> pred = gbm.predict(X)
>>> pred_mean = pred.mean()
>>> print(pred_mean)
21.2916233916
```



dart
```
>>> X, y = load_boston(True)
>>> params = {
...     'boosting_type': 'dart',
...     'objective': 'mape',
...     'verbose': -1,
...     'bagging_freq': 1,
...     'bagging_fraction': 0.8,
...     'feature_fraction': 0.8,
...     'boost_from_average': False,
... }
>>> y_mean = y.mean()
>>> print(y_mean)
22.5328063241
>>> lgb_train = lgb.Dataset(X, y)
>>> evals_result = {}
>>> gbm = lgb.train(params, lgb_train,
...                 num_boost_round=100,
...                 verbose_eval=False,
...                 evals_result=evals_result)
>>> pred = gbm.predict(X)
>>> pred_mean = pred.mean()
>>> print(pred_mean)
19.1290921058
```

**Comment by StrikerRUS** [comment]
@guolinke Wow, great news about multiclass RF!

Maybe add your [snippet](https://github.com/Microsoft/LightGBM/pull/1637#issuecomment-419628830) to tests?

**Comment by guolinke** [comment]
@StrikerRUS any other problems?

**Comment by StrikerRUS** [comment]
@guolinke Nope. Sorry, forgot to click "Approve".

Lets wait the response from @zhongxurpac and @LucasMaron

**Comment by guolinke** [comment]
@zhongxurpac @LucasMaron, I will merge this PR first. feel free to reopen the issues if still having problems.

**Pull request merged**
