### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by StrikerRUS**
Welcome Belinda!

I'm very glad you've agreed to join us!

Thank you!

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@btrotta 
BTW, feel free to add yourself to any other sections.

**Comment by btrotta** [comment]
Thanks everyone for being so welcoming!

**Comment by StrikerRUS** [comment]
@btrotta I can't find your email. Guess you're keeping it private. Can you please send it to my email, so that we'll be able to invite you in our dev Slack?

To make life for spam bots harder pasting a screenshot here:

image

**Comment by btrotta** [comment]
@StrikerRUS Thanks, I sent you an email

**Comment by StrikerRUS** [comment]
@btrotta Got it, thanks!

@guolinke Seems that I cannot send an invitation without your approval. Please check Slack.

**Pull request merged**
