### PR TITLE
[ci][SWIG] update SWIG version and use separate CI job to produce SWIG artifacts

### LINKED ISSUE #3716: Use latest SWIG version to build jar artifacts
https://github.com/microsoft/LightGBM/blob/d1014ea64e577921112160b2fe3cb018174861d7/.ci/setup.sh#L18
https://github.com/microsoft/LightGBM/pull/3477#issuecomment-714560441

### PR DESCRIPTION
**Pull request by StrikerRUS**
Closed #3716.

@imatiach-msft Hi! Could you please help to review this PR?

I'm attaching links to Windows and macOS artifacts to this message (GitHub doesn't allow attaching archives directly due to filetype restrictions), so that you are able to test them. I'm not attaching Linux artifact here, because updating SWIG for Linux requires more actions in https://github.com/guolinke/lightgbm-ci-docker. But it should be quite straightforward if you find artifacts for other OSes generally OK with new SWIG version. But feel free to ask for Linux artifact as well if you need to test it.

https://github.com/microsoft/LightGBM/releases/download/v2.0.12/lightgbmlib_macos.jar
https://github.com/microsoft/LightGBM/releases/download/v2.0.12/lightgbmlib_win.jar

### CODE REVIEW

**Comment by StrikerRUS** [comment]
gently ping @imatiach-msft

**Review by imatiach-msft — APPROVED** [review]
This looks great, thank you for updating SWIG version!  Just checking, will I still be able to get SWIG artifacts on every build on master after this PR?

**Comment by imatiach-msft** [comment]
Just took a look at both the jar files for windows and mac, they look great to me, thank you!

**Review by jameslamb — APPROVED** [review]

**Comment by StrikerRUS** [comment]
@imatiach-msft Thank you very much for trying new artifacts! Glad they are working!

> Just checking, will I still be able to get SWIG artifacts on every commit build on master after this PR?

Yeah, absolutely! Nothing is changing related to artifacts side. I only moved SWIG part to a separate job with the aim to make code and process clearer. Same environment, same checks for linked libraries versions, same artifacts, same names, etc.


The only thing I want to make you aware is that Docker changes with SWIG updates can take some time. So it is possible that some commits in the nearest future right after merging this PR will produce inconsistent artifacts. I mean, macOS and Windows will be built with SWIG**4**, while Linux artifacts will still be using SWIG**3**. I hope it will not take more than 1-2 days. And I'll ping you after sync will be finished.

**Comment by StrikerRUS** [comment]
@imatiach-msft Well, Docker has been successfully built!
It means that all next commits to the `master` branch after 4007b34fa83043cc30c2ec3c8cf2c7b059f07fec will be producing artifacts generated with SWIG version 4 for all OSes.

image


Feel free to ping me in case of any issues. We can rollback SWIG version bumping any time.

**Pull request merged**
