### PR TITLE
sklearn compatibility update- renames .feature_importance_ to .featur…

### PR DESCRIPTION
**Pull request by ClimbsRocks**
…e_importances_

My editor is set up to remove extraneous hanging whitespaces, so you'll see a fair bit of that edited in the docs file. 

Otherwise, simply changes .feature_importance_ to .feature_importances_ to stay consistent with scikit-learn's API, fixing https://github.com/Microsoft/LightGBM/issues/199

### CODE REVIEW

**Comment by wxchan** [comment]
what editor are you using?

**Comment by ClimbsRocks** [comment]
Sublime Text

**Comment by guolinke** [comment]
@wxchan can I merge it ?

**Comment by chivee** [comment]
@guolinke although it is a API breaking, but it is safe to merge

**Pull request merged**
