### PR TITLE
support kwargs for sklearn

### PR DESCRIPTION
**Pull request by wxchan**
#575

### CODE REVIEW

**Comment by guolinke** [comment]
we can add a link to the parameter.md for the comment of kwargs

**Comment by guolinke** [comment]
@wxchan 
Thanks very much.
BTW, Do these api document need to update ?

**Comment by wxchan** [comment]
I updated docstrings, will it be auto-updated? I don't know either.

**Comment by guolinke** [comment]
@wxchan I mean this file: https://github.com/Microsoft/LightGBM/blob/master/docs/Python-API.md
I think it cannot be auto updated. 
The ReadTheDocs build its own documents. So, Maybe it is better for us to delete that document? or put a link to the readTheDocs ?

**Comment by wxchan** [comment]
it's inconvenient to update them manually. maybe delete them is better.

**Pull request merged**
