### PR TITLE
[ci] fix linkchecker job

### LINKED ISSUE #6756: [ci] Link check job is broken
> Error: Config file .linkcheckerrc does not exist.
Execute '/home/runner/miniforge/envs/test-env/bin/linkchecker -h' for help

https://github.com/microsoft/LightGBM/actions/runs/12328181037/job/34411048698#step:3:3749

Job and config file:

https://github.com/microsoft/LightGBM/blob/b33a12ea3883f306388e69f12ceb421b1ee7ec29/.github/workflows/linkchecker.yml#L14
https://github.com/microsoft/LightGBM/blob/b33a12ea3883f306388e69f12ceb421b1ee7ec29/.ci/test.sh#L147-L152
https://github.com/microsoft/LightGBM/blob/b33a12ea3883f306388e69f12ceb421b1ee7ec29/docs/.linkcheckerrc#L1

### PR DESCRIPTION
**Pull request by jameslamb**
Fixes #6756

The relative path we pass to its config file needs to be updated (I think I broke this in #6497).

### How I tested this

Manually triggered the link check workflow from this branch: 

* first build: https://github.com/microsoft/LightGBM/actions/runs/12335479058
* after config changes from https://github.com/microsoft/LightGBM/pull/6757#pullrequestreview-2504292757: https://github.com/microsoft/LightGBM/actions/runs/12335867947
* setting `threads=10`: https://github.com/microsoft/LightGBM/actions/runs/12336243590
* setting `threads=4`: https://github.com/microsoft/LightGBM/actions/runs/12336463177

### CODE REVIEW

**Review by StrikerRUS — APPROVED** [review]
It works now, thanks a lot for quick fix!

As for the
```
Warning    [http-rate-limited] Rate limited (Retry-After: None)
Result     Valid: 429 Too Many Requests
```
errors, could you please try decreasing the `maxrequestspersecond` for one host to `0.1`?

https://github.com/microsoft/LightGBM/blob/b33a12ea3883f306388e69f12ceb421b1ee7ec29/docs/.linkcheckerrc#L2
Refer to
- https://github.com/microsoft/LightGBM/pull/3785#issuecomment-762481558
- https://linkchecker.github.io/linkchecker/man/linkcheckerrc.html#checking
> Values less than 1 and at least 0.001 can be used.

It's now possible to use values less than 1.

**Comment by jameslamb** [comment]
Just pushed https://github.com/microsoft/LightGBM/pull/6757/commits/52657867d508f258445d9bbb3fae227bafec3e98 with that change. I also put a floor on `linkchecker` pointing at the latest version... to be sure we always get a version that respects values less than 1 and to make installation a little faster.

Thanks for the references and the suggestion! That saved me some effort figuring out how to get around those errors 😊 

new test build: https://github.com/microsoft/LightGBM/actions/runs/12335867947

**Comment by StrikerRUS** [comment]
> new test build

In case of successful run, we can try to increase `threads` up to max `10`, I guess.
https://github.com/microsoft/LightGBM/blob/a924516d0d24d7167c6e99f44946e42e9e0e60e0/docs/.linkcheckerrc#L6

I hope that linkchecker ensures that requests to one host are done from the single thread.
https://github.com/linkchecker/linkchecker/issues/193

**Comment by jameslamb** [comment]
Oh interesting, yeah hopefully that tool divides the hosts across threads instead of just dividing links. Pushed https://github.com/microsoft/LightGBM/pull/6757/commits/4061211e76245e62f9986abc953d8507258d00ce setting `threads=10`, let's see how it goes: https://github.com/microsoft/LightGBM/actions/runs/12336243590

**Comment by jameslamb** [comment]
It's still taking a very long time with `nthreads=10`... maybe even slower than with `nthreads=1`: https://github.com/microsoft/LightGBM/actions/runs/12336243590/job/34428554660

I guess because the GitHub Actions Linux runners only have 4 vCPUS: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

`nthreads=10` might be oversubscribing them (just like we see with LightGBM and recommend against:

https://github.com/microsoft/LightGBM/blob/1090a93b39e16f49621aa6824cd09d4390c3678a/R-package/R/lightgbm.R#L128-L130

Trying a build limiting to 4 threads: https://github.com/microsoft/LightGBM/actions/runs/12336463177

**Comment by StrikerRUS** [comment]
Heh, still 48 minutes with 4 threads...

Seems that `maxrequestspersecond` has higher priority over `threads` and they don't play well with each other 😞 

Anyway, we have successful cron job with less than 1 hour execution time that is run once a day. I believe it's totally fine and we shouldn't spend more time for the speedup!

**Comment by jameslamb** [comment]
> *we have successful cron job with less than 1 hour execution time that is run once a day. I believe it's totally fine and we shouldn't spend more time for the speedup!*

Yep I agree! I'll merge this.

**Pull request merged**
