### PR TITLE
[CUDA] Add feature interaction constraint for cuda_exp (fix #4785)

### LINKED ISSUE #4785: [CUDA] Feature Interaction Constraints on New CUDA Version
## Summary

#4630 implements a new version of CUDA tree learner which dispatch the whole training process of a tree to GPU.

Interaction constraints limit which features can be used in the same root-to-leaf path the decision trees in GBDT. It can be used to integrate prior knowledge about the dataset. It was first introduced into LightGBM by #3126

## Motivation

For similar reason with monotonic constraints in #4781, we need to support interaction constraints for the new CUDA version.

### PR DESCRIPTION
**Pull request by shiyu1994**
Add feature interaction constraint for `cuda_exp`. This is to fix #4785.

### CODE REVIEW

**Review by guolinke — APPROVED** [review]

**Comment by jameslamb** [comment]
@shiyu1994 did you use admin powers to merge this despite failing CI checks?

It looks like most CUDA CI jobs are failing.

https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true

Screen Shot 2022-09-07 at 11 19 52 AM

**Comment by shiyu1994** [comment]
[bba92b5](https://github.com/microsoft/LightGBM/pull/5474/commits/bba92b5480810a24ece6dbb3960d4aae3bc12c2f) has passed all the tests. And [a883479](https://github.com/microsoft/LightGBM/pull/5474/commits/a883479396975c2313fbf934c84c7752188e0c77) just changes a comment. And the tests failed simply because the branch is already merged.
```bash
Syncing repository: microsoft/LightGBM
[11](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:12)
git version
[12](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:13)
git version 2.17.1
[13](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:14)
git init "/home/guoke/actions-runner/_work/LightGBM/LightGBM"
[14](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:15)
Initialized empty Git repository in /home/guoke/actions-runner/_work/LightGBM/LightGBM/.git/
[15](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:16)
git remote add origin https://github.com/microsoft/LightGBM
[16](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:17)
git config gc.auto 0
[17](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:18)
git config --get-all http.https://github.com/microsoft/LightGBM.extraheader
[18](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:19)
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules --depth=5 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/5474/merge:refs/remotes/pull/5474/merge
[19](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:20)
Error: fatal: Couldn't find remote ref refs/pull/5474/merge
[20](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:21)
Warning: Git fetch failed with exit code 128, back off 3.858 seconds before retry.
[21](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:22)
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules --depth=5 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/5474/merge:refs/remotes/pull/5474/merge
[22](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:23)
Error: fatal: Couldn't find remote ref refs/pull/5474/merge
[23](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:24)
Warning: Git fetch failed with exit code 128, back off 4.857 seconds before retry.
[24](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:25)
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules --depth=5 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/5474/merge:refs/remotes/pull/5474/merge
[25](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:26)
Error: fatal: Couldn't find remote ref refs/pull/5474/merge
[26](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:27)
Error: Git fetch failed with exit code: 128
[27](https://github.com/microsoft/LightGBM/runs/8229456885?check_suite_focus=true#step:4:28)
Error: Exit code 1 returned from process: file name '/home/guoke/actions-runner/bin.2.296.1/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
```

**Comment by jameslamb** [comment]
oooo ok I see, thanks @shiyu1994 

I normally would say we should wait for all of CI to run successfully before merging, but I understand that you're actively working on this part of the code right now and all other non-CUDA CI passed, so I think it was ok this time.

**Comment by shiyu1994** [comment]
@jameslamb Thanks for your kind understanding.

**Comment by jameslamb** [comment]
thank YOU for all your woek on cuda_exp! really exciting to see the progress 😊

**Pull request merged**
