### PR TITLE
[dask] determine output shape of array in predict (fixes #4285)

### LINKED ISSUE #4285: [ci] Dask tests on Linux failing
## Description

Created from https://github.com/microsoft/LightGBM/pull/4283#issuecomment-840735651.

Python CI jobs in many Linux environments are failing with the following error for all Dask tests.

```text
>       from distributed.protocol.core import dumps_msgpack
E       ImportError: cannot import name 'dumps_msgpack' from 'distributed.protocol.core' (/root/miniconda/envs/test-env/lib/python3.7/site-packages/distributed/protocol/core.py)
```

examples:

* GitHub Actions (CUDA): https://github.com/microsoft/LightGBM/pull/4283/checks?check_run_id=2577306748
* Azure: https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=10070&view=logs&j=fb919173-48b9-522d-5342-9a59a13eb10b&t=7fcbeee5-d4c1-571c-8072-1d5874591254

## Additional Comments

It seems `dumps_msgpack` was removed in `distributed` version 2021.04.1, in https://github.com/dask/distributed/pull/4677.

https://github.com/dask/distributed/blob/4637099e2548a963197fdcc04e563401f77adef5/docs/source/changelog.rst#2021041

So I think the root issue is that `dask` 2021.4.0 is not compatible with `distributed` 2021.4.1.

This looks very similar to the situation https://github.com/microsoft/LightGBM/pull/4054, where incompatible versions of `dask` and `distributed` are uploaded to the official anaconda channel several days apart.

I can see the following versions getting installed in the failing builds:

```text
dask               pkgs/main/noarch::dask-2021.4.0-pyhd3eb1b0_0
dask-core          pkgs/main/noarch::dask-core-2021.4.0-pyhd3eb1b0_0
distributed        pkgs/main/linux-64::distributed-2021.4.1-py39h06a4308_0
...
dask-2021.4.0              |     pyhd3eb1b0_0           5 KB
dask-core-2021.4.0         |     pyhd3eb1b0_0         670 KB
distributed-2021.4.1       |   py37h06a4308_0         1.0 MB
```

I'm not sure how we're ending up with `distributed` 2021.4.1 though, or why this just started breaking. It seems `dask`, `dask-core`, and `distributed` haven't been updated in a few weeks, and the latest version for all of them is 2021.4.0.

https://anaconda.org/anaconda/dask

image

https://anaconda.org/anaconda/dask-core

image

https://anaconda.org/anaconda/distributed

image

### PR DESCRIPTION
**Pull request by jmoralez**
In more recent versions of dask (>2021.4.0) the tests for the predict method with dask arrays are failing. Following https://github.com/microsoft/LightGBM/pull/4307#issuecomment-854366737, I believe a change in dask array caused the current implementation to stop working.

This PR proposes determining the output shape of the array containing the predictions and being explicit about it in the call to `map_blocks`. Right now I'm computing the predictions for the first row of data, however this is failing for `test_classifier_pred_contrib[multiclass-classification-scipy_csr_matrix]` and as pointed out in https://github.com/microsoft/LightGBM/pull/4307#issuecomment-855162481 there could be better approaches.

### CODE REVIEW

**Comment by jameslamb** [comment]
@jmoralez what is your plan for this PR? I noticed it is still a draft...are you planning to propose a change that will get CI passing, or are you waiting for me to suggest one?

If `lightgbm` is currently incompatible with `dask=2021.5.0+`, I definitely want to get a fix in for v3.3.0 (#4310).

**Comment by jmoralez** [comment]
I wanted to discuss my current approach, I think its more robust but I'm very confused about how the current implementation managed to convert a list to coo in the sparse matrices case.

**Comment by jameslamb** [comment]
Good morning, @jmoralez ! Now that #4378 has been merged to handle the multiclass pred_contrib case, can you update this PR? I support the approach you're taking where we get the shape by predicting on one row.

**Review by jameslamb — APPROVED** [review]
I like this approach, thanks! And I appreciate you also making the decision to thread the client through and use `client.compute()` instead of calling the Dask Array's `.compute()` method, to make sure that the expected client is being used.

I checked the logs of some CI jobs and I can see that the tests are running successfully against newer versions of Dask, as expected.

For example, `linux regular`: https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=10548&view=logs&j=c28dceab-947a-5848-c21f-eef3695e5f11&t=fa158246-17e2-53d4-5936-86070edbaacf

```text
dask-2021.6.2              |     pyhd3eb1b0_0           5 KB
dask-core-2021.6.2     |     pyhd3eb1b0_0         692 KB
distributed-2021.6.2   |   py39h06a4308_0         1.1 MB
```

And these changes are working for older versions of Dask as well. For example, `Linux_latest regular` uses Python 3.6, so conda gives it `dask` / `distributed` 2021.3.0

https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=10548&view=logs&j=275189f9-c769-596a-7ef9-49fb48a9ab70&t=3a9e7a4a-04e6-52a0-67ea-6e8f6cfda74f

```text
dask-2021.3.0              |     pyhd3eb1b0_0           5 KB
dask-core-2021.3.0         |     pyhd3eb1b0_0         659 KB
distributed-2021.3.0       |   py36h06a4308_0         1.0 MB
```

I'm very happy that we'll be able to get this fix into the 3.3.0 release (#4310). Thanks as always for your help!

**Pull request merged**
